### ISSUE TITLE
Dynamo WONT CONVERT for is_fx_tracing()

### ISSUE THREAD

**Issue by suo** [pytorch/torchdynamo#1010]
Probably the same as #1009. Repro:
```
import torchdynamo
from torch.fx._symbolic_trace import is_fx_tracing

def my_compiler(gm, inputs):
    return gm.forward

@torchdynamo.optimize(my_compiler)
def fn(x, y):
    if is_fx_tracing():
        return x
    else:
        return y

fn(1, 2)
```
returns
```
torchdynamo.convert_frame: [ERROR] WON'T CONVERT fn /private/home/suo/scratch/test.py line 8
due to:
Traceback (most recent call last):
  File "/raid/suo/torchdynamo/torchdynamo/variables/tensor.py", line 258, in create
    assert (
AssertionError: torch.* op returned non-Tensor bool call_function <function is_fx_tracing at 0x7f08b681e700>

from user code:
   File "/private/home/suo/scratch/test.py", line 10, in fn
    if is_fx_tracing():

Set torchdynamo.config.verbose=True for more information
==========
```

**Comment by jansel** [comment]
Woops sorry @voznesenskym didn't see you claimed it

**Comment by voznesenskym** [comment]
> Woops sorry @voznesenskym didn't see you claimed it

Only cause we spoke about it earlier! All yours if you want it :)
