### ISSUE TITLE
Shape errors from fake_tensor_propagation in detectron2 rcnn

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#1062]
Note this is a newer torchbench model, so you need to update torchbench if you have been using my branch.  We get this same error with many of the detectron2 models.

Repro:
```
$ ./benchmarks/torchbench.py --only detectron2_fasterrcnn_r_50_fpn -dcuda
```

Output:
```
cuda eval  detectron2_fasterrcnn_r_50_fpn     torchdynamo.convert_frame: [ERROR] WON'T CONVERT forward_pass ./benchmarks/torchbench.py line 350 
due to: 
Traceback (most recent call last):
  File "/home/jansel/pytorch/torch/_ops.py", line 60, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: The size of tensor a (75) must match the size of tensor b (76) at non-singleton dimension 3

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jansel/torchdynamo/torchdynamo/variables/tensor.py", line 146, in create
    raise TorchRuntimeError() from e
torchdynamo.exc.TorchRuntimeError

from user code:
   File "./benchmarks/torchbench.py", line 351, in forward_pass
    return mod(*inputs)

Set torchdynamo.config.verbose=True for more information
==========
torchdynamo.convert_frame: [ERROR] WON'T CONVERT forward /home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py line 122 
due to: 
Traceback (most recent call last):
  File "/home/jansel/pytorch/torch/_ops.py", line 60, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: The size of tensor a (75) must match the size of tensor b (76) at non-singleton dimension 3

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jansel/torchdynamo/torchdynamo/variables/tensor.py", line 146, in create
    raise TorchRuntimeError() from e
torchdynamo.exc.TorchRuntimeError

from user code:
   File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 146, in forward
    return self.inference(batched_inputs)

Set torchdynamo.config.verbose=True for more information
==========
torchdynamo.convert_frame: [ERROR] WON'T CONVERT inference /home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py line 174 
due to: 
Traceback (most recent call last):
  File "/home/jansel/pytorch/torch/_ops.py", line 60, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: The size of tensor a (75) must match the size of tensor b (76) at non-singleton dimension 3

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jansel/torchdynamo/torchdynamo/variables/tensor.py", line 146, in create
    raise TorchRuntimeError() from e
torchdynamo.exc.TorchRuntimeError

from user code:
   File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 200, in inference
    features = self.backbone(images.tensor)

Set torchdynamo.config.verbose=True for more information
==========
STAGE:2022-08-26 16:01:59 2198777:2198777 ActivityProfilerController.cpp:294] Completed Stage: Warm Up
STAGE:2022-08-26 16:01:59 2198777:2198777 ActivityProfilerController.cpp:300] Completed Stage: Collection
105/108 +0 frames  19s 53 graphs 53 graph calls 1150/1262 =  91% ops  77% time
```

If you apply this patch:
```patch
diff --git a/torchdynamo/config.py b/torchdynamo/config.py
index af2ddd0..e0d1510 100644
--- a/torchdynamo/config.py
+++ b/torchdynamo/config.py
@@ -63,7 +63,7 @@ class AccessLimitingConfig(ModuleType):
     dynamic_propagation = True
 
     # Run the FX graph with FakeTensors
-    fake_tensor_propagation = True
+    fake_tensor_propagation = False
 
     # run FX normalization passes in optimizer
     normalize_ir = True
```

The output becomes:
```
$ ./benchmarks/torchbench.py --only detectron2_fasterrcnn_r_50_fpn -dcuda
cuda eval  detectron2_fasterrcnn_r_50_fpn     STAGE:2022-08-26 16:03:19 2199000:2199000 ActivityProfilerController.cpp:294] Completed Stage: Warm Up
STAGE:2022-08-26 16:03:19 2199000:2199000 ActivityProfilerController.cpp:300] Completed Stage: Collection
110/110 +0 frames  20s 53 graphs 53 graph calls 1151/1265 =  91% ops  72% time
```

cc @eellison

**Comment by jansel** [comment]
@ezyang could this be a case of a meta tensor shape function being wrong somewhere?

**Comment by Chillee** [comment]
@jansel Yeah, it's possible now, since we use python re-implementations now.

**Comment by eellison** [comment]
I can some config or mode to double check our tensor properties as we run them with fake tensor (similar to @ezyang's CrossRef mode).
