### ISSUE TITLE
[aot_autograd] LSTM is not supported

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1147]
Repro:
```
benchmarks/torchbench.py -d cuda --inductor --training --float32 --no-skip -k demucs
benchmarks/torchbench.py -d cuda --inductor --training --float32 --no-skip -k tts_angular
```
Error:
```
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/benchmarks/common.py", line 1236, in run_one_model
    new_result = optimized_model_iter_fn(model, example_inputs)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/torchbench.py", line 338, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "benchmarks/torchbench.py", line 339, in <graph break in forward_and_backward_pass>
    cloned_inputs = clone_inputs(inputs)
  File "benchmarks/torchbench.py", line 342, in <graph break in forward_and_backward_pass>
    pred = mod(*cloned_inputs)
  File "/fsx/users/binbao/pytorch-release/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/users/binbao/torchbenchmark/torchbenchmark/models/demucs/__init__.py", line 27, in forward
    def forward(self, streams) -> Tuple[Tensor, Tensor]:
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 889, in forward
    return compiled_f(
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 875, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 75, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 450, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 306, in aot_dispatch_autograd
    fx_g = make_fx(joint_forward_backward)(*joint_inputs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/experimental/proxy_tensor.py", line 621, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/experimental/proxy_tensor.py", line 391, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/fsx/users/binbao/pytorch-release/torch/fx/_symbolic_trace.py", line 614, in flatten_fn
    tree_out = root_fn(*tree_args)
  File "/fsx/users/binbao/pytorch-release/torch/fx/experimental/proxy_tensor.py", line 405, in wrapped
    out = f(*tensors)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 139, in joint_forward_backward
    outs = fn(*primals)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 838, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/interpreter.py", line 129, in run
    self.env[node] = self.run_node(node)
  File "/fsx/users/binbao/pytorch-release/torch/fx/interpreter.py", line 162, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/interpreter.py", line 279, in call_module
    return submod(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/_symbolic_trace.py", line 717, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/experimental/proxy_tensor.py", line 357, in call_module
    return forward(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/_symbolic_trace.py", line 710, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/nn/modules/rnn.py", line 774, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
  File "/fsx/users/binbao/pytorch-release/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/experimental/proxy_tensor.py", line 424, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/experimental/proxy_tensor.py", line 443, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/experimental/proxy_tensor.py", line 280, in proxy_call
    proxy_out = proxy_mode.tracer.create_proxy('call_function', func, proxy_args, proxy_kwargs,
  File "/fsx/users/binbao/pytorch-release/torch/fx/proxy.py", line 66, in create_proxy
    args_ = self.create_arg(args)
  File "/fsx/users/binbao/pytorch-release/torch/fx/experimental/proxy_tensor.py", line 383, in create_arg
    return super().create_arg(a)
  File "/fsx/users/binbao/pytorch-release/torch/fx/_symbolic_trace.py", line 344, in create_arg
    return super().create_arg(a)
  File "/fsx/users/binbao/pytorch-release/torch/fx/proxy.py", line 140, in create_arg
    return type(a)(self.create_arg(elem) for elem in a)
  File "/fsx/users/binbao/pytorch-release/torch/fx/proxy.py", line 140, in <genexpr>
    return type(a)(self.create_arg(elem) for elem in a)
  File "/fsx/users/binbao/pytorch-release/torch/fx/experimental/proxy_tensor.py", line 383, in create_arg
    return super().create_arg(a)
  File "/fsx/users/binbao/pytorch-release/torch/fx/_symbolic_trace.py", line 344, in create_arg
    return super().create_arg(a)
  File "/fsx/users/binbao/pytorch-release/torch/fx/proxy.py", line 166, in create_arg
    raise NotImplementedError(f"argument of type: {type(a)}")
NotImplementedError: argument of type: <class 'torch.storage.UntypedStorage'>
ERROR
argument of type: <class 'torch.storage.UntypedStorage'>
```

**Comment by yanboliang** [comment]
This is similar to the issue that #806 is trying to fix, as FX doesn't support ```torch.storage.UntypedStorage``` as [base type](https://github.com/pytorch/pytorch/blob/master/torch/fx/proxy.py#L154), so throw ```NotImplementedError``` error when there is ```torch.storage.UntypedStorage``` in ```fx.node.args```.

**Comment by yanboliang** [comment]
I can't reproduce the original error, this is what I got:
```
Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/common.py", line 1300, in run_performance_test
    optimized_model_iter_fn(model, example_inputs)
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/torchbench.py", line 339, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/torchbench.py", line 340, in <graph break in forward_and_backward_pass>
    cloned_inputs = clone_inputs(inputs)
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/torchbench.py", line 343, in <graph break in forward_and_backward_pass>
    pred = mod(*cloned_inputs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/ybliang/work/repos/torchbenchmark/torchbenchmark/models/demucs/__init__.py", line 27, in forward
    def forward(self, streams) -> Tuple[Tensor, Tensor]:
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 904, in forward
    return compiled_f(
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 890, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 465, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 291, in aot_dispatch_autograd
    out = flat_fn(*flat_args)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 853, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/fx/interpreter.py", line 129, in run
    self.env[node] = self.run_node(node)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/fx/interpreter.py", line 162, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/fx/interpreter.py", line 279, in call_module
    return submod(*args, **kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 774, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 841, in __torch_dispatch__
    r = func(*args, **kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/_ops.py", line 191, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Attempted to set the storage of a tensor on device "meta" to a storage on different device "cuda:0".  This is no longer allowed; the devices must match.
```

**Comment by desertfire** [comment]
cc @eellison

**Comment by anijain2305** [comment]
Repro 

~~~

import torch
import torchdynamo
from torch import tensor, device
import torch.fx as fx
from torchdynamo.testing import rand_strided
from math import inf
from torchdynamo.debug_utils import run_fwd_maybe_bwd


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.self_mod_model_lstm_lstm = LSTM(2048, 2048, num_layers=2, bidirectional=True)



    def forward(self, permute : torch.Tensor):
        self_mod_model_lstm_lstm = self.self_mod_model_lstm_lstm(permute);  permute = None
        return ()


mod = Repro().cuda()
opt_mod = torchdynamo.optimize("inductor")(mod)


args = [((92, 4, 2048), (1, 188416, 92), torch.float32, 'cuda', False)]
args = [rand_strided(sh, st, dt, dev).requires_grad_(rg) for (sh, st, dt, dev, rg) in args]


with torch.cuda.amp.autocast(enabled=False):
    ref = run_fwd_maybe_bwd(mod, args)
    res = run_fwd_maybe_bwd(opt_mod, args)
~~~

**Comment by anijain2305** [comment]
This is not an inductor problem. This is aot_eager problem. `aot_eager` passes here because we fallback to eager for LSTM models. For reproing with `aot_eager` above, use the following diff

~~~
diff --git a/torchdynamo/optimizations/training.py b/torchdynamo/optimizations/training.py
index 7f64c86c..016079c4 100644
--- a/torchdynamo/optimizations/training.py
+++ b/torchdynamo/optimizations/training.py
@@ -29,8 +29,8 @@ class AotAutogradStrategy(object):

     @classmethod
     def compile_fn(cls, gm: torch.fx.GraphModule, example_inputs):
-        if count_calls(gm.graph) < 2:
-            return gm.forward  # no point for tiny graphs
+        # if count_calls(gm.graph) < 2:
+        #     return gm.forward  # no point for tiny graphs
         return cls(gm, example_inputs).verified_candidate()

     def __init__(self, gm: torch.fx.GraphModule, example_inputs):
@@ -56,9 +56,9 @@ class AotAutogradStrategy(object):
         gm_inputs = list(filter(lambda x: x.op == "placeholder", gm.graph.nodes))

         # 1) LSTM module (tts_angular) - https://github.com/pytorch/functorch/issues/586
-        for submod in self.gm.modules():
-            if submod.__class__.__name__ == "LSTM":
-                self.use_fallback = True
+        # for submod in self.gm.modules():
+        #     if submod.__class__.__name__ == "LSTM":
+        #         self.use_fallback = True

         # 2) set_grad_enabled
         has_set_grad_enabled = False
~~~


@jansel @Chillee Do you think we should have similar hacks/workarounds in inductor that we have for `aot_eager` - https://github.com/pytorch/torchdynamo/blob/main/torchdynamo/optimizations/training.py#L58-L83

**Comment by yanboliang** [comment]
I verified both model works well now.
