### ISSUE TITLE
TorchBench training error: CUDA graph error

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1149]
Repro:
```
 benchmarks/torchbench.py -d cuda --inductor --training --float32 --no-skip -k  mobilenet_v2_quantized_qat
 benchmarks/torchbench.py -d cuda --inductor --training --float32 --no-skip -k  resnet50_quantized_qat
```
Error:
```
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/benchmarks/common.py", line 1236, in run_one_model
    new_result = optimized_model_iter_fn(model, example_inputs)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/torchbench.py", line 338, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "benchmarks/torchbench.py", line 339, in <graph break in forward_and_backward_pass>
    cloned_inputs = clone_inputs(inputs)
  File "benchmarks/torchbench.py", line 342, in <graph break in forward_and_backward_pass>
    pred = mod(*cloned_inputs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/graph_module.py", line 658, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/fsx/users/binbao/pytorch-release/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/fsx/users/binbao/pytorch-release/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.2", line 4, in forward
    def forward(self, x : torch.Tensor) -> torch.Tensor:
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 889, in forward
    return compiled_f(
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 875, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 75, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 450, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 335, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(fw_module, flat_args)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 237, in f
    out_f = compiler(fx_g, inps)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 75, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/compile_fx.py", line 177, in fw_compiler
    return compile_fx_inner(
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/debug_utils.py", line 329, in debug_wrapper
    compiled_fn = compiler(gm, example_inputs, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/debug.py", line 182, in inner
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/compile_fx.py", line 63, in compile_fx_inner
    compiled_fn = cudagraphify(
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 75, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/compile_fx.py", line 114, in cudagraphify
    static_outputs = model(*static_inputs)
  File "/fsx/users/binbao/pytorch-release/torch/cuda/graphs.py", line 159, in __exit__
    self.cuda_graph.capture_end()
  File "/fsx/users/binbao/pytorch-release/torch/cuda/graphs.py", line 81, in capture_end
    super(CUDAGraph, self).capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
```

**Comment by desertfire** [comment]
Should be CUDA graph related. Turning off CUDA graph makes them pass.

**Comment by jansel** [comment]
@ngimel said this is due to `fused_moving_avg_obs_fake_quant_cuda`, which has a synchronization and thus cannot be captured. 

I think we just need to add the offending op to this function:
https://github.com/pytorch/torchdynamo/blob/fe3173f7e6c804e6330ac187ea8e4101f45ff9a2/torchinductor/utils.py#L170
