### ISSUE TITLE
Bert model training fails with inductor

### ISSUE THREAD

**Issue by yanboliang** [pytorch/torchdynamo#1178]
Repro:
```
import os

import torch
from datasets import load_dataset
from torch.utils.data import DataLoader
from transformers import AutoModelForSequenceClassification
from transformers import AutoTokenizer

import torchdynamo

torchdynamo.config.fake_tensor_propagation = False
torchdynamo.config.capture_scalar_outputs = True

os.environ["TOKENIZERS_PARALLELISM"] = "false"
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
num_samples = 100
num_epochs = 3


def data_processing(num_samples):
    dataset = load_dataset("yelp_review_full")
    tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

    def tokenize_function(examples):
        return tokenizer(examples["text"], padding="max_length", truncation=True)

    tokenized_datasets = dataset.map(tokenize_function, batched=True)

    tokenized_datasets = tokenized_datasets.remove_columns(["text"])
    tokenized_datasets = tokenized_datasets.rename_column("label", "labels")
    tokenized_datasets.set_format("torch")

    small_train_dataset = (
        tokenized_datasets["train"].shuffle(seed=42).select(range(num_samples))
    )
    small_eval_dataset = (
        tokenized_datasets["test"].shuffle(seed=42).select(range(num_samples))
    )

    train_dataloader = DataLoader(small_train_dataset, shuffle=True, batch_size=8)
    eval_dataloader = DataLoader(small_eval_dataset, batch_size=8)

    return train_dataloader, eval_dataloader

if __name__ == "__main__":
    train_dataloader, eval_dataloader = data_processing(num_samples)
    model = AutoModelForSequenceClassification.from_pretrained(
        "bert-base-cased", num_labels=5
    )
    model.to(device)
    model.train()
    opt_model = torchdynamo.optimize("inductor")(model)
    for i, batch in enumerate(train_dataloader, 0):
        batch = {k: v.to(device) for k, v in batch.items()}
        outputs = opt_model(**batch)
```
Error:
```
Traceback (most recent call last):
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 56, in preserve_rng_state
    yield
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 447, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 333, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(fw_module, flat_args)
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 235, in f
    out_f = compiler(fx_g, inps)
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/utils.py", line 75, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/home/ybliang/Meta/torchdynamo/torchinductor/compile_fx.py", line 183, in fw_compiler
    return compile_fx_inner(
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/debug_utils.py", line 330, in debug_wrapper
    compiled_fn = compiler(gm, example_inputs, **kwargs)
  File "/data/home/ybliang/Meta/torchdynamo/torchinductor/debug.py", line 182, in inner
    return fn(*args, **kwargs)
  File "/data/home/ybliang/Meta/torchdynamo/torchinductor/compile_fx.py", line 69, in compile_fx_inner
    compiled_fn = cudagraphify(
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/utils.py", line 75, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/home/ybliang/Meta/torchdynamo/torchinductor/compile_fx.py", line 112, in cudagraphify
    model(*inputs)
  File "/tmp/torchinductor_ybliang/l7/cl7xqryqw3t6hp2jgzeuhkbgc4vjocsknzj7awzhlhh36housjnd.py", line 4632, in call
    kernel38[grid(49152)](buf308, primals_204, seed_cuda_0, buf311, buf312, buf335, buf338, buf341, buf344, buf347, buf350, buf353, buf356, buf359, buf362, buf365, buf368, 49152, 512)
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/triton/code_gen.py", line 999, in __call__
    return self.kernel(*wargs, **kwargs, grid=self.grid)
  File "/data/home/ybliang/Meta/torchdynamo/torchinductor/triton_ops/autotune.py", line 50, in __call__
    timings = {
  File "/data/home/ybliang/Meta/torchdynamo/torchinductor/triton_ops/autotune.py", line 51, in <dictcomp>
    config: self._bench(*args, config=config, **kwargs)
  File "/data/home/ybliang/Meta/torchdynamo/torchinductor/triton_ops/autotune.py", line 42, in _bench
    return super()._bench(*args, config=config, **kwargs)
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/triton/code_gen.py", line 1054, in _bench
    return triton.testing.do_bench(kernel_call)
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/triton/testing.py", line 138, in do_bench
    torch.cuda.synchronize()
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/torch/cuda/__init__.py", line 501, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/ybliang/Meta/torchdynamo/debug/debug3.py", line 59, in <module>
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/eval_frame.py", line 146, in __call__
    return self.forward(*args, **kwargs)
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/eval_frame.py", line 143, in forward
    return optimized_forward(*args, **kwargs)
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 1502, in forward
    @add_start_docstrings_to_model_forward(BERT_INPUTS_DOCSTRING.format("batch_size, sequence_length"))
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 886, in forward
    return compiled_f(
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 872, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 450, in create_aot_dispatcher_function
    return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 60, in preserve_rng_state
    torch.cuda.set_rng_state(cuda_rng_state)
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/torch/cuda/random.py", line 64, in set_rng_state
    _lazy_call(cb)
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/torch/cuda/__init__.py", line 160, in _lazy_call
    callable()
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/torch/cuda/random.py", line 62, in cb
    default_generator.set_state(new_state_copy)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by yanboliang** [comment]
@Chillee

**Comment by voznesenskym** [comment]
> CUDA error: an illegal memory access was encountered
+
cudagraphify in the stack trace

Can you figure out which op this is, and add it to the forbidden list in has_incompatible_cudagraph_ops?

**Comment by ngimel** [comment]
The faulty kernel is kernel0 in backward, abridged repro (runnable) is in https://gist.github.com/ngimel/93acfb30c9b2eccbb57151d406e462d5#file-bert_training-py-L107. Note how buf4, buf5, buf340 (out_ptr4, out_ptr5, out_ptr6 in the kernel) are of size (4, 512, 768), where (4, 512) maps to X, so to properly address out_ptr4,5,6 x should be less than 4*512=2048. However, range of x is 4096 (xnumel argument to the kernel), so it looks like either the kernel is incorrectly generated, or the buffers are incorrectly allocated, cc @jansel.

**Comment by yanboliang** [comment]
@ngimel Thanks for fixing this! But the repro still doesn't work in my test, does it work well on your end?

**Comment by ngimel** [comment]
Yes it does

**Comment by yanboliang** [comment]
I updated my triton commit version and finally it works. Thanks!
