### ISSUE TITLE
[inductor][ddp] File not found when trying to rename tmp_path to path in code cache

### ISSUE THREAD

**Issue by davidberard98** [pytorch/torchdynamo#1185]
Repro:
Run with:
* inductor & dynamo, main branch
* pytorch, master branch
* torchbench, https://github.com/pytorch/benchmark/blob/wconstab/ddp_experiments/ddp_experiments.py
* 8 gpus per node, 2 nodes (I can repro more reliably with n>=2 nodes), resnet50 model (cannot repro on other models)

```
/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
WARNING:root:Using TorchDynamo with a context manager will be deprecated soon.Please read https://github.com/pytorch/torchdynamo#usage-example to use TorchDynamo using an annotation.
ERROR:root:Error while processing frame
Traceback (most recent call last):
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/eval_frame.py", line 225, in catch_errors
    log.debug(f"skipping {frame.f_code.co_name} {frame.f_code.co_filename}")
  File "/fsx/users/dberard/scratch-local/bench-fast/benchmark/torchbenchmark/util/model.py", line 188, in invoke
    self.train()
  File "/fsx/users/dberard/scratch-local/bench-fast/benchmark/torchbenchmark/util/framework/vision/model_factory.py", line 65, in train
    pred = self.model(data)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchvision/models/resnet.py", line 284, in forward
    def forward(self, x: Tensor) -> Tensor:
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 889, in forward
    return compiled_f(
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 875, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/utils.py", line 75, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 450, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 335, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(fw_module, flat_args)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 237, in f
    out_f = compiler(fx_g, inps)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/utils.py", line 75, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/compile_fx.py", line 177, in fw_compiler
    return compile_fx_inner(
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/debug_utils.py", line 329, in debug_wrapper
    compiled_fn = compiler(gm, example_inputs, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/debug.py", line 182, in inner
    return fn(*args, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/compile_fx.py", line 60, in compile_fx_inner
    compiled_fn = wrap(graph.compile_to_fn())
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/graph.py", line 333, in compile_to_fn
    return self.compile_to_module().call
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/utils.py", line 75, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/graph.py", line 323, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/codecache.py", line 162, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_dberard/s7/cs7yddkfqu2hqk2hbxty2b65q4zavo3yxmatm3yx2ie73ghiqkh7.py", line 18, in <module>
    kernel0 = TritonCodeCache.load('''
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/codecache.py", line 243, in load
    return PyCodeCache.load(source_code)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/codecache.py", line 156, in load
    key, path = write(source_code, "py")
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/codecache.py", line 46, in write
    os.rename(tmp_path, path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/torchinductor_dberard/hb/chbtiqye637eosh5eyoh7t3ve4mviybimx2m2uudsrm6bt22x3nd.py.1571306751' -> '/tmp/torchinductor_dberard/hb/chbtiqye637eosh5eyoh7t3ve4mviybimx2m2uudsrm6bt22x3nd.py'
submitit ERROR (2022-09-09 02:24:05,677) - Submitted job triggered an exception
ERROR:submitit:Submitted job triggered an exception
Traceback (most recent call last):
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/submitit/core/submission.py", line 72, in submitit_main
    process_job(args.folder)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/submitit/core/submission.py", line 65, in process_job
    raise error
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/submitit/core/submission.py", line 54, in process_job
    result = delayed.result()
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/submitit/core/utils.py", line 133, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "ddp_experiments.py", line 149, in __call__
    return trainer_class(self.args, model_class, model_args=self.model_args).measure()
  File "/fsx/users/dberard/scratch-local/bench-fast/benchmark/torchbenchmark/util/distributed/core_model/trainer.py", line 79, in measure
    self.benchmark.invoke()
  File "/fsx/users/dberard/scratch-local/bench-fast/benchmark/torchbenchmark/util/model.py", line 188, in invoke
    self.train()
  File "/fsx/users/dberard/scratch-local/bench-fast/benchmark/torchbenchmark/util/framework/vision/model_factory.py", line 65, in train
    pred = self.model(data)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchvision/models/resnet.py", line 284, in forward
    def forward(self, x: Tensor) -> Tensor:
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 889, in forward
    return compiled_f(
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 875, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/utils.py", line 75, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 450, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 335, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(fw_module, flat_args)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 237, in f
    out_f = compiler(fx_g, inps)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/utils.py", line 75, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/compile_fx.py", line 177, in fw_compiler
    return compile_fx_inner(
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/debug_utils.py", line 329, in debug_wrapper
    compiled_fn = compiler(gm, example_inputs, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/debug.py", line 182, in inner
    return fn(*args, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/compile_fx.py", line 60, in compile_fx_inner
    compiled_fn = wrap(graph.compile_to_fn())
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/graph.py", line 333, in compile_to_fn
    return self.compile_to_module().call
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/utils.py", line 75, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/graph.py", line 323, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/codecache.py", line 162, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_dberard/s7/cs7yddkfqu2hqk2hbxty2b65q4zavo3yxmatm3yx2ie73ghiqkh7.py", line 18, in <module>
    kernel0 = TritonCodeCache.load('''
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/codecache.py", line 243, in load
    return PyCodeCache.load(source_code)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/codecache.py", line 156, in load
    key, path = write(source_code, "py")
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchinductor/codecache.py", line 46, in write
    os.rename(tmp_path, path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/torchinductor_dberard/hb/chbtiqye637eosh5eyoh7t3ve4mviybimx2m2uudsrm6bt22x3nd.py.1571306751' -> '/tmp/torchinductor_dberard/hb/chbtiqye637eosh5eyoh7t3ve4mviybimx2m2uudsrm6bt22x3nd.py'
```

**Comment by wconstab** [comment]
we should probably rebase the ddp_experiments branch on latest torchbench main, if nothing else, it should get us past this `WARNING:root:Using TorchDynamo with a context manager will be deprecated soon.Please read https://github.com/pytorch/torchdynamo#usage-example to use TorchDynamo using an annotation.` since @xuzhao9 recently updated to use the new api.

**Comment by wconstab** [comment]
cc @jansel @ngimel any idea if /tmp errors like the above could be caused by /tmp being full on a machine?  we're farming these jobs out via slurm.  it is DDP, so we expect the same kernels get compiled on each rank.  does inductor do anything unsafe w.r.t. assuming that no other inductor process is running the same model on the same machine?

**Comment by jansel** [comment]
I don't think so.  If we were out of space the file creation on the line above would have failed.

I think this has to do with multiple forked processes racing trying to write the same file.  Perhaps this will fix it:
```patch
diff --git a/torchinductor/codecache.py b/torchinductor/codecache.py
index 3904a19..b04cf7c 100644
--- a/torchinductor/codecache.py
+++ b/torchinductor/codecache.py
@@ -8,6 +8,7 @@ import random
 import re
 import subprocess
 import sysconfig
+import tempfile
 import types
 from ctypes import cdll
 
@@ -39,10 +40,10 @@ def write(source_code, ext, extra=""):
         os.makedirs(subdir, exist_ok=True)
     path = os.path.join(subdir, f"{basename}.{ext}")
     if not os.path.exists(path):
-        # use a random temp file for thread safety
-        tmp_path = f"{path}.{random.randint(0, 2**31)}"
-        with open(tmp_path, "w") as fd:
-            fd.write(source_code)
+        # use a temp file for thread safety
+        fd, tmp_path = tempfile.mkstemp(dir=subdir)
+        with os.fdopen(fd, "w") as f:
+            f.write(source_code)
         os.rename(tmp_path, path)
     return basename, path
 

```

**Comment by jansel** [comment]
I already submitted #1191 (it seems like a good change even if it doesn't fix it)

**Comment by davidberard98** [comment]
#1191 looks like it fixes the issue, thanks!
