### ISSUE TITLE
TorchBench training error: RuntimeError: unsupported operation

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1188]
Repro:
```
benchmarks/torchbench.py -d cuda --inductor --float32 --no-skip --training -k tacotron2
```
Error:
```
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/benchmarks/common.py", line 1236, in run_one_model
    new_result = optimized_model_iter_fn(model, example_inputs)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/benchmarks/torchbench.py", line 335, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "/fsx/users/binbao/torchdynamo-tip/benchmarks/torchbench.py", line 336, in <graph break in forward_and_backward_pass>
    cloned_inputs = clone_inputs(inputs)
  File "/fsx/users/binbao/torchdynamo-tip/benchmarks/torchbench.py", line 339, in <graph break in forward_and_backward_pass>
    pred = mod(*cloned_inputs)
  File "/fsx/users/binbao/pytorch/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/users/binbao/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 499, in forward
    def forward(self, inputs):
  File "/fsx/users/binbao/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 505, in <graph break in forward>
    encoder_outputs = self.encoder(embedded_inputs, text_lengths)
  File "/fsx/users/binbao/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 513, in <graph break in forward>
    return self.parse_output(
  File "/fsx/users/binbao/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 487, in parse_output
    def parse_output(self, outputs, output_lengths=None):
  File "/fsx/users/binbao/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 489, in <graph break in parse_output>
    mask = ~get_mask_from_lengths(output_lengths)
  File "/fsx/users/binbao/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 493, in <graph break in parse_output>
    outputs[0].data.masked_fill_(mask, 0.0)
  File "/fsx/users/binbao/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 494, in <graph break in parse_output>
    outputs[1].data.masked_fill_(mask, 0.0)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/functorch/_src/aot_autograd.py", line 890, in forward
    return compiled_f(
  File "/fsx/users/binbao/pytorch/functorch/functorch/_src/aot_autograd.py", line 881, in new_func
    return compiled_fn(args)
  File "/fsx/users/binbao/pytorch/functorch/functorch/_src/aot_autograd.py", line 282, in new_fn
    fw_outs = call_func_with_args(compiled_fw, args)
  File "/fsx/users/binbao/pytorch/functorch/functorch/_src/aot_autograd.py", line 250, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/fsx/users/binbao/pytorch/functorch/functorch/_src/aot_autograd.py", line 228, in g
    return f(*args)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/compile_fx.py", line 132, in run
    dst.copy_(src)
RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.
```

**Comment by desertfire** [comment]
The same as the error reported in  https://github.com/pytorch/torchdynamo/issues/838

**Comment by desertfire** [comment]
The same as the error reported in  https://github.com/pytorch/torchdynamo/issues/838

**Comment by eellison** [comment]
Fixed with https://github.com/pytorch/torchdynamo/pull/1208
