### ISSUE TITLE
TorchBench training error: AttributeError: 'NoneType' object has no attribute 'type

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1200]
Repro:
```
 benchmarks/torchbench.py -d cuda --inductor --training --float32 --use-eval-mode --no-skip -k  vision_maskrcnn
```
Error:
```
Traceback (most recent call last):
  File "/scratch/binbao/work/triton/python/triton/code_gen.py", line 1309, in _compile
    generator.visit(self.parse())
  File "/scratch/binbao/work/triton/python/triton/code_gen.py", line 754, in visit
    return super().visit(node)
  File "/scratch/binbao/work/env/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/scratch/binbao/work/triton/python/triton/code_gen.py", line 245, in visit_Module
    ast.NodeVisitor.generic_visit(self, node)
  File "/scratch/binbao/work/env/lib/python3.9/ast.py", line 415, in generic_visit
    self.visit(item)
  File "/scratch/binbao/work/triton/python/triton/code_gen.py", line 754, in visit
    return super().visit(node)
  File "/scratch/binbao/work/env/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/scratch/binbao/work/triton/python/triton/code_gen.py", line 306, in visit_FunctionDef
    has_ret = self.visit_compound_statement(node.body)
  File "/scratch/binbao/work/triton/python/triton/code_gen.py", line 239, in visit_compound_statement
    self.last_ret = self.visit(stmt)
  File "/scratch/binbao/work/triton/python/triton/code_gen.py", line 754, in visit
    return super().visit(node)
  File "/scratch/binbao/work/env/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/scratch/binbao/work/triton/python/triton/code_gen.py", line 350, in visit_Assign
    values = self.visit(node.value)
  File "/scratch/binbao/work/triton/python/triton/code_gen.py", line 754, in visit
    return super().visit(node)
  File "/scratch/binbao/work/env/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/scratch/binbao/work/triton/python/triton/code_gen.py", line 434, in visit_BinOp
    return getattr(lhs, fn)(rhs, _builder=self.builder)
  File "/scratch/binbao/work/triton/python/triton/language/core.py", line 46, in wrapper
    return fn(*args, **kwargs)
  File "/scratch/binbao/work/triton/python/triton/language/core.py", line 439, in __add__
    return semantic.add(self, other, _builder)
  File "/scratch/binbao/work/triton/python/triton/language/semantic.py", line 123, in add
    input, other = binary_op_type_checking_impl(input, other, builder, True, True)
  File "/scratch/binbao/work/triton/python/triton/language/semantic.py", line 107, in binary_op_type_checking_impl
    lhs, rhs = broadcast_impl_value(lhs, rhs, builder)
  File "/scratch/binbao/work/triton/python/triton/language/semantic.py", line 509, in broadcast_impl_value
    rhs_ty = rhs.type
AttributeError: 'NoneType' object has no attribute 'type'
```

**Comment by desertfire** [comment]
```
import torch
import torchdynamo
from torch import tensor, device
import torch.fx as fx
from torchdynamo.testing import rand_strided
from math import inf
from torchdynamo.debug_utils import run_fwd_maybe_bwd


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.self_inner_blocks_3_0 = Conv2d(2048, 256, kernel_size=(1, 1), stride=(1, 1))
        self.self_layer_blocks_3_0 = Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.self_inner_blocks_2_0 = Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1))
        self.self_layer_blocks_0_0 = Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))



    def forward(self, x_2_ : torch.Tensor, x_3_ : torch.Tensor, self_layer_blocks_2_0, self_layer_blocks_1_0, self_inner_blocks_0_0, interpolate_2):
        self_inner_blocks_3_0 = self.self_inner_blocks_3_0(x_3_);  x_3_ = None
        self_layer_blocks_3_0 = self.self_layer_blocks_3_0(self_inner_blocks_3_0)
        self_inner_blocks_2_0 = self.self_inner_blocks_2_0(x_2_);  x_2_ = None
        interpolate = torch.nn.functional.interpolate(self_inner_blocks_3_0, size = (74, 76), mode = 'nearest');  self_inner_blocks_3_0 = None
        add_2 = self_inner_blocks_0_0 + interpolate_2;  self_inner_blocks_0_0 = interpolate_2 = None
        self_layer_blocks_0_0 = self.self_layer_blocks_0_0(add_2);  add_2 = None
        max_pool2d = torch.nn.functional.max_pool2d(self_layer_blocks_3_0, 1, 2, 0)
        return (self_layer_blocks_0_0, self_layer_blocks_1_0, self_layer_blocks_2_0, self_layer_blocks_3_0, max_pool2d)


mod = Repro().cuda()
opt_mod = torchdynamo.optimize("inductor")(mod)


args = [((4, 1024, 74, 76), (5758976, 5624, 76, 1), torch.float32, 'cuda', True), ((4, 2048, 37, 38), (2879488, 1406, 38, 1), torch.float32, 'cuda', True), ((4, 256, 74, 76), (1439744, 5624, 76, 1), torch.float32, 'cuda', True), ((4, 256, 148, 152), (5758976, 22496, 152, 1), torch.float32, 'cuda', True), ((4, 256, 296, 304), (23035904, 89984, 304, 1), torch.float32, 'cuda', True), ((4, 256, 296, 304), (23035904, 89984, 304, 1), torch.float32, 'cuda', True)]
args = [rand_strided(sh, st, dt, dev).requires_grad_(rg) for (sh, st, dt, dev, rg) in args]


with torch.cuda.amp.autocast(enabled=False):
    ref = run_fwd_maybe_bwd(mod, args)
    res = run_fwd_maybe_bwd(opt_mod, args)
```
