### ISSUE TITLE
pytorch core test failure: RuntimeError: CUDA driver API confirmed a leak

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1254]
Repro:
cherry-pick https://github.com/pytorch/pytorch/pull/85183
```
PYTORCH_TEST_WITH_INDUCTOR=1 pytest test/distributions/test_distributions.py  -k  test_beta_underflow_gpu
```

Error:
```
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 1971, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 1971, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 1561, in __exit__
    raise RuntimeError(msg)
RuntimeError: CUDA driver API confirmed a leak in test_distributions.TestDistributions.test_beta_underflow_gpu! Caching allocator allocated memory was 0 and is now reported as 2560 on device 0. CUDA driver allocated memory was 872349696 and is now 876544000.
----------------------------------------------------------------------------------------------------- Captured log call -----------------------------------------------------------------------------------------------------
WARNING  torchinductor.compile_fx:compile_fx.py:108 skipping cudagraphs due to complex input striding
WARNING  torchinductor.compile_fx:compile_fx.py:108 skipping cudagraphs due to complex input striding
WARNING  torchinductor.compile_fx:compile_fx.py:108 skipping cudagraphs due to complex input striding
WARNING  torchinductor.compile_fx:compile_fx.py:108 skipping cudagraphs due to complex input striding
```

**Comment by desertfire** [comment]
The test fails at an assertion, and I think dynamo didn't handle exception cleanly. Setting `torchdynamo.config.raise_on_assertion_error=True` would get rid of the leak.

**Comment by desertfire** [comment]
Close in favor of https://github.com/pytorch/torchdynamo/issues/1772
