### ISSUE TITLE
pytorch core test failure: RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1255]
Repro:
cherry-pick https://github.com/pytorch/pytorch/pull/85183
```
PYTORCH_TEST_WITH_INDUCTOR=1 pytest test/distributions/test_distributions.py  -k  test_cauchy
```
Error:
```
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 1600, in test_cauchy
    def test_cauchy(self):
  File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 1622, in <graph break in test_cauchy>
    c.backward(torch.ones_like(c))
  File "/fsx/users/binbao/pytorch/functorch/_src/monkey_patching.py", line 79, in _backward
    return _old_backward(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_tensor.py", line 482, in backward
    torch.autograd.backward(
  File "/fsx/users/binbao/pytorch/torch/autograd/__init__.py", line 191, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
----------------------------------------------------------------------------------------------------- Captured log call -----------------------------------------------------------------------------------------------------
ERROR    torchdynamo.convert_frame:convert_frame.py:357 WON'T CONVERT apply_fn /fsx/users/binbao/pytorch/test/distributions/test_distributions.py line 817 
due to: 
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/variables/tensor.py", line 266, in create
    assert (
AssertionError: torch.* op returned non-Tensor dtype call_function <built-in function get_default_dtype>

from user code:
   File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 818, in apply_fn
    return dist_ctor(*params).log_prob(s)

Set torchdynamo.config.verbose=True for more information
```

**Comment by anijain2305** [comment]
`drq` also fails with the same error 

`benchmarks/torchbench.py --accuracy -d cuda --inductor --training --float32 --no-skip --only=drq`

@desertfire assigning to you for ownership.

**Comment by anijain2305** [comment]
Also fails soft_actor_critic

`benchmarks/torchbench.py --accuracy -d cuda --inductor --training --float32 --no-skip --only=soft_actor_critic`

**Comment by anijain2305** [comment]
Two other failures here. Not sure if they are related to this one. Lets fix the above error and see if these also pass

~~~
benchmarks/timm_models.py --training -dcuda --accuracy --training --inductor --only=dla102
benchmarks/timm_models.py --training -dcuda --accuracy --training --inductor --only= dpn107
~~~

**Comment by desertfire** [comment]
Verified `drq, soft_actor_critic, dla102, dpn107` are fixed by https://github.com/pytorch/pytorch/pull/85658

**Comment by desertfire** [comment]
Close in favor of https://github.com/pytorch/torchdynamo/issues/1772
