### ISSUE TITLE
pytorch core test failure: AttributeError: 'NoneType' object has no attribute 'device'

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1256]
Repro:
cherry-pick https://github.com/pytorch/pytorch/pull/85183
```
PYTORCH_TEST_WITH_INDUCTOR=1 pytest test/distributions/test_distributions.py  -k  test_multivariate_normal_shape 
```
Error:
```
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/graph.py", line 255, in call_function
    return lowerings[target](*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/lowering.py", line 184, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/lowering.py", line 761, in handler
    result = ir.FallbackKernel.create(kernel, *args, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/ir.py", line 2807, in create
    example_output.device,
AttributeError: 'NoneType' object has no attribute 'device'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 2080, in test_multivariate_normal_shape
    def test_multivariate_normal_shape(self):
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 167, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 904, in forward
    return compiled_f(
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 890, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 468, in create_aot_dispatcher_function
    return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 278, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 237, in f
    out_f = compiler(fx_g, inps)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/compile_fx.py", line 246, in fw_compiler
    return compile_fx_inner(
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/debug_utils.py", line 332, in debug_wrapper
    compiled_fn = compiler(gm, example_inputs, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/debug.py", line 182, in inner
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/conda/envs/release/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/compile_fx.py", line 83, in compile_fx_inner
    wrap(graph.run)(*example_inputs)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/graph.py", line 145, in run
    return super().run(*args)
  File "/fsx/users/binbao/pytorch/torch/fx/interpreter.py", line 129, in run
    self.env[node] = self.run_node(node)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/graph.py", line 305, in run_node
    result = super().run_node(n)
  File "/fsx/users/binbao/pytorch/torch/fx/interpreter.py", line 162, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/graph.py", line 257, in call_function
    raise LoweringException(e, target, args, kwargs) from e
torchinductor.exc.LoweringException: AttributeError: 'NoneType' object has no attribute 'device'
  target: aten._linalg_check_errors.default
  args[0]: TensorBox(StorageBox(
    MultiOutput(
      name=buf5,
      layout=FixedLayout('cpu', torch.int32, size=[], stride=[]),
      inputs=[FallbackKernel(name='buf3', layout=MultiOutputLayout(device=device(type='cpu')), inputs=[ComputedBuffer(name='buf2', layout=FixedLayout('cpu', torch.float64, size=[3, 3], stride=[3, 1]), data=Pointwise(
        'cpu',
        torch.float64,
        load(buf1, i1 + 3 * i0) / constant(10, torch.float64),
        ranges=[3, 3],
        origins={div}
      ))], constant_args=(), output_view=None)],
      constant_args=(),
      output_view=None,
      origins={linalg_inv_ex}
    )
  ))
  args[1]: linalg.inv
  kwargs: {'is_matrix': True}
```

**Comment by Chillee** [comment]
This error is due to us trying to automatically create a fallback for certain operators where our fallback logic doesn't work for (I think, in particular, for ops whose outputs are not tensors).

**Comment by desertfire** [comment]
Close in favor of https://github.com/pytorch/torchdynamo/issues/1772
