### ISSUE TITLE
pytorch core test failure: RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1257]
Repro:
cherry-pick https://github.com/pytorch/pytorch/pull/85183
```
PYTORCH_TEST_WITH_INDUCTOR=1 pytest test/distributions/test_distributions.py  -k  test_pareto
```
Error:
```
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 2556, in test_pareto
    self._check_log_prob(Pareto(scale, alpha), ref_log_prob)
  File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 837, in _check_log_prob
    asset_fn(i, val.squeeze(), log_prob)
  File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 2550, in ref_log_prob
    def ref_log_prob(idx, x, log_prob):
  File "/fsx/users/binbao/conda/envs/release/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 1884, in logpdf
    def logpdf(self, x, *args, **kwds):
  File "/fsx/users/binbao/conda/envs/release/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 1907, in <graph break in logpdf>
    args, loc, scale = self._parse_args(*args, **kwds)
  File "/fsx/users/binbao/conda/envs/release/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 1908, in <graph break in logpdf>
    x, loc, scale = map(asarray, (x, loc, scale))
  File "/fsx/users/binbao/pytorch/torch/_tensor.py", line 945, in __array__
    return self.numpy()
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
----------------------------------------------------------------------------------------------------- Captured log call -----------------------------------------------------------------------------------------------------
ERROR    torchdynamo.convert_frame:convert_frame.py:357 WON'T CONVERT test_pareto /fsx/users/binbao/pytorch/test/distributions/test_distributions.py line 2535 
due to: 
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/variables/tensor.py", line 266, in create
    assert (
AssertionError: torch.* op returned non-Tensor dtype call_function <built-in function get_default_dtype>

from user code:
   File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 2541, in test_pareto
    self.assertEqual(Pareto(scale_1d, 0.5).mean, inf)

Set torchdynamo.config.verbose=True for more information
```

**Comment by sangongs** [comment]
Looks like this is related to a [functorch issue](https://github.com/pytorch/functorch/issues/1052). Basically, functorch AOT compiles `tensor.detach` to `aten.alias` and thus results in semantic discrepancy between the original graph and the compiled graph, which is then fed into `fw_compiler` of Inductor

But even if the functorch AOT does not turn `detach` into `alias`, it looks to me Inductor does not handle `detach` correctly. 
https://github.com/pytorch/torchdynamo/blob/986da5a19055e99901220ffdc18b80558b54aa7b/torchinductor/lowering.py#L467-L469
Here it says that AOT autograd handles detach. But `aot_autograd` in Dynamo does not handle it. 

Currently I am not sure where to fix this. There are three options in my mind:
1. Fix the [functorch issue](https://github.com/pytorch/functorch/issues/1052), such that `detach` remains in the compiled graph. And then handle `detach` correctly in Inductor codegen.
2. Handle this completely in functorch.
3. Handle this in TorchDynamo. Not sure if this is viable.

@desertfire Do you have any suggestions?

**Comment by sangongs** [comment]
A minimum issue to reproduce this issue:
```
import torch
import torchdynamo

@torchdynamo.optimize()
def fn(x):
    return x.detach()

r = fn(torch.randn(1, requires_grad=True))
r.numpy()

**Comment by sangongs** [comment]
There is already a functorch PR fixing this: https://github.com/pytorch/pytorch/pull/86838

After cherry-picking the PR, the minimum program runs correctly. But this test still fails. I will keep investigating it.
