### ISSUE TITLE
pytorch core test failure: AssertionError: Tensor-likes are not close!

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1268]
Repro:
```
PYTORCH_TEST_WITH_INDUCTOR=1   pytest test/test_indexing.py -k test_index_put_accumulate_non_contiguous_cuda
```
Error:
```
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/test/test_indexing.py", line 817, in test_index_put_accumulate_non_contiguous
    @onlyCUDA
  File "/fsx/users/binbao/pytorch/test/test_indexing.py", line 823, in <graph break in test_index_put_accumulate_non_contiguous>
    self.assertTrue(not t1.is_contiguous())
  File "/fsx/users/binbao/pytorch/test/test_indexing.py", line 824, in <graph break in test_index_put_accumulate_non_contiguous>
    self.assertTrue(not t2.is_contiguous())
  File "/fsx/users/binbao/pytorch/test/test_indexing.py", line 831, in <graph break in test_index_put_accumulate_non_contiguous>
    self.assertTrue(not t1.is_contiguous())
  File "/fsx/users/binbao/pytorch/test/test_indexing.py", line 832, in <graph break in test_index_put_accumulate_non_contiguous>
    self.assertTrue(not t2.is_contiguous())
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2438, in assertEqual
    assert_equal(
  File "/fsx/users/binbao/pytorch/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 4 / 10 (40.0%)
Greatest absolute difference: 3.3860615491867065 at index (1, 1) (up to 1e-05 allowed)
Greatest relative difference: 1.927540119616793 at index (1, 1) (up to 1.3e-06 allowed)
```

**Comment by desertfire** [comment]
Close in favor of https://github.com/pytorch/torchdynamo/issues/1772
