### ISSUE TITLE
"Infinite capacity path" in hf_Bert on inductor 

### ISSUE THREAD

**Issue by davidberard98** [pytorch/torchdynamo#1276]
Repro: from torchbench, `python run.py hf_Bert --torchdynamo inductor -t train -d cuda`

```
Traceback (most recent call last):
  File "run.py", line 271, in <module>
    run_one_step(test, model_flops=model_flops, model=m, export_dcgm_metrics_file=export_dcgm_metrics_file, stress=args.stress)
  File "run.py", line 61, in run_one_step
    func()
  File "/fsx/users/dberard/scratch-local/bench-fast/benchmark/torchbenchmark/util/model.py", line 188, in invoke
    self.train()
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/dberard/scratch-local/bench-fast/benchmark/torchbenchmark/util/framework/huggingface/model_factory.py", line 119, in train
    def train(self):
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 889, in forward
    return compiled_f(
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 875, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 450, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 326, in aot_dispatch_autograd
    fw_module, bw_module = aot_config.partition_fn(fx_g, joint_inputs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/partitioners.py", line 396, in min_cut_rematerialization_partition
    cut_value, partition = nx.minimum_cut(nx_graph, "source", "sink")
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/networkx/algorithms/flow/maxflow.py", line 458, in minimum_cut
    R = flow_func(flowG, _s, _t, capacity=capacity, value_only=True, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/networkx/algorithms/flow/preflowpush.py", line 421, in preflow_push
    R = preflow_push_impl(G, s, t, capacity, residual, global_relabel_freq, value_only)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/networkx/algorithms/flow/preflowpush.py", line 41, in preflow_push_impl
    detect_unboundedness(R, s, t)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/networkx/algorithms/flow/utils.py", line 166, in detect_unboundedness
    raise nx.NetworkXUnbounded(
networkx.exception.NetworkXUnbounded: Infinite capacity path, flow unbounded above.
```

cc @anijain2305

**Comment by davidberard98** [comment]
Also seeing this in resnet50.

**Comment by Chillee** [comment]
I'm guessing this is an AOTAutograd bug.

**Comment by davidberard98** [comment]
@Chillee I can't repro any more, I'm guessing I was running on a version of pytorch that was too old.
