### ISSUE TITLE
[aot_eager] speech_transformer - Already active mode

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#1287]
Repro
~~~

import torch
import torchdynamo
from torch import tensor, device
import torch.fx as fx
from torchdynamo.testing import rand_strided
from math import inf
from torchdynamo.debug_utils import run_fwd_maybe_bwd
from torchdynamo.debug_utils import same_two_models

args = [((17,), (1,), torch.int64, 'cuda', False)]
args = [rand_strided(sh, st, dt, dev).requires_grad_(rg) for (sh, st, dt, dev, rg) in args]


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()



    def forward(self, _stack0_0_ : torch.Tensor):
        new_1 = _stack0_0_.new([1])
        cat = torch.cat([new_1, _stack0_0_], dim = 0);  new_1 = _stack0_0_ = None
        return (cat,)


mod = Repro().cuda()
opt_mod = torchdynamo.optimize("aot_eager")(mod)


with torch.cuda.amp.autocast(enabled=False):
    ref = run_fwd_maybe_bwd(mod, args)
    res = run_fwd_maybe_bwd(opt_mod, args)
~~~

Error
~~~
Traceback (most recent call last):
  File "/scratch/anijain/work/torchdynamo/repro.py", line 34, in <module>
    res = run_fwd_maybe_bwd(opt_mod, args)
  File "/scratch/anijain/work/torchdynamo/torchdynamo/debug_utils.py", line 362, in run_fwd_maybe_bwd
    out = gm(*args)
  File "/scratch/anijain/work/torchdynamo/torchdynamo/eval_frame.py", line 146, in __call__
    return self.forward(*args, **kwargs)
  File "/scratch/anijain/work/torchdynamo/torchdynamo/eval_frame.py", line 143, in forward
    return optimized_forward(*args, **kwargs)
  File "/scratch/anijain/work/torchdynamo/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/scratch/anijain/work/torchdynamo/repro.py", line 22, in forward
    def forward(self, _stack0_0_ : torch.Tensor):
  File "/scratch/anijain/work/torchdynamo/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/scratch/anijain/work/pytorch/functorch/_src/aot_autograd.py", line 939, in forward
    return compiled_f(
  File "/scratch/anijain/work/pytorch/functorch/_src/aot_autograd.py", line 925, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/scratch/anijain/work/torchdynamo/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/anijain/work/pytorch/functorch/_src/aot_autograd.py", line 503, in create_aot_dispatcher_function
    return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
  File "/scratch/anijain/work/pytorch/functorch/_src/aot_autograd.py", line 278, in aot_dispatch_base
    fw_module = make_fx(flat_fn, aot_config.decompositions)(*flat_args)
  File "/scratch/anijain/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 634, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/scratch/anijain/work/torchdynamo/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/scratch/anijain/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 397, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/scratch/anijain/work/torchdynamo/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/scratch/anijain/work/pytorch/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/scratch/anijain/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 411, in wrapped
    out = f(*tensors)
  File "<string>", line 1, in <lambda>
  File "/scratch/anijain/work/pytorch/functorch/_src/aot_autograd.py", line 888, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/scratch/anijain/work/pytorch/torch/fx/interpreter.py", line 129, in run
    self.env[node] = self.run_node(node)
  File "/scratch/anijain/work/pytorch/torch/fx/interpreter.py", line 162, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/scratch/anijain/work/pytorch/torch/fx/interpreter.py", line 234, in call_function
    return target(*args, **kwargs)
  File "/scratch/anijain/work/pytorch/torch/_subclasses/fake_tensor.py", line 561, in __torch_dispatch__
    with enable_torch_dispatch_mode(fake_mode):
  File "/scratch/anijain/work/env/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/scratch/anijain/work/pytorch/torch/utils/_mode_utils.py", line 64, in _enable_mode
    raise ValueError(
ValueError: Attempted to enable_torch_dispatch_mode, but there is already an active mode <torch.fx.experimental.proxy_tensor.ProxyTorchDispatchMode object at 0x7fe7c433eb80>.  Use `with Mode():` instead.
~~~

**Comment by anijain2305** [comment]
cc @eellison

**Comment by eellison** [comment]
This will be fixed by https://github.com/pytorch/torchdynamo/pull/1152 and https://github.com/pytorch/pytorch/pull/84774

**Comment by anijain2305** [comment]
I still see these errors. Repro

~~~

import torch
import torchdynamo
from torch import tensor, device
import torch.fx as fx
from torchdynamo.testing import rand_strided
from math import inf
from torchdynamo.debug_utils import run_fwd_maybe_bwd


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()



    def forward(self, argsort, expand_2):
        new = argsort.new(2, 12, 4096)
        scatter_ = new.scatter_(-1, argsort, expand_2);  new = argsort = expand_2 = None
        return (scatter_,)


mod = Repro().cuda()
opt_mod = torchdynamo.optimize("aot_eager")(mod)


args = [((2, 12, 4096), (49152, 4096, 1), torch.int64, 'cuda', False), ((2, 12, 4096), (0, 0, 1), torch.int64, 'cuda', False)]
args = [rand_strided(sh, st, dt, dev).requires_grad_(rg) for (sh, st, dt, dev, rg) in args]


with torch.cuda.amp.autocast(enabled=True):
    ref = run_fwd_maybe_bwd(mod, args)
    res = run_fwd_maybe_bwd(opt_mod, args)
    
~~~

@Chillee @samdow 

Sam, could you take a look if this will be covered by your work?

**Comment by samdow** [comment]
@anijain2305 Could you check that you're running on nightly?

**Comment by anijain2305** [comment]
Closing.
