### ISSUE TITLE
pytorch core test failure: accuracy error

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1316]
Repro (in pytorch core):
```
TEST_WITH_TORCHINDUCTOR=1  pytest test/test_ops.py  -k  test_noncontiguous_samples_matmul
```

Error:
```
======================================================================= test session starts =======================================================================
platform linux -- Python 3.9.13, pytest-7.1.3, pluggy-1.0.0
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /fsx/users/binbao/pytorch, configfile: pytest.ini
plugins: hydra-core-1.1.2, benchmark-3.4.1, hypothesis-6.54.5
collected 50132 items / 50127 deselected / 5 selected                                                                                                             

test/test_ops.py ..s.F                                                                                                                                      [100%]

============================================================================ FAILURES =============================================================================
__________________________________________________ TestCommonCUDA.test_noncontiguous_samples_matmul_cuda_float32 __________________________________________________
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/test/test_ops.py", line 526, in test_noncontiguous_samples
    self.assertEqual(t, n, msg=msg.format(i))
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2438, in assertEqual
    assert_equal(
  File "/fsx/users/binbao/pytorch/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 10 (10.0%)
Greatest absolute difference: 2.47955322265625e-05 at index (5,) (up to 1e-05 allowed)
Greatest relative difference: 3.878614869057962e-06 at index (5,) (up to 1.3e-06 allowed) : Got different gradients for contiguous / non-contiguous inputs wrt input 1.
===================================================================== short test summary info =====================================================================
FAILED test/test_ops.py::TestCommonCUDA::test_noncontiguous_samples_matmul_cuda_float32 - AssertionError: Tensor-likes are not close!
============================================== 1 failed, 3 passed, 1 skipped, 50127 deselected, 9 warnings in 12.06s ==============================================
```

**Comment by desertfire** [comment]
Close in favor of https://github.com/pytorch/torchdynamo/issues/1772
