### ISSUE TITLE
pytorch core test failure: NameError: name 'buf1' is not defined

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1326]
Repro:
```
PYTORCH_TEST_WITH_INDUCTOR=1 pytest test/nn/test_packed_sequence.py -k test_unpad_sequence
```
Error:
```
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/test/nn/test_packed_sequence.py", line 198, in test_unpad_sequence
    def test_unpad_sequence(self):
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 957, in forward
    return compiled_f(
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 948, in new_func
    return compiled_fn(args)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 287, in new_fn
    fw_outs = call_func_with_args(compiled_fw, args)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 252, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 230, in g
    return f(*args)
  File "/tmp/torchinductor_binbao/fq/cfqpzozo4innru2jmmoop53cpc555pvcmhi7l3k35recvvd2e4ze.py", line 96, in call
    return (buf0, buf4, buf1, buf2, buf3, )
NameError: name 'buf1' is not defined
```

**Comment by desertfire** [comment]
Close in favor of https://github.com/pytorch/torchdynamo/issues/1772
