### ISSUE TITLE
AssertionError while running in class NNModuleVariable

### ISSUE THREAD

**Issue by jiayisunx** [pytorch/torchdynamo#135]
AssertionError happened when I tried to torchdynamo.optimize MaskRCNN, and the accuracy is low when using torchdynamo.run MaskRCNN.
I tried to enable torchdynamo for MaskRCNN(https://github.com/facebookresearch/maskrcnn-benchmark), and as the first step, I set my_compiler does nothing:
_def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    print("my_compiler() called with FX graph:")
    return gm.forward  # return a python callable_

and optimized the model:
    _with torch.no_grad():
        for i, batch in enumerate(tqdm(data_loader)):
            images, targets, image_ids = batch
            images = images.to(memory_format=torch.channels_last)
            with torchdynamo.optimize(my_compiler):
                print("------------inside torch dynamo optimize---------------------")
                model(images)
            break_

and ran this part, got this error log:
  0%|          | 0/2500 [00:00<?, ?it/s]------------inside torch dynamo optimize---------------------
ERROR FROM offset=16 filename /home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/anchor_generator.py 75 AssertionError
ERROR FROM offset=20 filename /home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/anchor_generator.py 114 AssertionError
ERROR FROM offset=22 filename /home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py 156 AssertionError
ERROR FROM offset=52 filename /home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py 50 AssertionError
========== TorchDynamo Stack Trace ==========
Traceback (most recent call last):
  File "/home/jiayisun/torchdynamo/torchdynamo/convert_frame.py", line 158, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/home/jiayisun/torchdynamo/torchdynamo/bytecode_transformation.py", line 284, in transform_code_object
    transformations(instructions, code_options)
  File "/home/jiayisun/torchdynamo/torchdynamo/convert_frame.py", line 134, in transform
    tracer.run()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 274, in run
    and self.step()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 252, in step
    getattr(self, inst.opname)(inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 140, in wrapper
    return inner_fn(self, inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 543, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 191, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/nn_module.py", line 183, in call_function
    return tx.inline_user_function_return(
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 223, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 1098, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 1140, in inline_call_
    tracer.run()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 274, in run
    and self.step()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 252, in step
    getattr(self, inst.opname)(inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 140, in wrapper
    return inner_fn(self, inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 543, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 191, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/nn_module.py", line 183, in call_function
    return tx.inline_user_function_return(
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 223, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 1098, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 1140, in inline_call_
    tracer.run()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 274, in run
    and self.step()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 252, in step
    getattr(self, inst.opname)(inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 140, in wrapper
    return inner_fn(self, inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 543, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 191, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/functions.py", line 182, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/functions.py", line 64, in call_function
    return tx.inline_user_function_return(
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 223, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 1098, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 1140, in inline_call_
    tracer.run()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 274, in run
    and self.step()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 252, in step
    getattr(self, inst.opname)(inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 140, in wrapper
    return inner_fn(self, inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 543, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 191, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/builtin.py", line 213, in call_function
    result = handler(tx, *args, **kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/builtin.py", line 284, in call_zip
    if all(x.has_unpack_var_sequence(tx) for x in args):
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/builtin.py", line 284, in <genexpr>
    if all(x.has_unpack_var_sequence(tx) for x in args):
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/base.py", line 196, in has_unpack_var_sequence
    self.unpack_var_sequence(tx)
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/nn_module.py", line 49, in unpack_var_sequence
    assert isinstance(
AssertionError: BufferList
========== Exception (above) while processing ==========
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/tools/test_net.py", line 151, in <module>
    main()
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/tools/test_net.py", line 127, in main
    inference(
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 163, in inference
    predictions = compute_on_dataset(model, data_loader, device, bbox_aug, inference_timer, bf16, jit, iterations, iter_warmup, enable_profiling)
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 68, in compute_on_dataset
    model(images)
  File "/home/jiayisun/anaconda3/envs/dynamo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 33, in forward
    def forward(self, images, targets=None):
========== End debug info ==========
my_compiler() called with FX graph:
ERROR FROM offset=16 filename /home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/anchor_generator.py 75 AssertionError
ERROR FROM offset=20 filename /home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/anchor_generator.py 114 AssertionError
ERROR FROM offset=22 filename /home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py 156 AssertionError
========== TorchDynamo Stack Trace ==========
Traceback (most recent call last):
  File "/home/jiayisun/torchdynamo/torchdynamo/convert_frame.py", line 158, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/home/jiayisun/torchdynamo/torchdynamo/bytecode_transformation.py", line 284, in transform_code_object
    transformations(instructions, code_options)
  File "/home/jiayisun/torchdynamo/torchdynamo/convert_frame.py", line 134, in transform
    tracer.run()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 274, in run
    and self.step()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 252, in step
    getattr(self, inst.opname)(inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 140, in wrapper
    return inner_fn(self, inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 543, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 191, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/nn_module.py", line 183, in call_function
    return tx.inline_user_function_return(
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 223, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 1098, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 1140, in inline_call_
    tracer.run()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 274, in run
    and self.step()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 252, in step
    getattr(self, inst.opname)(inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 140, in wrapper
    return inner_fn(self, inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 543, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 191, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/functions.py", line 182, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/functions.py", line 64, in call_function
    return tx.inline_user_function_return(
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 223, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 1098, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 1140, in inline_call_
    tracer.run()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 274, in run
    and self.step()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 252, in step
    getattr(self, inst.opname)(inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 140, in wrapper
    return inner_fn(self, inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 543, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 191, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/builtin.py", line 213, in call_function
    result = handler(tx, *args, **kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/builtin.py", line 284, in call_zip
    if all(x.has_unpack_var_sequence(tx) for x in args):
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/builtin.py", line 284, in <genexpr>
    if all(x.has_unpack_var_sequence(tx) for x in args):
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/base.py", line 196, in has_unpack_var_sequence
    self.unpack_var_sequence(tx)
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/nn_module.py", line 49, in unpack_var_sequence
    assert isinstance(
AssertionError: BufferList
========== Exception (above) while processing ==========
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/tools/test_net.py", line 151, in <module>
    main()
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/tools/test_net.py", line 127, in main
    inference(
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 163, in inference
    predictions = compute_on_dataset(model, data_loader, device, bbox_aug, inference_timer, bf16, jit, iterations, iter_warmup, enable_profiling)
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 68, in compute_on_dataset
    model(images)
  File "/home/jiayisun/anaconda3/envs/dynamo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/jiayisun/anaconda3/envs/dynamo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 140, in forward
    def forward(self, images, features, targets=None):
========== End debug info ==========
my_compiler() called with FX graph:
ERROR FROM offset=16 filename /home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/anchor_generator.py 75 AssertionError
ERROR FROM offset=20 filename /home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/anchor_generator.py 114 AssertionError
========== TorchDynamo Stack Trace ==========
Traceback (most recent call last):
  File "/home/jiayisun/torchdynamo/torchdynamo/convert_frame.py", line 158, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/home/jiayisun/torchdynamo/torchdynamo/bytecode_transformation.py", line 284, in transform_code_object
    transformations(instructions, code_options)
  File "/home/jiayisun/torchdynamo/torchdynamo/convert_frame.py", line 134, in transform
    tracer.run()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 274, in run
    and self.step()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 252, in step
    getattr(self, inst.opname)(inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 140, in wrapper
    return inner_fn(self, inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 543, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 191, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/functions.py", line 182, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/functions.py", line 64, in call_function
    return tx.inline_user_function_return(
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 223, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 1098, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 1140, in inline_call_
    tracer.run()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 274, in run
    and self.step()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 252, in step
    getattr(self, inst.opname)(inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 140, in wrapper
    return inner_fn(self, inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 543, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 191, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/builtin.py", line 213, in call_function
    result = handler(tx, *args, **kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/builtin.py", line 284, in call_zip
    if all(x.has_unpack_var_sequence(tx) for x in args):
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/builtin.py", line 284, in <genexpr>
    if all(x.has_unpack_var_sequence(tx) for x in args):
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/base.py", line 196, in has_unpack_var_sequence
    self.unpack_var_sequence(tx)
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/nn_module.py", line 49, in unpack_var_sequence
    assert isinstance(
AssertionError: BufferList
========== Exception (above) while processing ==========
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/tools/test_net.py", line 151, in <module>
    main()
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/tools/test_net.py", line 127, in main
    inference(
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 163, in inference
    predictions = compute_on_dataset(model, data_loader, device, bbox_aug, inference_timer, bf16, jit, iterations, iter_warmup, enable_profiling)
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 68, in compute_on_dataset
    model(images)
  File "/home/jiayisun/anaconda3/envs/dynamo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/jiayisun/anaconda3/envs/dynamo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 156, in forward
    anchors = self.anchor_generator(images, features)
  File "/home/jiayisun/anaconda3/envs/dynamo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/anchor_generator.py", line 112, in forward
    def forward(self, image_list, feature_maps):
========== End debug info ==========
ERROR FROM offset=16 filename /home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/anchor_generator.py 75 AssertionError
========== TorchDynamo Stack Trace ==========
Traceback (most recent call last):
  File "/home/jiayisun/torchdynamo/torchdynamo/convert_frame.py", line 158, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/home/jiayisun/torchdynamo/torchdynamo/bytecode_transformation.py", line 284, in transform_code_object
    transformations(instructions, code_options)
  File "/home/jiayisun/torchdynamo/torchdynamo/convert_frame.py", line 134, in transform
    tracer.run()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 274, in run
    and self.step()
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 252, in step
    getattr(self, inst.opname)(inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 140, in wrapper
    return inner_fn(self, inst)
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 543, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/jiayisun/torchdynamo/torchdynamo/symbolic_convert.py", line 191, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/builtin.py", line 213, in call_function
    result = handler(tx, *args, **kwargs)
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/builtin.py", line 284, in call_zip
    if all(x.has_unpack_var_sequence(tx) for x in args):
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/builtin.py", line 284, in <genexpr>
    if all(x.has_unpack_var_sequence(tx) for x in args):
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/base.py", line 196, in has_unpack_var_sequence
    self.unpack_var_sequence(tx)
  File "/home/jiayisun/torchdynamo/torchdynamo/variables/nn_module.py", line 49, in unpack_var_sequence
    assert isinstance(
AssertionError: BufferList
========== Exception (above) while processing ==========
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/tools/test_net.py", line 151, in <module>
    main()
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/tools/test_net.py", line 127, in main
    inference(
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 163, in inference
    predictions = compute_on_dataset(model, data_loader, device, bbox_aug, inference_timer, bf16, jit, iterations, iter_warmup, enable_profiling)
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 68, in compute_on_dataset
    model(images)
  File "/home/jiayisun/anaconda3/envs/dynamo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/jiayisun/anaconda3/envs/dynamo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 156, in forward
    anchors = self.anchor_generator(images, features)
  File "/home/jiayisun/anaconda3/envs/dynamo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/anchor_generator.py", line 114, in forward
    anchors_over_all_feature_maps = self.grid_anchors(grid_sizes)
  File "/home/jiayisun/frameworks.ai.models.intel-models/models/object_detection/pytorch/maskrcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/anchor_generator.py", line 73, in grid_anchors
    def grid_anchors(self, grid_sizes):
========== End debug info ==========
/home/jiayisun/anaconda3/envs/dynamo/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /home/jiayisun/frameworks.ai.pytorch.private-cpu/aten/src/ATen/native/TensorShape.cpp:2311.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

Although there were many AssertionError in this optimize process, the model ran through the whole dataset, but the accuracy is lower than that without torchdynamo.

**Comment by HensonMa** [comment]
I got the same assertion error `AssertionError: BufferList` when running dynamo compilation on Maskrcnn object detection model. How did you solve the problem? Thanks!

Model repo: https://github.com/mlcommons/training/tree/373dfedaa34a5c502e2e0d762e2b9fb20074762e
