### ISSUE TITLE
Benchmark script is suppressing too much error information

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#1369]
steps to reproduce:

patch in a failure like

```
diff --git a/functorch/_src/aot_autograd.py b/functorch/_src/aot_autograd.py
index 8a95f00c15..6d35d94794 100644
--- a/functorch/_src/aot_autograd.py
+++ b/functorch/_src/aot_autograd.py
@@ -507,6 +507,7 @@ def create_aot_dispatcher_function(
         def process_inputs(flat_args):
             if config.use_fake_tensor:
                 def convert(x):
+                    assert not isinstance(x, torch.nn.Parameter)
                     return fake_mode.from_tensor(x, shape_env=shape_env)
 
                 return pytree.tree_map_only(Tensor, convert, flat_args)
```

trigger the failure like

```
 python benchmarks/torchbench.py --only resnet18 --accuracy --backend aot_eager --training
```

output is

```
cuda train resnet18                           torchdynamo.symbolic_convert: [WARNING] Graph break: call_function in skip_files /data/users/ezyang/torchdynamo/torchdynamo/utils.py from user code at   File "/data/users/ezyang/torchdynamo/benchmarks/torchbench.py", line 341, in forward_and_backward_pass
    cloned_inputs = clone_inputs(inputs)

torchdynamo.symbolic_convert: [WARNING] Graph break: call_method NNModuleVariable() zero_grad [ConstantVariable(bool)] {} from user code at   File "/data/users/ezyang/torchdynamo/benchmarks/torchbench.py", line 342, in <graph break in forward_and_backward_pass>
    mod.zero_grad(True)

TorchDynamo optimized model failed to run because of following error

FAIL
10.60user 18.17system 0:07.15elapsed 402%CPU (0avgtext+0avgdata 2472204maxresident)k
```

information about the error has been entirely lost

**Comment by ezyang** [comment]
cc @anijain2305

**Comment by anijain2305** [comment]
https://github.com/pytorch/torchdynamo/pull/1361 should fix it.

**Comment by anijain2305** [comment]
The log is 

~~~
TorchDynamo optimized model failed to run because of following error
ERROR:common:
Traceback (most recent call last):
  File "/scratch/anijain/work/torchdynamo/benchmarks/common.py", line 1176, in check_accuracy
    new_result = optimized_model_iter_fn(model, example_inputs)
  File "/scratch/anijain/work/torchdynamo/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/scratch/anijain/work/torchdynamo/benchmarks/torchbench.py", line 340, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "/scratch/anijain/work/torchdynamo/benchmarks/torchbench.py", line 341, in <graph break in forward_and_backward_pass>
    cloned_inputs = clone_inputs(inputs)
  File "/scratch/anijain/work/torchdynamo/benchmarks/torchbench.py", line 344, in <graph break in forward_and_backward_pass>
    pred = mod(*cloned_inputs)
  File "/scratch/anijain/work/pytorch/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/anijain/work/torchvision/torchvision/models/resnet.py", line 284, in forward
    def forward(self, x: Tensor) -> Tensor:
  File "/scratch/anijain/work/torchdynamo/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/scratch/anijain/work/pytorch/functorch/_src/aot_autograd.py", line 958, in forward
    return compiled_f(
  File "/scratch/anijain/work/pytorch/functorch/_src/aot_autograd.py", line 944, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/scratch/anijain/work/torchdynamo/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/anijain/work/pytorch/functorch/_src/aot_autograd.py", line 503, in create_aot_dispatcher_function
    fake_flat_tensor_args = process_inputs(flat_args)
  File "/scratch/anijain/work/pytorch/functorch/_src/aot_autograd.py", line 499, in process_inputs
    return pytree.tree_map_only(Tensor, convert, flat_args)
  File "/scratch/anijain/work/pytorch/torch/utils/_pytree.py", line 256, in tree_map_only
    return tree_map(map_only(ty)(fn), pytree)
  File "/scratch/anijain/work/pytorch/torch/utils/_pytree.py", line 192, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/scratch/anijain/work/pytorch/torch/utils/_pytree.py", line 192, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/scratch/anijain/work/pytorch/torch/utils/_pytree.py", line 241, in inner
    return f(x)
  File "/scratch/anijain/work/pytorch/functorch/_src/aot_autograd.py", line 496, in convert
    assert not isinstance(x, torch.nn.Parameter)
AssertionError
FAIL
~~~

Closing now.
