### ISSUE TITLE
An example in README.md causes an exception

### ISSUE THREAD

**Issue by kiszk** [pytorch/torchdynamo#1373]
An example for `torch.nn.Module` causes the following exception while the first example works well. Since I am new to torchdynamo, I may make mistakes.

```
$ pip install pytorch
$ pip install torchdynamo
$ pip list
Package           Version
----------------- -------
numpy             1.23.3
pip               22.2.2
PyYAML            6.0
setuptools        57.4.0
tabulate          0.8.10
torch             1.12.1
torchdynamo       1.12.0
typing_extensions 4.3.0
$ python --version
Python 3.9.7
$ cat torchdynamo_example2.py 
import torch
import torchdynamo

def my_compiler(gm: torch.fx.GraphModule, example_inputs: list[torch.Tensor]):
    print("my_compiler() called with FX graph:")
    gm.graph.print_tabular()
    return gm.forward  # return a python callable

class MockModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.relu = torch.nn.ReLU()

    def forward(self, x):
        return self.relu(torch.cos(x))

mod = MockModule()
optimized_mod = torchdynamo.optimize(my_compiler)(mod)
optimized_mod(torch.randn(10))

$ python torchdynamo_example2.py 
Traceback (most recent call last):
  File "/home/torchdynamo/tmp/torchdynamo_example2.py", line 18, in <module>
    optimized_mod = torchdynamo.optimize(my_compiler)(mod)
  File "/home/torchdynamo/.venv-torchdynamo/lib/python3.9/site-packages/torchdynamo/eval_frame.py", line 102, in __call__
    always_optimize_code_objects[fn.__code__] = True
  File "/home/torchdynamo/.venv-torchdynamo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'MockModule' object has no attribute '__code__'
```

**Comment by yanboliang** [comment]
It works well on the latest branch, can you try to install torchdynamo from source code? You can follow this: https://github.com/pytorch/torchdynamo#developer-setup

**Comment by kiszk** [comment]
Yes, I realized that it works well when I installed torchdynamo from source code. So, it happens only when I installed from pip.

**Comment by jansel** [comment]
We don't plan to support pytorch 1.12.  Would recommend using PyTorch nightly build.
