### ISSUE TITLE
torchdynamo.export doesn't propagate "example value" when using tensor.T

### ISSUE THREAD

**Issue by tugsbayasgalan** [pytorch/torchdynamo#1476]
To repro:

```
def f(x: torch.Tensor):
    return torch.ones_like(x.T)


inputs = (torch.randint(0, 95, (24, 1)),)
torchdynamo.export(f, *inputs)
```
We get following error:
```
torchdynamo.convert_frame: [ERROR] WON'T CONVERT f <ipython-input-39-f864a2a947ae> line 1 
due to: 
Traceback (most recent call last):
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/variables/tensor.py", line 66, in visit
    return n.meta["example_value"]
KeyError: 'example_value'

from user code:
   File "<ipython-input-39-f864a2a947ae>", line 2, in f
    return torch.ones_like(x.T)

Set torchdynamo.config.verbose=True for more information
==========
torchdynamo.eval_frame: [ERROR] Error while processing frame
Traceback (most recent call last):
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/convert_frame.py", line 313, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/bytecode_transformation.py", line 338, in transform_code_object
    transformations(instructions, code_options)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/convert_frame.py", line 301, in transform
    tracer.run()
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/symbolic_convert.py", line 338, in run
    and self.step()
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/symbolic_convert.py", line 311, in step
    getattr(self, inst.opname)(inst)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/symbolic_convert.py", line 162, in wrapper
    return inner_fn(self, inst)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/symbolic_convert.py", line 706, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/symbolic_convert.py", line 248, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/variables/torch.py", line 217, in call_function
    tensor_variable = TensorVariable.create(
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/variables/tensor.py", line 111, in create
    args, kwargs = cls.propagate_args_kwargs(proxy.node)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/variables/tensor.py", line 68, in propagate_args_kwargs
    return torch.fx.node.map_arg((node.args, node.kwargs), visit)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torch/fx/node.py", line 601, in map_arg
    return map_aggregate(a, lambda x: fn(x) if isinstance(x, Node) else x)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torch/fx/node.py", line 609, in map_aggregate
    t = tuple(map_aggregate(elem, fn) for elem in a)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torch/fx/node.py", line 609, in <genexpr>
    t = tuple(map_aggregate(elem, fn) for elem in a)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torch/fx/node.py", line 609, in map_aggregate
    t = tuple(map_aggregate(elem, fn) for elem in a)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torch/fx/node.py", line 609, in <genexpr>
    t = tuple(map_aggregate(elem, fn) for elem in a)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torch/fx/node.py", line 619, in map_aggregate
    return fn(a)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torch/fx/node.py", line 601, in <lambda>
    return map_aggregate(a, lambda x: fn(x) if isinstance(x, Node) else x)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/variables/tensor.py", line 66, in visit
    return n.meta["example_value"]
KeyError: 'example_value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/eval_frame.py", line 235, in catch_errors
    return callback(frame, cache_size)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/convert_frame.py", line 110, in _fn
    return fn(*args, **kwargs)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/mnt/xarfuse/uid-20451/0e8abdac-seed-nspid4026533494_cgpid24059839-ns-4026533491/torchdynamo/convert_frame.py", line 361, in _convert_frame_assert
    raise InternalTorchDynamoError()
torchdynamo.exc.InternalTorchDynamoError
```

**Comment by tugsbayasgalan** [comment]
cc: @voznesenskym @jansel @anijain2305

**Comment by tugsbayasgalan** [comment]
Seems like this doesn't work:
```
def f(x: torch.Tensor):
    return x.T
```
Gives:
```
AssertionError: whole graph export entails exactly one call
```

**Comment by voznesenskym** [comment]
This is the same as your other issue - your graph is too small - what are you trying to capture here? are these contrived examples to find edge cases, or real cases we need to support?

**Comment by tugsbayasgalan** [comment]
This above example (not my comment) happens in real production model. So i think we need to support it.

**Comment by tugsbayasgalan** [comment]
Ok when I make the graph not trivial:

```
import torchdynamo
import torch

torchdynamo.config.dynamic_shapes = True
def f(x):
    return x.T.sum()

gm, _ = torchdynamo.export(f, torch.ones(6, 2))
print(gm.graph)
``` 
We get:
```
torchdynamo.exc.Unsupported: call_method GetAttrVariable(TensorVariable(), T) sum [] {}
```

**Comment by zhxchen17** [comment]
> This is the same as your other issue - your graph is too small 

@voznesenskym I don't this is true. Actually, we intentionally minify the repro for people to look at. If you realy prefer a "bigger" graph, I can provide you one, and you will find the same error being raised:

```
def f(x: torch.Tensor):
    pred = torch.nn.functional.log_softmax(x, dim=-1)
    symbols = torch.max(pred, dim=-1)[1].T

    delim_symbols = torch.cat((symbols, -torch.ones_like(symbols)[:, :1]), -1)
    delim_symbols = torch.unique_consecutive(delim_symbols)

    return delim_symbols[delim_symbols.nonzero()].view(-1)
```
>  what are you trying to capture here? are these contrived examples to find edge cases, or real cases we need to support?

This is from OCR Recognition model. We're blocked for a couple of days.

btw you can assume all the issues we raised recently are all from real models. 

cc @suo @gmagogsfm

**Comment by voznesenskym** [comment]
> > This is the same as your other issue - your graph is too small 
> 
> 
> 
> @voznesenskym I don't this is true. Actually, we intentionally minify the repro for people to look at. If you realy prefer a "bigger" graph, I can provide you one, and you will find the same error being raised:
> 
> 
> 
> ```
> 
> def f(x: torch.Tensor):
> 
>     pred = torch.nn.functional.log_softmax(x, dim=-1)
> 
>     symbols = torch.max(pred, dim=-1)[1].T
> 
> 
> 
>     delim_symbols = torch.cat((symbols, -torch.ones_like(symbols)[:, :1]), -1)
> 
>     delim_symbols = torch.unique_consecutive(delim_symbols)
> 
> 
> 
>     return delim_symbols[delim_symbols.nonzero()].view(-1)
> 
> ```
> 
> >  what are you trying to capture here? are these contrived examples to find edge cases, or real cases we need to support?
> 
> 
> 
> This is from OCR Recognition model. We're blocked for a couple of days on this model.
> 
> 
> 
> btw you can assume all the issues we raised recently are all from real models. 
> 
> 
> 
> cc @suo @gmagogsfm 

Understood entirely. I'll take a look this weekend.
