### ISSUE TITLE
TorchBench model tacotron2 failed due to ```assert device.type != "meta"```

### ISSUE THREAD

**Issue by yanboliang** [pytorch/torchdynamo#1483]
Repro:
```
benchmarks/torchbench.py -d cuda --inductor --training --float32 --accuracy --quiet --no-skip -k tacotron2
```

Error:
```
cuda train tacotron2                          torchdynamo.convert_frame: [ERROR] WON'T CONVERT <graph break in decode> /scratch/ybliang/work/repos/torchbenchmark/torchbenchmark/models/tacotron2/model.py line 361 
due to: 
Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/variables/tensor.py", line 75, in run_proxy
    return proxy.node.target(*args, **kwargs)
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/variables/tensor.py", line 156, in create
    raise TorchRuntimeError() from e
torchdynamo.exc.TorchRuntimeError

from user code:
   File "/scratch/ybliang/work/repos/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 365, in <graph break in decode>
    self.attention_weights_cum += self.attention_weights

Set torchdynamo.config.verbose=True for more information
==========
TorchDynamo optimized model failed to run because of following error
ERROR:common:
Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/common.py", line 1139, in check_accuracy
    new_result = optimized_model_iter_fn(model, example_inputs)
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/eval_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/torchbench.py", line 340, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/torchbench.py", line 341, in <graph break in forward_and_backward_pass>
    cloned_inputs = clone_inputs(inputs)
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/torchbench.py", line 344, in <graph break in forward_and_backward_pass>
    pred = mod(*cloned_inputs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/ybliang/work/repos/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 499, in forward
    def forward(self, inputs):
  File "/scratch/ybliang/work/repos/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 505, in <graph break in forward>
    encoder_outputs = self.encoder(embedded_inputs, text_lengths)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/ybliang/work/repos/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 381, in forward
    def forward(self, memory, decoder_inputs, memory_lengths):
  File "/scratch/ybliang/work/repos/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 396, in <graph break in forward>
    decoder_input = self.get_go_frame(memory).unsqueeze(0)
  File "/scratch/ybliang/work/repos/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 402, in <graph break in forward>
    memory, mask=~get_mask_from_lengths(memory_lengths))
  File "/scratch/ybliang/work/repos/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 407, in <graph break in forward>
    mel_output, gate_output, attention_weights = self.decode(
  File "/scratch/ybliang/work/repos/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 407, in <graph break in forward>
    mel_output, gate_output, attention_weights = self.decode(
  File "/scratch/ybliang/work/repos/torchbenchmark/torchbenchmark/models/tacotron2/model.py", line 407, in <graph break in forward>
    mel_output, gate_output, attention_weights = self.decode(
  [Previous line repeated 1 more time]
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/eval_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 797, in forward
    return compiled_f(
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 783, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 509, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 366, in aot_dispatch_autograd
    fx_g = make_fx(joint_forward_backward)(*joint_inputs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/fx/experimental/proxy_tensor.py", line 652, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/eval_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/fx/experimental/proxy_tensor.py", line 400, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/eval_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/fx/_symbolic_trace.py", line 614, in flatten_fn
    tree_out = root_fn(*tree_args)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/fx/experimental/proxy_tensor.py", line 414, in wrapped
    out = f(*tensors)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 165, in joint_forward_backward
    backward_out = torch.autograd.grad(
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/autograd/__init__.py", line 300, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/utils/_python_dispatch.py", line 101, in __torch_dispatch__
    return old.__torch_dispatch__(func, types, args, kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/fx/experimental/proxy_tensor.py", line 440, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/fx/experimental/proxy_tensor.py", line 465, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/fx/experimental/proxy_tensor.py", line 304, in proxy_call
    out = func(*args, **kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/_ops.py", line 257, in __call__
    return self._op(*args, **kwargs or {})
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/utils/_python_dispatch.py", line 101, in __torch_dispatch__
    return old.__torch_dispatch__(func, types, args, kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 814, in __torch_dispatch__
    return self.wrap_meta_outputs_with_default_device_logic(
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 849, in wrap_meta_outputs_with_default_device_logic
    return tree_map(partial(wrap), r)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/utils/_pytree.py", line 192, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/utils/_pytree.py", line 192, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 862, in wrap
    return converter(self, e, device or common_device)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 255, in __call__
    return self.from_meta_and_device(fake_mode, t, device)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 231, in from_meta_and_device
    out = FakeTensor(fake_mode, t, device)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 478, in __init__
    assert device.type != "meta"
AssertionError
FAIL
```

This error is sort of flaky, another model ```fastNLP_Bert``` has [the same error](https://app.circleci.com/pipelines/github/pytorch/torchdynamo/3314/workflows/4b76ed05-4c1f-40d4-954a-4e125d630ce8/jobs/34302/parallel-runs/0/steps/0-109) but even more flaky.

**Comment by yanboliang** [comment]
BTW, I was trying to minify it using TORCHDYNAMO_REPRO_AFTER="dynamo" but failed.

**Comment by yanboliang** [comment]
cc @eellison

**Comment by yanboliang** [comment]
Should be fixed when https://github.com/pytorch/pytorch/pull/86245 merged.

**Comment by yanboliang** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/86245.
