### ISSUE TITLE
YituTechConvBert: IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 4)

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1535]
Repro:
```
benchmarks/huggingface.py --accuracy --ci --training  -d cuda  --backend aot_eager  --only YituTechConvBert
```
```
cuda train YituTechConvBert                   TorchDynamo optimized model failed to run because of following error
ERROR:common:Dimension out of range (expected to be in range of [-1, 0], but got 4)
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/benchmarks/common.py", line 1098, in check_accuracy
    new_result = optimized_model_iter_fn(model, example_inputs)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 164, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/benchmarks/huggingface.py", line 438, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "/fsx/users/binbao/torchdynamo-tip/benchmarks/huggingface.py", line 439, in <graph break in forward_and_backward_pass>
    cloned_inputs = clone_inputs(inputs)
  File "/fsx/users/binbao/torchdynamo-tip/benchmarks/huggingface.py", line 442, in <graph break in forward_and_backward_pass>
    pred = mod(**cloned_inputs)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/transformers/models/convbert/modeling_convbert.py", line 900, in forward
    @add_start_docstrings_to_model_forward(CONVBERT_INPUTS_DOCSTRING.format("batch_size, sequence_length"))
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 164, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 797, in forward
    return compiled_f(
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 783, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 75, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 509, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 366, in aot_dispatch_autograd
    fx_g = make_fx(joint_forward_backward)(*joint_inputs)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 652, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 164, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 400, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 164, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 614, in flatten_fn
    tree_out = root_fn(*tree_args)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 414, in wrapped
    out = f(*tensors)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 165, in joint_forward_backward
    backward_out = torch.autograd.grad(
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/autograd/__init__.py", line 300, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/utils/_python_dispatch.py", line 101, in __torch_dispatch__
    return old.__torch_dispatch__(func, types, args, kwargs)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 440, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 465, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 304, in proxy_call
    out = func(*args, **kwargs)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/_ops.py", line 257, in __call__
    return self._op(*args, **kwargs or {})
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/utils/_python_dispatch.py", line 101, in __torch_dispatch__
    return old.__torch_dispatch__(func, types, args, kwargs)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 795, in __torch_dispatch__
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/_ops.py", line 257, in __call__
    return self._op(*args, **kwargs or {})
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/_prims_common/wrappers.py", line 212, in _fn
    result = fn(*args, **kwargs)
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/_decomp/decompositions.py", line 63, in inner
    r = f(*tree_map(increase_prec, args), **tree_map(increase_prec, kwargs))
  File "/fsx/users/binbao/conda/envs/ci_nightly_gpu/lib/python3.10/site-packages/torch/_decomp/decompositions.py", line 889, in col2im
    output = F.pad(output, (-padding_h, -padding_h, -padding_w, -padding_w))
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 4)
FAIL
```

**Comment by desertfire** [comment]
cc @eellison , not sure if this is a fake tensor or decomposition problem.
