### ISSUE TITLE
[inductor] KeyError: 'BLOCK_K' when Enabling Triton BMM

### ISSUE THREAD

**Issue by typedfemale** [pytorch/torchdynamo#1593]
When I set `torchinductor.config.triton.use_bmm = True`, I get the following exception:

```bash
  File "/opt/conda/lib/python3.7/site-packages/torchinductor/triton_ops/batched_matmul.py", line 274, in bmm_out
    _kernel[grid](a, b, c, M, N, K, K, 1, N, 1, N, 1, GROUP_M=8, ACC_TYPE=ACC_TYPE)
  File "/opt/conda/lib/python3.7/site-packages/triton/runtime/jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/triton/runtime/autotuner.py", line 199, in run
    kwargs[v] = heur({**dict(zip(self.arg_names, args)), **kwargs})
  File "/opt/conda/lib/python3.7/site-packages/torchinductor/triton_ops/batched_matmul.py", line 15, in <lambda>
    "EVEN_K": lambda args: args["K"] % (args["BLOCK_K"] * args["SPLIT_K"]) == 0,
KeyError: 'BLOCK_K'
```

You can reproduce by running `benchmarks/microbenchmarks/inductor_bmm.py` with the latest version of triton.

I'm really not sure what the canonical triton version is at this point, but I'm reporting it here regardless.

**Comment by typedfemale** [comment]
> Can you try with:
> 
> ```diff
> diff --git a/torchinductor/triton_ops/batched_matmul.py b/torchinductor/triton_ops/batched_matmul.py
> index 7e7a655..f14d42e 100644
> --- a/torchinductor/triton_ops/batched_matmul.py
> +++ b/torchinductor/triton_ops/batched_matmul.py
> @@ -9,11 +9,6 @@ if has_triton():
>      def init_to_zero(name):
>          return lambda nargs: nargs[name].zero_()
>  
> -    @triton.heuristics(
> -        {
> -            "EVEN_K": lambda args: args["K"] % (args["BLOCK_K"] * args["SPLIT_K"]) == 0,
> -        }
> -    )
>      @triton.autotune(
>          configs=[
>              # basic configs for compute-bound matmuls
> @@ -165,6 +160,11 @@ if has_triton():
>          #     "top_k": 18,
>          # },
>      )
> +    @triton.heuristics(
> +        {
> +            "EVEN_K": lambda args: args["K"] % (args["BLOCK_K"] * args["SPLIT_K"]) == 0,
> +        }
> +    )
>      @triton.jit
>      def _kernel(
>          A,
> ```
> 
> There was an upstream triton change the requires swapping `triton.heuristics` and `triton.autotune`.

Hmm, then I get: `TypeError: autotune() missing 1 required positional argument: 'key'`

**Comment by typedfemale** [comment]
Tried to figure out what config was breaking it (the other seem to work just fine?):
```
[2022-10-11 19:15:23,386] torchinductor.compile_fx: [WARNING] skipping cudagraphs due to complex input striding
[2022-10-11 19:15:23,386] torchinductor.compile_fx: [INFO] Step 1: torchinductor done compiling FORWARDS graph None
BLOCK_M: 128, BLOCK_N: 256, BLOCK_K: 32, SPLIT_K: 1, num_warps: 8, num_stages: 3
BLOCK_M: 256, BLOCK_N: 128, BLOCK_K: 32, SPLIT_K: 1, num_warps: 8, num_stages: 3
BLOCK_M: 256, BLOCK_N: 64, BLOCK_K: 32, SPLIT_K: 1, num_warps: 4, num_stages: 4
BLOCK_M: 64, BLOCK_N: 256, BLOCK_K: 32, SPLIT_K: 1, num_warps: 4, num_stages: 4
BLOCK_M: 128, BLOCK_N: 128, BLOCK_K: 32, SPLIT_K: 1, num_warps: 4, num_stages: 4
BLOCK_M: 128, BLOCK_N: 64, BLOCK_K: 32, SPLIT_K: 1, num_warps: 4, num_stages: 4
BLOCK_M: 64, BLOCK_N: 128, BLOCK_K: 32, SPLIT_K: 1, num_warps: 4, num_stages: 4
BLOCK_M: 128, BLOCK_N: 32, BLOCK_K: 32, SPLIT_K: 1, num_warps: 4, num_stages: 4
BLOCK_M: 64, BLOCK_N: 32, BLOCK_K: 32, SPLIT_K: 1, num_warps: 2, num_stages: 5
BLOCK_M: 128, BLOCK_N: 256, BLOCK_K: 64, SPLIT_K: 1, num_warps: 8, num_stages: 3
Traceback (most recent call last):
  File "<string>", line 21, in _kernel
KeyError: ('2-.-0-.-0-aced2afef9a9131c1822ef1dc83cefd3-7929002797455b30efce6e41eddc6b57-a40f57746c8f81a5640d64c0180d7001-9a7804636eb443036ab483d0f4f04f47-0f76008a374e725ca29ccb33f1ba668f-dc48432b6b79843e2f9c7ad2e7355f59-f40d73592c2578180d3d8e3f64e3957d-0dd03b0bd512a184b3512b278d9dfa59-db6f636da818acacb988a846c8287eaf', (torch.float32, torch.float32, torch.float32, 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), (128, 256, 64, 8, 1, True, triton.language.fp32), (True, True, True, (True, False), (False, True), (True, False), (True, False), (False, True), (False, True), (False, True), (False, True), (False, True)))

During handling of the above exception, another exception occurred:
```

**Comment by jansel** [comment]
Ah hrm could we just remove that config?

**Comment by typedfemale** [comment]
Hm, I'm just worried something has changed on the Triton side and that's why it's breaking...

**Comment by typedfemale** [comment]
Ah, I think I see what's going on (I think #1338 broke it), [see the new matmul kernel](https://github.com/openai/triton/blob/master/python/triton/ops/matmul.py) in the Triton repo.

**Comment by netw0rkf10w** [comment]
How to resolve this issue please? I encountered similar ones when using PT2 (https://github.com/pytorch/pytorch/issues/90167#issuecomment-1340262256).
As I understand, one needs to revert to some previous Triton version? Thanks.

**Comment by jansel** [comment]
I suspect this will be fixed by https://github.com/pytorch/pytorch/pull/90482 which rewrites how bmm works and removes the code throwing the error.

**Comment by netw0rkf10w** [comment]
@jansel Thanks!
