### ISSUE TITLE
[operatorbench] [10/31 sweep] AssertionError: cuda should have been normalized in lowering

### ISSUE THREAD

**Issue by Krovatkin** [pytorch/torchdynamo#1640]
Command(s) to reproduce:

```shell
python operatorbench.py --op=aten.fill_.Tensor --dtype=float16
```

```shell
python operatorbench.py --op=aten.new_empty_strided.default --dtype=float16
```

```shell
python operatorbench.py --op=aten.new_zeros.default --dtype=float16
```

Stacktrace:

```
Traceback (most recent call last):
  File "/home/villedepommes/github/torchdynamo2/benchmarks/microbenchmarks/operatorbench.py", line 281, in <module>
    benchmark()
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/villedepommes/github/torchdynamo2/benchmarks/microbenchmarks/operatorbench.py", line 262, in benchmark
    raise e
  File "/home/villedepommes/github/torchdynamo2/benchmarks/microbenchmarks/operatorbench.py", line 247, in benchmark
    microbenchmark(
  File "/home/villedepommes/github/torchdynamo2/benchmarks/microbenchmarks/operatorbench.py", line 88, in microbenchmark
    medians = compute_speedups(operator, compiled, gm_args, repeats, accuracy_checking)
  File "/home/villedepommes/github/torchdynamo2/benchmarks/microbenchmarks/operatorbench.py", line 45, in compute_speedups
    median_ms, _, _ = triton.testing.do_bench(lambda: model(*example_inputs))
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/triton/testing.py", line 136, in do_bench
    fn()
  File "/home/villedepommes/github/torchdynamo2/benchmarks/microbenchmarks/operatorbench.py", line 45, in <lambda>
    median_ms, _, _ = triton.testing.do_bench(lambda: model(*example_inputs))
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 812, in forward
    return compiled_f(
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 798, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/home/villedepommes/github/torchdynamo2/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 527, in create_aot_dispatcher_function
    return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 283, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 239, in f
    out_f = compiler(fx_g, inps)
  File "/home/villedepommes/github/torchdynamo2/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/villedepommes/github/torchdynamo2/torchinductor/compile_fx.py", line 332, in fw_compiler
    return compile_fx_inner(
  File "/home/villedepommes/github/torchdynamo2/torchdynamo/debug_utils.py", line 445, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/villedepommes/github/torchdynamo2/torchinductor/debug.py", line 180, in inner
    return fn(*args, **kwargs)
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/villedepommes/github/torchdynamo2/torchinductor/compile_fx.py", line 104, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/home/villedepommes/github/torchdynamo2/torchinductor/graph.py", line 351, in compile_to_fn
    return self.compile_to_module().call
  File "/home/villedepommes/github/torchdynamo2/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/villedepommes/github/torchdynamo2/torchinductor/graph.py", line 337, in compile_to_module
    code = self.codegen()
  File "/home/villedepommes/github/torchdynamo2/torchinductor/graph.py", line 329, in codegen
    self.scheduler = Scheduler(self.buffers)
  File "/home/villedepommes/github/torchdynamo2/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/villedepommes/github/torchdynamo2/torchinductor/scheduler.py", line 566, in __init__
    group_fn = self.get_backend(node.get_device()).group_fn
  File "/home/villedepommes/github/torchdynamo2/torchinductor/scheduler.py", line 1056, in get_backend
    self.backends[device] = self.create_backend(device)
  File "/home/villedepommes/github/torchdynamo2/torchinductor/scheduler.py", line 1041, in create_backend
    assert (
AssertionError: cuda should have been normalized in lowering
```

**Comment by Krovatkin** [comment]
cc: @eellison @desertfire

**Comment by eellison** [comment]
These might just be a problem in the script
