### ISSUE TITLE
[inductor] Cannot broadcast, the expanded size of the tensor

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#1654]
Repro
~~~

import torch
from torch import tensor, device
import torch.fx as fx
from torch._dynamo.testing import rand_strided
from math import inf
from torch.fx.experimental.proxy_tensor import make_fx

# torch version: 1.14.0a0+git25725fd
# torch cuda version: 11.6
# torch git version: 25725fd62448165b91647304c26d676db22b6955


# CUDA Info: 
# nvcc: NVIDIA (R) Cuda compiler driver 
# Copyright (c) 2005-2022 NVIDIA Corporation 
# Built on Thu_Feb_10_18:23:41_PST_2022 
# Cuda compilation tools, release 11.6, V11.6.112 
# Build cuda_11.6.r11.6/compiler.30978841_0 

# GPU Hardware Info: 
# NVIDIA A100-SXM4-40GB : 8 


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()

    
    
    def forward(self, x, y):
        ne = torch.ops.aten.ne.Scalar(x, 1)
        sum_1 = torch.ops.aten.sum.dim_IntList(ne, [1])
        sub = torch.ops.aten.sub.Tensor(sum_1, 1)
        unsqueeze = torch.ops.aten.unsqueeze.default(sub, -1)
        gather = torch.ops.aten.gather.default(x, 1, unsqueeze)
        squeeze = torch.ops.aten.squeeze.default(gather)
        out = torch.ops.aten.multiply(y, squeeze)
        return (out, )
        # return (sum_1, sub, unsqueeze, gather, squeeze, out,)
        
args = [((1, 128), (128, 1), torch.int64, 'cuda'), ((1, 128), (128, 1), torch.int64, 'cuda')]
args = [rand_strided(sh, st, dt, dev) for (sh, st, dt, dev) in args]
mod = make_fx(Repro().to(device="cuda"))(*args)

# ref = mod(*args)
# print(ref)
# for r in ref:
#     print(r.shape, r.dtype)
# sum_1 torch.Size([1]) torch.int64 
# sub torch.Size([1]) torch.int64
# unsqueeze - torch.Size([1, 1]) torch.int64
# gather - torch.Size([1, 1]) torch.int64
# squeeze - torch.Size([]) torch.int64
# out - torch.Size([1, 128]) torch.int64
# sub -> 
from torch._inductor.compile_fx import compile_fx_inner
from torch._dynamo.debug_utils import same_two_models

compiled = compile_fx_inner(mod, args)
res = compiled(args)
print(res)



~~~

Error
~~~
  File "/scratch/anijain/work/env/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/scratch/anijain/work/triton/python/triton/compiler.py", line 320, in visit_FunctionDef
    has_ret = self.visit_compound_statement(node.body)
  File "/scratch/anijain/work/triton/python/triton/compiler.py", line 254, in visit_compound_statement
    self.last_ret = self.visit(stmt)
  File "/scratch/anijain/work/triton/python/triton/compiler.py", line 771, in visit
    return super().visit(node)
  File "/scratch/anijain/work/env/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/scratch/anijain/work/triton/python/triton/compiler.py", line 648, in visit_For
    self.visit_compound_statement(node.body)
  File "/scratch/anijain/work/triton/python/triton/compiler.py", line 254, in visit_compound_statement
    self.last_ret = self.visit(stmt)
  File "/scratch/anijain/work/triton/python/triton/compiler.py", line 771, in visit
    return super().visit(node)
  File "/scratch/anijain/work/env/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/scratch/anijain/work/triton/python/triton/compiler.py", line 367, in visit_Assign
    values = self.visit(node.value)
  File "/scratch/anijain/work/triton/python/triton/compiler.py", line 771, in visit
    return super().visit(node)
  File "/scratch/anijain/work/env/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/scratch/anijain/work/triton/python/triton/compiler.py", line 710, in visit_Call
    ret = fn(*args, _builder=self.builder, **kws)
  File "/scratch/anijain/work/triton/python/triton/language/core.py", line 46, in wrapper
    return fn(*args, **kwargs)
  File "/scratch/anijain/work/triton/python/triton/language/core.py", line 799, in load
    return semantic.load(pointer, mask, other, cache_modifier, eviction_policy, volatile, _builder)
  File "/scratch/anijain/work/triton/python/triton/language/semantic.py", line 697, in load
    mask = broadcast_impl_shape(mask, ptr.type.get_block_shapes(), builder)
  File "/scratch/anijain/work/triton/python/triton/language/semantic.py", line 498, in broadcast_impl_shape
    raise ValueError(f"Cannot broadcast, the expanded size of the tensor ({shape[i]})"
ValueError: Cannot broadcast, the expanded size of the tensor (1) must match the existing size (128) at non-singleton dimension 1: [1, 128], [1, 1]

~~~

**Comment by desertfire** [comment]
I am looking into this as an oncall task since it's coming from a recent correctness regression in huggingface models (MBartForConditionalGeneration , PLBartForConditionalGeneration).

Locally I am getting a different error msg, and this is actually an example of the indexing error being discussed in #1657 (notice the error msg from eager).

```
/fsx/users/binbao/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:145: operator(): block: [0,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
WARNING:torchinductor.lowering:make_fallback(aten.cumsum): a decomposition exists, we should switch to it
WARNING:torchinductor.lowering:make_fallback(aten.unfold): a decomposition exists, we should switch to it
WARNING:torchinductor.lowering:make_fallback(aten.unfold_backward): a decomposition exists, we should switch to it
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/tmp.py", line 51, in <module>
    compiled = compile_fx_inner(mod, args)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/debug_utils.py", line 446, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/debug.py", line 180, in inner
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/conda/envs/release/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/compile_fx.py", line 104, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/graph.py", line 351, in compile_to_fn
    return self.compile_to_module().call
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/graph.py", line 341, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/codecache.py", line 191, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_binbao/2v/c2vngbf6kvzs3l7xlsm5eu4nccunzv7qyltljipgp2rieyvqykbx.py", line 17, in <module>
    kernel0 = async_compile.triton('''
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/codecache.py", line 242, in triton
    self._context_keepalive = torch.tensor([1], device="cuda")
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

If I ran MBartForConditionalGeneration training directly, I got an error similar to the one in https://github.com/pytorch/torchdynamo/issues/1515#issuecomment-1277879228. 
```
triton.compiler.CompilationError: at 33:43:
def kernel(in_ptr0, out_ptr0, out_ptr1, xnumel, rnumel, XBLOCK : tl.constexpr, RBLOCK : tl.constexpr):
    xnumel = 1
    rnumel = 128
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK, 1])
    xmask = xindex < xnumel
    rbase = tl.reshape(tl.arange(0, RBLOCK), [1, RBLOCK])
    _tmp7 = tl.zeros([XBLOCK, RBLOCK], tl.int64) + 0
    for roffset in range(0, rnumel, RBLOCK):
        rindex = roffset + rbase
        rmask = rindex < rnumel
        r0 = rindex
        tmp0 = tl.load(in_ptr0 + (r0), rmask, eviction_policy='evict_last')
        tmp1 = -100
        tmp2 = tmp0 == tmp1
        tmp3 = 1
        tmp4 = tl.where(tmp2, tmp3, tmp0)
        tmp5 = tmp4 != tmp3
        tmp6 = tmp5.to(tl.int64)
        _tmp7 = tl.where(xmask & rmask, _tmp7 + tmp6, _tmp7)
    tmp7 = tl.reshape(tl.sum(_tmp7, 1), [XBLOCK, 1])
    tl.store(out_ptr0 + 0 + tl.zeros([XBLOCK, 1], tl.int32), tmp7, None)
    for roffset in range(0, rnumel, RBLOCK):
        rindex = roffset + rbase
        rmask = rindex < rnumel
        r0 = rindex
        tmp24 = tl.load(in_ptr0 + (r0), rmask, eviction_policy='evict_last')
        tmp8 = r0
        tmp9 = 0
        tmp10 = tmp8 == tmp9
        tmp11 = 1
        tmp12 = tmp7 - tmp11
        tmp13 = tl.load(in_ptr0 + (tmp12), rmask, eviction_policy='evict_last')
                                           ^
FAIL
```

So all the dots are connected now. We can conclude this is a real bug, not a new regression, but somehow it was hidden until now.

**Comment by ngimel** [comment]
fwiw, to make repro fail in triton you need to replace 
```
sub = torch.ops.aten.sub.Tensor(sum_1, 1);  sum_1 = None
```
with 
```
sub = torch.ops.aten.sub.Tensor(sum_1, 0);  sum_1 = None
```

**Comment by anijain2305** [comment]
Somewhat simpler repro

~~~

import torch
from torch import tensor, device
import torch.fx as fx
from torch._dynamo.testing import rand_strided
from math import inf
from torch.fx.experimental.proxy_tensor import make_fx

# torch version: 1.14.0a0+git25725fd
# torch cuda version: 11.6
# torch git version: 25725fd62448165b91647304c26d676db22b6955


# CUDA Info: 
# nvcc: NVIDIA (R) Cuda compiler driver 
# Copyright (c) 2005-2022 NVIDIA Corporation 
# Built on Thu_Feb_10_18:23:41_PST_2022 
# Cuda compilation tools, release 11.6, V11.6.112 
# Build cuda_11.6.r11.6/compiler.30978841_0 

# GPU Hardware Info: 
# NVIDIA A100-SXM4-40GB : 8 


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()

    
    
    def forward(self, x, y):
        ne = torch.ops.aten.ne.Scalar(x, 1)
        sum_1 = torch.ops.aten.sum.dim_IntList(ne, [1])
        sub = torch.ops.aten.sub.Tensor(sum_1, 1)
        unsqueeze = torch.ops.aten.unsqueeze.default(sub, -1)
        gather = torch.ops.aten.gather.default(x, 1, unsqueeze)
        squeeze = torch.ops.aten.squeeze.default(gather)
        out = torch.ops.aten.multiply(y, squeeze)
        return (ne, out,)
        
args = [((1, 128), (128, 1), torch.int64, 'cuda'), ((1, 128), (128, 1), torch.int64, 'cuda')]
args = [rand_strided(sh, st, dt, dev) for (sh, st, dt, dev) in args]
mod = make_fx(Repro().to(device="cuda"))(*args)

ref = mod(*args)
print(ref)
from torch._inductor.compile_fx import compile_fx_inner
from torch._dynamo.debug_utils import same_two_models

compiled = compile_fx_inner(mod, args)
res = compiled(args)
print(res)


~~~~

**Comment by anijain2305** [comment]
The error log is here - https://www.internalfb.com/phabricator/paste/view/P557277418

The main issue is in the second reduction loop

~~~
def kernel(in_ptr0, in_ptr1, out_ptr1, xnumel, rnumel, XBLOCK : tl.constexpr, RBLOCK : tl.constexpr):
    xnumel = 1
    rnumel = 128
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK, 1])
    xmask = xindex < xnumel
    rbase = tl.reshape(tl.arange(0, RBLOCK), [1, RBLOCK])
    _tmp4 = tl.zeros([XBLOCK, RBLOCK], tl.int64) + 0
    for roffset in range(0, rnumel, RBLOCK):
        rindex = roffset + rbase
        rmask = rindex < rnumel
        r0 = rindex
        tmp0 = tl.load(in_ptr0 + (r0), rmask, eviction_policy='evict_last')
        tmp1 = 1
        tmp2 = tmp0 != tmp1
        tmp3 = tmp2.to(tl.int64)
        _tmp4 = tl.where(xmask & rmask, _tmp4 + tmp3, _tmp4)
    tmp4 = tl.reshape(tl.sum(_tmp4, 1), [XBLOCK, 1])
    for roffset in range(0, rnumel, RBLOCK):
        rindex = roffset + rbase
        rmask = rindex < rnumel
        r0 = rindex
        tmp5 = tl.load(in_ptr1 + (r0), rmask, eviction_policy='evict_last')
        tmp6 = 1
        tmp7 = tmp4 - tmp6
        tmp8 = tl.load(in_ptr0 + (tmp7), xmask & rmask, eviction_policy='evict_last') # FAILS IN THIS LINE
        tmp9 = tmp5 * tmp8
        tl.store(out_ptr1 + (r0 + tl.zeros([XBLOCK, RBLOCK], tl.int32)), tmp9, xmask & rmask)
~~~

The main lines are tmp4, tmp6 and tmp7

* tmp7 is of size (1, 1) because XBLOCK = 1, and thus tmp4 is (1, 1)
* (xmask & rmask) is (1, 128)

Triton here does not support broadcasting the address offsets depending on the mask.

Ideally, tmp7 is not dependent on the rloop and therefore the mask in `tmp8` should be just xmask.

I am kind of stuck here, as I don't know how to do a dependency check on `tmp7` so that I don't put `rmask` here - https://github.com/pytorch/pytorch/blob/master/torch/_inductor/codegen/triton.py#L740

**Comment by jansel** [comment]
Does `torch._inductor.config.dense_indexing = True` fix this issue?
