### ISSUE TITLE
Segmentation fault with inductor for huggingface/diffusers

### ISSUE THREAD

**Issue by mreso** [pytorch/torchdynamo#1681]
Hi,

running the [stable_diffusion](https://github.com/huggingface/diffusers/tree/main/src/diffusers/pipelines/stable_diffusion) example from huggingface/diffusers results in segmentation fault.

Repro:
pip install --upgrade diffusers transformers

Then run:
```
import torchdynamo

from diffusers import StableDiffusionPipeline

pipeline = DiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4") #ACCESS TOKEN REQUIRED
pipe = pipe.to("cuda")

@torchdynamo.optimize("inductor")
def apply(x):
    return pipe(x)

prompt = "a photo of an astronaut riding a horse on mars"
image = apply(prompt).images[0]  
```

Error message:
```
ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.
WARNING:torchinductor.lowering:make_fallback(aten.unfold): a decomposition exists, we should switch to it
WARNING:torchinductor.lowering:make_fallback(aten.unfold_backward): a decomposition exists, we should switch to it
[2022-10-15 01:43:28,669] torchdynamo.symbolic_convert: [WARNING] Graph break: call_function UserDefinedObjectVariable(StableDiffusionPipeline) [ConstantVariable(str)] {} from user code at   File "/home/ubuntu/torchdynamo/test.py", line 14, in apply
    return pipe(x)

[2022-10-15 01:43:28,770] torchdynamo.symbolic_convert: [WARNING] Graph break: call_function UserDefinedObjectVariable(CLIPTokenizer) [ConstantVariable(str)] {'padding': ConstantVariable(str), 'max_length': ConstantVariable(int), 'return_tensors': Cons
tantVariable(str)} from user code at   File "/home/ubuntu/miniconda3/envs/torchdynamo/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 214, in __call__
    text_inputs = self.tokenizer(

[2022-10-15 01:43:34,247] torchdynamo.symbolic_convert: [WARNING] Graph break: call_function BuiltinVariable(dict) [UserDefinedObjectVariable(FrozenDict)] {} from user code at   File "/home/ubuntu/miniconda3/envs/torchdynamo/lib/python3.10/site-package
s/diffusers/pipeline_utils.py", line 205, in device
    module_names, _ = self.extract_init_dict(dict(self.config))

[2022-10-15 01:43:37,990] torchinductor.graph: [WARNING] Creating implicit fallback for:
  target: aten.triu_.default
  args[0]: TensorBox(StorageBox(
    ComputedBuffer(name='buf0', layout=FlexibleLayout('cpu', torch.float32, size=[1, 77, 77], stride=[5929, 77, 1]), data=Pointwise(
      'cpu',
      torch.float32,
      constant(-3.4028234663852886e+38, torch.float32),
      ranges=[1, 77, 77],
      origins={fill_}
    ))
  ))
  args[1]: 1
[2022-10-15 01:43:37,992] torchinductor.ir: [WARNING] Using FallbackKernel: torch.ops.aten.triu_.default
[2022-10-15 01:43:37,992] torchinductor.ir: [WARNING] DeviceCopy
[2022-10-15 01:43:43,374] torchinductor.compile_fx: [WARNING] skipping cudagraphs due to multiple devices
[2022-10-15 01:43:55,938] torchdynamo.symbolic_convert: [WARNING] Graph break: call_method GetAttrVariable(UserDefinedObjectVariable(Version), _regex) search [ConstantVariable(str)] {} from user code at   File "/home/ubuntu/miniconda3/envs/torchdynamo/
lib/python3.10/site-packages/diffusers/schedulers/scheduling_pndm.py", line 161, in set_timesteps
    deprecated_offset = deprecate(
  File "/home/ubuntu/miniconda3/envs/torchdynamo/lib/python3.10/site-packages/diffusers/utils/deprecation_utils.py", line 17, in deprecate
    if version.parse(version.parse(__version__).base_version) >= version.parse(version_name):
  File "/home/ubuntu/miniconda3/envs/torchdynamo/lib/python3.10/site-packages/packaging/version.py", line 49, in parse
    return Version(version)
  File "/home/ubuntu/miniconda3/envs/torchdynamo/lib/python3.10/site-packages/packaging/version.py", line 264, in __init__
    match = self._regex.search(version)

[2022-10-15 01:43:55,947] torchdynamo.symbolic_convert: [WARNING] Graph break: numpy from user code at   File "/home/ubuntu/miniconda3/envs/torchdynamo/lib/python3.10/site-packages/diffusers/schedulers/scheduling_pndm.py", line 170, in <graph break in
set_timesteps>
    self._timesteps = (np.arange(0, num_inference_steps) * step_ratio).round()

[2022-10-15 01:43:56,134] torchdynamo.symbolic_convert: [WARNING] Graph break: call_function in skip_files /home/ubuntu/miniconda3/envs/torchdynamo/lib/python3.10/site-packages/tqdm/asyncio.py from user code at   File "/home/ubuntu/miniconda3/envs/torc
hdynamo/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 559, in progress_bar
    return tqdm(iterable, **self._progress_bar_config)

  0%|
                                                                                       | 0/51 [00:00<?, ?it/s][2022-10-15 01:43:59,438] torchdynamo.symbolic_convert: [WARNING] Graph break: call_function UserDefinedClassVariable() [] {'sample': TensorVa
riable()} from user code at   File "/home/ubuntu/miniconda3/envs/torchdynamo/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 341, in forward
    return UNet2DConditionOutput(sample=sample)

[2022-10-15 01:47:47,542] torchdynamo.symbolic_convert: [WARNING] Graph break: inline __setitem__ from user code at   File "<string>", line 4, in <graph break in __init__>
  File "/home/ubuntu/miniconda3/envs/torchdynamo/lib/python3.10/site-packages/diffusers/utils/outputs.py", line 72, in __post_init__
    self[field.name] = v

[2022-10-15 01:47:47,550] torchdynamo.symbolic_convert: [WARNING] Graph break: non-function or method super: <slot wrapper '__setitem__' of 'collections.OrderedDict' objects> from user code at   File "/home/ubuntu/miniconda3/envs/torchdynamo/lib/python
3.10/site-packages/diffusers/utils/outputs.py", line 104, in __setitem__
    super().__setitem__(key, value)

[2022-10-15 01:47:47,553] torchdynamo.symbolic_convert: [WARNING] Graph break: non-function or method super: <slot wrapper '__setattr__' of 'object' objects> from user code at   File "/home/ubuntu/miniconda3/envs/torchdynamo/lib/python3.10/site-package
s/diffusers/utils/outputs.py", line 106, in <graph break in __setitem__>
    super().__setattr__(key, value)

[2022-10-15 01:47:47,565] torchdynamo.symbolic_convert: [WARNING] Graph break: data dependent operator: aten._local_scalar_dense.default from user code at   File "/home/ubuntu/miniconda3/envs/torchdynamo/lib/python3.10/site-packages/diffusers/scheduler
s/scheduling_pndm.py", line 225, in step
    return self.step_plms(model_output=model_output, timestep=timestep, sample=sample, return_dict=return_dict)
  File "/home/ubuntu/miniconda3/envs/torchdynamo/lib/python3.10/site-packages/diffusers/schedulers/scheduling_pndm.py", line 340, in step_plms
    prev_sample = self._get_prev_sample(sample, timestep, prev_timestep, model_output)
  File "/home/ubuntu/miniconda3/envs/torchdynamo/lib/python3.10/site-packages/diffusers/schedulers/scheduling_pndm.py", line 374, in _get_prev_sample
    alpha_prod_t = self.alphas_cumprod[timestep]

[2022-10-15 01:47:48,531] torchdynamo.symbolic_convert: [WARNING] Graph break: data dependent operator: aten._local_scalar_dense.default from user code at   File "/home/ubuntu/miniconda3/envs/torchdynamo/lib/python3.10/site-packages/diffusers/scheduler
s/scheduling_pndm.py", line 375, in <graph break in _get_prev_sample>
    alpha_prod_t_prev = self.alphas_cumprod[prev_timestep] if prev_timestep >= 0 else self.final_alpha_cumprod

[2022-10-15 01:47:49,100] torchinductor.compile_fx: [WARNING] skipping cudagraphs due to multiple devices
Segmentation fault (core dumped)
```

Expected result:
Example works with eager + aot_eager and successfully generates an image. Crashed with inductor.

Env info:
```
Collecting environment information...
PyTorch version: 1.14.0.dev20221014+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1020-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A10G
Nvidia driver version: 510.73.08
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.14.0.dev20221014+cu116
[pip3] torchdynamo==1.14.0.dev0
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] torch                     1.14.0.dev20221014+cu116          pypi_0    pypi
[conda] torchdynamo               1.14.0.dev0              pypi_0    pypi
```

**Comment by voznesenskym** [comment]
Can you run the minifier on this please?

**Comment by anijain2305** [comment]
@mreso These are my steps to make progress

* I ran it with `eager`, `aot_eager` backend. Both were passing. `inductor` failed with segfault.
* I ran with `TORCHDYNAMO_REPRO_AFTER="aot"` but nothing happened. And this was my mistake, I forgot to tell that for segfaults, we need to add one more flag. `TORCHDYNAMO_REPRO_AFTER="aot" TORCHDYNAMO_REPRO_LEVEL=4`
* With this, I got a small `minifier_launcher.py`. This minifier launcher got hung ... sigh. I will make changes so that either it does not hang or gracefully exits.
* I looked at `minifier_launcher.py` and manually added code to run inductor. And was able to get a segfault.

cc @mlazos for the debugging playbook edits.

This is the repro

~~~
import torch
from torch import tensor, device
import torch.fx as fx
from torch._dynamo.testing import rand_strided
from math import inf
from torch.fx.experimental.proxy_tensor import make_fx

# torch version: 1.14.0a0+git8a8cd09
# torch cuda version: 11.6
# torch git version: 8a8cd092c8537b226f5c38ed88bc07e181b0946c


# CUDA Info:
# nvcc: NVIDIA (R) Cuda compiler driver
# Copyright (c) 2005-2022 NVIDIA Corporation
# Built on Thu_Feb_10_18:23:41_PST_2022
# Cuda compilation tools, release 11.6, V11.6.112
# Build cuda_11.6.r11.6/compiler.30978841_0

# GPU Hardware Info:
# NVIDIA A100-SXM4-40GB : 2


from torch.nn import *
from torch._inductor.compile_fx import compile_fx_inner

class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer('_tensor_constant0', torch.randn([], dtype=torch.float32))
        self.register_buffer('_tensor_constant1', torch.randn([], dtype=torch.float32))



    def forward(self, arg0_1, arg1_1, arg2_1, arg3_1):
        _tensor_constant0 = self._tensor_constant0
        lift_fresh_copy = torch.ops.aten.lift_fresh_copy.default(_tensor_constant0);  _tensor_constant0 = None
        sub = torch.ops.aten.sub.Tensor(lift_fresh_copy, arg3_1);  lift_fresh_copy = None
        _tensor_constant1 = self._tensor_constant1
        lift_fresh_copy_1 = torch.ops.aten.lift_fresh_copy.default(_tensor_constant1);  _tensor_constant1 = None
        sub_1 = torch.ops.aten.sub.Tensor(lift_fresh_copy_1, arg0_1);  lift_fresh_copy_1 = None
        div = torch.ops.aten.div.Tensor(arg0_1, arg3_1)
        pow_1 = torch.ops.aten.pow.Tensor_Scalar(div, 0.5);  div = None
        pow_2 = torch.ops.aten.pow.Tensor_Scalar(sub_1, 0.5);  sub_1 = None
        mul = torch.ops.aten.mul.Tensor(arg3_1, pow_2);  pow_2 = None
        mul_1 = torch.ops.aten.mul.Tensor(arg3_1, sub);  sub = None
        mul_2 = torch.ops.aten.mul.Tensor(mul_1, arg0_1);  mul_1 = None
        pow_3 = torch.ops.aten.pow.Tensor_Scalar(mul_2, 0.5);  mul_2 = None
        add = torch.ops.aten.add.Tensor(mul, pow_3);  mul = pow_3 = None
        mul_3 = torch.ops.aten.mul.Tensor(pow_1, arg1_1);  pow_1 = arg1_1 = None
        sub_2 = torch.ops.aten.sub.Tensor(arg0_1, arg3_1);  arg0_1 = arg3_1 = None
        mul_4 = torch.ops.aten.mul.Tensor(sub_2, arg2_1);  sub_2 = arg2_1 = None
        div_1 = torch.ops.aten.div.Tensor(mul_4, add);  mul_4 = add = None
        sub_3 = torch.ops.aten.sub.Tensor(mul_3, div_1);  mul_3 = div_1 = None
        return (sub_3,)

args = [((), (), torch.float32, 'cpu'), ((1, 4, 64, 64), (16384, 4096, 64, 1), torch.float32, 'cuda'), ((1, 4, 64, 64), (16384, 4096, 64, 1), torch.float32, 'cuda'), ((), (), torch.float32, 'cuda')]
args = [rand_strided(sh, st, dt, dev) for (sh, st, dt, dev) in args]
mod = make_fx(Repro().to(device="cuda"))(*args)

opt_mod = compile_fx_inner(mod, args)
opt_mod(args)
~~~

**Comment by anijain2305** [comment]
cc @ngimel @Chillee for the actual segfault with inductor.

**Comment by ngimel** [comment]
Codegen generates buf0 on cpu and passes it to triton kernel:
```
buf0 = empty_strided((1, s0, s1, s1), (s0*(s1*s1), s1*s1, s1, 1), device='cpu', dtype=torch.float32)
```

**Comment by ngimel** [comment]
@yanboliang we were supposed to copy all 0d cpu args to gpu? arg0_1 is on cpu

**Comment by ngimel** [comment]
0d scalar handling is dead wrong (why didn't OpInfo catch this? Probably we are not running all samples yet). 

```
@torchdynamo.optimize("inductor")
def div(x, y):
    return torch.ops.aten.div(x, y)

x = torch.tensor(3., dtype=torch.float, device="cpu")
y = torch.randn(4, dtype=torch.float, device="cuda")
print(div(x,y))
```

**Comment by penguinwu** [comment]
"I ran with TORCHDYNAMO_REPRO_AFTER="aot" but nothing happened. And this was my mistake, I forgot to tell that for segfaults, we need to add one more flag. TORCHDYNAMO_REPRO_AFTER="aot" TORCHDYNAMO_REPRO_LEVEL=4"

@mlazos Could the rageshaker tool be smart enough to know to enable TORCHDYNAMO_REPRO_LEVEL=4 based on error types?

**Comment by yanboliang** [comment]
> @yanboliang we were supposed to copy all 0d cpu args to gpu? arg0_1 is on cpu

Yes, that's what we did now. We can't tell the if the 0d tensor is converted from unspecialized variable or user's explicit input at inductor level.

**Comment by mlazos** [comment]
> "I ran with TORCHDYNAMO_REPRO_AFTER="aot" but nothing happened. And this was my mistake, I forgot to tell that for segfaults, we need to add one more flag. TORCHDYNAMO_REPRO_AFTER="aot" TORCHDYNAMO_REPRO_LEVEL=4"
> 
> @mlazos Could the rageshaker tool be smart enough to know to enable TORCHDYNAMO_REPRO_LEVEL=4 based on error types?

I'm not sure how segfaults are detected, if the whole program (with dynamo) crashes, I'm not sure how the minifier can be triggered after this event. I do think we can automatically disambiguate with the other error levels though.

**Comment by anijain2305** [comment]
Another segfault related to 0d tensors. This one affects longformer models

~~~


import torch
from torch import tensor, device
import torch.fx as fx
from torch._dynamo.testing import rand_strided
from math import inf
from torch.fx.experimental.proxy_tensor import make_fx

# torch version: 1.14.0a0+git8a8cd09
# torch cuda version: 11.6
# torch git version: 8a8cd092c8537b226f5c38ed88bc07e181b0946c


# CUDA Info:
# nvcc: NVIDIA (R) Cuda compiler driver
# Copyright (c) 2005-2022 NVIDIA Corporation
# Built on Thu_Feb_10_18:23:41_PST_2022
# Cuda compilation tools, release 11.6, V11.6.112
# Build cuda_11.6.r11.6/compiler.30978841_0

# GPU Hardware Info:
# NVIDIA A100-SXM4-40GB : 2


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()



    def forward(self, primals_1, primals_2):
        unsqueeze = torch.ops.aten.unsqueeze.default(primals_1, 4);  primals_1 = None
        permute = torch.ops.aten.permute.default(unsqueeze, [0, 1, 2, 4, 3])
        permute_1 = torch.ops.aten.permute.default(unsqueeze, [0, 1, 4, 2, 3]);  unsqueeze = None
        permute_2 = torch.ops.aten.permute.default(permute, [0, 1, 2, 4, 3]);  permute = None
        clone = torch.ops.aten.clone.default(permute_2, memory_format = torch.contiguous_format);  permute_2 = None
        _unsafe_view = torch.ops.aten._unsafe_view.default(clone, [36, 512, 64]);  clone = None
        permute_3 = torch.ops.aten.permute.default(permute_1, [0, 1, 4, 3, 2]);  permute_1 = None
        clone_1 = torch.ops.aten.clone.default(permute_3, memory_format = torch.contiguous_format);  permute_3 = None
        _unsafe_view_1 = torch.ops.aten._unsafe_view.default(clone_1, [36, 64, 512]);  clone_1 = None
        bmm = torch.ops.aten.bmm.default(_unsafe_view, _unsafe_view_1)
        view = torch.ops.aten.view.default(bmm, [12, 3, 512, 1, 512]);  bmm = None
        permute_4 = torch.ops.aten.permute.default(view, [0, 1, 2, 4, 3]);  view = None
        sum_1 = torch.ops.aten.sum.dim_IntList(permute_4, [4]);  permute_4 = None
        constant_pad_nd = torch.ops.aten.constant_pad_nd.default(sum_1, [0, 0, 0, 1], 0.0);  sum_1 = None
        view_1 = torch.ops.aten.view.default(constant_pad_nd, [12, 3, 512, 513]);  constant_pad_nd = None
        add = torch.ops.aten.add.Tensor(primals_2, 1);  primals_2 = None
        permute_6 = torch.ops.aten.permute.default(_unsafe_view, [0, 2, 1]);  _unsafe_view = None
        permute_7 = torch.ops.aten.permute.default(_unsafe_view_1, [0, 2, 1]);  _unsafe_view_1 = None
        return [view_1, add, permute_6, permute_7]

args = [((12, 3, 512, 64), (64, 196608, 768, 1), torch.float32, 'cuda'), ((), (), torch.int64, 'cpu')]
args = [rand_strided(sh, st, dt, dev) for (sh, st, dt, dev) in args]
mod = make_fx(Repro().to(device="cuda"))(*args)

from torch._inductor.compile_fx import compile_fx_inner
opt_mod = compile_fx_inner(mod, args)
opt_mod(args)
~~~

**Comment by anijain2305** [comment]
Opening so that @mreso can check and see if he finds more bugs.

**Comment by ngimel** [comment]
@anijain2305 your segfault is different, as we've discussed yesterday. Hopefully @yanboliang can disable copying of 0d cpu tensors, that should fix it.

**Comment by anijain2305** [comment]
@ngimel Yup. I reopened the bug just for @mreso to continue the thread for diffusers end-to-end inference.

**Comment by yanboliang** [comment]
@anijain2305 https://github.com/pytorch/pytorch/pull/87329 fixed your repro for longformer models.

**Comment by mreso** [comment]
Thanks @anijain2305 & @ngimel, I can now successfully run my example with inductor and qualitatively get the same result as in eager mode! 
But I am experiencing quite some non deterministic runtime errors (~50% of the times when running with inductor). I observed two flavors. 

First error is:
```
RuntimeError: Triton Error [CUDA]: an illegal memory access was encountered
```

Its much more frequent than the second which is:
```
RuntimeError: CUDA: Error- illegal address
+
RuntimeError: false INTERNAL ASSERT FAILED at "../c10/cuda/CUDAGraphsC10Utils.h":73, please report a bug to PyTorch. Unknown CUDA graph CaptureStatus32650
```

Any thoughts on how I can help to collect more data or could create more reliable repros?

I collected the stack traces of the failed attempts here: https://gist.github.com/mreso/982ef0b4c915eea6170fd81f0de16e98
Example for the first error is:
```
Traceback (most recent call last):
  File "/home/mreso/torchdynamo/test.py", line 40, in <module>
    image = apply(prompt).images[0]
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/home/mreso/torchdynamo/test.py", line 29, in apply
    return pipe(x)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 214, in __call__
    text_inputs = self.tokenizer(
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 269, in <graph break in __call__>
    uncond_embeddings = self.text_encoder(uncond_input.input_ids.to(self.device))[0]
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1357, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py", line 705, in forward
    @add_start_docstrings_to_model_forward(CLIP_TEXT_INPUTS_DOCSTRING)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 870, in forward
    return compiled_f(
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 861, in new_func
    return compiled_fn(args)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 299, in new_fn
    fw_outs = call_func_with_args(compiled_fw, args, disable_amp=disable_amp)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 255, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 194, in run
    return model(new_inputs_to_cuda)
  File "/tmp/torchinductor_mreso/qt/cqt3tpyb2awwxhp3vhrmtamvb6b57ctovraioa5mbqzemitewns2.py", line 915, in call
    kernel2.run(arg197_1, arg0_1, arg196_1, arg1_1, arg2_1, arg3_1, buf7, 77, 768, grid=grid(77), stream=stream0)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 170, in run
    result = launcher(
  File "<string>", line 4, in launcher
RuntimeError: Triton Error [CUDA]: an illegal memory access was encountered
```
For the second error its:
```
[2022-10-21 00:11:28,203] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT forward /home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/diffusers/models/unet_2d_condition.py line 232
due to:
Traceback (most recent call last):
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 401, in clone_input
    result.copy_(x.clone())
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 410, in clone_input
    y = torch.clone(x)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

from user code:
   File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/diffusers/models/unet_2d_condition.py", line 286, in forward
    t_emb = t_emb.to(dtype=self.dtype)

Set torch._dynamo.config.verbose=True for more information
==========
  0%|                                                                                                                                                                                                                                                                                                                                              | 0/51 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 65, in preserve_rng_state
    yield
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 579, in create_aot_dispatcher_function
    return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 295, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 85, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 362, in fw_compiler
    return compile_fx_inner(
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 464, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_inductor/debug.py", line 178, in inner
    return fn(*args, **kwargs)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 127, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_inductor/graph.py", line 339, in compile_to_fn
    return self.compile_to_module().call
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 85, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_inductor/graph.py", line 329, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 212, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_mreso/gb/cgb5kyxk5qcj67xbzxmiuwpxlrcjspq7dyscbrllcrgknkoahswm.py", line 94, in <module>
    async_compile.wait(globals())
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 352, in wait
    scope[key] = result.result()
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 260, in result
    kernel = self.kernel = _load_kernel(self.source_code)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 246, in _load_kernel
    kernel.precompile()
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 58, in precompile
    self.launchers = [
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 59, in <listcomp>
    self._precompile_config(c, warm_cache_only_with_cc)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 83, in _precompile_config
    binary = triton.compile(
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/triton/compiler.py", line 1263, in compile
    return CompiledKernel(name, so_cache_manager._make_path(so_name), fn_cache_manager.cache_dir, device)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/triton/compiler.py", line 1296, in __init__
    mod, func, n_regs, n_spills = _triton.code_gen.load_binary(metadata["name"], self.asm["cubin"], self.shared, device)
RuntimeError: CUDA: Error- illegal address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mreso/torchdynamo/test.py", line 24, in <module>
    image = apply(prompt).images[0]
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/home/mreso/torchdynamo/test.py", line 21, in apply
    return pipe(x)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 214, in __call__
    text_inputs = self.tokenizer(
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 326, in <graph break in __call__>
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1357, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/diffusers/models/unet_2d_condition.py", line 281, in forward
    t_emb = self.time_proj(timesteps)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1357, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/diffusers/models/embeddings.py", line 91, in forward
    def forward(self, timesteps):
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 870, in forward
    return compiled_f(
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 856, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 579, in create_aot_dispatcher_function
    return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 69, in preserve_rng_state
    torch.cuda.set_rng_state(cuda_rng_state)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/cuda/random.py", line 64, in set_rng_state
    _lazy_call(cb)
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/cuda/__init__.py", line 176, in _lazy_call
    callable()
  File "/home/mreso/miniconda3/envs/torchdynamo2/lib/python3.9/site-packages/torch/cuda/random.py", line 62, in cb
    default_generator.set_state(new_state_copy)
RuntimeError: false INTERNAL ASSERT FAILED at "../c10/cuda/CUDAGraphsC10Utils.h":73, please report a bug to PyTorch. Unknown CUDA graph CaptureStatus32650
```

**Comment by soumith** [comment]
@mreso can you open a new issue for these intermittent cudagraphs errors. I saw them too last night -- exactly the same set of errors.

**Comment by ngimel** [comment]
@mreso can you try running with cuda graphs disabled and with PYTORCH_NO_CUDA_MEMORY_CACHING=1 ?

**Comment by mreso** [comment]
@soumith sure, I created #1743 to track this issue now

@ngimel how do I disable cuda graphs?

**Comment by ngimel** [comment]
In `_inductor/config.py`, or set `torch._inductor.config.triton.cudagraphs=False`
