### ISSUE TITLE
examples/imagenet failing

### ISSUE THREAD

**Issue by soumith** [pytorch/torchdynamo#1687]
This is the diff of me taking examples/imagenet and modifying it to include `dynamo`:

```python
diff --git a/imagenet/main.py b/imagenet/main.py
index e828ea0..3e47c92 100644
--- a/imagenet/main.py
+++ b/imagenet/main.py
@@ -7,6 +7,7 @@ import warnings
 from enum import Enum

 import torch
+import torch._dynamo as dynamo
 import torch.backends.cudnn as cudnn
 import torch.distributed as dist
 import torch.multiprocessing as mp
@@ -266,6 +267,8 @@ def main_worker(gpu, ngpus_per_node, args):
         val_dataset, batch_size=args.batch_size, shuffle=False,
         num_workers=args.workers, pin_memory=True, sampler=val_sampler)

+    model = dynamo.optimize()(model)
+
     if args.evaluate:
         validate(val_loader, model, criterion, args)
         return
```

This is the failure:

```
$ python main.py /home/soumith/dataset/imagenet
/home/soumith/code/vision/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension:
  warn(f"Failed to load image Python extension: {e}")
=> creating model 'resnet18'
WARNING:torch._inductor.lowering:make_fallback(aten.unfold): a decomposition exists, we should switch to it
WARNING:torch._inductor.lowering:make_fallback(aten.unfold_backward): a decomposition exists, we should switch to it
Epoch: [0][   1/5005]   Time 11.746 (11.746)    Data  2.157 ( 2.157)    Loss 7.0818e+00 (7.0818e+00)    Acc@1   0.00 (  0.00)   Acc@5   0.00 (  0.00)
Traceback (most recent call last):
  File "/home/soumith/code/examples/imagenet/main.py", line 514, in <module>
    main()
  File "/home/soumith/code/examples/imagenet/main.py", line 121, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "/home/soumith/code/examples/imagenet/main.py", line 281, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, device, args)
  File "/home/soumith/code/examples/imagenet/main.py", line 328, in train
    output = model(images)
  File "/home/soumith/code/pytorch/torch/_dynamo/eval_frame.py", line 137, in __call__
    return self.forward(*args, **kwargs)
  File "/home/soumith/code/pytorch/torch/_dynamo/eval_frame.py", line 134, in forward
    return optimized_forward(*args, **kwargs)
  File "/home/soumith/code/pytorch/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/home/soumith/code/pytorch/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/soumith/code/pytorch/torch/nn/modules/module.py", line 1357, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/soumith/code/vision/torchvision/models/resnet.py", line 284, in forward
    def forward(self, x: Tensor) -> Tensor:
  File "/home/soumith/code/pytorch/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/home/soumith/code/pytorch/functorch/_src/aot_autograd.py", line 856, in forward
    return compiled_f(
  File "/home/soumith/code/pytorch/functorch/_src/aot_autograd.py", line 847, in new_func
    return compiled_fn(args)
  File "/home/soumith/code/pytorch/functorch/_src/aot_autograd.py", line 230, in g
    return f(*args)
  File "/home/soumith/code/pytorch/functorch/_src/aot_autograd.py", line 475, in compiled_function
    return CompiledFunction.apply(*remove_dupe_args(args))
RuntimeError: A view was created in no_grad mode and its base or another view of its base has been modified inplace with grad mode enabled. Given that this use case is ambiguous and error-prone, it is forbidden. You can clarify your code by moving both the view and the inplace either both inside the no_grad block (if you don't want the inplace to be tracked) or both outside (if you want the inplace to be tracked).
```

## What works?

- `dynamo.optimize('eager')(model)` works fine and runs without error.
- dynamo.optimize('aot_eager')(model)` also works fine and runs without error

## Minifying

Here's my attempt to minify and didn't really see anything minified come out:

**Attempt 1:** 

```
$ TORCHDYNAMO_REPRO_AFTER="dynamo" python main.py /home/soumith/dataset/imagenet
[exactly same output as above]
```

**Attempt 2:** 
```
$ TORCHDYNAMO_REPRO_AFTER="aot" python main.py /home/soumith/dataset/imagenet
/home/soumith/code/vision/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension:
  warn(f"Failed to load image Python extension: {e}")
=> creating model 'resnet18'
WARNING:torch._inductor.lowering:make_fallback(aten.unfold): a decomposition exists, we should switch to it
WARNING:torch._inductor.lowering:make_fallback(aten.unfold_backward): a decomposition exists, we should switch to it
Epoch: [0][   1/5005]   Time 11.820 (11.820)    Data  1.918 ( 1.918)    Loss 6.9964e+00 (6.9964e+00)    Acc@1   0.00 (  0.00)   Acc@5   0.00 (  0.00)
WARNING:torch._dynamo.debug_utils:Writing minified repro to /tmp/minifier_soumith/minifier_launcher.py
WARNING:torch._dynamo.debug_utils:Copying minified repro from /tmp/minifier_soumith/minifier_launcher.py to /home/soumith/code/pytorch/minifier_launch
er.py for convenience
Traceback (most recent call last):
  File "/home/soumith/code/pytorch/torch/fx/interpreter.py", line 199, in placeholder
    return next(self.args_iter)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/soumith/code/examples/imagenet/main.py", line 514, in <module>
    main()
  File "/home/soumith/code/examples/imagenet/main.py", line 121, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "/home/soumith/code/examples/imagenet/main.py", line 281, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, device, args)
  File "/home/soumith/code/examples/imagenet/main.py", line 339, in train
    loss.backward()
  File "/home/soumith/code/pytorch/torch/_tensor.py", line 488, in backward
   torch.autograd.backward(
  File "/home/soumith/code/pytorch/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/soumith/code/pytorch/torch/autograd/function.py", line 270, in apply
    return user_fn(self, *args)
  File "/home/soumith/code/pytorch/functorch/_src/aot_autograd.py", line 468, in backward
    out = call_func_with_args(
  File "/home/soumith/code/pytorch/functorch/_src/aot_autograd.py", line 255, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/home/soumith/code/pytorch/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/home/soumith/code/pytorch/torch/_dynamo/debug_utils.py", line 444, in deferred_for_real_inputs
    raise e
  File "/home/soumith/code/pytorch/torch/_dynamo/debug_utils.py", line 428, in deferred_for_real_inputs
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/soumith/code/pytorch/torch/_inductor/debug.py", line 178, in inner
    return fn(*args, **kwargs)
  File "/home/soumith/miniconda3/envs/pytorch/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/soumith/code/pytorch/torch/_inductor/compile_fx.py", line 106, in compile_fx_inner
    graph.run(*example_inputs)
  File "/home/soumith/code/pytorch/torch/_dynamo/utils.py", line 85, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/soumith/code/pytorch/torch/_inductor/graph.py", line 143, in run
    return super().run(*args)
  File "/home/soumith/code/pytorch/torch/fx/interpreter.py", line 130, in run
    self.env[node] = self.run_node(node)
  File "/home/soumith/code/pytorch/torch/_inductor/graph.py", line 311, in run_node
    result = super().run_node(n)
  File "/home/soumith/code/pytorch/torch/fx/interpreter.py", line 171, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/soumith/code/pytorch/torch/_inductor/graph.py", line 208, in placeholder
    example: torch.Tensor = super().placeholder(target, args, kwargs)
  File "/home/soumith/code/pytorch/torch/fx/interpreter.py", line 204, in placeholder
    raise RuntimeError(f'Expected positional argument for parameter {target}, but one was not passed in!')
RuntimeError: Expected positional argument for parameter primals_1, but one was not passed in!

While executing %primals_1 : [#users=1] = placeholder[target=primals_1]
Original traceback:
None
```

## System Info
Latest PyTorch built from source, pinned Triton, CUDA 11.6, single GTX 3090.

```
Collecting environment information...
PyTorch version: 1.14.0a0+git054a2fd
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.9.13 (main, Oct 13 2022, 21:15:33)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-50-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] torch==1.14.0a0+git054a2fd
[pip3] torchvision==0.15.0a0+f467349
[conda] blas                      1.0                         mkl
```

**Comment by soumith** [comment]
Just to confirm that `DataParallel` wasn't the root cause, I ran the same command with `DataParallel` disabled, by providing `--gpu 0`, and confirmed that the model wasn't wrapped in any data parallelism.
The same error persisted.

```
$ python main.py --gpu 0 /home/soumith/dataset/imagenet
/home/soumith/code/vision/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension:
  warn(f"Failed to load image Python extension: {e}")
/home/soumith/code/examples/imagenet/main.py:100: UserWarning: You have chosen a specific GPU. This will completely disable data parallelism.
  warnings.warn('You have chosen a specific GPU. This will completely '
Use GPU: 0 for training
=> creating model 'resnet18'
WARNING:torch._inductor.lowering:make_fallback(aten.unfold): a decomposition exists, we should switch to it
WARNING:torch._inductor.lowering:make_fallback(aten.unfold_backward): a decomposition exists, we should switch to it
Epoch: [0][   1/5005]   Time 11.536 (11.536)    Data  1.817 ( 1.817)    Loss 7.0478e+00 (7.0478e+00)    Acc@1   0.00 (  0.00)   Acc@5   0.39 (  0.39)
Traceback (most recent call last):
  File "/home/soumith/code/examples/imagenet/main.py", line 515, in <module>
    main()
  File "/home/soumith/code/examples/imagenet/main.py", line 121, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "/home/soumith/code/examples/imagenet/main.py", line 282, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, device, args)
  File "/home/soumith/code/examples/imagenet/main.py", line 329, in train
    output = model(images)
  File "/home/soumith/code/pytorch/torch/_dynamo/eval_frame.py", line 137, in __call__
    return self.forward(*args, **kwargs)
  File "/home/soumith/code/pytorch/torch/_dynamo/eval_frame.py", line 134, in forward
    return optimized_forward(*args, **kwargs)
  File "/home/soumith/code/pytorch/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/home/soumith/code/vision/torchvision/models/resnet.py", line 284, in forward
    def forward(self, x: Tensor) -> Tensor:
  File "/home/soumith/code/pytorch/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/home/soumith/code/pytorch/functorch/_src/aot_autograd.py", line 856, in forward
    return compiled_f(
  File "/home/soumith/code/pytorch/functorch/_src/aot_autograd.py", line 847, in new_func
    return compiled_fn(args)
  File "/home/soumith/code/pytorch/functorch/_src/aot_autograd.py", line 230, in g
    return f(*args)
  File "/home/soumith/code/pytorch/functorch/_src/aot_autograd.py", line 475, in compiled_function
    return CompiledFunction.apply(*remove_dupe_args(args))
RuntimeError: A view was created in no_grad mode and its base or another view of its base has been modified inplace with grad mode enabled. Given that this use case is ambiguous and error-prone, it is forbidden. You can clarify your code by moving both the view and the inplace either both inside the no_grad block (if you don't want the inplace to be tracked) or both outside (if you want the inplace to be tracked).

**Comment by soumith** [comment]
Manually minimized the example to:

```
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch._dynamo as dynamo
import torch.optim

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, 3, 1)
        self.fc1 = nn.Linear(21632, 128)

    def forward(self, x):
        x = self.conv1(x)
        x = torch.flatten(x, 1)
        x = self.fc1(x)
        return x


device = torch.device('cuda:0')
images = torch.randn(10, 1, 28, 28, device=device)

model = Net().cuda()
optimizer = torch.optim.SGD(model.parameters(), 0.001)

model = dynamo.optimize()(model)


for i in range(2):
    output = model(images)
    optimizer.zero_grad()
    output.sum().backward()
    optimizer.step()
    print('iter')
```

**Comment by soumith** [comment]
the second iteration of `model(images)` fails, and it only fails if `optimizer.step()` is done in the first iteration

**Comment by yanboliang** [comment]
I had encountered similar issue [before](https://github.com/pytorch/torchdynamo/issues/1189#issuecomment-1243226980).  I tested this minimized example and found it has the same symptom: error only on GPU, CPU works well.

**Comment by anijain2305** [comment]
So, the issue is somewhere in `cudagraphify_impl` of TorchInductor. Adding these two lines pass the testcase

~~~
import torch._inductor.config as inductor_config
inductor_config.triton.cudagraphs = False
~~~

@jansel @eellison you might have a better idea.

**Comment by jansel** [comment]
Perhaps the view is from `index_expanded_dims` which takes a slice. Or the `as_strided` call.

Managing grads/views feels like something AotAutograd should handle even if the backend takes a view.  Also, I'd expect functionalization to remove the mutation.  

@Chillee any ideas, I seem to recall you talking about a similar issue.

**Comment by anijain2305** [comment]
These are the fwd/bwd graphs from AOT Autograd (and these are sent to `compile_fx_inner`)

~~~
====== Forward graph ======
class GraphModule(torch.nn.Module):
    def forward(self, primals_1: f32[32, 1, 3, 3], primals_2: f32[32], primals_3: f32[128, 21632], primals_4: f32[128], primals_5: f32[10, 1, 28, 28]):
        # Module stack: {'self_conv1': 'Conv2d'}, File: /scratch/anijain/work/pytorch/soumith.py:22, code: x = self.conv1(x)
        convolution: f32[10, 32, 26, 26] = torch.ops.aten.convolution.default(primals_5, primals_1, primals_2, [1, 1], [0, 0], [1, 1], False, [0, 0], 1);  primals_2 = None

        # Module stack: {}, File: /scratch/anijain/work/pytorch/soumith.py:23, code: x = torch.flatten(x, 1)
        view: f32[10, 21632] = torch.ops.aten.view.default(convolution, [10, 21632]);  convolution = None

        # Module stack: {'self_fc1': 'Linear'}, File: /scratch/anijain/work/pytorch/soumith.py:24, code: x = self.fc1(x)
        permute: f32[21632, 128] = torch.ops.aten.permute.default(primals_3, [1, 0]);  primals_3 = None
        addmm: f32[10, 128] = torch.ops.aten.addmm.default(primals_4, view, permute);  primals_4 = None
        permute_1: f32[128, 21632] = torch.ops.aten.permute.default(permute, [1, 0]);  permute = None
        return [addmm, primals_1, primals_5, view, permute_1]

====== Backward graph ======
class GraphModule(torch.nn.Module):
    def forward(self, primals_1: f32[32, 1, 3, 3], primals_5: f32[10, 1, 28, 28], view: f32[10, 21632], permute_1: f32[128, 21632], tangents_1: f32[10, 128]):
        # Module stack: {'self_fc1': 'Linear'}, File: /scratch/anijain/work/pytorch/soumith.py:24, code: x = self.fc1(x)
        mm: f32[10, 21632] = torch.ops.aten.mm.default(tangents_1, permute_1);  permute_1 = None
        permute_2: f32[128, 10] = torch.ops.aten.permute.default(tangents_1, [1, 0])
        mm_1: f32[128, 21632] = torch.ops.aten.mm.default(permute_2, view);  permute_2 = view = None
        permute_3: f32[21632, 128] = torch.ops.aten.permute.default(mm_1, [1, 0]);  mm_1 = None
        sum_1: f32[1, 128] = torch.ops.aten.sum.dim_IntList(tangents_1, [0], True);  tangents_1 = None
        view_1: f32[128] = torch.ops.aten.view.default(sum_1, [128]);  sum_1 = None
        permute_4: f32[128, 21632] = torch.ops.aten.permute.default(permute_3, [1, 0]);  permute_3 = None

        # Module stack: {}, File: /scratch/anijain/work/pytorch/soumith.py:23, code: x = torch.flatten(x, 1)
        view_2: f32[10, 32, 26, 26] = torch.ops.aten.view.default(mm, [10, 32, 26, 26]);  mm = None

        # Module stack: {'self_conv1': 'Conv2d'}, File: /scratch/anijain/work/pytorch/soumith.py:22, code: x = self.conv1(x)
        convolution_backward = torch.ops.aten.convolution_backward.default(view_2, primals_5, primals_1, [32], [1, 1], [0, 0], [1, 1], False, [0, 0], 1, [False, True, True]);  view_2 = primals_5 = primals_1 = None
        getitem_1: f32[32, 1, 3, 3] = convolution_backward[1]
        getitem_2: f32[32] = convolution_backward[2];  convolution_backward = None
        return [getitem_1, getitem_2, permute_4, view_1, None]
 ~~~

**Comment by anijain2305** [comment]
And the mutation is coming from the `optimizer.step()`. Replaced the `step` with relavant portion here

~~~
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch._dynamo as dynamo
import torch.optim
import torch._dynamo as dynamo

# Added debug flags
import torch._inductor.config as inductor_config
# inductor_config.triton.cudagraphs = False
import functorch.compile
functorch.compile.config.debug_graphs = True


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, 3, 1)
        self.fc1 = nn.Linear(21632, 128)

    def forward(self, x):
        x = self.conv1(x)
        x = torch.flatten(x, 1)
        x = self.fc1(x)
        return x


device = torch.device('cuda:0')
images = torch.randn(10, 1, 28, 28, device=device)

model = Net().cuda()
optimizer = torch.optim.SGD(model.parameters(), 0.001)

model = dynamo.optimize()(model)


for i in range(2):
    output = model(images)
    optimizer.zero_grad()
    output.sum().backward()
    with torch.no_grad():
        for param in model.parameters():
            param.add_(1.0)

    # optimizer.step()
    print('iter')
~~~

**Comment by soumith** [comment]
Here's a more simplified / minimalist version.
The `nn` version below fails, but the same thing implemented as functions passes.

1. Failing

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch._dynamo as dynamo
import torch._inductor as inductor
import torch.optim

device = torch.device('cuda:0')

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.weight1 = nn.Parameter(torch.randn(10, 20, requires_grad=True))
        self.weight2 = nn.Parameter(torch.randn(20, 30, requires_grad=True))

    def forward(self, x):
        x = torch.matmul(x, self.weight1)
        x = torch.matmul(x, self.weight2)                   # failing to execute this line on the second iter
        return x


input = torch.randn(10, 10, device=device)

model = Net().cuda()
model = dynamo.optimize()(model)


for i in range(2):
    output = model(input)
    output.sum().backward()
    with torch.no_grad():
        for param in model.parameters():
            param.add_(1.0)


    print('iter')
```

2. Passing

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch._dynamo as dynamo
import torch._inductor as inductor
import torch.optim

device = torch.device('cuda:0')


def model(x, weight1, weight2):
    x = torch.matmul(x, weight1)
    x = torch.matmul(x, weight2)
    return x

weight1 = torch.randn(10, 20, requires_grad=True, device=device)
weight2 = torch.randn(20, 30, requires_grad=True, device=device)
input = torch.randn(10, 10, device=device)

model = dynamo.optimize()(model)


for i in range(2):
    output = model(input, weight1, weight2)
    output.sum().backward()
    with torch.no_grad():
        weight1.add_(1.0)
        weight2.add_(1.0)
    print('iter')
```

**Comment by soumith** [comment]
I'm more certain now that this is an Inductor bug.

In the failing "nn.Module" case (1), and in the passing "Function" case (2), the `fwd/bwd graphs from AOT Autograd` are exactly the same (I canonicalized the variable names manually:

Failing code snippet (1) from previous comment:

```
====== Forward graph ======
class GraphModule(torch.nn.Module):
    def forward(self, primals_1: f32[10, 20], primals_2: f32[20, 30], primals_3: f32[10, 10]):
        # Module stack: {}, File: /home/soumith/code/examples/imagenet/sample.py:22, code: x = torch.matmul(x, self.weight1)
        mm: f32[10, 20] = torch.ops.aten.mm.default(primals_3, primals_1);  primals_1 = None

        # Module stack: {}, File: /home/soumith/code/examples/imagenet/sample.py:23, code: x = torch.matmul(x, self.weight2)
        mm_1: f32[10, 30] = torch.ops.aten.mm.default(mm, primals_2)
        permute: f32[20, 10] = torch.ops.aten.permute.default(mm, [1, 0]);  mm = None
        permute_1: f32[30, 20] = torch.ops.aten.permute.default(primals_2, [1, 0]);  primals_2 = None

        # Module stack: {}, File: /home/soumith/code/examples/imagenet/sample.py:22, code: x = torch.matmul(x, self.weight1)
        permute_2: f32[10, 10] = torch.ops.aten.permute.default(primals_3, [1, 0]);  primals_3 = None
        return [mm_1, permute, permute_1, permute_2]

====== Backward graph ======
class GraphModule(torch.nn.Module):
    def forward(self, permute: f32[20, 10], permute_1: f32[30, 20], permute_2: f32[10, 10], tangents_1: f32[10, 30]):
        # Module stack: {}, File: /home/soumith/code/examples/imagenet/sample.py:23, code: x = torch.matmul(x, self.weight2)
        mm_2: f32[20, 30] = torch.ops.aten.mm.default(permute, tangents_1);  permute = None
        mm_3: f32[10, 20] = torch.ops.aten.mm.default(tangents_1, permute_1);  tangents_1 = permute_1 = None

        # Module stack: {}, File: /home/soumith/code/examples/imagenet/sample.py:22, code: x = torch.matmul(x, self.weight1)
        mm_4: f32[10, 20] = torch.ops.aten.mm.default(permute_2, mm_3);  permute_2 = mm_3 = None
        return [mm_4, mm_2, None]
```

Passing code snippet 2:

```
====== Forward graph ======
class GraphModule(torch.nn.Module):
    def forward(self, primals_3: f32[10, 10], primals_1: f32[10, 20], primals_2: f32[20, 30]):
        # Module stack: {}, File: /home/soumith/code/examples/imagenet/sample2.py:17, code: x = torch.matmul(x, weight1)
        mm: f32[10, 20] = torch.ops.aten.mm.default(primals_3, primals_1);  primals_1 = None

        # Module stack: {}, File: /home/soumith/code/examples/imagenet/sample2.py:18, code: x = torch.matmul(x, weight2)
        mm_1: f32[10, 30] = torch.ops.aten.mm.default(mm, primals_2)
        permute: f32[20, 10] = torch.ops.aten.permute.default(mm, [1, 0]);  mm = None
        permute_1: f32[30, 20] = torch.ops.aten.permute.default(primals_2, [1, 0]);  primals_2 = None

        # Module stack: {}, File: /home/soumith/code/examples/imagenet/sample2.py:17, code: x = torch.matmul(x, weight1)
        permute_2: f32[10, 10] = torch.ops.aten.permute.default(primals_3, [1, 0]);  primals_3 = None
        return [mm_1, permute, permute_1, permute_2]

====== Backward graph ======
class GraphModule(torch.nn.Module):
    def forward(self, permute: f32[20, 10], permute_1: f32[30, 20], permute_2: f32[10, 10], tangents_1: f32[10, 30]):
        # Module stack: {}, File: /home/soumith/code/examples/imagenet/sample2.py:18, code: x = torch.matmul(x, weight2)
        mm_2: f32[20, 30] = torch.ops.aten.mm.default(permute, tangents_1);  permute = None
        mm_3: f32[10, 20] = torch.ops.aten.mm.default(tangents_1, permute_1);  tangents_1 = permute_1 = None

        # Module stack: {}, File: /home/soumith/code/examples/imagenet/sample2.py:17, code: x = torch.matmul(x, weight1)
        mm_4: f32[10, 20] = torch.ops.aten.mm.default(permute_2, mm_3);  permute_2 = mm_3 = None
        return [mm_4, mm_2, None]
```

**Comment by soumith** [comment]
i take back that it might be an inductor bug. the inductor dumps from `TORCHINDUCTOR_TRACE=1` look the exact same for both examples

**Comment by ngimel** [comment]
as @anijain2305 said, this looks like a bug in `cudagraphify` in inductor (that won't affect any of `TORCHINDUCTOR_TRACE=1` dumps), as disabling cudagraphs fixes this minimum example also.
