### ISSUE TITLE
TorchBench model training failure: tacotron2

### ISSUE THREAD

**Issue by yanboliang** [pytorch/torchdynamo#1693]
Repro:
```
benchmarks/torchbench.py -d cuda --inductor --training --float32 --accuracy --no-skip --only tacotron2
```

There are several errors in different graphs:
Error1:
```
Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/common.py", line 1164, in check_accuracy
    new_result = optimized_model_iter_fn(model, example_inputs)
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/eval_frame.py", line 163, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/torchbench.py", line 330, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/torchbench.py", line 331, in <graph break in forward_and_backward_pass>
    cloned_inputs = clone_inputs(inputs)
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/torchbench.py", line 336, in <graph break in forward_and_backward_pass>
    self.grad_scaler.scale(loss).backward()
  File "/scratch/ybliang/work/repos/pytorch-dev/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/scratch/ybliang/work/repos/pytorch-dev/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/scratch/ybliang/work/repos/pytorch-dev/torch/autograd/function.py", line 270, in apply
    return user_fn(self, *args)
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/eval_frame.py", line 163, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch-dev/functorch/_src/aot_autograd.py", line 464, in backward
    CompiledFunction.compiled_bw = aot_config.bw_compiler(
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/optimizations/backends.py", line 555, in _wrapped_bw_compiler
    return disable(bw_compiler(*args, **kwargs))
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/utils.py", line 86, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/compile_fx.py", line 357, in bw_compiler
    return compile_fx_inner(
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/debug_utils.py", line 450, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/debug.py", line 180, in inner
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/compile_fx.py", line 110, in compile_fx_inner
    graph.run(*example_inputs)
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/utils.py", line 86, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/graph.py", line 147, in run
    return super().run(*args)
  File "/scratch/ybliang/work/repos/pytorch-dev/torch/fx/interpreter.py", line 130, in run
    self.env[node] = self.run_node(node)
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/graph.py", line 315, in run_node
    result = super().run_node(n)
  File "/scratch/ybliang/work/repos/pytorch-dev/torch/fx/interpreter.py", line 171, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/graph.py", line 307, in output
    self.finalize()
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/graph.py", line 311, in finalize
    buf.decide_layout()
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/ir.py", line 1891, in decide_layout
    reads = self.get_read_writes().reads
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/utils.py", line 176, in wrapper
    setattr(self, key, fn(self))
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/ir.py", line 1867, in get_read_writes
    return extract_read_writes(
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/dependencies.py", line 248, in extract_read_writes
    fn(*args)
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/ir.py", line 353, in store_output
    return ops.store(output_name, indexer(vars), self.inner_fn(vars))
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/lowering.py", line 316, in inner_fn
    return fn(*[load(index) for load in loaders])
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/lowering.py", line 316, in <listcomp>
    return fn(*[load(index) for load in loaders])
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/lowering.py", line 316, in inner_fn
    return fn(*[load(index) for load in loaders])
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/lowering.py", line 316, in <listcomp>
    return fn(*[load(index) for load in loaders])
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/lowering.py", line 316, in inner_fn
    return fn(*[load(index) for load in loaders])
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/lowering.py", line 316, in <listcomp>
    return fn(*[load(index) for load in loaders])
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/lowering.py", line 316, in inner_fn
    return fn(*[load(index) for load in loaders])
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/lowering.py", line 316, in <listcomp>
    return fn(*[load(index) for load in loaders])
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/lowering.py", line 316, in inner_fn
    return fn(*[load(index) for load in loaders])
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/lowering.py", line 316, in <listcomp>
    return fn(*[load(index) for load in loaders])
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/lowering.py", line 316, in inner_fn
    return fn(*[load(index) for load in loaders])
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/lowering.py", line 316, in <listcomp>
    return fn(*[load(index) for load in loaders])
 <many other lines...>
RecursionError: maximum recursion depth exceeded
```

Error2:
```
ERROR:common:one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2, 1024]] is at version 723; expected version 722 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/common.py", line 1164, in check_accuracy
    new_result = optimized_model_iter_fn(model, example_inputs)
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/eval_frame.py", line 163, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/torchbench.py", line 330, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/torchbench.py", line 331, in <graph break in forward_and_backward_pass>
    cloned_inputs = clone_inputs(inputs)
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/torchbench.py", line 336, in <graph break in forward_and_backward_pass>
    self.grad_scaler.scale(loss).backward()
  File "/scratch/ybliang/work/repos/pytorch-dev/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/scratch/ybliang/work/repos/pytorch-dev/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/scratch/ybliang/work/repos/pytorch-dev/torch/autograd/function.py", line 270, in apply
    return user_fn(self, *args)
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/eval_frame.py", line 163, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch-dev/functorch/_src/aot_autograd.py", line 460, in backward
    all_args = list(ctx.symints) + list(ctx.saved_tensors) + list(contiguous_args)
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2, 1024]] is at version 723; expected version 722 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
FAIL

```

**Comment by anijain2305** [comment]
@yanboliang Can we close this one?

**Comment by anijain2305** [comment]
Closing in favor of https://github.com/pytorch/torchdynamo/issues/1907
