### ISSUE TITLE
Following pattern in code seems to break dynamo graph tracing

### ISSUE THREAD

**Issue by ngoyal2707** [pytorch/torchdynamo#1695]
```
import torch
import torchdynamo

from torch import nn

class TestModel(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.linears = nn.Sequential(
            nn.Linear(100, 100),
            nn.Linear(100, 100),
            nn.Linear(100, 100),
            nn.Linear(100, 100),
        )

    def forward(self, x):
        all_but_last, last = self.linears[:-1], self.linears[-1]
        x = all_but_last(x)
        x = last(x)
        return x


# @torchdynamo.optimize('eager')
def toy_example(model, input):
    return model(input)

model = TestModel().cuda()
x = torch.rand((8, 100), device='cuda')

for _ in range(10):
    toy_example(model, x)
```

Its okay if the answer is, this is not supported but just wanted to raise it as fyi

**Comment by voznesenskym** [comment]
What graph break do you see? which pattern are you talking about?

**Comment by ngoyal2707** [comment]
sorry didn't mean break graph, basically above code gives following error with dynamo :
```
    return model(input)
  File "examples/DALLE2/scripts/test_dynamo.py", line 18, in forward
    x = all_but_last(x)

Traceback (most recent call last):
  File "examples/DALLE2/scripts/test_dynamo.py", line 31, in <module>
    toy_example(model, x)
  File "/shared/home/namangoyal/src/torchdynamo/torchdynamo/eval_frame.py", line 163, in _fn
    return fn(*args, **kwargs)
  File "examples/DALLE2/scripts/test_dynamo.py", line 23, in toy_example
    @torchdynamo.optimize('eager')
  File "/shared/home/namangoyal/miniconda3/envs/ldm_ait/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1274, in _call_impl
    return forward_call(*input, **kwargs)
  File "examples/DALLE2/scripts/test_dynamo.py", line 16, in forward
    def forward(self, x):
TypeError: 'tuple' object is not callable
```


but works without it

**Comment by voznesenskym** [comment]
gotcha :) thanks - can you port this issue to pytorch? Just realized its in dynamo, and this repo is effectively closed.

**Comment by ngoyal2707** [comment]
sure: closing this and opened https://github.com/pytorch/pytorch/issues/87121

**Comment by voznesenskym** [comment]
> @voznesenskym we're still using the dynamo issue tracker

My mistake. Apologies @ngoyal2707

**Comment by ngoyal2707** [comment]
lol alright, I closed the PT one

**Comment by voznesenskym** [comment]
https://github.com/pytorch/pytorch/pull/87156/

**Comment by voznesenskym** [comment]
Sorry it took so long, did not get around to it till an hour ago or so

**Comment by voznesenskym** [comment]
Forgot to close it, solved in pytorch. https://github.com/pytorch/pytorch/pull/87156
