### ISSUE TITLE
[BUG] moco fails without suppress errors: RuntimeError: Tensors must be CUDA and dense                                                              

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#1747]
### 🐛 Describe the bug

Patch in https://github.com/pytorch/pytorch/pull/87440 to turn off error suppression

run `python benchmarks/dynamo/torchbench.py  --accuracy --backend eager --training --only moco`

fails with

```
  File "/raid/ezyang/pytorch-scratch2/torch/_dynamo/variables/tensor.py", line 132, in <lambda>           
    lambda: _run_node(tx.output, node, args, kwargs, nnmodule)                                            
  File "/raid/ezyang/pytorch-scratch2/torch/_dynamo/variables/tensor.py", line 51, in _run_node       
    return node.target(*args, **kwargs)                                                                   
  File "/raid/ezyang/pytorch-scratch2/torch/distributed/distributed_c10d.py", line 2264, in all_gather    
    work = default_pg.allgather([tensor_list], [tensor])                                                  
  File "/raid/ezyang/pytorch-scratch2/torch/utils/_python_dispatch.py", line 101, in __torch_dispatch__   
    return old.__torch_dispatch__(func, types, args, kwargs)                                              
  File "/raid/ezyang/pytorch-scratch2/torch/_subclasses/fake_tensor.py", line 822, in __torch_dispatch__  
    r = func(*args, **kwargs)                                                                             
  File "/raid/ezyang/pytorch-scratch2/torch/_ops.py", line 257, in __call__
    return self._op(*args, **kwargs or {})                                                                
RuntimeError: Tensors must be CUDA and dense
```

### Error logs

https://gist.github.com/5a54f01612589820947d15ac2256a9a2

### Minified repro

minifier does not work because captured dynamo graph has distributed operations in it, but process groups are not initialized

**Comment by ezyang** [comment]
cc @Chillee about minifier

**Comment by anijain2305** [comment]
This definitely seems like `fake_tensor` issue. IIUC, fake tensors dont work with this

![image](https://user-images.githubusercontent.com/13822661/197298930-0b38b7ad-71a9-4539-8952-8d5062a5cdd2.png)

@ezyang This is eager, so Fx minifiers are not useful.

@mlazos Record-replay dumped the frame, but it missed the global state of init_process. The replay gave this error (instead of CUDA and dense)
~~~
Traceback (most recent call last):
  File "/scratch/anijain/work/pytorch/torch/distributed/distributed_c10d.py", line 584, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

~~~

**Comment by anijain2305** [comment]
assigning to @bdhirsh , cc @eellison
