### ISSUE TITLE
Repro is generating minifier_launcher.py that fails with: AttributeError: torch._dynamo.config.repro_dir does not exist

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#1758]
### 🐛 Describe the bug

```
Traceback (most recent call last):
  File "minifier_launcher.py", line 13, in <module>
    torch._dynamo.config.repro_dir = "/raid/ezyang/pytorch-scratch2/torchdynamo_debug/run_2022_10_24_06_53_17_018120/minifier"
  File "/raid/ezyang/pytorch-scratch2/torch/_dynamo/config.py", line 164, in __setattr__
    raise AttributeError(f"{__name__}.{name} does not exist")
AttributeError: torch._dynamo.config.repro_dir does not exist
```

full generated minifier script: https://gist.github.com/b1838891ff91c9c64a47fe1aeed0dae0

how I generated the minifier:

```
TORCHDYNAMO_REPRO_AFTER=dynamo TORCHDYNAMO_DYNAMIC_SHAPES=1 time python benchmarks/dynamo/timm_models.py  --accuracy --backend aot_eager --training --only sebotnet33ts_256
```

**Comment by mlazos** [comment]
William is looking at adding more exhaustive tests, we don't have any coverage for the minifier_launcher.py, which should cover most of these issues.

cc @williamwen42
