### ISSUE TITLE
test_conv_cudnn_nhwc_support_cuda_float32: AssertionError: Tensor.is_contiguous() unhandled kwargs

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1783]
Repro:
```
 PYTORCH_TEST_WITH_INDUCTOR=1 python test/test_nn.py -k test_conv_cudnn_nhwc_support_cuda_float32
```

Error:
```
[2022-10-27 23:30:54,172] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT test_conv_cudnn_nhwc_support /fsx/users/binbao/pytorch/test/test_nn.py line 16716 
due to: 
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/_dynamo/variables/tensor.py", line 503, in call_method
    assert not kwargs, f"Tensor.{name}() unhandled kwargs"
AssertionError: Tensor.is_contiguous() unhandled kwargs

from user code:
   File "/fsx/users/binbao/pytorch/test/test_nn.py", line 16724, in test_conv_cudnn_nhwc_support
    self.assertTrue(o.is_contiguous(memory_format=torch.channels_last))
```

**Comment by yanboliang** [comment]
Updated command:
```
PYTORCH_TEST_WITH_INDUCTOR=1 python test/nn/test_convolution.py -k test_conv_cudnn_nhwc_support_cuda_float32
```
