### ISSUE TITLE
test_GroupNorm_general_cuda: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1788]
Repro:
```
PYTORCH_TEST_WITH_INDUCTOR=1 python test/test_nn.py -k    test_GroupNorm_general_cuda
```
Error:
```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2001, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2001, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    result = test(self, **param_kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_device_type.py", line 1027, in only_fn
    return fn(self, *args, **kwargs)
  File "/fsx/users/binbao/pytorch/test/test_nn.py", line 13623, in test_GroupNorm_general
    self._test_GroupNorm_cuda_half()
  File "/fsx/users/binbao/pytorch/test/test_nn.py", line 12308, in _test_GroupNorm_cuda_half
    def _test_GroupNorm_cuda_half(self):
  File "/fsx/users/binbao/pytorch/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 870, in forward
    return compiled_f(
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 856, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 86, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 579, in create_aot_dispatcher_function
    return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 285, in aot_dispatch_base
    fw_module = make_fx(flat_fn, aot_config.decompositions)(*flat_args)
  File "/fsx/users/binbao/pytorch/torch/fx/experimental/proxy_tensor.py", line 657, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/fsx/users/binbao/pytorch/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/fx/experimental/proxy_tensor.py", line 415, in dispatch_trace
    return GraphModule(tracer.root, graph, name)
  File "/fsx/users/binbao/pytorch/torch/fx/graph_module.py", line 368, in __init__
    self.graph = graph
  File "/fsx/users/binbao/pytorch/torch/nn/modules/module.py", line 1564, in __setattr__
    super().__setattr__(name, value)
  File "/fsx/users/binbao/pytorch/torch/fx/graph_module.py", line 409, in graph
    self.recompile()
  File "/fsx/users/binbao/pytorch/torch/fx/graph_module.py", line 646, in recompile
    cls.forward = _forward_from_src(self._code, python_code.globals)
  File "/fsx/users/binbao/pytorch/torch/fx/graph_module.py", line 79, in _forward_from_src
    _exec_with_source(src, globals_copy)
  File "/fsx/users/binbao/pytorch/torch/fx/graph_module.py", line 73, in _exec_with_source
    exec(compile(src, key, 'exec'), globals)
  File "<eval_with_key>.6", line 9
    random_ = torch.ops.aten.random_.from(_to_copy_1, 1, 10);  _to_copy_1 = None
                                     ^
SyntaxError: invalid syntax
```

**Comment by desertfire** [comment]
Duplicate of https://github.com/pytorch/torchdynamo/issues/1795
