### ISSUE TITLE
test_InstanceNorm1d_general_cuda: RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1789]
Repro:
```
PYTORCH_TEST_WITH_INDUCTOR=1 python test/test_nn.py -k   test_InstanceNorm1d_general_cuda
```
Error:
```
[2022-10-27 23:53:04,104] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT test_InstanceNorm1d_general /fsx/users/binbao/pytorch/test/test_nn.py line 13502 
due to: 
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/_dynamo/variables/tensor.py", line 51, in _run_node
    return node.target(*args, **kwargs)
TypeError: rand() received an invalid combination of arguments - got (FakeTensor, FakeTensor, FakeTensor), but expected one of:
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


from user code:
   File "/fsx/users/binbao/pytorch/test/test_nn.py", line 13507, in test_InstanceNorm1d_general
    input = torch.rand(b, c, d)

Set torch._dynamo.config.verbose=True for more information
==========
[2022-10-27 23:53:05,578] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT <graph break in _test_InstanceNorm_general> /fsx/users/binbao/pytorch/test/test_nn.py line 12135 
due to: 
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/_dynamo/variables/tensor.py", line 105, in visit
    return n.meta["example_value"]
KeyError: 'example_value'

from user code:
   File "/fsx/users/binbao/pytorch/test/test_nn.py", line 12143, in <graph break in _test_InstanceNorm_general>
    self.assertEqual(torch.abs(mean.data).mean(), 0, atol=1e-5, rtol=0)

Set torch._dynamo.config.verbose=True for more information
==========
E
======================================================================
ERROR: test_InstanceNorm1d_general_cuda (__main__.TestNNDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2001, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2001, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_device_type.py", line 394, in instantiated_test
    raise rte
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    result = test(self, **param_kwargs)
  File "/fsx/users/binbao/pytorch/test/test_nn.py", line 13508, in test_InstanceNorm1d_general
    self._test_InstanceNorm_general(nn.InstanceNorm1d, input, device)
  File "/fsx/users/binbao/pytorch/test/test_nn.py", line 12135, in _test_InstanceNorm_general
    IN = cls(c, eps=0).to(device, dtype)
  File "/fsx/users/binbao/pytorch/test/test_nn.py", line 12135, in <graph break in _test_InstanceNorm_general>
    IN = cls(c, eps=0).to(device, dtype)
  File "/fsx/users/binbao/pytorch/test/test_nn.py", line 12149, in <graph break in _test_InstanceNorm_general>
    output.backward(grad_out)
  File "/fsx/users/binbao/pytorch/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/fsx/users/binbao/pytorch/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

**Comment by desertfire** [comment]
Despite the dynamo graph breaks here, the problem is similar to https://github.com/pytorch/torchdynamo/issues/1791. https://github.com/pytorch/pytorch/blob/0bc19e77d27db1d0f2e6cc6504576b3729dde4ab/test/test_nn.py#L7554 is where `requires_grad_` is used inside of a function, which breaks aot-autograd.

Close as duplicated for now.
