### ISSUE TITLE
test_advancedindex_mixed_cpu_devices_cuda

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1793]
Repro:
```
PYTORCH_TEST_WITH_INDUCTOR=1 python test/test_torch.py -k  test_advancedindex_mixed_cpu_devices_cuda
```
Error:
```
[2022-10-28 00:08:08,980] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT test_advancedindex_mixed_cpu_devices /fsx/users/binbao/pytorch/test/test_torch.py line 5320 
due to: 
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/_dynamo/variables/base.py", line 196, in reconstruct
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/_dynamo/exc.py", line 71, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: reconstruct: ConstantVariable(device)

Set torch._dynamo.config.verbose=True for more information
==========
E
======================================================================
ERROR: test_advancedindex_mixed_cpu_devices_cuda (__main__.TestDevicePrecisionCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 241, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/lowering.py", line 204, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/lowering.py", line 1724, in index
    indices, start_offset, end_offset = check_and_broadcast_indices(indices)
  File "/fsx/users/binbao/pytorch/torch/_inductor/lowering.py", line 1714, in check_and_broadcast_indices
    assert all((i is not None) for i in tmp)
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2001, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2001, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_device_type.py", line 394, in instantiated_test
    raise rte
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    result = test(self, **param_kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_device_type.py", line 1015, in multi_fn
    return fn(slf, devices, *args, **kwargs)
  File "/fsx/users/binbao/pytorch/test/test_torch.py", line 5345, in test_advancedindex_mixed_cpu_devices
    test(x, ia, ib)
  File "/fsx/users/binbao/pytorch/test/test_torch.py", line 5322, in test
    def test(x: torch.Tensor, ia: torch.Tensor, ib: torch.Tensor) -> None:
  File "/fsx/users/binbao/pytorch/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 870, in forward
    return compiled_f(
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 856, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 86, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 579, in create_aot_dispatcher_function
    return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 295, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/fsx/users/binbao/pytorch/torch/_dynamo/utils.py", line 87, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/compile_fx.py", line 352, in fw_compiler
    return compile_fx_inner(
  File "/fsx/users/binbao/pytorch/torch/_dynamo/debug_utils.py", line 466, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/debug.py", line 177, in inner
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/conda/envs/release/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/fsx/users/binbao/pytorch/torch/_inductor/compile_fx.py", line 122, in compile_fx_inner
    graph.run(*example_inputs)
  File "/fsx/users/binbao/pytorch/torch/_dynamo/utils.py", line 87, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 131, in run
    return super().run(*args)
  File "/fsx/users/binbao/pytorch/torch/fx/interpreter.py", line 130, in run
    self.env[node] = self.run_node(node)
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 301, in run_node
    result = super().run_node(n)
  File "/fsx/users/binbao/pytorch/torch/fx/interpreter.py", line 171, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 244, in call_function
    raise LoweringException(e, target, args, kwargs) from e
torch._inductor.exc.LoweringException: AssertionError: 
  target: aten.index.Tensor
  args[0]: TensorBox(
    View(
      ReinterpretView(
        StorageBox(
          InputBuffer(name='arg0_1', layout=FixedLayout('cuda', torch.float32, size=[3, 4, 4, 4, 3], stride=[192, 48, 12, 3, 1]))
        ),
        FixedLayout('cuda', torch.float32, size=[3, 4, 1, 4, 1, 3], stride=[192, 48, 48, 12, 3, 1]),
        origins={select}
      ),
      size=(3, 4, 1, 4, 3),
      reindex=lambda i0, i1, i2, i3, i4: [i0, i1, 0, i3, 0, i4],
      origins={select}
    )
  )
  args[1]: [None, TensorBox(StorageBox(
    InputBuffer(name='arg1_1', layout=FixedLayout('cpu', torch.int64, size=[3], stride=[1]))
  )), None, TensorBox(StorageBox(
    InputBuffer(name='arg2_1', layout=FixedLayout('cpu', torch.int64, size=[3], stride=[1]))
  ))]

While executing %index : [#users=1] = call_function[target=torch.ops.aten.index.Tensor](args = (%select, [None, %arg1_1, None, %arg2_1]), kwargs = {})
Original traceback:
Module stack: {}
  File "/fsx/users/binbao/pytorch/test/test_torch.py", line 5324, in test
    self.assertEqual(x[:, ia, None, ib, 0].cpu(),
```

**Comment by desertfire** [comment]
https://github.com/pytorch/pytorch/pull/90022
