### ISSUE TITLE
test_cumprod_cuda: assert not any(isinstance(x, TensorBox) for x in kwargs.values())

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1798]
Repro:
```
PYTORCH_TEST_WITH_INDUCTOR=1 python test/test_torch.py -k  test_cumprod_cuda
```
Error:
```
======================================================================
ERROR: test_cumprod_cuda (__main__.TestTorchDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 241, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/lowering.py", line 168, in wrapped
    assert not any(isinstance(x, TensorBox) for x in kwargs.values())
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2001, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2001, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_device_type.py", line 394, in instantiated_test
    raise rte
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    result = test(self, **param_kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 1053, in wrapper
    fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/test/test_torch.py", line 2310, in test_cumprod
    @skipIfMps
  File "/fsx/users/binbao/pytorch/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 870, in forward
    return compiled_f(
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 856, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 86, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 579, in create_aot_dispatcher_function
    return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 295, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/fsx/users/binbao/pytorch/torch/_dynamo/utils.py", line 87, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/compile_fx.py", line 352, in fw_compiler
    return compile_fx_inner(
  File "/fsx/users/binbao/pytorch/torch/_dynamo/debug_utils.py", line 466, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/debug.py", line 177, in inner
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/conda/envs/release/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/fsx/users/binbao/pytorch/torch/_inductor/compile_fx.py", line 122, in compile_fx_inner
    graph.run(*example_inputs)
  File "/fsx/users/binbao/pytorch/torch/_dynamo/utils.py", line 87, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 131, in run
    return super().run(*args)
  File "/fsx/users/binbao/pytorch/torch/fx/interpreter.py", line 130, in run
    self.env[node] = self.run_node(node)
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 301, in run_node
    result = super().run_node(n)
  File "/fsx/users/binbao/pytorch/torch/fx/interpreter.py", line 171, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 244, in call_function
    raise LoweringException(e, target, args, kwargs) from e
torch._inductor.exc.LoweringException: AssertionError: 
  target: aten.cumprod.out
  args[0]: TensorBox(StorageBox(
    ComputedBuffer(name='buf0', layout=FixedLayout('cuda', torch.float32, size=[100, 100], stride=[100, 1]), data=Pointwise(
      'cuda',
      torch.float32,
      rand(bitwise_xor(load(seed_cuda_0, 0), constant(65535, torch.int32)), index_expr(i1 + 100 * i0, torch.int32), torch.float32),
      ranges=[100, 100],
      origins={rand}
    ))
  ))
  args[1]: 1
  kwargs: {'out': TensorBox(StorageBox(
    Pointwise(
      'cuda',
      torch.float32,
      constant(0, torch.float32),
      ranges=[0],
      origins={_to_copy}
    )
  ))}

While executing %cumprod_1 : [#users=1] = call_function[target=torch.ops.aten.cumprod.out](args = (%alias, 1), kwargs = {out: %_to_copy})
Original traceback:
Module stack: {}
  File "/fsx/users/binbao/pytorch/test/test_torch.py", line 2315, in test_cumprod
    torch.cumprod(x, 1, out=res2)
```

**Comment by desertfire** [comment]
related to https://github.com/pytorch/torchdynamo/issues/1805
