### ISSUE TITLE
test_pairwise_distance_empty_cuda: TypeError: reduce() of empty sequence with no initial value

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1799]
Repro:
```
PYTORCH_TEST_WITH_INDUCTOR=1 python test/test_torch.py -k  test_pairwise_distance_empty_cuda
```
Error:
```
======================================================================
ERROR: test_pairwise_distance_empty_cuda (__main__.TestTorchDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2001, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2001, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    result = test(self, **param_kwargs)
  File "/fsx/users/binbao/pytorch/test/test_torch.py", line 2027, in test_pairwise_distance_empty
    def test_pairwise_distance_empty(self, device):
  File "/fsx/users/binbao/pytorch/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 870, in forward
    return compiled_f(
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 856, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 86, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 579, in create_aot_dispatcher_function
    return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 295, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/fsx/users/binbao/pytorch/torch/_dynamo/utils.py", line 87, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/compile_fx.py", line 352, in fw_compiler
    return compile_fx_inner(
  File "/fsx/users/binbao/pytorch/torch/_dynamo/debug_utils.py", line 466, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/debug.py", line 177, in inner
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/conda/envs/release/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/fsx/users/binbao/pytorch/torch/_inductor/compile_fx.py", line 122, in compile_fx_inner
    graph.run(*example_inputs)
  File "/fsx/users/binbao/pytorch/torch/_dynamo/utils.py", line 87, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 131, in run
    return super().run(*args)
  File "/fsx/users/binbao/pytorch/torch/fx/interpreter.py", line 130, in run
    self.env[node] = self.run_node(node)
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 315, in run_node
    if isinstance(result, TensorBox) and result.has_exceeded_max_reads():
  File "/fsx/users/binbao/pytorch/torch/_inductor/ir.py", line 3517, in has_exceeded_max_reads
    self.num_reads() > config.realize_acc_reads_threshold
  File "/fsx/users/binbao/pytorch/torch/_inductor/utils.py", line 175, in wrapper
    setattr(self, key, fn(self))
  File "/fsx/users/binbao/pytorch/torch/_inductor/ir.py", line 3555, in num_reads
    read_writes = ComputedBuffer(
  File "/fsx/users/binbao/pytorch/torch/_inductor/utils.py", line 175, in wrapper
    setattr(self, key, fn(self))
  File "/fsx/users/binbao/pytorch/torch/_inductor/ir.py", line 1870, in get_read_writes
    return extract_read_writes(
  File "/fsx/users/binbao/pytorch/torch/_inductor/dependencies.py", line 248, in extract_read_writes
    fn(*args)
  File "/fsx/users/binbao/pytorch/torch/_inductor/ir.py", line 339, in store_output
    return ops.store(output_name, indexer(vars), self.inner_fn(vars))
  File "/fsx/users/binbao/pytorch/torch/_inductor/ir.py", line 643, in fn
    return functools.reduce(
TypeError: reduce() of empty sequence with no initial value

While executing %sum_1 : [#users=1] = call_function[target=torch.ops.prims.sum.default](args = (%pow_1, [1]), kwargs = {})
Original traceback:
Module stack: {}
  File "/fsx/users/binbao/pytorch/test/test_torch.py", line 2032, in test_pairwise_distance_empty
    self.assertEqual(torch.zeros(2, device=device), torch.pairwise_distance(x, y))
```

**Comment by desertfire** [comment]
https://github.com/pytorch/pytorch/pull/88280
