### ISSUE TITLE
test_pin_memory_from_constructor_cuda:  assert not pin_memory

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1800]
Repro:
```
PYTORCH_TEST_WITH_INDUCTOR=1 python test/test_torch.py -k  test_pin_memory_from_constructor_cuda
```
Error
```
[2022-10-28 01:09:43,913] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT test_pin_memory_from_constructor /fsx/users/binbao/pytorch/test/test_torch.py line 4650 
due to: 
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/_subclasses/fake_tensor.py", line 422, in nyi
    assert func not in _device_not_kwarg_ops, f"NYI: {func}"
AssertionError: NYI: aten.is_pinned.default

from user code:
   File "/fsx/users/binbao/pytorch/test/test_torch.py", line 4678, in test_pin_memory_from_constructor
    self.assertTrue(x.is_pinned())

Set torch._dynamo.config.verbose=True for more information
==========
E
======================================================================
ERROR: test_pin_memory_from_constructor_cuda (__main__.TestTorchDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 241, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/lowering.py", line 204, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/lowering.py", line 1065, in randn
    return fast_randn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/lowering.py", line 1005, in rand_or_randn
    assert not pin_memory
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2001, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2001, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_device_type.py", line 394, in instantiated_test
    raise rte
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    result = test(self, **param_kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_device_type.py", line 991, in only_fn
    return fn(slf, *args, **kwargs)
  File "/fsx/users/binbao/pytorch/test/test_torch.py", line 4676, in test_pin_memory_from_constructor
    pinned_tensors = _get_tensors(pin_memory=True) + _get_like(torch.empty(5, dtype=torch.float64), pin_memory=True)
  File "/fsx/users/binbao/pytorch/test/test_torch.py", line 4663, in _get_tensors
    def _get_tensors(**kwargs):
  File "/fsx/users/binbao/pytorch/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 870, in forward
    return compiled_f(
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 856, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 86, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 579, in create_aot_dispatcher_function
    return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 295, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/fsx/users/binbao/pytorch/torch/_dynamo/utils.py", line 87, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/compile_fx.py", line 352, in fw_compiler
    return compile_fx_inner(
  File "/fsx/users/binbao/pytorch/torch/_dynamo/debug_utils.py", line 466, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/debug.py", line 177, in inner
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/conda/envs/release/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/fsx/users/binbao/pytorch/torch/_inductor/compile_fx.py", line 122, in compile_fx_inner
    graph.run(*example_inputs)
  File "/fsx/users/binbao/pytorch/torch/_dynamo/utils.py", line 87, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 131, in run
    return super().run(*args)
  File "/fsx/users/binbao/pytorch/torch/fx/interpreter.py", line 130, in run
    self.env[node] = self.run_node(node)
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 301, in run_node
    result = super().run_node(n)
  File "/fsx/users/binbao/pytorch/torch/fx/interpreter.py", line 171, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 244, in call_function
    raise LoweringException(e, target, args, kwargs) from e
torch._inductor.exc.LoweringException: AssertionError: 
  target: aten.randn.default
  args[0]: [3, 5]
  kwargs: {'device': device(type='cpu'), 'pin_memory': True}

While executing %randn : [#users=1] = call_function[target=torch.ops.aten.randn.default](args = ([3, 5],), kwargs = {device: cpu, pin_memory: True})
Original traceback:
Module stack: {}
  File "/fsx/users/binbao/pytorch/test/test_torch.py", line 4666, in _get_tensors
    torch.randn(3, 5, **kwargs),
```

**Comment by desertfire** [comment]
Low priority, https://github.com/pytorch/pytorch/pull/88143 skips the test.
