### ISSUE TITLE
test_scatter_reduce_scalar_cuda_float16: RuntimeError: aten::scatter_reduce_() Expected a value of type 'Tensor' for argument 'src' but instead found type 'int'.

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1801]
Repro:
```
PYTORCH_TEST_WITH_INDUCTOR=1 python test/test_torch.py -k test_scatter_reduce_scalar_cuda_float16
```
Error:
```
======================================================================
ERROR: test_scatter_reduce_scalar_cuda_float16 (__main__.TestTorchDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 241, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/lowering.py", line 204, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/lowering.py", line 1872, in scatter_
    return scatter_reduce_(self, dim, index, src, reduce)
  File "/fsx/users/binbao/pytorch/torch/_inductor/lowering.py", line 204, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/lowering.py", line 1903, in scatter_reduce_
    return fallback_scatter_reduce_(
  File "/fsx/users/binbao/pytorch/torch/_inductor/lowering.py", line 931, in handler
    result = ir.FallbackKernel.create(kernel, *args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/ir.py", line 2890, in create
    example_output = kernel(
  File "/fsx/users/binbao/pytorch/torch/_ops.py", line 446, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: aten::scatter_reduce_() Expected a value of type 'Tensor' for argument 'src' but instead found type 'int'.
Position: 3
Value: 2
Declaration: aten::scatter_reduce_.two(Tensor(a!) self, int dim, Tensor index, Tensor src, str reduce, *, bool include_self=True) -> Tensor(a!)
Cast error details: Unable to cast 2 to Tensor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2001, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 2001, in wrapper
    method(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_device_type.py", line 394, in instantiated_test
    raise rte
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    result = test(self, **param_kwargs)
  File "/fsx/users/binbao/pytorch/test/test_torch.py", line 3383, in test_scatter_reduce_scalar
    @dtypes(*floating_and_complex_types())
  File "/fsx/users/binbao/pytorch/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 870, in forward
    return compiled_f(
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 856, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 86, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 579, in create_aot_dispatcher_function
    return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
  File "/fsx/users/binbao/pytorch/functorch/_src/aot_autograd.py", line 295, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/fsx/users/binbao/pytorch/torch/_dynamo/utils.py", line 87, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/compile_fx.py", line 352, in fw_compiler
    return compile_fx_inner(
  File "/fsx/users/binbao/pytorch/torch/_dynamo/debug_utils.py", line 466, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/debug.py", line 177, in inner
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/conda/envs/release/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/fsx/users/binbao/pytorch/torch/_inductor/compile_fx.py", line 122, in compile_fx_inner
    graph.run(*example_inputs)
  File "/fsx/users/binbao/pytorch/torch/_dynamo/utils.py", line 87, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 131, in run
    return super().run(*args)
  File "/fsx/users/binbao/pytorch/torch/fx/interpreter.py", line 130, in run
    self.env[node] = self.run_node(node)
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 301, in run_node
    result = super().run_node(n)
  File "/fsx/users/binbao/pytorch/torch/fx/interpreter.py", line 171, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/fsx/users/binbao/pytorch/torch/_inductor/graph.py", line 244, in call_function
    raise LoweringException(e, target, args, kwargs) from e
torch._inductor.exc.LoweringException: RuntimeError: aten::scatter_reduce_() Expected a value of type 'Tensor' for argument 'src' but instead found type 'int'.
Position: 3
Value: 2
Declaration: aten::scatter_reduce_.two(Tensor(a!) self, int dim, Tensor index, Tensor src, str reduce, *, bool include_self=True) -> Tensor(a!)
Cast error details: Unable to cast 2 to Tensor
  target: aten.scatter_.value_reduce
  args[0]: TensorBox(
    ExpandView(data=View(
      StorageBox(
        ComputedBuffer(name='buf0', layout=FixedLayout('cuda', torch.float16, size=[1], stride=[1]), data=Pointwise(
          'cuda',
          torch.float16,
          constant(2.0, torch.float16),
          ranges=[1],
          origins={lift_fresh_copy_2}
        ))
      ),
      size=(1, 1),
      reindex=lambda i0, i1: [0],
      origins={repeat}
    ), size=[4, 4])
  )
  args[1]: 0
  args[2]: TensorBox(StorageBox(
    ComputedBuffer(name='buf2', layout=FixedLayout('cuda', torch.int64, size=[2, 1], stride=[1, 1]), data=Pointwise(
      'cuda',
      torch.int64,
      load(constant0, i0),
      ranges=[2, 1],
      origins={lift_fresh_copy}
    ))
  ))
  args[3]: 2
  kwargs: {'reduce': 'multiply'}

While executing %scatter_ : [#users=1] = call_function[target=torch.ops.aten.scatter_.value_reduce](args = (%repeat, 0, %lift_fresh_copy, 2), kwargs = {reduce: multiply})
Original traceback:
Module stack: {}
  File "/fsx/users/binbao/pytorch/test/test_torch.py", line 3405, in test_scatter_reduce_scalar
    input.scatter_(0, index, src, reduce=operation)
```

**Comment by desertfire** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/88894
