### ISSUE TITLE
RuntimeError: Triton Error [CUDA]: invalid argument

### ISSUE THREAD

**Issue by mreso** [pytorch/torchdynamo#1804]
### 🐛 Describe the bug

Hi,

another issue I encountered when trying stable diffusion training:

```
RuntimeError: Triton Error [CUDA]: invalid argument
```

### Error logs

```
Traceback (most recent call last):
  File "/home/mreso/torchdynamo/diffuser_training/repro.py", line 48, in <module>
    compiled = compile_fx_inner(mod, args)
  File "/home/mreso/.local/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 466, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/mreso/.local/lib/python3.9/site-packages/torch/_inductor/debug.py", line 177, in inner
    return fn(*args, **kwargs)
  File "/home/mreso/miniconda3/envs/td4/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/mreso/.local/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 137, in compile_fx_inner
    compiled_fn = cudagraphify(
  File "/home/mreso/.local/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 87, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/mreso/.local/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 196, in cudagraphify
    return cudagraphify_impl(model, inputs, static_input_idxs)
  File "/home/mreso/.local/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 260, in cudagraphify_impl
    model(list(static_inputs))
  File "/tmp/torchinductor_mreso/ft/cftvwfqghcry6zv2dbxxafe6gmf4krsbbenqzrdyyefvz2psskzz.py", line 90, in call
    kernel1.run(arg0_1, buf0, arg1_1, arg2_1, buf1, 33554432, grid=grid(33554432), stream=stream0)
  File "/home/mreso/.local/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 170, in run
    result = launcher(
  File "<string>", line 4, in launcher
RuntimeError: Triton Error [CUDA]: invalid argument
```

### Minified repro

```
import torch._inductor.overrides

import torch
from torch import tensor, device
import torch.fx as fx
from torch._dynamo.testing import rand_strided
from math import inf
from torch.fx.experimental.proxy_tensor import make_fx

# torch version: 1.14.0a0+gitac0c13f
# torch cuda version: 11.7
# torch git version: ac0c13f665aa14c99837779580da74f01d9b96ab


# CUDA Info: 
# nvcc: NVIDIA (R) Cuda compiler driver 
# Copyright (c) 2005-2022 NVIDIA Corporation 
# Built on Wed_Jun__8_16:49:14_PDT_2022 
# Cuda compilation tools, release 11.7, V11.7.99 
# Build cuda_11.7.r11.7/compiler.31442593_0 

# GPU Hardware Info: 
# NVIDIA A100-SXM4-80GB : 1 


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()

    
    
    def forward(self, view, reciprocal, unsqueeze_3):
        mean = torch.ops.aten.mean.dim(view, [2, 3], True)
        sub = torch.ops.aten.sub.Tensor(view, mean);  view = mean = None
        mul_5 = torch.ops.aten.mul.Tensor(sub, reciprocal);  sub = reciprocal = None
        view_1 = torch.ops.aten.view.default(mul_5, [16, 128, 128, 128]);  mul_5 = None
        mul_6 = torch.ops.aten.mul.Tensor(view_1, unsqueeze_3);  view_1 = unsqueeze_3 = None
        return (mul_6,)
        
args = [((16, 32, 4, 16384), (2097152, 65536, 16384, 1), torch.float32, 'cuda'), ((16, 32, 1, 1), (32, 1, 1, 1), torch.float32, 'cuda'), ((128, 1, 1), (1, 1, 1), torch.float32, 'cuda')]
args = [rand_strided(sh, st, dt, dev) for (sh, st, dt, dev) in args]
mod = make_fx(Repro().to(device="cuda"))(*args)

from torch._inductor.compile_fx import compile_fx_inner
from torch._dynamo.debug_utils import same_two_models

compiled = compile_fx_inner(mod, args)
compiled(args)
```

**Comment by ngimel** [comment]
Doesn't repro for me

**Comment by mreso** [comment]
Must have been a local issue. Does not repro on a new instance for me as well. Thanks!
