### ISSUE TITLE
[DDP-Dynamo] failure in DLRM (RuntimeError: Tensors must be CUDA and dense)

### ISSUE THREAD

**Issue by wconstab** [pytorch/torchdynamo#1849]
`python benchmarks/dynamo/torchbench.py --training --inductor --ddp --accuracy --only dlrm --no-optimize-ddp`

(`--no-optimize-ddp` is not necessary, it just simplifies the situation. the error repros with or without DDPOptimizer/graph-breaks)

```
cuda train dlrm                               [W reducer.cpp:1305] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, cons
ider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())           
Traceback (most recent call last):
  File "benchmarks/dynamo/torchbench.py", line 349, in <module>    main(TorchBenchmarkRunner(), original_dir)                    
  File "/scratch/whc/work/pytorch/benchmarks/dynamo/common.py", line 1579, in main
    return maybe_fresh_cache(run, args.cold_start_latency and args.only)(  File "/scratch/whc/work/pytorch/benchmarks/dynamo/common.py", line 775, in inner                
    return fn(*args, **kwargs) 
  File "/scratch/whc/work/pytorch/benchmarks/dynamo/common.py", line 1905, in run          
    runner.run_one_model(
  File "/scratch/whc/work/pytorch/benchmarks/dynamo/common.py", line 1296, in run_one_model
    status = self.check_accuracy(                             
  File "/scratch/whc/work/pytorch/benchmarks/dynamo/common.py", line 1097, in check_accuracy
    correct_result = self.run_n_iterations(
  File "/scratch/whc/work/pytorch/benchmarks/dynamo/common.py", line 1020, in run_n_iterations 
    self.model_iter_fn(mod, inputs, collect_outputs=False)
  File "benchmarks/dynamo/torchbench.py", line 337, in forward_and_backward_pass                  
    self.grad_scaler.scale(loss).backward()             
  File "/scratch/whc/work/pytorch/torch/_tensor.py", line 488, in backward                          
    torch.autograd.backward( 
  File "/scratch/whc/work/pytorch/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Tensors must be CUDA and dense
```

**Comment by wconstab** [comment]
Making this explicit via https://github.com/pytorch/pytorch/pull/88712
