### ISSUE TITLE
Dynamo bug: AssertionError: ReLU in NNModuleVariable.unpack_var_sequence

### ISSUE THREAD

**Issue by yanboliang** [pytorch/torchdynamo#1864]
### 🐛 Describe the bug

I found this when I re-run 7k github model, and this issue(and similar one, replace ```ReLu``` with other modules) occurs a lot.
```
import torch
import torch.nn as nn
import torch._dynamo
import logging

torch._dynamo.config.log_level = logging.DEBUG
torch._dynamo.config.verbose = True

class BasicConv2d(nn.Module):

    def __init__(self, in_planes, out_planes, kernel_size, stride=1, padding=0, output_relu=True):
        super(BasicConv2d, self).__init__()
        self.conv = nn.Conv2d(in_planes, out_planes, kernel_size=kernel_size, stride=stride, padding=padding, bias=False)
        self.bn = nn.BatchNorm2d(out_planes)
        self.relu = nn.ReLU() if output_relu else None

    def forward(self, x):
        x = self.conv(x)
        x = self.bn(x)
        if self.relu:
            x = self.relu(x)
        return x

model = BasicConv2d(160, 64, kernel_size=1, stride=1)
opt_model = torch._dynamo.optimize("eager")(model)
# opt_model = model
x = torch.rand([4, 160, 64, 64])
print(opt_model(x))
```

### Error logs

```
Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/pytorch/debug/debug2.py", line 42, in <module>
    print(opt_model(x))
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/eval_frame.py", line 137, in __call__
    return self.forward(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/eval_frame.py", line 134, in forward
    return optimized_forward(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/eval_frame.py", line 169, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/eval_frame.py", line 247, in catch_errors
    return callback(frame, cache_size)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 476, in _convert_frame
    result = inner_convert(frame, cache_size)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 118, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 89, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 349, in _convert_frame_assert
    return _compile(
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 404, in _compile
    out_code = transform_code_object(code, transform)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 392, in transform
    tracer.run()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1518, in run
    super().run()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 384, in run
    and self.step()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 354, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 188, in wrapper
    return inner_fn(self, inst)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 811, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 296, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/variables/nn_module.py", line 183, in call_function
    tx.call_function(
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 296, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/variables/nn_module.py", line 222, in call_function
    return tx.inline_user_function_return(
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 325, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1590, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1644, in inline_call_
    tracer.run()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 384, in run
    and self.step()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 354, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 161, in inner
    elif not isinstance(value, TensorVariable) and value.has_unpack_var_sequence(
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/variables/base.py", line 203, in has_unpack_var_sequence
    self.unpack_var_sequence(tx)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/variables/nn_module.py", line 49, in unpack_var_sequence
    assert isinstance(
AssertionError: ReLU

from user code:
   File "/scratch/ybliang/work/repos/pytorch/debug/debug2.py", line 33, in forward
    x0 = self.branch0(x)
  File "/scratch/ybliang/work/repos/pytorch/debug/debug2.py", line 21, in forward
    if self.relu:


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

```

**Comment by wconstab** [comment]
> if self.relu:
> 
> 
> You can suppress this exception and fall back to eager by setting:
>     torch._dynamo.config.suppress_errors = True

I don't recall this error.  Is this something I worked on before (can you remind me more context?)

**Comment by anijain2305** [comment]
@yanboliang Can you try this - https://github.com/pytorch/pytorch/pull/89095

**Comment by yanboliang** [comment]
It works!!!

**Comment by anijain2305** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/89095
