### ISSUE TITLE
[Dynamo Bug] TypeError: <lambda>() missing 3 required positional arguments

### ISSUE THREAD

**Issue by yanboliang** [pytorch/torchdynamo#1866]
### 🐛 Describe the bug

This comes from Meta internal models, I tried to minimize it as the following repro:
```
import torch
import torch._dynamo
import logging
import collections

torch._dynamo.config.log_level = logging.DEBUG
torch._dynamo.config.verbose = True


def fn(x, s):
    a = x**2
    if isinstance(s, Student):
        return a + 1
    else:
        return a - 1

Student = collections.namedtuple("Student", ["name", "gender", "age", "rating"])
s = Student("Ethan", "M", 23, "A")
x = torch.ones((2, 2))

opt_fn = torch._dynamo.optimize("eager")(fn)
res = opt_fn(x, s)
print(res)
```

### Error logs

```
Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 404, in _compile
    out_code = transform_code_object(code, transform)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 392, in transform
    tracer.run()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1612, in run
    super().run()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 478, in run
    and self.step()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 448, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 282, in wrapper
    return inner_fn(self, inst)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 905, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 390, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/variables/builtin.py", line 232, in call_function
    constant_args = check_constant_args(args, kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 605, in check_constant_args
    return all(x.is_python_constant() for x in itertools.chain(args, kwargs.values()))
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 605, in <genexpr>
    return all(x.is_python_constant() for x in itertools.chain(args, kwargs.values()))
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/variables/base.py", line 141, in is_python_constant
    self.as_python_constant()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/variables/lists.py", line 36, in as_python_constant
    return self.python_type()([x.as_python_constant() for x in self.items])
TypeError: <lambda>() missing 3 required positional arguments: 'gender', 'age', and 'rating'

from user code:
   File "/scratch/ybliang/work/repos/pytorch/debug/debug1.py", line 12, in fn
    if isinstance(s, Student):


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

**Comment by yanboliang** [comment]
This is because ```NamedTupleVariable``` doesn't implement ```as_python_constant```, so fallback to the parent ```BaseListVariable```. However, namedtuple should be handled different.

**Comment by yanboliang** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/89110
