### ISSUE TITLE
[Inductor] accuracy failure in torchbench model detectron2_fcos_r_50_fpn

### ISSUE THREAD

**Issue by chuanqi129** [pytorch/torchdynamo#1873]
### 🐛 Describe the bug

This failure was found in latest **TorchInductor CPU Performance Dashboard** refresh test in https://github.com/pytorch/torchdynamo/issues/1617#issuecomment-1316633340

SW information

SW	| Nightly commit	| Master/Main commit
----|--------|-----
Pytorch	|[637228b](https://github.com/blzheng/pytorch/commit/637228bcc4d2566fb617bbf1c4abeff69b3bdae7)	|[46796fe](https://github.com/blzheng/pytorch/commit/46796fe5e9b74602d45927304773fdcda1c3215a)
Torchbench|	/	|[022dfe3](https://github.com/pytorch/benchmark/commit/022dfe3d89db9278119bf1cd179997076b5ec5b5)
torchaudio	|[4b10b6a](https://github.com/pytorch/audio/commit/4b10b6adece473ad70e221bb3f9442d11906111f)	|[74f9a89](https://github.com/pytorch/audio/commit/74f9a894fcd4e7d635919803b364e47577a2b6e8)
torchtext	|[71e4561](https://github.com/pytorch/text/commit/71e456119d39cf72a511ce6acb10b737e02102d3)	|[c047efe](https://github.com/pytorch/text/commit/c047efeba813ac943cb8046a49e858a8b529d577)
torchvision	|[797e1ac](https://github.com/pytorch/vision/commit/797e1acf043621c5b53319032a269cbe1190b018)	|[ffd5a56](https://github.com/pytorch/vision/commit/ffd5a567eb90abf6b5555063da434d3c130d540f)

detail info reference the [Dashboard](https://github.com/pytorch/torchdynamo/issues/1617#issuecomment-1316633340) 

### Error logs

`RuntimeError: Storage size calculation overflowed with sizes=[2, 3, 140639896720224, 140639896720384]`

### Minified repro

`python benchmarks/dynamo/torchbench.py --accuracy --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only=detectron2_fcos_r_50_fpn --batch_size 2 `

**Comment by chuanqi129** [comment]
Update for latest [ TorchInductor CPU Performance Dashboard](https://github.com/pytorch/torchdynamo/issues/1617#issuecomment-1319683695) refresh test with below error log

SW info:

SW	|Nightly commit	|Master/Main commit
--|--|--
Pytorch	|[0662e90](https://github.com/pytorch/pytorch/commit/0662e90840324708ada3bca6ec316cce8250dc49)	|[e2f0648](https://github.com/pytorch/pytorch/commit/e2f0648750f2d0d0ac648728ce4c514db178cfa1)
Torchbench	|/	|[022dfe3](https://github.com/pytorch/benchmark/commit/022dfe3d89db9278119bf1cd179997076b5ec5b5)
torchaudio	|[4b10b6a](https://github.com/pytorch/audio/commit/4b10b6adece473ad70e221bb3f9442d11906111f)	|[74f9a89](https://github.com/pytorch/audio/commit/74f9a894fcd4e7d635919803b364e47577a2b6e8)
torchtext	|[71e4561](https://github.com/pytorch/text/commit/71e456119d39cf72a511ce6acb10b737e02102d3)	|[c047efe](https://github.com/pytorch/text/commit/c047efeba813ac943cb8046a49e858a8b529d577)
torchvision	|[797e1ac](https://github.com/pytorch/vision/commit/797e1acf043621c5b53319032a269cbe1190b018)	|[ffd5a56](https://github.com/pytorch/vision/commit/ffd5a567eb90abf6b5555063da434d3c130d540f)


```
ERROR:common:Failed for dynamo 

from user code:
   File "/opt/conda/lib/python3.8/site-packages/detectron2/modeling/meta_arch/dense_detector.py", line 126, in preprocess_image
    images = ImageList.from_tensors(images, self.backbone.size_divisibility)
  File "/opt/conda/lib/python3.8/site-packages/detectron2/structures/image_list.py", line 102, in from_tensors
    batched_imgs = F.pad(tensors[0], padding_size, value=pad_value).unsqueeze_(0)

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
Traceback (most recent call last):
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 1076, in run_node
    return node.target(*args, **kwargs)
  File "/workspace/pytorch/torch/_subclasses/fake_tensor.py", line 879, in __torch_dispatch__
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/workspace/pytorch/torch/_subclasses/fake_tensor.py", line 366, in data_dep
    raise DataDependentOutputException(func)
torch._subclasses.fake_tensor.DataDependentOutputException: aten._local_scalar_dense.default

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 1042, in get_fake_value
    return wrap_fake_exception(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 721, in wrap_fake_exception
    return fn()
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 1043, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 1085, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_function <built-in function pad>(*(FakeTensor(FakeTensor(..., device='meta', size=(3, 800, 1199)), cpu), [0, FakeTensor(FakeTensor(..., device='meta', size=(), dtype=torch.int64), cpu), 0, FakeTensor(FakeTensor(..., device='meta', size=(), dtype=torch.int64), cpu)]), **{'value': 0.0}):
aten._local_scalar_dense.default
(scroll up for backtrace)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 1204, in warmup
    fn(model, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 169, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 247, in catch_errors
    return callback(frame, cache_size)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 476, in _convert_frame
    result = inner_convert(frame, cache_size)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 118, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 89, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 349, in _convert_frame_assert
    return _compile(
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 404, in _compile
    out_code = transform_code_object(code, transform)
  File "/workspace/pytorch/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 392, in transform
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 1612, in run
    super().run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 478, in run
    and self.step()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 448, in step
    getattr(self, inst.opname)(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 282, in wrapper
    return inner_fn(self, inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 942, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 390, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/workspace/pytorch/torch/_dynamo/variables/nn_module.py", line 222, in call_function
    return tx.inline_user_function_return(
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 419, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 1684, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 1738, in inline_call_
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 478, in run
    and self.step()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 448, in step
    getattr(self, inst.opname)(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 282, in wrapper
    return inner_fn(self, inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 905, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 390, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/workspace/pytorch/torch/_dynamo/variables/functions.py", line 224, in call_function
    return super().call_function(tx, args, kwargs)
  File "/workspace/pytorch/torch/_dynamo/variables/functions.py", line 194, in call_function
    return super(UserFunctionVariable, self).call_function(tx, args, kwargs)
  File "/workspace/pytorch/torch/_dynamo/variables/functions.py", line 65, in call_function
    return tx.inline_user_function_return(
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 419, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 1684, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 1738, in inline_call_
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 478, in run
    and self.step()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 448, in step
    getattr(self, inst.opname)(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 282, in wrapper
    return inner_fn(self, inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 905, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 390, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/workspace/pytorch/torch/_dynamo/variables/functions.py", line 194, in call_function
    return super(UserFunctionVariable, self).call_function(tx, args, kwargs)
  File "/workspace/pytorch/torch/_dynamo/variables/functions.py", line 65, in call_function
    return tx.inline_user_function_return(
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 419, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 1684, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 1738, in inline_call_
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 478, in run
    and self.step()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 448, in step
    getattr(self, inst.opname)(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 282, in wrapper
    return inner_fn(self, inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 954, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 390, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/workspace/pytorch/torch/_dynamo/variables/torch.py", line 406, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/workspace/pytorch/torch/_dynamo/variables/builder.py", line 636, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/workspace/pytorch/torch/_dynamo/variables/builder.py", line 676, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 1055, in get_fake_value
    raise TorchRuntimeError() from e
torch._dynamo.exc.TorchRuntimeError: 

from user code:
   File "/opt/conda/lib/python3.8/site-packages/detectron2/modeling/meta_arch/dense_detector.py", line 126, in preprocess_image
    images = ImageList.from_tensors(images, self.backbone.size_divisibility)
  File "/opt/conda/lib/python3.8/site-packages/detectron2/structures/image_list.py", line 102, in from_tensors
    batched_imgs = F.pad(tensors[0], padding_size, value=pad_value).unsqueeze_(0)

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
    ```
