### ISSUE TITLE
[fake_tensor] convit_base 

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#1886]
### Error logs

~~~
WARNING:root:convit_base failed to load
(/scratch/anijain/work/env)  anijain@a100-st-p4d24xlarge-15 /scratch/anijain/work/pytorch (master) $ python failures/bigbird.py
Traceback (most recent call last):
  File "/scratch/anijain/work/pytorch/torch/_dynamo/utils.py", line 1086, in run_node
    return getattr(args[0], node.target)(*args[1:], **kwargs)
  File "/scratch/anijain/work/pytorch/torch/_subclasses/fake_tensor.py", line 879, in __torch_dispatch__
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/scratch/anijain/work/pytorch/torch/_subclasses/fake_tensor.py", line 358, in dyn_shape
    raise DynamicOutputShapeException(func)
torch._subclasses.fake_tensor.DynamicOutputShapeException: aten.repeat_interleave.Tensor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/anijain/work/pytorch/torch/_dynamo/utils.py", line 1050, in get_fake_value
    return wrap_fake_exception(
  File "/scratch/anijain/work/pytorch/torch/_dynamo/utils.py", line 729, in wrap_fake_exception
    return fn()
  File "/scratch/anijain/work/pytorch/torch/_dynamo/utils.py", line 1051, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/scratch/anijain/work/pytorch/torch/_dynamo/utils.py", line 1093, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_method repeat_interleave(*(FakeTensor(FakeTensor(..., device='meta', size=(14, 14), dtype=torch.int64), cpu), 14), **{'dim': 0}):
aten.repeat_interleave.Tensor
(scroll up for backtrace)

~~~

### Minified repro

~~~


def fn(a):
    return a.repeat_interleave(14, dim=0).repeat_interleave(14, dim=1)


x = torch.ones(14, 14).to(dtype=torch.int64)
opt_fn = torch._dynamo.optimize("eager")(fn)
opt_fn(x)

~~~

**Comment by ngimel** [comment]
Yeah, we should graph-break on `repeat_interleave` with tensor repeat args, `unique`, `nonzero`, indexing with bool index, one_hot without output shape etc.

**Comment by chuanqi129** [comment]
Also captured this issue in the latest [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/torchdynamo/issues/1617#issuecomment-1319683695) refresh test.

**Comment by eellison** [comment]
We used to graph-break here, there's logic for that [here](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/utils.py#L1056). Not sure why it's not being triggered, I think recent regression. Bisecting now

**Comment by eellison** [comment]
Hey @voznesenskym, I bisected the failure to https://github.com/pytorch/pytorch/pull/88768. Would you mind taking a look at this ? If you don't have bandwidth let me know.

**Comment by voznesenskym** [comment]
I can take it

**Comment by shingjan** [comment]
hi @voznesenskym @eellison does this issue still persist? I am seeing 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/torch/testing/_comparison.py", line 1250, in assert_equal
    pair.compare()
  File "/usr/local/lib/python3.8/site-packages/torch/testing/_comparison.py", line 704, in compare
    self._compare_values(actual, expected)
  File "/usr/local/lib/python3.8/site-packages/torch/testing/_comparison.py", line 822, in _compare_values
    compare_fn(
  File "/usr/local/lib/python3.8/site-packages/torch/testing/_comparison.py", line 995, in _compare_regular_values_close
    if torch.all(matches):
  File "/usr/local/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 611, in __torch_dispatch__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/_ops.py", line 285, in __call__
    return self._op(*args, **kwargs or {})
  File "/usr/local/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 878, in __torch_dispatch__
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 373, in data_dep
    raise DataDependentOutputException(func)
torch._subclasses.fake_tensor.DataDependentOutputException: aten._local_scalar_dense.default

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 586, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 915, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "<stdin>", line 10, in tvm_compiler
  File "<stdin>", line 19, in create_tvm_backend
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/jit/_trace.py", line 792, in trace
    return trace_module(
  File "/usr/local/lib/python3.8/site-packages/torch/jit/_trace.py", line 1076, in trace_module
    _check_trace(
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 34, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/jit/_trace.py", line 553, in _check_trace
    if compare_outputs(traced_outs, fn_outs, "Python function"):
  File "/usr/local/lib/python3.8/site-packages/torch/jit/_trace.py", line 527, in compare_outputs
    torch.testing.assert_close(
  File "/usr/local/lib/python3.8/site-packages/torch/testing/_comparison.py", line 1519, in assert_close
    assert_equal(
  File "/usr/local/lib/python3.8/site-packages/torch/testing/_comparison.py", line 1256, in assert_equal
    raise RuntimeError(
RuntimeError: Comparing

TensorLikePair(
    id=(),
    actual=FakeTensor(FakeTensor(..., device='meta', size=(10,), dtype=torch.float64), cpu),
    expected=FakeTensor(FakeTensor(..., device='meta', size=(10,), dtype=torch.float64), cpu),
    rtol=1e-05,
    atol=1e-05,
    equal_nan=True,
    check_device=True,
    check_dtype=True,
    check_layout=True,
    check_stride=False,
    check_is_coalesced=True,
)

resulted in the unexpected exception above. If you are a user and see this message during normal operation please file an issue at https://github.com/pytorch/pytorch/issues. If you are a developer and working on the comparison functions, please except the previous error and raise an expressive `ErrorMeta` instead.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 67, in <module>
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 332, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 476, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 395, in _compile
    out_code = transform_code_object(code, transform)
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 382, in transform
    tracer.run()
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1621, in run
    super().run()
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 485, in run
    and self.step()
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 454, in step
    getattr(self, inst.opname)(inst)
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 232, in inner
    self.output.compile_subgraph(
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 439, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 510, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/usr/local/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 591, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: tvm_compiler raised RuntimeError: Comparing

TensorLikePair(
    id=(),
    actual=FakeTensor(FakeTensor(..., device='meta', size=(10,), dtype=torch.float64), cpu),
    expected=FakeTensor(FakeTensor(..., device='meta', size=(10,), dtype=torch.float64), cpu),
    rtol=1e-05,
    atol=1e-05,
    equal_nan=True,
    check_device=True,
    check_dtype=True,
    check_layout=True,
    check_stride=False,
    check_is_coalesced=True,
)

```
while running resnet18 on torchdynamo with `tvm` as backend on CPU. Seems like a regression to me.
