### ISSUE TITLE
[inductor] regression coming from https://github.com/pytorch/pytorch/pull/89031

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1890]
### 🐛 Describe the bug

`python benchmarks/dynamo/torchbench.py --training --accuracy --device cuda --inductor --float32  --only functorch_dp_cifar10`

### Error logs

```
Traceback (most recent call last):
  File "/scratch/binbao/work/pytorch/benchmarks/dynamo/common.py", line 1164, in check_accuracy
    new_result = optimized_model_iter_fn(
  File "/scratch/binbao/work/pytorch/torch/_dynamo/eval_frame.py", line 169, in _fn
    return fn(*args, **kwargs)
  File "/scratch/binbao/work/pytorch/benchmarks/dynamo/common.py", line 1062, in run_n_iterations
    self.model_iter_fn(mod, inputs, collect_outputs=False)
  File "/scratch/binbao/work/pytorch/benchmarks/dynamo/torchbench.py", line 332, in forward_and_backward_pass
    cloned_inputs = clone_inputs(inputs)
  File "/scratch/binbao/work/pytorch/benchmarks/dynamo/torchbench.py", line 337, in <graph break in forward_and_backward_pass>
    self.grad_scaler.scale(loss).backward()
  File "/scratch/binbao/work/pytorch/torch/_tensor.py", line 473, in backward
    torch.autograd.backward(
  File "/scratch/binbao/work/pytorch/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/scratch/binbao/work/pytorch/torch/autograd/function.py", line 270, in apply
    return user_fn(self, *args)
  File "/scratch/binbao/work/pytorch/functorch/_src/aot_autograd.py", line 558, in backward
    CompiledFunction.compiled_bw = aot_config.bw_compiler(
  File "/scratch/binbao/work/pytorch/torch/_dynamo/optimizations/backends.py", line 555, in _wrapped_bw_compiler
    return disable(disable(bw_compiler)(*args, **kwargs))
  File "/scratch/binbao/work/pytorch/torch/_dynamo/eval_frame.py", line 169, in _fn
    return fn(*args, **kwargs)
  File "/scratch/binbao/work/pytorch/torch/_dynamo/utils.py", line 89, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/binbao/work/pytorch/torch/_inductor/compile_fx.py", line 362, in bw_compiler
    return compile_fx_inner(
  File "/scratch/binbao/work/pytorch/torch/_dynamo/debug_utils.py", line 444, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/scratch/binbao/work/pytorch/torch/_inductor/debug.py", line 177, in inner
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/conda/envs/py3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/scratch/binbao/work/pytorch/torch/_inductor/compile_fx.py", line 135, in compile_fx_inner
    compiled_fn = cudagraphify(
  File "/scratch/binbao/work/pytorch/torch/_dynamo/utils.py", line 89, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/binbao/work/pytorch/torch/_inductor/compile_fx.py", line 194, in cudagraphify
    return cudagraphify_impl(model, inputs, static_input_idxs)
  File "/scratch/binbao/work/pytorch/torch/_inductor/compile_fx.py", line 257, in cudagraphify_impl
    model(list(static_inputs))
  File "/tmp/torchinductor_binbao/uf/cuf6zzffmpwsmxqhkmx5w2ezmnkmknwchegct3ju7kbgirpk5y6i.py", line 2409, in call
    assert_size_stride(buf23, (2, 256, 2, 2), (1024, 4, 2, 1))
AssertionError: expected size 256==256, stride 1==4 at dim=1
```

**Comment by desertfire** [comment]
@Chillee `git bisect` points to https://github.com/pytorch/pytorch/pull/89031

**Comment by ngimel** [comment]
Yeah that sounds right, but we need #89031 for channels-last, so we should forward fix rather than revert.

**Comment by desertfire** [comment]
> Yeah that sounds right, but we need #89031 for channels-last, so we should forward fix rather than revert.

Agree, that's why I skipped the test instead of reverting Horace's PR.
