### ISSUE TITLE
[tacotron2] One of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#1907]
### 🐛 Describe the bug

Even eager backend fails 

`python benchmarks/dynamo/torchbench.py --training --performance --backend=eager --float32 --only=tacotron2`

### Error logs

~~~
cuda train tacotron2                          ERROR:common:Failed for dynamo one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [64, 80, 857]], which is output 0 of AsStridedBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
Traceback (most recent call last):
  File "/scratch/anijain/work/pytorch/benchmarks/dynamo/common.py", line 1181, in warmup
    fn(model, example_inputs)
  File "/scratch/anijain/work/pytorch/torch/_dynamo/eval_frame.py", line 194, in _fn
    return fn(*args, **kwargs)
  File "/scratch/anijain/work/pytorch/benchmarks/dynamo/torchbench.py", line 348, in forward_and_backward_pass
    cloned_inputs = clone_inputs(inputs)
  File "/scratch/anijain/work/pytorch/benchmarks/dynamo/torchbench.py", line 353, in <graph break in forward_and_backward_pass>
    self.grad_scaler.scale(loss).backward()
  File "/scratch/anijain/work/pytorch/torch/_tensor.py", line 473, in backward
    torch.autograd.backward(
  File "/scratch/anijain/work/pytorch/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [64, 80, 857]], which is output 0 of AsStridedBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
~~~

**Comment by bdhirsh** [comment]
As of a master commit from yesterday, when I run tacotron2 I get a guard error on duplicate inputs:
command:
```
python benchmarks/dynamo/torchbench.py  --accuracy --backend aot_eager --training --only tacotron2
```

error:
```
  File "/scratch/hirsheybar3/work/benchmark/torchbenchmark/models/tacotron2/model.py", line 401, in <graph break in forward>
    self.initialize_decoder_states(
  File "/scratch/hirsheybar3/work/pytorch/torch/_dynamo/eval_frame.py", line 333, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/scratch/hirsheybar3/work/pytorch/torch/_dynamo/convert_frame.py", line 480, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/scratch/hirsheybar3/work/pytorch/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/scratch/hirsheybar3/work/pytorch/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/hirsheybar3/work/pytorch/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/scratch/hirsheybar3/work/pytorch/torch/_dynamo/convert_frame.py", line 440, in _compile
    check_fn = CheckFunctionManager(
  File "/scratch/hirsheybar3/work/pytorch/torch/_dynamo/guards.py", line 467, in __init__
    self.check_fn = self.compile_check_fn(
  File "/scratch/hirsheybar3/work/pytorch/torch/_dynamo/guards.py", line 524, in compile_check_fn
    assert pos_b < len(self.output_graph.graphargs) and pos_a < len(
AssertionError: Deduped args out of bounds
```
