### ISSUE TITLE
Dynamo/TorchXLA Integration: the traced graph for models using BatchNorm2d returning unexpected number of outputs

### ISSUE THREAD

**Issue by shunting314** [pytorch/torchdynamo#1908]
### 🐛 Describe the bug

For models like resnet18, resnet50, mnasnet1_0, etc, we fail to enable aot_autograd for them. The failed run complains the traced xla graph returning the wrong number of outputs. We are able to simplified a small repro and it turns out that the issue is caused by BatchNorm2d op.

### Error logs

```
Graph:


def forward(self, primals_1, primals_2, primals_3, primals_4, primals_5, primals_6):
    native_batch_norm = torch.ops.aten.native_batch_norm.default(primals_6, primals_1, primals_2, primals_3, primals_4, True, 0.1, 1e-05);  primals_2 = None
    getitem = native_batch_norm[0]
    getitem_1 = native_batch_norm[1]
    getitem_2 = native_batch_norm[2];  native_batch_norm = None
    sum_1 = torch.ops.aten.sum.default(getitem);  getitem = None
    return [sum_1, getitem_2, primals_4, getitem_1, primals_1, primals_6, primals_3]

#inplace update: 2
#args_and_out: 9
Traceback (most recent call last):
  File "myscripts/repro_batchnorm.py", line 37, in <module>
    dynamo.optimize(compiler)(lambda: model(*inputs).sum().backward())()
  File "/pytorch/torch/_dynamo/eval_frame.py", line 194, in _fn
    return fn(*args, **kwargs)
  File "myscripts/repro_batchnorm.py", line 37, in <lambda>
    dynamo.optimize(compiler)(lambda: model(*inputs).sum().backward())()
  File "/pytorch/torch/_dynamo/eval_frame.py", line 194, in _fn
    return fn(*args, **kwargs)
  File "/pytorch/functorch/_src/aot_autograd.py", line 954, in forward
    **kwargs,
  File "/pytorch/functorch/_src/aot_autograd.py", line 942, in new_func
    return compiled_fn(args)
  File "/pytorch/functorch/_src/aot_autograd.py", line 321, in g
    return f(*args)
  File "/pytorch/functorch/_src/aot_autograd.py", line 570, in compiled_function
    return CompiledFunction.apply(*remove_dupe_args(args))
  File "/pytorch/functorch/_src/aot_autograd.py", line 529, in forward
    CompiledFunction.compiled_fw, deduped_flat_tensor_args, disable_amp=disable_amp
  File "/pytorch/functorch/_src/aot_autograd.py", line 346, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/pytorch/functorch/_src/aot_autograd.py", line 321, in g
    return f(*args)
  File "/pytorch/torch/_dynamo/optimizations/torchxla_integration.py", line 275, in optimized_mod
    assert len(res) == len(args_and_out), f"{len(res)} v.s. {len(args_and_out)}"
AssertionError: 11 v.s. 9
```

### Minified repro

```
from torch import nn
import torch
import torch_xla.core.xla_model as xm
import torch._dynamo as dynamo
from torch._dynamo.optimizations.backends import BACKENDS
import functorch.compile
from functorch.compile import aot_module_simplified
from functorch.compile import make_boxed_compiler
import os
os.environ["GPU_NUM_DEVICES"] = "1"

class MyBatchNormModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.bn = nn.BatchNorm2d(3)

    def forward(self, x):
        return self.bn(x)

    def get_example_inputs(self):
        return (torch.rand(2, 3, 8, 10),)

xla_dev = xm.xla_device()
model = MyBatchNormModel().to(device=xla_dev)
inputs = list(map(lambda x: x.to(device=xla_dev), model.get_example_inputs()))

functorch.compile.config.use_fake_tensor = False

def compiler(gm, inputs):
    @make_boxed_compiler
    @dynamo.disable
    def fw_compiler(graph, inputs, *args, **kwargs):
        print(f"Graph: {graph.code}")
        return BACKENDS["torchxla_trace_once"](graph, inputs)
    return aot_module_simplified(gm, fw_compiler=fw_compiler)

dynamo.optimize(compiler)(lambda: model(*inputs).sum().backward())()
print("bye")
```

**Comment by shunting314** [comment]
cc @wconstab @jansel @jackcaog

**Comment by shunting314** [comment]
We've understood the tricky part of how XLA returns inputs in https://github.com/pytorch/pytorch/pull/89536 . We implement `DumbReturnHandler` in https://github.com/pytorch/pytorch/pull/88449 to handle this case. BatchNorm2d works with that.
