### ISSUE TITLE
[inductor][Triton] SegFault - LongFormer

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#1928]
### 🐛 Describe the bug

UPDATE - The description has been updated to give a much smaller repro than before.

This is the generated Triton code. It fails during the autotuning. You might have to run multiple times for it to fail.

cc @ngimel 

### Error logs

~~~
Traceback (most recent call last):
  File "/scratch/anijain/work/pytorch/fail_triton_allen.py", line 181, in <module>
    print_performance(lambda: call([arg0_1, arg1_1, arg2_1, arg3_1, arg4_1, arg5_1, arg6_1, arg7_1, arg8_1]))
  File "/scratch/anijain/work/pytorch/torch/_inductor/utils.py", line 197, in print_performance
    timings = [timed(fn, args, times) for _ in range(repeat)]
  File "/scratch/anijain/work/pytorch/torch/_inductor/utils.py", line 197, in <listcomp>
    timings = [timed(fn, args, times) for _ in range(repeat)]
  File "/scratch/anijain/work/pytorch/torch/_inductor/utils.py", line 188, in timed
    result = model(*example_inputs)
  File "/scratch/anijain/work/pytorch/fail_triton_allen.py", line 181, in <lambda>
    print_performance(lambda: call([arg0_1, arg1_1, arg2_1, arg3_1, arg4_1, arg5_1, arg6_1, arg7_1, arg8_1]))
  File "/scratch/anijain/work/pytorch/fail_triton_allen.py", line 165, in call
    triton_fused_slice_43_permute_6_slice_scatter_8_slice_scatter_16_slice_47_unsqueeze_2_eq_2_slice_35_view_11_slice_5513.run(buf17, buf9, buf8, buf6, buf7, buf16, buf18, buf20, 12288, 513, grid=grid(12288), stream=stream0)
  File "/scratch/anijain/work/pytorch/torch/_inductor/triton_ops/autotune.py", line 171, in run
    result = launcher(
  File "<string>", line 4, in launcher
RuntimeError: Triton Error [CUDA]: an illegal memory access was encountered
~~~

### Minified repro

~~~
import torch._inductor.overrides

import torch
from torch import tensor, device
import torch.fx as fx
from torch._dynamo.testing import rand_strided
from math import inf
from torch.fx.experimental.proxy_tensor import make_fx

# REPLACEABLE COMMENT FOR TESTING PURPOSES

# torch version: 1.14.0a0+git2c0bd85
# torch cuda version: 11.6
# torch git version: 2c0bd85c755043d696452ddab354f3ff6775738b


# CUDA Info:
# nvcc: NVIDIA (R) Cuda compiler driver
# Copyright (c) 2005-2022 NVIDIA Corporation
# Built on Thu_Feb_10_18:23:41_PST_2022
# Cuda compilation tools, release 11.6, V11.6.112
# Build cuda_11.6.r11.6/compiler.30978841_0

# GPU Hardware Info:
# NVIDIA A100-SXM4-40GB : 8


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()



    def forward(self, slice_scatter_12, slice_scatter_6, slice_16, slice_17, slice_18, slice_scatter_15, view_10):
        constant_pad_nd = torch.ops.aten.constant_pad_nd.default(view_10, [0, 0, 0, 1], 0.0);  view_10 = None
        view_11 = torch.ops.aten.view.default(constant_pad_nd, [12, 3, 512, 513]);  constant_pad_nd = None
        slice_1 = torch.ops.aten.slice.Tensor(view_11, 0, 0, 9223372036854775807);  view_11 = None
        slice_2 = torch.ops.aten.slice.Tensor(slice_1, 1, 0, 9223372036854775807);  slice_1 = None
        slice_10 = torch.ops.aten.slice.Tensor(slice_2, 2, -257, -1);  slice_2 = None
        slice_11 = torch.ops.aten.slice.Tensor(slice_10, 3, 257, 9223372036854775807);  slice_10 = None
        slice_scatter_7 = torch.ops.aten.slice_scatter.default(slice_18, slice_11, 3, 0, 256);  slice_18 = slice_11 = None
        slice_scatter_8 = torch.ops.aten.slice_scatter.default(slice_17, slice_scatter_7, 2, 0, 9223372036854775807);  slice_17 = slice_scatter_7 = None
        slice_scatter_9 = torch.ops.aten.slice_scatter.default(slice_16, slice_scatter_8, 1, 1, 9223372036854775807);  slice_16 = slice_scatter_8 = None
        slice_scatter_10 = torch.ops.aten.slice_scatter.default(slice_scatter_6, slice_scatter_9, 0, 0, 9223372036854775807);  slice_scatter_6 = slice_scatter_9 = None
        slice_19 = torch.ops.aten.slice.Tensor(slice_scatter_10, 0, 0, 9223372036854775807)
        select_scatter_1 = torch.ops.aten.select_scatter.default(slice_19, slice_scatter_12, 1, 0);  slice_19 = slice_scatter_12 = None
        slice_scatter_13 = torch.ops.aten.slice_scatter.default(slice_scatter_10, select_scatter_1, 0, 0, 9223372036854775807);  slice_scatter_10 = select_scatter_1 = None
        view_12 = torch.ops.aten.view.default(slice_scatter_13, [1, 12, 1024, 513]);  slice_scatter_13 = None
        permute_10 = torch.ops.aten.permute.default(view_12, [0, 2, 1, 3]);  view_12 = None
        slice_23 = torch.ops.aten.slice.Tensor(permute_10, 0, 0, 9223372036854775807);  permute_10 = None
        slice_scatter_16 = torch.ops.aten.slice_scatter.default(slice_23, slice_scatter_15, 1, 0, 256);  slice_23 = slice_scatter_15 = None
        return (slice_scatter_16,)

args = [((12, 256, 513), (131328, 513, 1), torch.float32, 'cuda'), ((12, 4, 256, 513), (525312, 131328, 513, 1), torch.float32, 'cuda'), ((12, 4, 256, 513), (525312, 131328, 513, 1), torch.float32, 'cuda'), ((12, 3, 256, 513), (525312, 131328, 513, 1), torch.float32, 'cuda'), ((12, 3, 256, 513), (525312, 131328, 513, 1), torch.float32, 'cuda'), ((1, 256, 12, 513), (1575936, 513, 131328, 1), torch.float32, 'cuda'), ((12, 3, 512, 512), (786432, 262144, 512, 1), torch.float32, 'cuda')]
args = [rand_strided(sh, st, dt, dev) for (sh, st, dt, dev) in args]
mod = make_fx(Repro())(*args)

from torch._inductor.compile_fx import compile_fx_inner
from torch._dynamo.debug_utils import same_two_models

compiled = compile_fx_inner(mod, args)
ref = compiled(args)
print(ref)
~~~~

**Comment by anijain2305** [comment]
Maybe little simpler triton code to debug - https://gist.github.com/anijain2305/e78c542382f9e177a4b1ce4774bca30c

This one is generated by setting fusion group size to 1. Minifier is not helping because it seems the error is flaky.
