### ISSUE TITLE
HF Models Triggering AssertError in Functorch

### ISSUE THREAD

**Issue by williamwen42** [pytorch/torchdynamo#1937]
### 🐛 Describe the bug

The following 4 models: DebertaV2ForQuestionAnswering, DebertaForMaskedLM, DebertaForQuestionAnswering, DebertaV2ForMaskedLM, all trigger an AssertError in functorch, e.g.
```
ERROR:common:Failed for dynamo At compilation time, this graph was compiled under the assumption that some inputs were duplicate, but at runtime input 3 was not a duplicate of 2.  This indicates a guard bug in AOTAutograd or Dynamo, please file a bug to PyTorch.
Traceback (most recent call last):
  File "/scratch/williamwen/work/pytorch2/benchmarks/dynamo/common.py", line 1159, in warmup
    fn(model, example_inputs)
  File "/scratch/williamwen/work/pytorch2/torch/_dynamo/eval_frame.py", line 193, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/dynamo/huggingface.py", line 482, in forward_and_backward_pass
    cloned_inputs = clone_inputs(inputs)
  File "benchmarks/dynamo/huggingface.py", line 485, in <graph break in forward_and_backward_pass>
    pred = mod(**cloned_inputs)
  File "/scratch/williamwen/work/pytorch2/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/williamwen/work/bisect-env/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py", line 1369, in forward
    outputs = self.deberta(
  File "/scratch/williamwen/work/pytorch2/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/williamwen/work/bisect-env/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py", line 946, in forward
    embedding_output = self.embeddings(
  File "/scratch/williamwen/work/bisect-env/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py", line 954, in <graph break in forward>
    encoder_outputs = self.encoder(
  File "/scratch/williamwen/work/pytorch2/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/williamwen/work/bisect-env/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py", line 447, in forward
    hidden_states = layer_module(
  File "/scratch/williamwen/work/pytorch2/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/williamwen/work/bisect-env/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py", line 352, in forward
    attention_output = self.attention(
  File "/scratch/williamwen/work/pytorch2/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/williamwen/work/bisect-env/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py", line 285, in forward
    self_output = self.self(
  File "/scratch/williamwen/work/bisect-env/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py", line 297, in <graph break in forward>
    attention_output = self.output(self_output, query_states)
  File "/scratch/williamwen/work/pytorch2/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/williamwen/work/bisect-env/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py", line 264, in forward
    hidden_states = self.dropout(hidden_states)
  File "/scratch/williamwen/work/bisect-env/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py", line 264, in <graph break in forward>
    hidden_states = self.dropout(hidden_states)
  File "/scratch/williamwen/work/pytorch2/torch/_dynamo/eval_frame.py", line 193, in _fn
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch2/functorch/_src/aot_autograd.py", line 1901, in forward
    return compiled_f(
  File "/scratch/williamwen/work/pytorch2/functorch/_src/aot_autograd.py", line 1898, in compiled_f
    return compiled_fn(args)
  File "/scratch/williamwen/work/pytorch2/functorch/_src/aot_autograd.py", line 787, in g
    return f(*args)
  File "/scratch/williamwen/work/pytorch2/functorch/_src/aot_autograd.py", line 1126, in debug_wrapper
    assert x is y, (
AssertionError: At compilation time, this graph was compiled under the assumption that some inputs were duplicate, but at runtime input 3 was not a duplicate of 2.  This indicates a guard bug in AOTAutograd or Dynamo, please file a bug to PyTorch.
```
The models were ran with the command `python benchmarks/dynamo/huggingface.py --performance --amp -dcuda --training --inductor --no-skip --dashboard --only <model name> --cold_start_latency`.

The 4 models also trigger the accuracy minifier with the command `TORCHDYNAMO_REPRO_AFTER=dynamo TORCHDYNAMO_REPRO_LEVEL=4 python benchmarks/dynamo/huggingface.py --performance --amp -dcuda --training --inductor --no-skip --dashboard --only <model name> --cold_start_latency`.

**Comment by ezyang** [comment]
The accuracy minifier looks like a red herring, when I run the minifier on one of the models I get

```
    def forward(self, empty_like):
        bernoulli_ = empty_like.bernoulli_(0.9);  empty_like = None
        sub = 1 - bernoulli_;  bernoulli_ = None
        to = sub.to(torch.bool);  sub = None
        return (to,)
```

which is just RNG being RNG.

**Comment by williamwen42** [comment]
Performance runs for affected models are no longer failing.
