### ISSUE TITLE
[Torch2 CPU] torch._inductor.ir: [WARNING] Using FallbackKernel: aten.cumsum

### ISSUE THREAD

**Issue by boitavoi** [pytorch/torchdynamo#2013]
### 🐛 Describe the bug

I'm trying to compile a UniXcoder model (variation of BERT) from huggingface transformers on CPU.
I use python version '3.8.16' and torch version '2.0.0.dev20221222+cpu'.
When performing `model = torch.compile(model)` with the default mode, as well as `mode=reduce-overhead` on a machine with 8GB ram, I encounter the error provided below. 
Any idea how to get through it?

Thank you!

### Error logs

```
[2022-12-22 14:41:22,477] torch._inductor.ir: [WARNING] Using FallbackKernel: aten.cumsum
[2022-12-22 14:41:35,196] torch._inductor.ir: [WARNING] Using FallbackKernel: aten.cumsum
[2022-12-22 14:41:45,469] torch._inductor.ir: [WARNING] Using FallbackKernel: aten.cumsum
[2022-12-22 14:41:56,081] torch._inductor.ir: [WARNING] Using FallbackKernel: aten.cumsum
[2022-12-22 14:42:06,499] torch._inductor.ir: [WARNING] Using FallbackKernel: aten.cumsum
[2022-12-22 14:42:19,296] torch._inductor.ir: [WARNING] Using FallbackKernel: aten.cumsum
[2022-12-22 14:42:30,450] torch._inductor.ir: [WARNING] Using FallbackKernel: aten.cumsum
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 676, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/debug_utils.py", line 945, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 1151, in __call__
    return self.compile_fn(model_, inputs_)
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/compile_fx.py", line 398, in compile_fx
    return aot_autograd(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/optimizations/training.py", line 78, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 2353, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 2050, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_tensor_args, aot_config)
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 1305, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 955, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/compile_fx.py", line 373, in fw_compiler
    return inner_compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/debug_utils.py", line 507, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/debug.py", line 223, in inner
    return fn(*args, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/compile_fx.py", line 140, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/graph.py", line 538, in compile_to_fn
    return self.compile_to_module().call
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/graph.py", line 527, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/codecache.py", line 461, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_root/ih/cihuzmkrufm4dzdsf7l5l6b7nhtybr7fexjtnk72btsrlnrnbtew.py", line 6242, in <module>
    async_compile.wait(globals())
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/codecache.py", line 656, in wait
    scope[key] = result.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/codecache.py", line 633, in task
    return CppCodeCache.load(source_code).kernel
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/codecache.py", line 438, in load
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1639, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "compile.py", line 596, in <module>
    embeddings = get_embeddings(model, code_segments)
  File "compile.py", line 582, in get_embeddings
    _,code_embedding = model(source_ids)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/unixcoder.py", line 83, in forward
    token_embeddings = self.model(source_ids,attention_mask = mask.unsqueeze(1) * mask.unsqueeze(2))[0]
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 83, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 212, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 333, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 480, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 400, in _compile
    out_code = transform_code_object(code, transform)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 387, in transform
    tracer.run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1684, in run
    super().run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1750, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 553, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 600, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 681, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised OSError: [Errno 12] Cannot allocate memory

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

**Comment by williamwen42** [comment]
Do you get the same error when you try `backend="eager"` or `backend="aot_eager"` as an option in `torch.compile`?

**Comment by boitavoi** [comment]
> Do you get the same error when you try `backend="eager"` or `backend="aot_eager"` as an option in `torch.compile`?

Thank you for replying.
I tried them both, it actually doesn't crash anymore, but - the runtime performance is really bad.
I compare the runtime of the original model (without compile) to the model compiled with both `eager` and `aot_eager` backends:

**Without compile:**
`Total time 28.479018211364746`
**eager:**
`Total time 104.0422477722168`
**aot_eager:**
`Total time 175.95780992507935`

any idea why?

**Comment by jgong5** [comment]
@boitavoi Do you mind share the reproducer code?

**Comment by boitavoi** [comment]
> @boitavoi Do you mind share the reproducer code?

Sure, in the attached zip you'll find:
- unixcoder.py (as given by https://github.com/microsoft/CodeBERT/tree/master/UniXcoder) 
- code.py - simple python script that creates embedding for source code fragments.
[code.zip](https://github.com/pytorch/torchdynamo/files/10303176/code.zip)

**Comment by joseph-c-kim** [comment]
Is there an update on this? I'm having the exact same issue.

**Comment by Valentine233** [comment]
The issue is not caused by `[WARNING] Using FallbackKernel: aten.cumsum`. For `aten.cumsum`, using fallback is on purpose for low efficiency of decomposition https://github.com/pytorch/torchdynamo/issues/883.

The error above is `Cannot allocate memory`. Actually, I could run the code with inductor mode without error and it seems that the error is due to inefficiency of inductor mode. I compared the performance in four modes. 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/xuanliao/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/xuanliao/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">



mode | time
-- | --
without compile | 6.491733
inductor | 15.01677
eager | 5.857629
aot_eager | 6.040424



</body>

</html>

Notice that the first time of compiling mode is usually time-consuming and it is better to run repeatedly. I've run 10 times and excluded the first performance here.

Details of data:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/xuanliao/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/xuanliao/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">



without compile
8.862784147
7.331763983
8.797510624
6.193632603
6.044025898
5.985580683
5.909735918
6.417853832
5.958158016
5.787334919
 
inductor
522.4309599
18.03655243
15.26723146
15.8309319
15.37905502
14.9801507
14.20492935
14.25522494
13.8550992
14.27873015
14.07980537
 
eager
76.17847276
5.888897419
5.793441057
5.563881159
5.665488482
5.629543304
6.018662691
5.815788269
5.927585363
6.117486238
6.155511618
 
aot_eager
142.1525922
6.320661306
5.981152534
5.77075839
5.898153543
5.977357864
5.99329257
6.369976044
6.220510244
5.851990461
6.020391941



</body>

</html>

**Comment by Valentine233** [comment]
For the reasons why inductor performs worse than eager, here are some updates.

1. 7500 `mkl_linear` of inductor cost an additional 1s compared to aten::addmm of eager;
2. Inductor kernels cannot do vectorization due to `to_type` (float, int) 1300 times;
3. Both using the same ops, it is strange that inductor is slower than eager. Also, the number of callings sometimes does not match.
    * `aten::bmm`: inductor 629ms #2400; aten 525ms #2400
    * `aten::as_strided`: inductor 41ms #13600; 9ms #27500
    * `aten::empty`: inductor 35ms #7400; aten 10ms #9100


### Profilings
**Inductor**
--------------------------  ------------  ------------  ------------  ------------  ------------  ------------
                      Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
          mkl::_mkl_linear        25.21%        4.348s        25.41%        4.383s     600.434us          7300
                 aten::bmm         3.65%     628.859ms         3.65%     628.897ms     262.040us          2400
          aten::as_strided         0.24%      41.000ms         0.24%      41.000ms       3.015us         13600
               aten::empty         0.21%      35.677ms         0.21%      35.677ms       4.821us          7400
      graph_7_kernel_cpp_4         0.13%      22.478ms         0.13%      22.478ms       4.496ms             5
     graph_10_kernel_cpp_4         0.13%      22.447ms         0.13%      22.447ms       4.489ms             5
     graph_7_kernel_cpp_60         0.13%      22.298ms         0.13%      22.298ms       4.460ms             5
     graph_7_kernel_cpp_11         0.13%      22.153ms         0.13%      22.153ms       4.431ms             5
     graph_7_kernel_cpp_46         0.13%      22.033ms         0.13%      22.033ms       4.407ms             5
     graph_7_kernel_cpp_25         0.13%      22.026ms         0.13%      22.026ms       4.405ms             5
     graph_7_kernel_cpp_39         0.13%      21.936ms         0.13%      21.936ms       4.387ms             5
     graph_7_kernel_cpp_67         0.13%      21.891ms         0.13%      21.891ms       4.378ms             5
     graph_7_kernel_cpp_74         0.13%      21.852ms         0.13%      21.852ms       4.370ms             5
     graph_7_kernel_cpp_81         0.13%      21.704ms         0.13%      21.704ms       4.341ms             5
     graph_7_kernel_cpp_32         0.13%      21.702ms         0.13%      21.702ms       4.340ms             5
     graph_7_kernel_cpp_18         0.13%      21.650ms         0.13%      21.650ms       4.330ms             5
    graph_10_kernel_cpp_11         0.13%      21.563ms         0.13%      21.563ms       4.313ms             5
     graph_7_kernel_cpp_53         0.12%      21.488ms         0.12%      21.488ms       4.298ms             5
    graph_10_kernel_cpp_32         0.12%      21.449ms         0.12%      21.449ms       4.290ms             5
    graph_10_kernel_cpp_53         0.12%      21.269ms         0.12%      21.269ms       4.254ms             5
    graph_10_kernel_cpp_74         0.12%      21.265ms         0.12%      21.265ms       4.253ms             5
    graph_10_kernel_cpp_18         0.12%      21.226ms         0.12%      21.226ms       4.245ms             5
    graph_10_kernel_cpp_60         0.12%      21.201ms         0.12%      21.201ms       4.240ms             5
    graph_10_kernel_cpp_46         0.12%      21.122ms         0.12%      21.122ms       4.224ms             5
    graph_10_kernel_cpp_81         0.12%      21.089ms         0.12%      21.089ms       4.218ms             5
    graph_10_kernel_cpp_67         0.12%      20.947ms         0.12%      20.947ms       4.189ms             5
    graph_10_kernel_cpp_39         0.12%      20.828ms         0.12%      20.828ms       4.166ms             5
    graph_10_kernel_cpp_25         0.12%      20.755ms         0.12%      20.755ms       4.151ms             5
    graph_29_kernel_cpp_18         0.12%      19.973ms         0.12%      19.973ms       3.995ms             5
    graph_29_kernel_cpp_67         0.11%      19.611ms         0.11%      19.611ms       3.922ms             5
    graph_29_kernel_cpp_53         0.11%      19.512ms         0.11%      19.512ms       3.902ms             5
    graph_29_kernel_cpp_81         0.11%      19.491ms         0.11%      19.491ms       3.898ms             5
    graph_29_kernel_cpp_11         0.11%      19.443ms         0.11%      19.443ms       3.889ms             5
    graph_29_kernel_cpp_60         0.11%      19.437ms         0.11%      19.437ms       3.887ms             5
    graph_29_kernel_cpp_39         0.11%      19.427ms         0.11%      19.427ms       3.885ms             5
    graph_29_kernel_cpp_32         0.11%      19.388ms         0.11%      19.388ms       3.878ms             5
     graph_29_kernel_cpp_4         0.11%      19.256ms         0.11%      19.256ms       3.851ms             5
    graph_29_kernel_cpp_46         0.11%      19.079ms         0.11%      19.079ms       3.816ms             5
    graph_29_kernel_cpp_74         0.11%      18.881ms         0.11%      18.881ms       3.776ms             5
    graph_29_kernel_cpp_25         0.11%      18.763ms         0.11%      18.763ms       3.753ms             5
     graph_11_kernel_cpp_4         0.11%      18.587ms         0.11%      18.587ms       4.647ms             4
    graph_11_kernel_cpp_18         0.10%      17.638ms         0.10%      17.638ms       4.410ms             4
    graph_11_kernel_cpp_60         0.10%      17.627ms         0.10%      17.627ms       4.407ms             4
    graph_11_kernel_cpp_32         0.10%      17.560ms         0.10%      17.560ms       4.390ms             4
    graph_11_kernel_cpp_39         0.10%      17.406ms         0.10%      17.406ms       4.351ms             4
    graph_11_kernel_cpp_81         0.10%      17.397ms         0.10%      17.397ms       4.349ms             4
    graph_11_kernel_cpp_74         0.10%      17.299ms         0.10%      17.299ms       4.325ms             4
    graph_11_kernel_cpp_67         0.10%      17.143ms         0.10%      17.143ms       4.286ms             4
    graph_11_kernel_cpp_11         0.10%      17.117ms         0.10%      17.117ms       4.279ms             4
    graph_11_kernel_cpp_25         0.10%      16.873ms         0.10%      16.873ms       4.218ms             4
    graph_11_kernel_cpp_53         0.10%      16.753ms         0.10%      16.753ms       4.188ms             4
     graph_30_kernel_cpp_4         0.10%      16.701ms         0.10%      16.701ms       4.175ms             4
    graph_11_kernel_cpp_46         0.10%      16.700ms         0.10%      16.700ms       4.175ms             4
    graph_30_kernel_cpp_32         0.10%      16.577ms         0.10%      16.577ms       4.144ms             4
    graph_30_kernel_cpp_46         0.10%      16.511ms         0.10%      16.511ms       4.128ms             4
     graph_27_kernel_cpp_4         0.09%      16.361ms         0.09%      16.361ms       4.090ms             4
    graph_30_kernel_cpp_67         0.09%      16.314ms         0.09%      16.314ms       4.079ms             4
    graph_30_kernel_cpp_60         0.09%      16.040ms         0.09%      16.040ms       4.010ms             4
                 aten::mul         0.09%      15.999ms         0.11%      19.498ms      97.490us           200
    graph_27_kernel_cpp_53         0.09%      15.978ms         0.09%      15.978ms       3.994ms             4
    graph_30_kernel_cpp_18         0.09%      15.946ms         0.09%      15.946ms       3.986ms             4
    graph_30_kernel_cpp_81         0.09%      15.874ms         0.09%      15.874ms       3.969ms             4
    graph_30_kernel_cpp_25         0.09%      15.857ms         0.09%      15.857ms       3.964ms             4
    graph_27_kernel_cpp_74         0.09%      15.855ms         0.09%      15.855ms       3.964ms             4
    graph_27_kernel_cpp_25         0.09%      15.853ms         0.09%      15.853ms       3.963ms             4
    graph_30_kernel_cpp_74         0.09%      15.847ms         0.09%      15.847ms       3.962ms             4
    graph_30_kernel_cpp_11         0.09%      15.841ms         0.09%      15.841ms       3.960ms             4
    graph_27_kernel_cpp_46         0.09%      15.778ms         0.09%      15.778ms       3.945ms             4
    graph_27_kernel_cpp_67         0.09%      15.759ms         0.09%      15.759ms       3.940ms             4
    graph_27_kernel_cpp_81         0.09%      15.722ms         0.09%      15.722ms       3.930ms             4
    graph_27_kernel_cpp_39         0.09%      15.717ms         0.09%      15.717ms       3.929ms             4
    graph_27_kernel_cpp_18         0.09%      15.700ms         0.09%      15.700ms       3.925ms             4
    graph_30_kernel_cpp_39         0.09%      15.699ms         0.09%      15.699ms       3.925ms             4
    graph_27_kernel_cpp_32         0.09%      15.568ms         0.09%      15.568ms       3.892ms             4
    graph_27_kernel_cpp_60         0.09%      15.539ms         0.09%      15.539ms       3.885ms             4
    graph_27_kernel_cpp_11         0.09%      15.447ms         0.09%      15.447ms       3.862ms             4
    graph_30_kernel_cpp_53         0.09%      15.394ms         0.09%      15.394ms       3.849ms             4
      graph_1_kernel_cpp_4         0.08%      14.516ms         0.08%      14.516ms       4.839ms             3
     graph_12_kernel_cpp_4         0.08%      14.502ms         0.08%      14.502ms       4.834ms             3
      graph_2_kernel_cpp_4         0.08%      13.993ms         0.08%      13.993ms       4.664ms             3
     graph_1_kernel_cpp_60         0.08%      13.971ms         0.08%      13.971ms       4.657ms             3
     graph_2_kernel_cpp_18         0.08%      13.653ms         0.08%      13.653ms       4.551ms             3
     graph_2_kernel_cpp_60         0.08%      13.610ms         0.08%      13.610ms       4.537ms             3
     graph_2_kernel_cpp_11         0.08%      13.578ms         0.08%      13.578ms       4.526ms             3
     graph_1_kernel_cpp_67         0.08%      13.546ms         0.08%      13.546ms       4.515ms             3
    graph_12_kernel_cpp_18         0.08%      13.534ms         0.08%      13.534ms       4.511ms             3
     graph_15_kernel_cpp_4         0.08%      13.534ms         0.08%      13.534ms       4.511ms             3
     graph_2_kernel_cpp_46         0.08%      13.529ms         0.08%      13.529ms       4.510ms             3
     graph_2_kernel_cpp_74         0.08%      13.517ms         0.08%      13.517ms       4.506ms             3
     graph_1_kernel_cpp_46         0.08%      13.508ms         0.08%      13.508ms       4.503ms             3
     graph_1_kernel_cpp_25         0.08%      13.467ms         0.08%      13.467ms       4.489ms             3
     graph_5_kernel_cpp_18         0.08%      13.464ms         0.08%      13.464ms       4.488ms             3
      graph_5_kernel_cpp_4         0.08%      13.456ms         0.08%      13.456ms       4.485ms             3
     graph_1_kernel_cpp_81         0.08%      13.396ms         0.08%      13.396ms       4.465ms             3
     graph_1_kernel_cpp_74         0.08%      13.355ms         0.08%      13.355ms       4.452ms             3
     graph_1_kernel_cpp_53         0.08%      13.348ms         0.08%      13.348ms       4.449ms             3
    graph_12_kernel_cpp_11         0.08%      13.332ms         0.08%      13.332ms       4.444ms             3
    graph_15_kernel_cpp_32         0.08%      13.317ms         0.08%      13.317ms       4.439ms             3
     graph_5_kernel_cpp_39         0.08%      13.305ms         0.08%      13.305ms       4.435ms             3
     graph_2_kernel_cpp_53         0.08%      13.267ms         0.08%      13.267ms       4.422ms             3
--------------------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 17.247s

**Eager**
---------------------------  ------------  ------------  ------------  ------------  ------------  ------------
                       Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
                aten::addmm        52.64%        3.280s        58.06%        3.618s     495.552us          7300
                  aten::bmm         8.43%     525.192ms         8.43%     525.192ms     218.830us          2400
                  aten::add         7.74%     482.587ms         7.75%     483.054ms     123.860us          3900
                  aten::div         6.84%     426.328ms         7.23%     450.471ms     346.516us          1300
                aten::copy_         6.53%     407.151ms         6.53%     407.151ms      37.699us         10800
                 aten::gelu         5.66%     352.548ms         5.66%     352.548ms     293.790us          1200
             aten::_softmax         4.21%     262.120ms         4.21%     262.120ms     218.433us          1200
    aten::native_layer_norm         2.44%     152.096ms         2.56%     159.429ms      63.772us          2500
               aten::linear         0.66%      41.319ms        59.65%        3.717s     509.139us          7300
               aten::expand         0.47%      29.157ms         0.51%      31.720ms       2.600us         12200
            aten::transpose         0.41%      25.438ms         0.48%      29.791ms       3.505us          8500
               aten::matmul         0.41%      25.335ms         9.55%     595.245ms     248.019us          2400
                 aten::view         0.35%      21.498ms         0.35%      21.498ms       0.877us         24500
                    aten::t         0.31%      19.162ms         0.71%      43.998ms       6.027us          7300
              aten::reshape         0.29%      17.767ms         0.39%      24.554ms       4.815us          5100
              aten::permute         0.25%      15.397ms         0.27%      16.905ms       3.522us          4800
         aten::index_select         0.24%      14.656ms         0.26%      15.906ms      53.020us           300
                  aten::mul         0.22%      13.540ms         0.26%      16.038ms      40.095us           400
             aten::_to_copy         0.20%      12.321ms         0.45%      28.054ms      12.197us          2300
                aten::clone         0.17%      10.861ms         1.44%      89.456ms      74.547us          1200
                aten::empty         0.16%       9.740ms         0.16%       9.740ms       1.070us          9100
           aten::as_strided         0.15%       9.316ms         0.15%       9.316ms       0.339us         27500
           aten::layer_norm         0.15%       9.231ms         2.71%     168.660ms      67.464us          2500
              aten::softmax         0.14%       8.645ms         4.27%     265.976ms     221.647us          1200
                   aten::to         0.13%       8.003ms         0.54%      33.950ms      13.580us          2500
       aten::_reshape_alias         0.12%       7.332ms         0.12%       7.332ms       1.438us          5100
                  aten::sum         0.11%       6.898ms         0.13%       8.194ms      40.970us           200
        aten::empty_strided         0.09%       5.850ms         0.09%       5.850ms       2.543us          2300
         aten::_unsafe_view         0.08%       4.827ms         0.08%       4.827ms       2.011us          2400
                  aten::sub         0.06%       3.961ms         0.07%       4.541ms      45.410us           100
           aten::contiguous         0.06%       3.736ms         1.49%      92.583ms      77.153us          1200
           aten::empty_like         0.05%       3.253ms         0.10%       6.278ms       5.232us          1200
                 aten::add_         0.04%       2.275ms         0.04%       2.275ms      22.750us           100
               aten::select         0.03%       2.108ms         0.04%       2.192ms       3.131us           700
            aten::embedding         0.03%       1.945ms         0.30%      18.883ms      62.943us           300
                aten::slice         0.03%       1.902ms         0.03%       1.996ms       3.327us           600
                 aten::tanh         0.03%       1.873ms         0.03%       1.873ms      18.730us           100
                   aten::ne         0.03%       1.745ms         0.03%       1.745ms       8.725us           200
            aten::unsqueeze         0.02%       1.406ms         0.02%       1.537ms       3.074us           500
               aten::cumsum         0.02%     975.000us         0.02%       1.542ms      15.420us           100
                 aten::rsub         0.01%     645.000us         0.08%       5.186ms      51.860us           100
              aten::detach_         0.01%     444.000us         0.01%     566.000us       5.660us           100
                aten::fill_         0.01%     328.000us         0.01%     328.000us       1.640us           200
                    detach_         0.00%     162.000us         0.00%     162.000us       1.620us           100
              aten::type_as         0.00%     139.000us         0.01%     614.000us       6.140us           100
         aten::resolve_conj         0.00%      13.000us         0.00%      13.000us       0.001us         19400
              aten::dropout         0.00%       9.000us         0.00%       9.000us       0.002us          3700
           aten::lift_fresh         0.00%       3.000us         0.00%       3.000us       0.030us           100
---------------------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 6.231s

**Comment by Valentine233** [comment]
Inductor mode generates 50 graphs and each one occupies about 1 GB of memory. It is found that inductor uses a high memory due to mkl linear weight prepack which would store an extra copy of the weight.

**Comment by jansel** [comment]
Perhaps we need a config to disable the weight prepacking for memory savings
