### ISSUE TITLE
_pack_padded_sequence fails in dynamo due to requiring a non-fake 2nd argument

### ISSUE THREAD

**Issue by davidberard98** [pytorch/torchdynamo#2024]
### 🐛 Describe the bug

`_pack_padded_sequence()` op takes a 2nd argument as a tensor of integers. The current implementation fails in dynamo when trying to `get_fake_value()`, because the 2nd argument is converted to a fake tensor.

Repro:
```python
import torch
import torch._dynamo

def fn(x, seq_lens):
    return torch.nn.utils.rnn.pack_padded_sequence(x, seq_lens.tolist(), batch_first=True)

args = [torch.rand((4, 4, 4)), torch.ones([4], dtype=torch.int64)]

fn(*args)
fn_opt = torch._dynamo.optimize("eager")(fn)
fn_opt(*args)
```

Stacktrace:
```python
$ python repro_pack.py
Traceback (most recent call last):
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/utils.py", line 1078, in run_node
    return node.target(*args, **kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/nn/utils/rnn.py", line 263, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
  File "/scratch/dberard/dynamo38/pytorch/torch/_subclasses/fake_tensor.py", line 916, in __torch_dispatch__
    r = func(*args, **kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D meta Long tensor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/utils.py", line 1037, in get_fake_value
    return wrap_fake_exception(
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/utils.py", line 714, in wrap_fake_exception
    return fn()
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/utils.py", line 1038, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/utils.py", line 1090, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_function <function pack_padded_sequence at 0x7f86cc82c0d0>(*(FakeTensor(FakeTensor(..., device='meta', size=(4, 4, 4)), cpu), [1, 1, 1, 1]), **{'batch_
first': True}):
'lengths' argument should be a 1D CPU int64 tensor, but got 1D meta Long tensor
(scroll up for backtrace)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "repro_pack.py", line 11, in <module>
    fn_opt(*args)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/eval_frame.py", line 212, in _fn
    return fn(*args, **kwargs)
  File "repro_pack.py", line 5, in fn
    return torch.nn.utils.rnn.pack_padded_sequence(x, seq_lens.tolist(), batch_first=True)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/eval_frame.py", line 333, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/convert_frame.py", line 480, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/utils.py", line 94, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/convert_frame.py", line 400, in _compile
    out_code = transform_code_object(code, transform)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/convert_frame.py", line 387, in transform
    tracer.run()
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/symbolic_convert.py", line 1684, in run
    super().run()
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/symbolic_convert.py", line 307, in wrapper
    return inner_fn(self, inst)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/symbolic_convert.py", line 1015, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/symbolic_convert.py", line 435, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/variables/torch.py", line 470, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/variables/builder.py", line 731, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/variables/builder.py", line 766, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/utils.py", line 1057, in get_fake_value
    raise TorchRuntimeError() from e
torch._dynamo.exc.TorchRuntimeError:

from user code:
   File "repro_pack.py", line 5, in <graph break in fn>
    return torch.nn.utils.rnn.pack_padded_sequence(x, seq_lens.tolist(), batch_first=True)

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

Failure occurs here: https://github.com/pytorch/pytorch/blob/32e9b29ce92604908bbe6f73796aa17e82b4462f/aten/src/ATen/native/PackedSequence.cpp#L25

**Comment by ngimel** [comment]
It's a dynamic output shape op, should be added to corresponding list in dynamo (it's similar to jagged tensor ops)

**Comment by davidberard98** [comment]
@ngimel thanks for the insight, could you provide some pointers for this? I took a look but I couldn't find such a list in dynamo.

more context / what I found when I was looking around:
* I was comparing `_pack_padded_sequence` to `tensor_split`, since both of these take a `Tensor[int] | list[int]` as one of the arguments.
  + `tensor_split` has a [variant that takes a SymInt[]](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L1364) as well as a variant that takes a tensor, whereas `_pack_padded_sequence` only has a [variant that takes a tensor](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L7214). Do I need to add an implementation that takes a SymInt[] or is there a way around this without a new variant?
  + The tensor_split variant that takes a `Tensor` input also fails in a similar way to `_pack_padded_sequence`. i.e., `torch.tensor_split(x, sizes.tolist())` passes, but `torch.tensor_split(x, sizes)` . Do we expect the second usage to pass, and if so how do we do this?

**Comment by ngimel** [comment]
Tagging dynamic shapes gang @voznesenskym @ezyang time has come to decide what we are doing with those dynamic output size ops (or popularize existing solutions if we have those). For _pack_padded_sequence the output size depends on the values in the `len` argument. Specializing on them will be useless as we expect them to change every iteration, making `len` a tensor of `SymInt` is kinda getting there, but do we have or want to have SymInt tensors?
Other ops that will be in the same bucket are `one_hot` (without output size), `repeat_interleave` (without output size), and various jagged tensor conversions.

**Comment by ezyang** [comment]
Let's set aside the tensor of SymInts thing for a moment, that's its own kettle of fish.

The way this is supposed to work today is we graph break on operators that have data dependent output size, run the operator in traditional eager mode, and then start a new subgraph. When dynamic shapes is enabled the subgraph can deal with the input tensor dynamically varying in size and we only compile once. For real world users this is not useful atm, because inductor dynamic shapes is not working (cc @Chillee). But it will be soon. If Dynamo isn't graph breaking on these operators,  we should.

**Comment by ezyang** [comment]
Now, the original example is a little more complicated because there is a tensor.tolist() call. We haven't really discussed this case very much, and how complicated it is kind of depends on the characteristics of tensor.

The simple case is when tensor is 1D and tensor.size(0) is static. Then tensor.tolist() desugars to a fixed size [tensor[0], tensor[1]] (eg). This is essentially equivalent to item() support in Dynamo. Now our item() support in Dynamo is kind of bad but if you graph break until after pack padded sequences the items are all gone and you have a packed sequence whose length is derived from summing each of these symints.

However, this probably not what you want, because (1) your batch size is typically dynamic and (2) even if the batch size was static it's probably pretty big and you don't want Dynamo to have to reason about on order of 8k individual SymInts (well I guess you could but Dynamo, being written in Python, will probably scale poorly here.) So we probably would prefer to model the sequence lengths directly as a CPU tensor. This puts is in a pickle when the user writes tolist(). I guess the easiest thing to do is introduce a new list tracking variable that is "tolist of some tensor" and see if we can avoid actually specializing on the size (or better yet, optimize away the tolist call so it's tensor operations only). This is kind of similar to how our item() handling works, where we keep the og tensor around for modeling in FX graph.
