### ISSUE TITLE
[python key tracing] Parameters showing up as FX constants for demucs

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#203]
I think this might be an issue with python key tracing.  I am getting this error:
```
ERROR FROM offset=54 filename /home/jansel/torchbenchmark/torchbenchmark/models/demucs/demucs/model.py 30 AssertionError
========== TorchDynamo Stack Trace ==========
Traceback (most recent call last):
  File "/home/jansel/torchdynamo/torchdynamo/convert_frame.py", line 174, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/home/jansel/torchdynamo/torchdynamo/bytecode_transformation.py", line 338, in transform_code_object
    transformations(instructions, code_options)
  File "/home/jansel/torchdynamo/torchdynamo/convert_frame.py", line 150, in transform
    tracer.run()
  File "/home/jansel/torchdynamo/torchdynamo/symbolic_convert.py", line 278, in run
    and self.step()
  File "/home/jansel/torchdynamo/torchdynamo/symbolic_convert.py", line 256, in step
    getattr(self, inst.opname)(inst)
  File "/home/jansel/torchdynamo/torchdynamo/symbolic_convert.py", line 1194, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/home/jansel/torchdynamo/torchdynamo/output_graph.py", line 240, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/jansel/torchdynamo/torchdynamo/output_graph.py", line 303, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/jansel/torchdynamo/torchdynamo/output_graph.py", line 317, in call_user_compiler
    compiled_fn = self.compiler_fn(gm, self.example_inputs())
  File "/home/jansel/torchdynamo/torchinductor/compile_fx.py", line 124, in compile_fx
    wrap(graph.run)(*example_inputs)
  File "/home/jansel/torchdynamo/torchdynamo/optimizations/python_key.py", line 129, in call_fn
    return inner(*params_flat, *args)
  File "/home/jansel/torchdynamo/torchinductor/graph.py", line 76, in run
    return super().run(*args)
  File "/home/jansel/pytorch/torch/fx/interpreter.py", line 125, in run
    self.env[node] = self.run_node(node)
  File "/home/jansel/torchdynamo/torchinductor/graph.py", line 132, in run_node
    result = super().run_node(n)
  File "/home/jansel/pytorch/torch/fx/interpreter.py", line 152, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/jansel/torchdynamo/torchinductor/graph.py", line 119, in get_attr
    assert value.shape == (), value
AssertionError: Parameter containing:
tensor([[-0.0095,  0.0026, -0.0003,  ..., -0.0194, -0.0178, -0.0041],
        [ 0.0028, -0.0139,  0.0045,  ...,  0.0077, -0.0161, -0.0211],
        [-0.0152,  0.0152, -0.0165,  ...,  0.0195, -0.0218, -0.0163],
        ...,
        [ 0.0041,  0.0097, -0.0110,  ...,  0.0207, -0.0085,  0.0128],
        [-0.0210,  0.0018,  0.0106,  ..., -0.0131,  0.0188,  0.0023],
        [ 0.0190,  0.0088, -0.0028,  ...,  0.0201, -0.0161, -0.0155]],
       device='cuda:0', requires_grad=True)
```

Which is triggering this line:
https://github.com/jansel/torchdynamo/blob/1b2d10ce2e1243f2b97aa2c63f3d2496abbaed62/torchinductor/graph.py#L119

I believe this behavior is wrong.  Python key tracing should be lifting all weights into inputs into the graph, though it appears at least one is slipping through.

This might cause correctness issues in training.

cc @Chillee

**Comment by Chillee** [comment]
This might be the same issue as LSTMs: https://github.com/pytorch/functorch/issues/586

Will look into it.

**Comment by ezyang** [comment]
I don't get any more errors on master with

```
$ ./torchbench.py --no-skip  -n 1 -k demucs --devices cuda --python-key
```
