### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by chexiangying** [pytorch/torchdynamo#2039]
### 🐛 Describe the bug

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [1024]] is at version 24; expected version 23 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

### Error logs

[2023-01-17 16:14:06,580] torch._inductor.ir: [WARNING] DeviceCopy
[2023-01-17 16:14:06,584] torch._inductor.ir: [WARNING] DeviceCopy
[2023-01-17 16:14:06,587] torch._inductor.ir: [WARNING] DeviceCopy
[2023-01-17 16:14:06,617] torch._inductor.ir: [WARNING] DeviceCopy
[2023-01-17 16:14:06,638] torch._inductor.ir: [WARNING] DeviceCopy
[2023-01-17 16:14:06,638] torch._inductor.ir: [WARNING] DeviceCopy
[2023-01-17 16:14:06,671] torch._inductor.ir: [WARNING] DeviceCopy
[2023-01-17 16:14:06,679] torch._inductor.ir: [WARNING] DeviceCopy
[2023-01-17 16:14:06,726] torch._inductor.compile_fx: [WARNING] skipping cudagraphs due to multiple devices
[2023-01-17 16:14:06,736] torch._inductor.compile_fx: [WARNING] skipping cudagraphs due to multiple devices
[2023-01-17 16:14:06,743] torch._inductor.compile_fx: [WARNING] skipping cudagraphs due to multiple devices
[2023-01-17 16:14:06,759] torch._inductor.compile_fx: [WARNING] skipping cudagraphs due to multiple devices
[2023-01-17 16:14:06,778] torch._inductor.compile_fx: [WARNING] skipping cudagraphs due to multiple devices
[2023-01-17 16:14:06,787] torch._inductor.compile_fx: [WARNING] skipping cudagraphs due to multiple devices
[2023-01-17 16:14:06,820] torch._inductor.compile_fx: [WARNING] skipping cudagraphs due to multiple devices
[2023-01-17 16:14:06,831] torch._inductor.compile_fx: [WARNING] skipping cudagraphs due to multiple devices
/home/tiger/.local/lib/python3.7/site-packages/torch/cuda/graphs.py:82: UserWarning: The CUDA Graph is empty. This ususally means that the graph was attempted to be captured on wrong device or stream. (Triggered internally at ../aten/src/ATen/cuda/CUDAGraph.cpp:191.)
  super(CUDAGraph, self).capture_end()
/home/tiger/.local/lib/python3.7/site-packages/torch/cuda/graphs.py:82: UserWarning: The CUDA Graph is empty. This ususally means that the graph was attempted to be captured on wrong device or stream. (Triggered internally at ../aten/src/ATen/cuda/CUDAGraph.cpp:191.)
  super(CUDAGraph, self).capture_end()
/home/tiger/.local/lib/python3.7/site-packages/torch/cuda/graphs.py:82: UserWarning: The CUDA Graph is empty. This ususally means that the graph was attempted to be captured on wrong device or stream. (Triggered internally at ../aten/src/ATen/cuda/CUDAGraph.cpp:191.)
  super(CUDAGraph, self).capture_end()
/home/tiger/.local/lib/python3.7/site-packages/torch/cuda/graphs.py:82: UserWarning: The CUDA Graph is empty. This ususally means that the graph was attempted to be captured on wrong device or stream. (Triggered internally at ../aten/src/ATen/cuda/CUDAGraph.cpp:191.)
  super(CUDAGraph, self).capture_end()
/home/tiger/.local/lib/python3.7/site-packages/torch/cuda/graphs.py:82: UserWarning: The CUDA Graph is empty. This ususally means that the graph was attempted to be captured on wrong device or stream. (Triggered internally at ../aten/src/ATen/cuda/CUDAGraph.cpp:191.)
  super(CUDAGraph, self).capture_end()
/home/tiger/.local/lib/python3.7/site-packages/torch/cuda/graphs.py:82: UserWarning: The CUDA Graph is empty. This ususally means that the graph was attempted to be captured on wrong device or stream. (Triggered internally at ../aten/src/ATen/cuda/CUDAGraph.cpp:191.)
  super(CUDAGraph, self).capture_end()
/home/tiger/.local/lib/python3.7/site-packages/torch/cuda/graphs.py:82: UserWarning: The CUDA Graph is empty. This ususally means that the graph was attempted to be captured on wrong device or stream. (Triggered internally at ../aten/src/ATen/cuda/CUDAGraph.cpp:191.)
  super(CUDAGraph, self).capture_end()
/home/tiger/.local/lib/python3.7/site-packages/torch/cuda/graphs.py:82: UserWarning: The CUDA Graph is empty. This ususally means that the graph was attempted to be captured on wrong device or stream. (Triggered internally at ../aten/src/ATen/cuda/CUDAGraph.cpp:191.)
  super(CUDAGraph, self).capture_end()
Traceback (most recent call last):
  File "fsdp_pretrain.py", line 423, in <module>
Traceback (most recent call last):
  File "fsdp_pretrain.py", line 423, in <module>
    main(args)
  File "fsdp_pretrain.py", line 318, in main
    main(args)
  File "fsdp_pretrain.py", line 318, in main
    scaler.scale(loss).backward()
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward
        self, gradient, retain_graph, create_graph, inputs=inputsscaler.scale(loss).backward()

  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 199, in backward
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/function.py", line 276, in apply
    self, gradient, retain_graph, create_graph, inputs=inputs
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 199, in backward
    return user_fn(self, *args)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_functorch/aot_autograd.py", line 1848, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/function.py", line 276, in apply
    return user_fn(self, *args)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_functorch/aot_autograd.py", line 1848, in backward
    list(ctx.symints) + list(ctx.saved_tensors) + list(contiguous_args)
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [1024]] is at version 24; expected version 23 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
    list(ctx.symints) + list(ctx.saved_tensors) + list(contiguous_args)
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [1024]] is at version 24; expected version 23 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
Traceback (most recent call last):
  File "fsdp_pretrain.py", line 423, in <module>
Traceback (most recent call last):
  File "fsdp_pretrain.py", line 423, in <module>
    main(args)
  File "fsdp_pretrain.py", line 318, in main
    scaler.scale(loss).backward()
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward
    self, gradient, retain_graph, create_graph, inputs=inputs
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 199, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/function.py", line 276, in apply
    return user_fn(self, *args)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_functorch/aot_autograd.py", line 1848, in backward
        list(ctx.symints) + list(ctx.saved_tensors) + list(contiguous_args)main(args)

RuntimeError  File "fsdp_pretrain.py", line 318, in main
: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [1024]] is at version 24; expected version 23 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
    scaler.scale(loss).backward()
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward
    self, gradient, retain_graph, create_graph, inputs=inputs
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 199, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/function.py", line 276, in apply
    return user_fn(self, *args)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_functorch/aot_autograd.py", line 1848, in backward
    list(ctx.symints) + list(ctx.saved_tensors) + list(contiguous_args)
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [1024]] is at version 24; expected version 23 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
Traceback (most recent call last):
  File "fsdp_pretrain.py", line 423, in <module>
    main(args)
  File "fsdp_pretrain.py", line 318, in main
    scaler.scale(loss).backward()
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward
    self, gradient, retain_graph, create_graph, inputs=inputs
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 199, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/function.py", line 276, in apply
    return user_fn(self, *args)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_functorch/aot_autograd.py", line 1848, in backward
    list(ctx.symints) + list(ctx.saved_tensors) + list(contiguous_args)
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [1024]] is at version 24; expected version 23 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
Traceback (most recent call last):
  File "fsdp_pretrain.py", line 423, in <module>
    main(args)
  File "fsdp_pretrain.py", line 318, in main
    scaler.scale(loss).backward()
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward
    self, gradient, retain_graph, create_graph, inputs=inputs
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 199, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/function.py", line 276, in apply
    return user_fn(self, *args)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_functorch/aot_autograd.py", line 1848, in backward
    list(ctx.symints) + list(ctx.saved_tensors) + list(contiguous_args)
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [1024]] is at version 24; expected version 23 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
Traceback (most recent call last):
  File "fsdp_pretrain.py", line 423, in <module>
Traceback (most recent call last):
  File "fsdp_pretrain.py", line 423, in <module>
text: Unable to write to output stream.
text: Unable to write to output stream.
    main(args)
  File "fsdp_pretrain.py", line 318, in main
    main(args)
  File "fsdp_pretrain.py", line 318, in main
    scaler.scale(loss).backward()
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward
    self, gradient, retain_graph, create_graph, inputs=inputs
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 199, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/function.py", line 276, in apply
    return user_fn(self, *args)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_functorch/aot_autograd.py", line 1848, in backward
    scaler.scale(loss).backward()
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward
    self, gradient, retain_graph, create_graph, inputs=inputs
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 199, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/autograd/function.py", line 276, in apply
    return user_fn(self, *args)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_functorch/aot_autograd.py", line 1848, in backward
    list(ctx.symints) + list(ctx.saved_tensors) + list(contiguous_args)
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [1024]] is at version 24; expected version 23 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
    list(ctx.symints) + list(ctx.saved_tensors) + list(contiguous_args)
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [1024]] is at version 24; expected version 23 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.text: Unable to write to output stream.

text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
  0%|                                                                                                                                                         | 0/50000 [00:23<?, ?it/s]
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
text: Unable to write to output stream.
n128-097-221:216103:217023 [0] NCCL INFO [Service thread] Connection closed by localRank 0
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 216096) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/distributed/run.py", line 773, in run
    )(*cmd_args)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 252, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
fsdp_pretrain.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-01-17_16:14:30
  host      : n128-097-221.byted.org
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 216097)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-01-17_16:14:30
  host      : n128-097-221.byted.org
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 216098)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-01-17_16:14:30
  host      : n128-097-221.byted.org
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 216099)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2023-01-17_16:14:30
  host      : n128-097-221.byted.org
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 216100)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2023-01-17_16:14:30
  host      : n128-097-221.byted.org
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 216101)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2023-01-17_16:14:30
  host      : n128-097-221.byted.org
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 216102)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2023-01-17_16:14:30
  host      : n128-097-221.byted.org
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 216103)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-01-17_16:14:30
  host      : n128-097-221.byted.org
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 216096)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by yanboliang** [comment]
This is related to #1907

**Comment by eellison** [comment]
Hi @chexiangying, please run the minifier and submit a minified repro: https://pytorch.org/docs/master/dynamo/troubleshooting.html.
