### ISSUE TITLE
TorchDynamo is incompatible with einops.repeat

### ISSUE THREAD

**Issue by kaiyaointel** [pytorch/torchdynamo#241]
Hi,

We are doing some functionality validation and performance benchmark for TorchDynamo, and we found that TorchDynamo is incompatible with "einops" (pip package)'s "repeat" function (or maybe also some other functions in einops). For all models that call einops.repeat in nn.Module model definition (e.g. vision transformers models from https://github.com/lucidrains/vit-pytorch), the models can run with regular PyTorch but failed when using TorchDynamo with simply a FX backend, like the example shown in TorchDynamo homepage README.

Reproduction code (test.py):
```
import torch
from torch import nn
from einops import repeat
import argparse

parser = argparse.ArgumentParser(description='')
parser.add_argument('--regular', action='store_true')
parser.add_argument('--torchdynamo', action='store_true')
args = parser.parse_args()

class Net(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        repeat(x, 'h w -> h w c', c=3).shape # an einops.repeat() sentence
        return x

X = torch.randn(30, 40)
model = Net()

model.eval()

# Regular
if args.regular:
    model(X)

# Torchdynamo
if args.torchdynamo:
    import torchdynamo
    from typing import List
    
    def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
        return gm.forward
    
    with torchdynamo.optimize(my_compiler), torch.no_grad():
        model(X)
```
For this code snippet, ```python test.py --regular``` will pass but ```python test.py --torchdynamo``` will fail.

Error Log:
```
Traceback (most recent call last):
  File "/tmp/kyao/torchdynamo/test_einops.py", line 37, in <module>
    model(X)
  File "/mnt/local_disk/miniconda3/envs/ipexnew/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/tmp/kyao/torchdynamo/test_einops.py", line 15, in forward
    def forward(self, x):
  File "/mnt/local_disk/miniconda3/envs/ipexnew/lib/python3.9/site-packages/einops-0.4.1-py3.9.egg/einops/einops.py", line 490, in repeat
    def repeat(tensor: Tensor, pattern: str, **axes_lengths) -> Tensor:
  File "/mnt/local_disk/miniconda3/envs/ipexnew/lib/python3.9/site-packages/einops-0.4.1-py3.9.egg/einops/einops.py", line 410, in reduce
    return _apply_recipe(recipe, tensor, reduction_type=reduction)
  File "/mnt/local_disk/miniconda3/envs/ipexnew/lib/python3.9/site-packages/einops-0.4.1-py3.9.egg/einops/einops.py", line 229, in _apply_recipe
    def _apply_recipe(recipe: TransformRecipe, tensor: Tensor, reduction_type: Reduction) -> Tensor:
  File "/mnt/local_disk/miniconda3/envs/ipexnew/lib/python3.9/site-packages/einops-0.4.1-py3.9.egg/einops/_backends.py", line 22, in get_backend
    def get_backend(tensor) -> 'AbstractBackend':
  File "/mnt/local_disk/miniconda3/envs/ipexnew/lib/python3.9/site-packages/einops-0.4.1-py3.9.egg/einops/_backends.py", line 22, in get_backend
    def get_backend(tensor) -> 'AbstractBackend':
IndexError: list index out of range
```

**Comment by jansel** [comment]
Thanks for reporting this and providing a repro.  I'd expect just a graph break here (which falls back to eager), so clearly something is going wrong.

@yanboliang do you want to take a look at this one?

**Comment by voznesenskym** [comment]
A smaller repro, that might make things easier :)

```
import torch
from torch import nn
from einops import repeat, _backends
import argparse


parser = argparse.ArgumentParser(description='')
parser.add_argument('--regular', action='store_true')
parser.add_argument('--torchdynamo', action='store_true')
args = parser.parse_args()

X = torch.randn(30, 40)

# Regular
if args.regular:
    backend = _backends.get_backend(X)

# Torchdynamo
if args.torchdynamo:
    import torchdynamo
    from typing import List
    
    def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
        print("gm")
        gm.graph.print_tabular()
        return gm.forward
    
    with torchdynamo.optimize(my_compiler), torch.no_grad():
        backend = _backends.get_backend(X)
```

**Comment by jansel** [comment]
@voznesenskym if you want to take a crack at it feel free to assign to yourself.  Just coordinate with @yanboliang, so there is no duplicated work.

**Comment by voznesenskym** [comment]
Thanks @jansel. Will take a look and see what I can do :)

**Comment by voznesenskym** [comment]
@kaiyaointel - we landed a fix, can you give it a try and see if it works for you now?

**Comment by kaiyaointel** [comment]
@voznesenskym I have verified on the related models, and they're runnable now at the latest commit of TorchDynamo.
