### ISSUE TITLE
Unable to torch.jit.script subgraph passed to backend

### ISSUE THREAD

**Issue by ramiro050** [pytorch/torchdynamo#277]
I'm working on adding a custom backend to pytorch using torchdynamo that requires that I run `torch.jit.script` on the subgraph passed by torchdynamo before I compile it further. However, for certain models in torchbench, this results in the error:

```
jit_script error
Traceback (most recent call last):
  File "/usr/local/google/home/ramiroleal/torchdynamo/torchdynamo/optimizations/backends.py", line 48, in inner
    return fn(model, **kwargs)
  File "/usr/local/google/home/ramiroleal/torchdynamo/torchdynamo/optimizations/backends.py", line 99, in jit_script
    return torch.jit.script(subgraph.model)
  File "/usr/local/google/home/ramiroleal/torch-mlir/venv-torch-mlir/lib/python3.9/site-packages/torch/jit/_script.py", line 1265, in script
    return torch.jit._recursive.create_script_module(
  File "/usr/local/google/home/ramiroleal/torch-mlir/venv-torch-mlir/lib/python3.9/site-packages/torch/jit/_recursive.py", line 456, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/usr/local/google/home/ramiroleal/torch-mlir/venv-torch-mlir/lib/python3.9/site-packages/torch/jit/_recursive.py", line 522, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/usr/local/google/home/ramiroleal/torch-mlir/venv-torch-mlir/lib/python3.9/site-packages/torch/jit/_recursive.py", line 373, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
Python builtin <built-in function _set_grad_enabled> is currently not supported in Torchscript:
  File "<eval_with_key>.1", line 5
def forward(self):
    _set_grad_enabled = torch._C._set_grad_enabled(False)
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _set_grad_enabled_1 = torch._C._set_grad_enabled(True)
    return ()

----------------------------------------
TORCHDYNAMO: backend compiler failed
```

Is this expected behavior, or are the subgraphs passed to the backends meant to be always scriptable using Torchscript?

To recreate:

1. Add a backend to [backends.py](https://github.com/pytorch/torchdynamo/blob/main/torchdynamo/optimizations/backends.py)

```python
@create_backend
def jit_script(subgraph):
    return torch.jit.script(subgraph.model)
```

2. In torchbench, run `python run.py hf_T5 -d cpu -t eval -m eager --torchdynamo jit_script`

**Comment by jansel** [comment]
This is what TorchDynamo converts `with torch.no_grad(): ...` to.  

As a workaround you could use `torch.jit.trace()` instead of `torch.jit.script()`

@eellison do you know if this is something easy to get working with `jit.script`, perhaps by changing the function TorchDynamo calls, or is this something TorchScript can't support?

**Comment by Chillee** [comment]
I guess another option is to trace through it first with AOTAutograd/"python-key tracing" before passing it to `jit.script`.

**Comment by jansel** [comment]
Links to:
- [AOT Autograd](https://github.com/pytorch/torchdynamo/blob/4cdfae7e7943eb128b0b867d6170685dc34cafd9/torchdynamo/optimizations/backends.py#L517) (training)
- [python key tracing](https://github.com/pytorch/torchdynamo/blob/4cdfae7e7943eb128b0b867d6170685dc34cafd9/torchdynamo/optimizations/python_key.py#L137) (inference)

Since they aren't well document yet.  Both of these will lower from the graph captured by dynamo to a simpler graph consisting of torch.ops.aten.* calls.

**Comment by eellison** [comment]
It would be supportable but it general functions like these I think it would be easier to always run them in pure python since I don't think any backend will be optimizing them.

**Comment by ramiro050** [comment]
Thanks for the prompt response! I tried switching to `torch.jit.trace()` or `python_key`, but I now get a different error:

```
Running eval method from hf_T5 on cpu in eager mode.
terminate called after throwing an instance of 'c10::Error'
  what():  Tensors of type TensorImpl do not have sizes
Exception raised from sizes_custom at ../c10/core/TensorImpl.cpp:372 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x7f8d4d2f1bbe in /usr/local/google/home/ramiroleal/torch-mlir/venv-torch-mlir/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5c (0x7f8d4d2cce38 in /usr/local/google/home/ramiroleal/torch-mlir/venv-torch-mlir/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: c10::TensorImpl::sizes_custom() const + 0x75 (0x7f8d4d2daa75 in /usr/local/google/home/ramiroleal/torch-mlir/venv-torch-mlir/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x6ae6 (0x7f8d3bb4eae6 in /usr/local/google/home/ramiroleal/torchdynamo/torchdynamo/_guards.cpython-39-x86_64-linux-gnu.so)
frame #4: python() [0x522057]
<omitting python frames>
frame #9: python() [0x515111]
frame #11: python() [0x53985f]
frame #14: python() [0x515111]
frame #17: python() [0x515111]
frame #20: python() [0x515111]
frame #23: python() [0x515111]
frame #25: <unknown function> + 0x1dd4 (0x7f8d4b8b3dd4 in /usr/local/google/home/ramiroleal/torchdynamo/torchdynamo/_eval_frame.cpython-39-x86_64-linux-gnu.so)
frame #26: python() [0x515111]
frame #30: python() [0x53d70c]
frame #32: python() [0x515111]
frame #35: python() [0x515111]
frame #38: python() [0x6306a7]
frame #39: python() [0x62d510]
frame #40: python() [0x6302c9]
frame #44: __libc_start_main + 0xcd (0x7f8da69287fd in /lib/x86_64-linux-gnu/libc.so.6)

fish: Job 2, 'python run.py hf_T5 -d cpu -t e…' terminated by signal SIGABRT (Abort)
```

Not sure what is causing it. I also noticed that running the model with the `eager` backend also results in the same error: `python run.py hf_T5 -d cpu -t eval -m eager --torchdynamo eager`

**Comment by Chillee** [comment]
@ramiro050 Looks like a mismatch with PyTorch version - see https://github.com/pytorch/torchdynamo/issues/211#issuecomment-1127631604

**Comment by ramiro050** [comment]
> @ramiro050 Looks like a mismatch with PyTorch version - see [#211 (comment)](https://github.com/pytorch/torchdynamo/issues/211#issuecomment-1127631604)

That was it! I had to force a clean build by deleting the `build` folder. Running `python setup.py clean` does not work. I'll go ahead and close this since the solutions mentioned are working for me. Thanks!

**Comment by anijain2305** [comment]
@ramiro050 I typically do `make clean` instead of `python setup.py clean` whenever I want a fresh build. `make clean` removes build and some other stuff as well.
