### ISSUE TITLE
AOTAutograd + TorchDynamo can lead to graphs where leaf variable requires grad and has inplace operation

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#288]
Repro

~~~
import functorch
import torch
import torchdynamo
from functorch.compile import aot_function, nop
from torchdynamo.optimizations.training import aot_autograd_speedup_strategy


def fn(x, y):
    x *= y
    return torch.sin(x)


def outer_fn(x, y):
    z = torch.sin(x)
    print("Hello world")  # --> Graph break to call AOT on the the fn itself
    return fn(z, y)


x = torch.randn(4, requires_grad=True)
y = torch.randn(4, requires_grad=True)

ref = outer_fn(x, y)

with torchdynamo.optimize(aot_autograd_speedup_strategy):
    outer_fn(x, y)

# def outer_fn_aot(x, y):
#     z = torch.sin(x)
#     return aot_function(fn, nop)(z, y)

# ref = outer_fn_aot(x, y)

~~~

Error signature
~~~
Traceback (most recent call last):
  File "/scratch/anijain/pytorch/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/scratch/anijain/pytorch/torch/fx/_symbolic_trace.py", line 577, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/scratch/anijain/functorch/functorch/_src/python_key.py", line 129, in call_module
    return forward(*args, **kwargs)
  File "/scratch/anijain/pytorch/torch/fx/_symbolic_trace.py", line 573, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/scratch/anijain/pytorch/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.3", line 5, in forward
    z *= y;  imul = z;  z = y = None
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

Call using an FX-traced Module, line 5 of the traced Module's generated forward function:
def forward(self, y : torch.Tensor, z : torch.Tensor):
    z *= y;  imul = z;  z = y = None

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    sin = torch.sin(imul);  imul = None

    return (sin,)

Traceback (most recent call last):
  File "/scratch/anijain/functorch/playground/test_inplace.py", line 25, in <module>
    outer_fn(x, y)
  File "/scratch/anijain/functorch/playground/test_inplace.py", line 14, in outer_fn
    def outer_fn(x, y):
  File "/scratch/anijain/functorch/playground/test_inplace.py", line 14, in outer_fn
    def outer_fn(x, y):
  File "/scratch/anijain/torchdynamo/torchdynamo/eval_frame.py", line 80, in _fn
    return fn(*args, **kwargs)
  File "/scratch/anijain/pytorch/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/anijain/functorch/functorch/_src/aot_autograd.py", line 620, in forward
    return compiled_f(
  File "/scratch/anijain/torchdynamo/torchdynamo/eval_frame.py", line 80, in _fn
    return fn(*args, **kwargs)
  File "/scratch/anijain/functorch/functorch/_src/aot_autograd.py", line 165, in forward
    fx_g = make_fx(joint_forward_backward, aot_decompositions)(
  File "/scratch/anijain/functorch/functorch/_src/python_key.py", line 206, in wrapped
    t = pythonkey_trace(wrap_key(f, args), concrete_args=tuple(phs))
  File "/scratch/anijain/functorch/functorch/_src/python_key.py", line 169, in pythonkey_trace
    graph = tracer.trace(root, concrete_args)
  File "/scratch/anijain/pytorch/torch/fx/_symbolic_trace.py", line 587, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "/scratch/anijain/pytorch/torch/fx/_symbolic_trace.py", line 463, in flatten_fn
    tree_out = root_fn(*tree_args)
  File "/scratch/anijain/functorch/functorch/_src/python_key.py", line 188, in wrapped
    out = f(*tree_args)
  File "/scratch/anijain/functorch/functorch/_src/aot_autograd.py", line 61, in joint_forward_backward
    outs = fn(*primals)
  File "/scratch/anijain/functorch/functorch/_src/aot_autograd.py", line 580, in functional_call
    out = mod(*args[params_len:], **kwargs)
  File "/scratch/anijain/pytorch/torch/fx/graph_module.py", line 652, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/scratch/anijain/pytorch/torch/fx/graph_module.py", line 275, in __call__
    raise e.with_traceback(None)
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
~~~

The eager `outer_fn` passes because the in-place operation is not at the leaf variable. However, AOTAutograd is specifically called on `fn` because of the graph break, and it errors out with the above error.

cc @Chillee

**Comment by ezyang** [comment]
This test passes on master now

```
$ python arf.py
Hello world
Hello world
```
