### ISSUE TITLE
Dynamo segfault

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#341]
Steps to repro:

Patch skipfiles.py with

```
FILENAME_ALLOWLIST = {
    torch.nn.Sequential.__init__.__code__.co_filename,
    torch._refs.__file__,
    torch._refs.special.__file__,
    torch._refs.nn.functional.__file__,
    torch._prims.__file__,
}
```

apply

```
diff --git a/test/test_decomp.py b/test/test_decomp.py
index d33882cf06..ff10affc79 100644
--- a/test/test_decomp.py
+++ b/test/test_decomp.py
@@ -405,7 +405,13 @@ class TestDecomp(TestCase):
                 do_relative_check = test_dtype in [torch.float16, torch.bfloat16]
                 real_out_unflat = func(*args, **kwargs)
                 real_out, _ = tree_flatten(real_out_unflat)
-                decomp_out, _ = tree_flatten(decomposition(*args, **kwargs))
+
+                import torchdynamo
+                import torchdynamo.config
+                torchdynamo.config.debug = True
+                #with torchdynamo.optimize("eager", nopython=True):
+                with torchdynamo.optimize("eager", nopython=False):
+                    decomp_out, _ = tree_flatten(decomposition(*args, **kwargs))
                 assert len(real_out) == len(decomp_out)
 
                 if do_relative_check:
```

run `python test/test_decomp.py -k test_quick_frac_cpu_bfloat16 -v`

This segfaults with this trace

```
  #0  0x00007fffbb0e1680 in void c10::function_ref<void (char**, long const*, long, long)>::callback_fn<at::native::AVX2::VectorizedLoop2d<at::native::(anonymous namespace)::direct_copy_kernel(at::TensorIteratorBase&)::{lambda()#3}::operator()() const::{lambda()#8}::operator()() const::{lambda(float)#1}, at::native::(anonymous namespace)::direct_copy_kernel(at::TensorIteratorBase&)::{lambda()#3}::operator()() const::{lambda()#3}::operator()() const::{lambda(at::vec::AVX2::Vectorized<float>)#2}> >(long, char**, long const*, long, long) ()
   from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_cpu.so
#1  0x00007fffb760cf81 in at::TensorIteratorBase::serial_for_each(c10::function_ref<void (char**, long const*, long, long)>, at::Range) const () from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_cpu.so
#2  0x00007fffb760d537 in at::TensorIteratorBase::for_each(c10::function_ref<void (char**, long const*, long, long)>, long) () from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_cpu.so
#3  0x00007fffbb10cff8 in at::native::(anonymous namespace)::copy_same_dtype(at::TensorIteratorBase&, bool, bool) ()
   from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_cpu.so
#4  0x00007fffbb10d6ff in at::native::(anonymous namespace)::copy_kernel(at::TensorIterator&, bool) ()
   from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_cpu.so
#5  0x00007fffb7856780 in at::native::copy_impl(at::Tensor&, at::Tensor const&, bool) ()
   from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_cpu.so
#6  0x00007fffb7857a7a in at::native::copy_(at::Tensor&, at::Tensor const&, bool) ()
   from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_cpu.so
#7  0x00007fffb82c6800 in at::_ops::copy_::call(at::Tensor&, at::Tensor const&, bool) ()
   from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_cpu.so
#8  0x00007fffb7b3cd50 in at::native::clone(at::Tensor const&, c10::optional<c10::MemoryFormat>) ()
   from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_cpu.so
#9  0x00007fffb85f3428 in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, c10::optional<c10::MemoryFormat>), &at::(anonymous namespace)::(anonymous namespace)::wrapper__clone>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, c10::optional<c10::MemoryFormat> > >, at::Tensor (at::Tensor const&, c10::optional<c10::MemoryFormat>)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, c10::optional<c10::MemoryFormat>) ()
   from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_cpu.so
#10 0x00007fffb8077d5c in at::_ops::clone::call(at::Tensor const&, c10::optional<c10::MemoryFormat>) ()
   from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_cpu.so
#11 0x00007fffc0bfc467 in torch::autograd::THPVariable_clone(_object*, _object*, _object*) ()
   from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_python.so
#12 0x00005555556f8a07 in method_vectorcall_VARARGS_KEYWORDS (func=<optimized out>, args=<optimized out>, 
    nargsf=<optimized out>, kwnames=<optimized out>)
    at /tmp/build/80754af9/python_1593706424329/work/Objects/descrobject.c:332
#13 0x000055555565356d in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7ffed37db520, 
    callable=0x7ffff745d950) at /tmp/build/80754af9/python_1593706424329/work/Include/cpython/abstract.h:127
#14 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x5555558e92c0)
    at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4963
```

Removing `torch._prims.__file__` from the allow list makes it stop segfaulting.

**Comment by ezyang** [comment]
A fuller PR to repro with is at https://github.com/pytorch/pytorch/pull/79107
