### ISSUE TITLE
Reasonable graph breaks turn into torchdynamo.exc.InternalTorchDynamoError with nopython=True

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#349]
Repro:

```
    def test_isinstance_dtype(self):
        @torchdynamo.optimize("eager", nopython=True)
        def fn(x):
            isinstance(torch.bfloat16, torch.dtype)
            return x

        fn(torch.randn(3))
```

results in

```
Traceback (most recent call last):
  File "/raid/ezyang/torchdynamo/torchdynamo/convert_frame.py", line 278, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/raid/ezyang/torchdynamo/torchdynamo/bytecode_transformation.py", line 338, in transform_code_object
    transformations(instructions, code_options)
  File "/raid/ezyang/torchdynamo/torchdynamo/convert_frame.py", line 254, in transform
    tracer.run()
  File "/raid/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 306, in run
    and self.step()
  File "/raid/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 284, in step
    getattr(self, inst.opname)(inst)
  File "/raid/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 145, in wrapper
    return inner_fn(self, inst)
  File "/raid/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 619, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/raid/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 220, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/raid/ezyang/torchdynamo/torchdynamo/variables/builtin.py", line 220, in call_function
    result = handler(tx, *args, **kwargs)
  File "/raid/ezyang/torchdynamo/torchdynamo/variables/builtin.py", line 354, in call_isinstance
    arg_type = arg.python_type()
  File "/raid/ezyang/torchdynamo/torchdynamo/variables/torch.py", line 67, in python_type
    return super().python_type()
  File "/raid/ezyang/torchdynamo/torchdynamo/variables/base.py", line 137, in python_type
    raise NotImplementedError(f"{self} has no type")
NotImplementedError: TorchVariable() has no type
        
During handling of the above exception, another exception occurred:
            
Traceback (most recent call last):
  File "/raid/ezyang/torchdynamo/torchdynamo/eval_frame.py", line 133, in catch_errors
    return callback(frame, cache_size)
  File "/raid/ezyang/torchdynamo/torchdynamo/convert_frame.py", line 116, in _fn
    return fn(*args, **kwargs)
  File "/raid/ezyang/torchdynamo/torchdynamo/convert_frame.py", line 311, in _convert_frame_assert
    raise InternalTorchDynamoError()
torchdynamo.exc.InternalTorchDynamoError
```

`_convert_frame_assert` probably needs to transform these errors into something else in nopython situation

**Comment by ezyang** [comment]
oh maybe we just need

```
diff --git a/torchdynamo/convert_frame.py b/torchdynamo/convert_frame.py
index 1fe572c..a15dc09 100644
--- a/torchdynamo/convert_frame.py
+++ b/torchdynamo/convert_frame.py
@@ -296,7 +296,7 @@ def convert_frame_assert(compiler_fn: Callable, one_graph=True):
             assert output.guards is not None
             CleanupManager.instance[code] = output.cleanups
             return GuardedCode(code, output.guards, frame.f_locals, frame.f_globals)
-        except (Unsupported, TorchRuntimeError):
+        except (Unsupported, TorchRuntimeError, NotImplementedError):
             debug_print("WONT CONVERT")
             raise
         except Exception:
```

**Comment by ezyang** [comment]
Or maybe we should just not be raising NotImplementedError lol

**Comment by jansel** [comment]
Yeah, could just call unimplemented("") in this case.

**Comment by yanboliang** [comment]
I think this had been fixed by https://github.com/pytorch/torchdynamo/issues/354
