### ISSUE TITLE
[inductor] pytorch_struct training failure

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#530]
Can be reproduced with `./benchmarks/torchbench.py -d cuda --inductor --training --float16 -k pytorch_struct` on the torchdynamo tip.

```
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo/torchinductor/graph.py", line 194, in call_function
    return lowerings[target](*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo/torchinductor/lowering.py", line 120, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo/torchinductor/lowering.py", line 554, in bmm
    return TensorBox.create(ir.BatchMatrixMultiply.create(a, b))
  File "/fsx/users/binbao/torchdynamo/torchinductor/ir.py", line 1898, in create
    data = MatrixMultiply(
  File "/fsx/users/binbao/torchdynamo/torchinductor/ir.py", line 1839, in __init__
    super().__init__(layout, inputs, constant_args, output_view)
  File "/fsx/users/binbao/torchdynamo/torchinductor/ir.py", line 1752, in __init__
    super().__init__(None, layout, self.unwrap_storage(inputs), constant_args)
  File "/fsx/users/binbao/torchdynamo/torchinductor/ir.py", line 1570, in unwrap_storage
    assert isinstance(x, (Buffer, ReinterpretView)), x
AssertionError: View(
  ReinterpretView(
    StorageBox(
      InputBuffer(name='view_default_4', layout=FixedLayout('cuda', torch.float16, size=[1, 30, 256], stride=[7680, 256, 1]))
    ),
    FixedLayout('cuda', torch.float16, size=[1, 256, 30], stride=[7680, 1, 256])
  ),
  size=(256, 30),
  reindex=lambda i0, i1: [0, i0, i1]
)
```

**Comment by desertfire** [comment]
https://github.com/pytorch/torchdynamo/pull/532 solves the assertion.

The new error is,
```
torchinductor.exc.MissingOperator: missing lowering/decomposition
  target: aten.scatter_add.default
```

We need to add the support for `scatter_add`.

**Comment by jansel** [comment]
I suspect `scatter_add` will look similar to `index_put_(..., accumulate=True)`, which we already support.  Perhaps we can decompose it to that?

**Comment by desertfire** [comment]
> I suspect `scatter_add` will look similar to `index_put_(..., accumulate=True)`, which we already support. Perhaps we can decompose it to that?

I was working on that direction, but after a few local tries, I think the semantics difference between the two makes it awkward to write `scatter_add` as a simple decomposition. I will try to add its support in lowering, by borrowing some logic from `index_put_`.

**Comment by desertfire** [comment]
Another problem after fixing `scatter_add`,

```
  File "/fsx/users/binbao/torchdynamo/torchinductor/graph.py", line 264, in compile_to_fn
    code = self.codegen()
  File "/fsx/users/binbao/torchdynamo/torchinductor/graph.py", line 257, in codegen
    self.scheduler = Scheduler(self.buffers)
  File "/fsx/users/binbao/torchdynamo/torchinductor/scheduler.py", line 412, in __init__
    self.nodes.append(SchedulerNode(self, node, group_fn))
  File "/fsx/users/binbao/torchdynamo/torchinductor/scheduler.py", line 206, in __init__
    super().__init__(scheduler, node)
  File "/fsx/users/binbao/torchdynamo/torchinductor/scheduler.py", line 60, in __init__
    self.set_read_writes(node.get_read_writes())
  File "/fsx/users/binbao/torchdynamo/torchinductor/ir.py", line 1304, in get_read_writes
    self.get_store_function(),
  File "/fsx/users/binbao/torchdynamo/torchinductor/ir.py", line 1309, in get_store_function
    indexer = self.layout.as_fixed().make_indexer()
  File "/fsx/users/binbao/torchdynamo/torchinductor/ir.py", line 1179, in make_indexer
    return self.target.make_indexer()
  File "/fsx/users/binbao/torchdynamo/torchinductor/ir.py", line 2379, in __getattr__
    fn = getattr(self.data, name)
  File "/fsx/users/binbao/torchdynamo/torchinductor/ir.py", line 2379, in __getattr__
    fn = getattr(self.data, name)
AttributeError: 'Pointwise' object has no attribute 'make_indexer'
```

**Comment by desertfire** [comment]
> RuntimeError: Internal Triton PTX codegen error: 

This one is a bit hard to debug. Running the generated Triton code individually does not trigger the error. The stackdump seems to suggest this `kernel9` is problematic, but I don't see anything obviously wrong.

```
@pointwise_heuristics(size_hints=[65536])
@triton.jit
def kernel9(in_ptr0, in_ptr1, out_ptr0, xnumel: tl.constexpr, XBLOCK : tl.constexpr):
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK])
    xmask = xindex < xnumel
    x0_next = xindex // 30
    x1 = x0_next % 29
    x1_next = x0_next // 29
    x2 = x1_next
    x0 = xindex % 30
    x4 = xindex
    tmp0 = tl.load(in_ptr0 + x0 + (30*x2) + (1200*x1), xmask)
    tmp1 = tl.load(in_ptr1 + x0 + (30*x2) + (1200*x1), xmask).to(tl.float32)
    tl.atomic_add(out_ptr0 + tmp0 + (4771*x4) + tl.zeros([XBLOCK], tl.int32), tmp1, xmask)
```

Also I found the error does not exist if we use --float32.

**Comment by jansel** [comment]
Are you using the latest triton?

**Comment by desertfire** [comment]
> Are you using the latest triton?

I am using the latest nightly of triton.

**Comment by jansel** [comment]
This seems to be working now.

**Comment by desertfire** [comment]
I got accuracy error, both on the tip and on Jason's branch,

```
$ ./benchmarks/torchbench.py -d cuda   --float16 --training  --inductor  -k  pytorch_struct
cuda train pytorch_struct                     Similarity score=0.8526728749275208
Accuracy failed for key name term_emb.grad
INCORRECT
1.416x p=0.00
speedup gmean=1.42x mean=1.42x
```

@Chillee @ngimel , can you help to verify this?

**Comment by jansel** [comment]
I described how to debug this here: https://github.com/pytorch/torchdynamo/issues/511#issuecomment-1187670163

**Comment by ngimel** [comment]
Yes, for training blindly using fp16 won't provide good results, and that's especially true for hpc models that typically don't use fp16. AMP should have better precision.
