### ISSUE TITLE
`UnboundLocalError: ___random_values_0' from hf_Bart

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#545]
Repro:
```
./benchmarks/torchbench.py -dcuda -k hf_Bart
```

Output:
```
cuda eval  hf_Bart                            ERROR:root:unhandled error
Traceback (most recent call last):
  File "/home/jansel/torchdynamo/benchmarks/common.py", line 690, in run_one_model
    new_result = model_iter_fn(model, example_inputs)
  File "./benchmarks/torchbench.py", line 306, in forward_pass
    def forward_pass(self, mod, inputs, collect_outputs=True):
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/torchbenchmark/torchbenchmark/util/framework/huggingface/model_factory.py", line 34, in forward
    def forward(self, input_ids, decoder_input_ids):
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/bart/modeling_bart.py", line 1308, in forward
    outputs = self.model(
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/bart/modeling_bart.py", line 1181, in forward
    encoder_outputs = self.encoder(
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/bart/modeling_bart.py", line 706, in forward
    def forward(
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/bart/modeling_bart.py", line 706, in forward
    def forward(
UnboundLocalError: local variable '___random_values_0' referenced before assignment
```

**Comment by jansel** [comment]
@yanboliang this may be caused by #392

**Comment by yanboliang** [comment]
Thanks for catching this, I'll assign this to me and dig into this.
