### ISSUE TITLE
SystemError: error return without exception set

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#565]
I wanted to make it easier to unconditionally turn on torchdynamo when testing random scripts, so I added this to my `torch/__init__.py`

```
    import torchdynamo
    torchdynamo.config.cache_size_limit = 1
    _DYNAMO_CTX = torchdynamo.optimize("eager")
    _DYNAMO_CTX.__enter__()
```

When I run `test/test_torch.py` with this, I get some odd errors at initialization:

```
Exception ignored in: <generator object <genexpr> at 0x7f8ce3d2f4a0>                                 
Traceback (most recent call last):                                                                                             
  File "/scratch/ezyang/pytorch-scratch2-env/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing/results.py", line 8, i
n <genexpr>                                                                                                                    
    _generator_type = type((_ for _ in ()))                                                                                    
SystemError: error return without exception set                                                                                
Exception ignored in: <generator object <genexpr> at 0x7f8ce374e510>                                                
Traceback (most recent call last):                                                                                             
  File "/scratch/ezyang/pytorch-scratch2-env/lib/python3.8/site-packages/setuptools/_vendor/pyparsing/results.py", line 8, in <
genexpr>                                                                                                                       
    _generator_type = type((_ for _ in ()))    
```

The script seems to continue to run, so this doesn't seem too damaging, but it would be nice to work out what is causing this problem.

**Comment by jansel** [comment]
That's a weird one.  Should be possible to support, just add some tests of taking types of generators/list comprehensions.
