### ISSUE TITLE
FakeTensor issue causing failure on GNNs

### ISSUE THREAD

**Issue by puririshi98** [pytorch/torchdynamo#572]
Torch dynamo fails on the propagate step of GNNs. All GNNs inherit MessagePassing. The [propagate](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/conv/message_passing.py#L280-L401) function calls the message and aggregate functions which can be overridden for each type of gnn. In this case torch dynamo fails at the [step of aggregation](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/conv/message_passing.py#L380). Aggregate is defined [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/conv/message_passing.py#L490-L503) and initialized [here](https://github.com/pyg-team/pytorch_geometric/blob/da7be5d7c617c45c93cf76243009da786c0ae873/torch_geometric/nn/conv/message_passing.py#L120-L133). This calls [reduce](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/aggr/base.py#L95-L104) which is a sparse reduction function (from [torch_scatter](https://pytorch-scatter.readthedocs.io/en/latest/functions/scatter.html) which has third party integration into torch).

repro
`pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric; git clone -b patch-1 https://github.com/puririshi98/simple_dl_models.git; cd simple_dl_models/; python3 gnn_homogenous_conv.py; python3 gnn_homogenous_conv.py --torchdynamo `

Failure occurs on `python3 gnn_homogenous_conv.py --torchdynamo`

For background, this doc describes the general structure of a gnn conv:
https://pytorch-geometric.readthedocs.io/en/latest/notes/create_gnn.html

**Comment by jansel** [comment]
Thanks for the report!

What is the error message?  Would it be possible to get a smaller repro?

**Comment by puririshi98** [comment]
This is the error:
`root@nvdl-a112-asus02:/workspace/simple_dl_models# python3 gnn_homogenous_conv.py --torchdynamo
Data(y=[15409], edge_index=[2, 307956], x=[15409, 64])
----------------------------------------
TORCHDYNAMO: backend compiler failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/output_graph.py", line 341, in call_user_compiler
    compiled_fn = self.compiler_fn(gm, self.example_inputs())
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/training.py", line 147, in __call__
    return AOTAutogradMemoryEfficientFusion.compile_fn(gm, example_inputs)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/training.py", line 24, in compile_fn
    return cls(gm, example_inputs).verified_candidate()
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/training.py", line 64, in __init__
    has_mutation(self.gm, self.example_inputs)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/analysis.py", line 128, in has_mutation
    ShapeAliasingAndMutationProp(new_gm).run(*example_inputs)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/analysis.py", line 108, in run
    super().run(*args)
  File "/opt/pytorch/pytorch/torch/fx/interpreter.py", line 127, in run
    self.env[node] = self.run_node(node)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/analysis.py", line 51, in run_node
    result = getattr(self, n.op)(n.target, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/interpreter.py", line 248, in call_method
    return getattr(self_obj, target)(*args_tail, **kwargs)
  File "/opt/pytorch/pytorch/torch/_subclasses/fake_tensor.py", line 346, in __torch_dispatch__
    return func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 49, in __call__
    return self._op(*args, **kwargs or {})
  File "/opt/pytorch/pytorch/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_subclasses/fake_tensor.py", line 482, in __torch_dispatch__
    raise Exception(
Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.scatter_add_.default
----------------------------------------
ERROR:root:Error while processing frame
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/output_graph.py", line 341, in call_user_compiler
    compiled_fn = self.compiler_fn(gm, self.example_inputs())
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/training.py", line 147, in __call__
    return AOTAutogradMemoryEfficientFusion.compile_fn(gm, example_inputs)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/training.py", line 24, in compile_fn
    return cls(gm, example_inputs).verified_candidate()
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/training.py", line 64, in __init__
    has_mutation(self.gm, self.example_inputs)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/analysis.py", line 128, in has_mutation
    ShapeAliasingAndMutationProp(new_gm).run(*example_inputs)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/analysis.py", line 108, in run
    super().run(*args)
  File "/opt/pytorch/pytorch/torch/fx/interpreter.py", line 127, in run
    self.env[node] = self.run_node(node)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/analysis.py", line 51, in run_node
    result = getattr(self, n.op)(n.target, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/interpreter.py", line 248, in call_method
    return getattr(self_obj, target)(*args_tail, **kwargs)
  File "/opt/pytorch/pytorch/torch/_subclasses/fake_tensor.py", line 346, in __torch_dispatch__
    return func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 49, in __call__
    return self._op(*args, **kwargs or {})
  File "/opt/pytorch/pytorch/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_subclasses/fake_tensor.py", line 482, in __torch_dispatch__
    raise Exception(
Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.scatter_add_.default

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/eval_frame.py", line 147, in catch_errors
    return callback(frame, cache_size)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/convert_frame.py", line 363, in _convert_frame
    result = inner_convert(frame, cache_size)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/convert_frame.py", line 124, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/convert_frame.py", line 304, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/bytecode_transformation.py", line 338, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/convert_frame.py", line 280, in transform
    tracer.run()
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/symbolic_convert.py", line 310, in run
    and self.step()
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/symbolic_convert.py", line 288, in step
    getattr(self, inst.opname)(inst)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/symbolic_convert.py", line 1325, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/output_graph.py", line 286, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/output_graph.py", line 327, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/output_graph.py", line 350, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torchdynamo.exc.BackendCompilerFailed: ? raised Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.scatter_add_.default

You can suppress this exception and fall back to eager by setting:
    torchdynamo.config.raise_on_backend_error = False
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/output_graph.py", line 341, in call_user_compiler
    compiled_fn = self.compiler_fn(gm, self.example_inputs())
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/training.py", line 147, in __call__
    return AOTAutogradMemoryEfficientFusion.compile_fn(gm, example_inputs)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/training.py", line 24, in compile_fn
    return cls(gm, example_inputs).verified_candidate()
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/training.py", line 64, in __init__
    has_mutation(self.gm, self.example_inputs)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/analysis.py", line 128, in has_mutation
    ShapeAliasingAndMutationProp(new_gm).run(*example_inputs)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/analysis.py", line 108, in run
    super().run(*args)
  File "/opt/pytorch/pytorch/torch/fx/interpreter.py", line 127, in run
    self.env[node] = self.run_node(node)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/optimizations/analysis.py", line 51, in run_node
    result = getattr(self, n.op)(n.target, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/interpreter.py", line 248, in call_method
    return getattr(self_obj, target)(*args_tail, **kwargs)
  File "/opt/pytorch/pytorch/torch/_subclasses/fake_tensor.py", line 346, in __torch_dispatch__
    return func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 49, in __call__
    return self._op(*args, **kwargs or {})
  File "/opt/pytorch/pytorch/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_subclasses/fake_tensor.py", line 482, in __torch_dispatch__
    raise Exception(
Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.scatter_add_.default

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gnn_homogenous_conv.py", line 33, in <module>
    runner.run(sys.argv, 'Homogenous_GNN_Conv', TestModule(), optim_func, input_func, None)
  File "/workspace/simple_dl_models/execution/runner.py", line 79, in run
    result_records.append(execution_loop.execute(args, name, model_name, model, optim_func, input_func, grad_func, eager_record))
  File "/workspace/simple_dl_models/execution/execution_loop.py", line 110, in execute
    loss = forward_pass(model, batch)
  File "/workspace/simple_dl_models/execution/execution_loop.py", line 34, in forward_pass
    return model(batch.x, batch.edge_index, batch.y)
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/eval_frame.py", line 147, in catch_errors
    return callback(frame, cache_size)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/convert_frame.py", line 363, in _convert_frame
    result = inner_convert(frame, cache_size)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/convert_frame.py", line 124, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/convert_frame.py", line 304, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/bytecode_transformation.py", line 338, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/convert_frame.py", line 280, in transform
    tracer.run()
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/symbolic_convert.py", line 310, in run
    and self.step()
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/symbolic_convert.py", line 288, in step
    getattr(self, inst.opname)(inst)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/symbolic_convert.py", line 1325, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/output_graph.py", line 286, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/output_graph.py", line 327, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/opt/conda/lib/python3.8/site-packages/torchdynamo/output_graph.py", line 350, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torchdynamo.exc.BackendCompilerFailed: ? raised Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.scatter_add_.default

You can suppress this exception and fall back to eager by setting:
    torchdynamo.config.raise_on_backend_error = False`

I can work on a simpler isolated repro

**Comment by jansel** [comment]
cc @eellison this error looks FakeTensor related

Can you try with `torchdynamo.config.fake_tensor_propagation=False`
https://github.com/pytorch/torchdynamo/blob/1e4d17e2fc1e61894f5dac08aabdbdc71378bf5f/torchdynamo/config.py#L56

**Comment by puririshi98** [comment]
This zip contains a python file for a much simpler repro w/ `python3 torchdynamo_repro.py`
[torchdynamo_repro.zip](https://github.com/pytorch/torchdynamo/files/9115703/torchdynamo_repro.zip)

**Comment by jansel** [comment]
Thanks for the repro!  @eellison who wrote the FakeTensor stuff is out this week, but should be able to take a look once he is back.

`torchdynamo.config.fake_tensor_propagation` is primarily for memory usage reduction during tracing, so you should be able to safely disable it until this issue is fixed.

**Comment by eellison** [comment]
This no longer repros for me on master.
