### ISSUE TITLE
AOT Autograd failure from pyhpc_isoneutral_mixing

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#590]
`./benchmarks/torchbench.py --inductor --float16 -dcuda --no-skip -k pyhpc_isoneutral_mixing`
```
cuda eval  pyhpc_isoneutral_mixing            ERROR:root:unhandled error
Traceback (most recent call last):
  File "/home/jansel/torchdynamo/benchmarks/common.py", line 687, in run_one_model
    new_result = model_iter_fn(model, example_inputs)
  File "./benchmarks/torchbench.py", line 314, in forward_pass
    def forward_pass(self, mod, inputs, collect_outputs=True):
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 93, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/functorch/functorch/_src/aot_autograd.py", line 646, in forward
    return compiled_f(
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 93, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/functorch/functorch/_src/aot_autograd.py", line 199, in forward
    fw_module, bw_module = partition_fn(fx_g, joint_inputs)
  File "/home/jansel/functorch/functorch/_src/partitioners.py", line 363, in min_cut_rematerialization_partition
    cut_value, partition = nx.minimum_cut(nx_graph, "source", "sink")
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/networkx/algorithms/flow/maxflow.py", line 458, in minimum_cut
    R = flow_func(flowG, _s, _t, capacity=capacity, value_only=True, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/networkx/algorithms/flow/preflowpush.py", line 421, in preflow_push
    R = preflow_push_impl(G, s, t, capacity, residual, global_relabel_freq, value_only)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/networkx/algorithms/flow/preflowpush.py", line 27, in preflow_push_impl
    raise nx.NetworkXError(f"node {str(t)} not in graph")
networkx.exception.NetworkXError: node sink not in graph
```

**Comment by jansel** [comment]
Similar error from `vision_maskrcnn`:

```
$ ./benchmarks/torchbench.py --no-skip -dcuda --inductor --float16 -k vision_maskrcnn
cuda eval  vision_maskrcnn                    ERROR:root:unhandled error
Traceback (most recent call last):
  File "/home/jansel/torchdynamo/benchmarks/common.py", line 702, in run_one_model
    new_result = model_iter_fn(model, example_inputs)
  File "./benchmarks/torchbench.py", line 343, in forward_pass
    def forward_pass(self, mod, inputs, collect_outputs=True):
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/torchvision/torchvision/models/detection/generalized_rcnn.py", line 46, in forward
    def forward(self, images, targets=None):
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 93, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/functorch/functorch/_src/aot_autograd.py", line 646, in forward
    return compiled_f(
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 93, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/functorch/functorch/_src/aot_autograd.py", line 199, in forward
    fw_module, bw_module = partition_fn(fx_g, joint_inputs)
  File "/home/jansel/functorch/functorch/_src/partitioners.py", line 363, in min_cut_rematerialization_partition
    cut_value, partition = nx.minimum_cut(nx_graph, "source", "sink")
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/networkx/algorithms/flow/maxflow.py", line 458, in minimum_cut
    R = flow_func(flowG, _s, _t, capacity=capacity, value_only=True, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/networkx/algorithms/flow/preflowpush.py", line 421, in preflow_push
    R = preflow_push_impl(G, s, t, capacity, residual, global_relabel_freq, value_only)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/networkx/algorithms/flow/preflowpush.py", line 25, in preflow_push_impl
    raise nx.NetworkXError(f"node {str(s)} not in graph")
networkx.exception.NetworkXError: node source not in graph
```

**Comment by ezyang** [comment]
this is still erroring

**Comment by Chillee** [comment]
This error is usually due to in-place operators.

**Comment by ezyang** [comment]
this no longer fails

```
$ ./benchmarks/torchbench.py --inductor --float16 -dcuda --no-skip -k pyhpc_isoneutral_mixing
cuda eval  pyhpc_isoneutral_mixing            Torchdynamo: [WARNING] skipping cudagraphs due to input mutation
3.234x p=0.00
speedup    gmean=3.23x mean=3.23x
```

vision_maskrcnn currently tracked at https://github.com/pytorch/torchdynamo/issues/739
