### ISSUE TITLE
Fake tensor issues with Torchbench/Huggingface models

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#592]
* [ ] T5ForConditionalGeneration_t5, t5-small

Repro - `python benchmarks/huggingface.py --float32 -dcuda -- --training --nvfuser --accuracy-aot-ts-mincut --use-eval-mode --isolate --only=T5ForConditionalGeneration_t5`

Error signature - 
~~~
    result = getattr(self, n.op)(n.target, args, kwargs)
  File "/scratch/anijain/work/pytorch/torch/fx/interpreter.py", line 226, in call_function
    return target(*args, **kwargs)
  File "/scratch/anijain/work/pytorch/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/scratch/anijain/work/pytorch/torch/_subclasses/fake_tensor.py", line 482, in __torch_dispatch__
    raise Exception(
Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.fill_.Tensor
~~~

* [ ] google-fnet-base

Repro - `python benchmarks/huggingface.py --float32 -dcuda -- --training --nvfuser --accuracy-aot-ts-mincut --use-eval-mode --isolate --only=google-fnet-base`
Signature - 
~~~
Traceback (most recent call last):
  File "/scratch/anijain/work/torchdynamo/torchdynamo/utils.py", line 455, in wrap_fake_exception
    return fn()
  File "/scratch/anijain/work/torchdynamo/torchdynamo/utils.py", line 464, in <lambda>
    return wrap_fake_exception(lambda: fake_mode.from_tensor(e))
  File "/scratch/anijain/work/pytorch/torch/_subclasses/fake_tensor.py", line 511, in from_tensor
    return self.fake_tensor_converter(self, tensor)
  File "/scratch/anijain/work/pytorch/torch/_subclasses/fake_tensor.py", line 153, in __call__
    return self.from_real_tensor(fake_mode, t)
  File "/scratch/anijain/work/pytorch/torch/_subclasses/fake_tensor.py", line 130, in from_real_tensor
    raise UnsupportedFakeTensorException("complex nyi in meta tensors")
torch._subclasses.fake_tensor.UnsupportedFakeTensorException: complex nyi in meta tensors
~~~

* [ ] moco

Repro - `python benchmarks/torchbench.py --float32 -dcuda -- --training --nvfuser --accuracy-aot-ts-mincut --use-eval-mode --isolate --only=moco`
Signature - 
~~~
  File "/scratch/anijain/work/pytorch/torch/fx/interpreter.py", line 226, in call_function
    return target(*args, **kwargs)
  File "/scratch/anijain/work/pytorch/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/scratch/anijain/work/pytorch/torch/_subclasses/fake_tensor.py", line 512, in __torch_dispatch__
    raise Exception(
Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.copy_.default(*(FakeTensor(cuda:0, torch.Size([]), torch.int64), tensor(32)), **{})
~~~

* [ ] speech_transformer

Repro - `python benchmarks/torchbench.py --float32 -dcuda -- --training --nvfuser --accuracy-aot-ts-mincut --use-eval-mode --isolate --only=speech_transformer`
Signature - 
~~~
  File "/scratch/anijain/work/pytorch/torch/fx/interpreter.py", line 127, in run
    self.env[node] = self.run_node(node)
  File "/scratch/anijain/work/torchdynamo/torchdynamo/optimizations/analysis.py", line 50, in run_node
    result = getattr(self, n.op)(n.target, args, kwargs)
  File "/scratch/anijain/work/pytorch/torch/fx/interpreter.py", line 226, in call_function
    return target(*args, **kwargs)
  File "/scratch/anijain/work/pytorch/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/scratch/anijain/work/pytorch/torch/_subclasses/fake_tensor.py", line 512, in __torch_dispatch__
    raise Exception(
Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.fill_.Tensor(*(FakeTensor(cuda:0, torch.Size([204]), torch.float32), tensor(0.)), **{})
~~~

cc @eellison @ezyang

**Comment by jansel** [comment]
@842974287 was seeing a similar issue inside Meta, P516945018
```
RuntimeError: The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.
```

**Comment by eellison** [comment]
CC @Chillee the Moco repro here fails because the input to `c10::broadcast_` is a list so the [https://github.com/pytorch/pytorch/blob/master/torch/fx/experimental/proxy_tensor.py#L168](following) errors with `"'list' object has no attribute 'proxy'"` (I think this is being tracked somewhere but I couldn't find it). 

The `T5ForConditionalGeneration_t5` doesn't error with FakeTensor, but there are AssertionErrors printed see: https://github.com/pytorch/torchdynamo/issues/592

No more FakeTensor errors though so closing.
