### ISSUE TITLE
Incorrect output if cudagraphs=True

### ISSUE THREAD

**Issue by pyjhzwh** [pytorch/torchdynamo#601]
Setting `torchinductor.config.triton.cudagraphs = True` will cause that only partial output values are copied( the remaining values are just 0s).
repro is: #600

**Comment by ngimel** [comment]
Another error with cuda graphs:
```
import torch
import torchdynamo
import torchinductor
from torchinductor import config

torchinductor.config.debug = True
#torchinductor.config.triton.cudagraphs=False - #uncomment to make example run

@torchdynamo.optimize("inductor")
def mean(x0):
    return torch.mean(x0)


device='cuda'
dtype=torch.half

x0 = torch.randn(2**24, device=device, dtype=dtype)
# print(mean(x0), torch.mean(x0))
x0 = x0[::2]
print(mean(x0), torch.mean(x0))

```
with graphs enabled (default) errors out with 
```
TORCHDYNAMO: backend compiler failed
Traceback (most recent call last):
  File "/scratch/ngimel/work/repos/torchdynamo/torchinductor/compile_fx.py", line 193, in cudagraphify
    static_outputs = model(*static_inputs)
  File "/scratch/ngimel/work/repos/torchdynamo/torchdynamo/optimizations/python_key.py", line 168, in call_fn
    return inner(*params_flat, *args)
  File "/tmp/torchinductor_ngimel/mv/cmvs7vfbkxpoj3whnohuc32tsi2clnv3wwdbh7nr3zqetjuf72pu.py", line 66, in call
    kernel0[grid(128)](arg0, buf0, s1, 128, 65536)
  File "/scratch/ngimel/work/repos/triton/python/triton/code_gen.py", line 999, in __call__
    return self.kernel(*wargs, **kwargs, grid=self.grid)
  File "/scratch/ngimel/work/repos/triton/python/triton/code_gen.py", line 1086, in __call__
    return self.kernel(*args, num_warps=config.num_warps, num_stages=config.num_stages, **kwargs, **config.kwargs)
  File "/scratch/ngimel/work/repos/triton/python/triton/code_gen.py", line 988, in __call__
    return _triton.runtime.launch(wargs, self.fn.do_not_specialize, cache_key, self.fn.arg_names,
  File "/scratch/ngimel/work/repos/triton/python/triton/code_gen.py", line 956, in add_to_cache
    return self.fn._warmup(key, arg_types=arg_types, device=device_idx, attributes=attributes, constants=constants, num_warps=num_warps, num_stages=num_stages,
  File "/scratch/ngimel/work/repos/triton/python/triton/code_gen.py", line 1294, in _warmup
    self.bin_cache[key] = LoadedBinary(device, binary)
  File "/scratch/ngimel/work/repos/triton/python/triton/code_gen.py", line 772, in __init__
    module, kernel, n_regs, n_spills = _triton.code_gen.load_binary(bin.backend,
RuntimeError: unimplemented code: 900
```
with uncommented line disabling cuda graphs it passes.

**Comment by ezyang** [comment]
related (but since these are errors in triton I don't think it helps) https://github.com/pytorch/pytorch/pull/80566

**Comment by ezyang** [comment]
related (but since these are errors in triton I don't think it helps) https://github.com/pytorch/pytorch/pull/80566

**Comment by ngimel** [comment]
@pyjhzwh can you try running with `CUDA_DISABLE_KERNEL_MEMCPY=1`?

**Comment by pyjhzwh** [comment]
> @pyjhzwh can you try running with `CUDA_DISABLE_KERNEL_MEMCPY=1`?

It seems `CUDA_DISABLE_KERNEL_MEMCPY=1` would not solve the problem
