### ISSUE TITLE
size_hint assertion: "hf_Reformer"

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#633]
Repro:
```
./torchbench.py -dcuda --inductor --float16 --no-skip -k hf_Reformer
```

**Comment by desertfire** [comment]
The latest error,
```
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/graph.py", line 221, in call_function
    return lowerings[target](*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/lowering.py", line 139, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/lowering.py", line 1347, in index
    output_size[j] = V.graph.sizevars.guard_equals(
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/sizevars.py", line 127, in guard_equals
    assert self.size_hint(expr) == 0, (expr, self.size_hint(expr))
AssertionError: (-4999, -4999)

torchinductor.exc.LoweringException: AssertionError: (-4999, -4999)
  target: aten.index.Tensor
  args[0]: TensorBox(
    ReinterpretView(
      StorageBox(
        InputBuffer(name='primals_2', layout=FixedLayout('cuda', torch.float32, size=[1438452, 1], stride=[1, 1]))
      ),
      FixedLayout('cuda', torch.float32, size=[4, 359613], stride=[359613, 1])
    )
  )
  args[1]: [TensorBox(
    View(
      StorageBox(
        Pointwise(
          'cuda',
          torch.float32,
          index_expr(i0, torch.float32),
          ranges=[4]
        )
      ),
      size=(4, 1),
      reindex=lambda i0, i1: [i0]
    )
  ), TensorBox(StorageBox(
    ConcatKernel(name='buf31', layout=FixedLayout('cuda', torch.int64, size=[4, 5000], stride=[5000, 1]), inputs=[ComputedBuffer(name='buf26', layout=AliasedLayout('cuda', torch.int64, size=[4, 1000], stride=[5000, 1]), data=Pointwise(
      'cuda',
      torch.int64,
      load(buf9, 1000*i0 + i1, False) + constant(0, torch.int64),
      ranges=[4, 1000]
    )), ComputedBuffer(name='buf27', layout=AliasedLayout('cuda', torch.int64, size=[4, 1000], stride=[5000, 1]), data=Pointwise(
      'cuda',
      torch.int64,
      load(buf13, 1000*i0 + i1, False) + constant(269952, torch.int64),
      ranges=[4, 1000]
    )), ComputedBuffer(name='buf28', layout=AliasedLayout('cuda', torch.int64, size=[4, 1000], stride=[5000, 1]), data=Pointwise(
      'cuda',
      torch.int64,
      load(buf17, 1000*i0 + i1, False) + constant(337440, torch.int64),
      ranges=[4, 1000]
    )), ComputedBuffer(name='buf29', layout=AliasedLayout('cuda', torch.int64, size=[4, 1000], stride=[5000, 1]), data=Pointwise(
      'cuda',
      torch.int64,
      load(buf21, 1000*i0 + i1, False) + constant(354312, torch.int64),
      ranges=[4, 1000]
    )), ComputedBuffer(name='buf30', layout=AliasedLayout('cuda', torch.int64, size=[4, 1000], stride=[5000, 1]), data=Pointwise(
      'cuda',
      torch.int64,
      load(buf25, 1000*i0 + i1, False) + constant(358530, torch.int64),
      ranges=[4, 1000]
    ))])
  ))]
```

**Comment by Chillee** [comment]
Do you have a command to repro this error?

**Comment by Chillee** [comment]
I'm not totally sure I see the same error (I see an error related to scatter), but here's a minified version

```
import torch
inps = [(torch.Size([1, 12, 4096]), torch.int64), (torch.Size([1, 12, 4096]), torch.int64), (torch.Size([1, 12, 4096]), torch.int64)]
inps = [torch.zeros(())] + [torch.ones(shape, dtype=dtype, device='cuda') for (shape, dtype) in inps]



def forward(self, getitem_5, expand_default_23, clone_default_6):
    scatter__src_1 = torch.ops.aten.scatter_.src(clone_default_6, -1, getitem_5, expand_default_23);  clone_default_6 = getitem_5 = expand_default_23 = None
    return (scatter__src_1,)

from functorch import make_fx
mod = make_fx(forward)(*inps)

from torchinductor.compile_fx import compile_fx_inner
compile_fx_inner(mod, inps)
```

**Comment by desertfire** [comment]
Latest error msg:
```
  File "torchinductor/scheduler.py", line 411, in __init__
    assert self.group == node.group
AssertionError
```

**Comment by Chillee** [comment]
@desertfire I'll look at it.

**Comment by desertfire** [comment]
> @desertfire I'll look at it.

Cool! I tried minifier, but the generated code wasn't really "mini".

**Comment by Chillee** [comment]
@desertfire :O How many nodes did the result have?
