### ISSUE TITLE
TorchBench Inference Accuracy Error: "hf_Longformer"

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#634]
Repro:
```
benchmarks/torchbench.py -d cuda --float32 --inductor --no-skip -k hf_Longformer
```

**Comment by desertfire** [comment]
Repro: `python benchmarks/torchbench.py -d cuda --float16 --inductor --no-skip -k hf_Longformer`

Accuracy error:
```
Similarity score=0.9814952611923218
Accuracy failed for key name logits
INCORRECT
ERROR
```

Hits OOM with `--float32` on A100

**Comment by Chillee** [comment]
That similarity score looks .... pretty close.

**Comment by jansel** [comment]
We could compare both eager and inductor to float64 and see which one is closer. Since fused ops use float32 for internal math, inductor might be closer to float64 in some cases.  98% similarly might just be float16 rounding.

**Comment by desertfire** [comment]
@Chillee , the latest error is
```
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/graph.py", line 227, in call_function
    return lowerings[target](*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/lowering.py", line 179, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/lowering.py", line 2655, in copy_
    return mutate_to(dst, src)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/lowering.py", line 2636, in mutate_to
    ir.MutationLayout.realize_into(val, changed_data)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/ir.py", line 1552, in realize_into
    src.data.layout = MutationLayout(dst)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/ir.py", line 1521, in __init__
    target.get_stride(),
AttributeError: 'SliceView' object has no attribute 'get_stride'
```

I think it relates to your recent PR, https://github.com/pytorch/torchdynamo/pull/869

**Comment by Chillee** [comment]
@desertfire Oops I think you're right.

**Comment by desertfire** [comment]
This issue is actually for tracking hf_Longformer inference failure. Let's reopen it as there are some other issues after your fix.

**Comment by desertfire** [comment]
close this one, track in https://github.com/pytorch/torchdynamo/issues/1304
