### ISSUE TITLE
torchinductor fallback cannot deal with lists of tensors

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#723]
```

Traceback (most recent call last):
  File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/d5479947763d4841/hpc/torchrec/models/feed/benchmark/__vdd_benchmark__/vdd_benchmark#link-tree/torchinductor/graph.py", line 196, in call_function
    return lowerings[target](*args, **kwargs)
  File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/d5479947763d4841/hpc/torchrec/models/feed/benchmark/__vdd_benchmark__/vdd_benchmark#link-tree/torchinductor/lowering.py", line 139, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/d5479947763d4841/hpc/torchrec/models/feed/benchmark/__vdd_benchmark__/vdd_benchmark#link-tree/torchinductor/lowering.py", line 583, in handler
    result = ir.FallbackKernel.create(kernel, *args)
  File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/d5479947763d4841/hpc/torchrec/models/feed/benchmark/__vdd_benchmark__/vdd_benchmark#link-tree/torchinductor/ir.py", line 2264, in create
    return [
  File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/d5479947763d4841/hpc/torchrec/models/feed/benchmark/__vdd_benchmark__/vdd_benchmark#link-tree/torchinductor/ir.py", line 2268, in <listcomp>
    example_output[i].device,
AttributeError: 'list' object has no attribute 'device'
```

Triggered by fbgemm.jagged_dense_dense_elementwise_add_jagged_output.default

to repro in fbcode, check out V2 of https://www.internalfb.com/diff/D38488051

**Comment by ezyang** [comment]
relevant schema `"jagged_dense_dense_elementwise_add_jagged_output(Tensor x_values, Tensor[] x_offsets, Tensor y_0, Tensor y_1) -> (Tensor, Tensor[])`

**Comment by jansel** [comment]
The fix for this would be make this "unwrap" logic recursive.
https://github.com/pytorch/torchdynamo/blob/3b4f9bcc5f596bb7958b61fa83b6e5459c367e31/torchinductor/lowering.py#L659

**Comment by ezyang** [comment]
crappy recursive version, dunno if it works

```
	
            i = 0
            def go(t):
                nonlocal i
                try:
                    if t is not None:
                        return MultiOutput(
                            FixedLayout(
                                t.device,
                                t.dtype,
                                [sympy.Integer(s) for s in t.size()],
                                [sympy.Integer(s) for s in t.stride()],
                            ),
                            packed,
                            i,
                        )
                    else:
                        return None
                finally:
                    i += 1
            return pytree.tree_map(go, example_output)
```
