### ISSUE TITLE
Inductor training hf_GPT2: illegal memory access was encountered

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#741]
```
$ TORCH_SHOW_CPP_STACKTRACES=1 CUDA_LAUNCH_BLOCKING=1 ./benchmarks/torchbench.py -dcuda --inductor --training -k hf_GPT2 --no-skip
cuda train hf_GPT2                            WARNING:root:using triton random, expect difference from eager
ERROR:root:unhandled error
Traceback (most recent call last):
  File "/home/jansel/torchdynamo/benchmarks/common.py", line 879, in run_one_model
    new_result = model_iter_fn(model, example_inputs)
  File "./benchmarks/torchbench.py", line 362, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "./benchmarks/torchbench.py", line 362, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "./benchmarks/torchbench.py", line 368, in forward_and_backward_pass
    self.grad_scaler.scale(loss).backward()
  File "/home/jansel/functorch/functorch/_src/monkey_patching.py", line 77, in _backward
    return _old_backward(*args, **kwargs)
  File "/home/jansel/pytorch/torch/_tensor.py", line 371, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/jansel/pytorch/torch/autograd/__init__.py", line 191, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: an illegal memory access was encountered
Exception raised from launch_vectorized_kernel at /home/jansel/pytorch/aten/src/ATen/native/cuda/CUDALoops.cuh:99 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6c (0x7f8f64316d4c in /home/jansel/pytorch/torch/lib/libc10.so)
frame #1: void at::native::gpu_kernel_impl<at::native::CUDAFunctor_add<float> >(at::TensorIteratorBase&, at::native::CUDAFunctor_add<float> const&) + 0xfa4 (0x7f8f674d66a4 in /home/jansel/pytorch/torch/lib/libtorch_cuda.so)
frame #2: void at::native::gpu_kernel<at::native::CUDAFunctor_add<float> >(at::TensorIteratorBase&, at::native::CUDAFunctor_add<float> const&) + 0x36b (0x7f8f674d71fb in /home/jansel/pytorch/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0x30d5ab8 (0x7f8f67480ab8 in /home/jansel/pytorch/torch/lib/libtorch_cuda.so)
frame #4: at::native::add_kernel(at::TensorIteratorBase&, c10::Scalar const&) + 0x34 (0x7f8f674823a4 in /home/jansel/pytorch/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x2ed5fe7 (0x7f8f67280fe7 in /home/jansel/pytorch/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x2ed60cb (0x7f8f672810cb in /home/jansel/pytorch/torch/lib/libtorch_cuda.so)
frame #7: at::_ops::add_Tensor::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::Scalar const&) + 0x8f (0x7f8f6fe55d7f in /home/jansel/pytorch/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x398170f (0x7f8f7162870f in /home/jansel/pytorch/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x3981d6e (0x7f8f71628d6e in /home/jansel/pytorch/torch/lib/libtorch_cpu.so)
frame #10: at::_ops::add_Tensor::call(at::Tensor const&, at::Tensor const&, c10::Scalar const&) + 0x17d (0x7f8f6fe8206d in /home/jansel/pytorch/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x41c3494 (0x7f8f71e6a494 in /home/jansel/pytorch/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x41c443e (0x7f8f71e6b43e in /home/jansel/pytorch/torch/lib/libtorch_cpu.so)
frame #13: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x1004 (0x7f8f71e55f54 in /home/jansel/pytorch/torch/lib/libtorch_cpu.so)
frame #14: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x651 (0x7f8f71e56fd1 in /home/jansel/pytorch/torch/lib/libtorch_cpu.so)
frame #15: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x9f (0x7f8f71e4e06f in /home/jansel/pytorch/torch/lib/libtorch_cpu.so)
frame #16: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x67 (0x7f8f7c3769f7 in /home/jansel/pytorch/torch/lib/libtorch_python.so)
frame #17: <unknown function> + 0xd6de4 (0x7f8f7e4cdde4 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #18: <unknown function> + 0x8609 (0x7f8fb3420609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #19: clone + 0x43 (0x7f8fb3345133 in /lib/x86_64-linux-gnu/libc.so.6)
```

Hrm, looks like `at::native::add_kernel`.

Are we somehow creating an invalid tensor?

_Originally posted by @jansel in https://github.com/pytorch/torchdynamo/issues/708#issuecomment-1207149848_  (more context in PR comments)

**Comment by Chillee** [comment]
I figured out the error. The arguments that AOTAutograd is passing to the backwards compiler are not correct - the gradOuts should be contiguous, but we don't currently do that.

**Comment by Chillee** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/83367

**Comment by Chillee** [comment]
```
INCORRECT
1.802x p=0.00
speedup    gmean=1.80x mean=1.80x
```

**Comment by Chillee** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/83367
