### ISSUE TITLE
min_cut_rematerialization_partition error from pytorch_struct

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#749]
```
./benchmarks/torchbench.py -dcuda --float16 --inductor --training  -k pytorch_struct
```

```
cuda train pytorch_struct                     ERROR:root:unhandled error
Traceback (most recent call last):
  File "/home/jansel/torchdynamo/benchmarks/common.py", line 879, in run_one_model
    new_result = model_iter_fn(model, example_inputs)
  File "./benchmarks/torchbench.py", line 371, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "./benchmarks/torchbench.py", line 371, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "./benchmarks/torchbench.py", line 375, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/torchbenchmark/torchbenchmark/models/pytorch_struct/networks/NeuralCFG.py", line 43, in forward
    def forward(self, input):
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 94, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/pytorch/functorch/functorch/_src/aot_autograd.py", line 696, in forward
    return compiled_f(
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 94, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/pytorch/functorch/functorch/_src/aot_autograd.py", line 239, in forward
    fw_module, bw_module = partition_fn(fx_g, joint_inputs)
  File "/home/jansel/pytorch/functorch/functorch/_src/partitioners.py", line 411, in min_cut_rematerialization_partition
    fw_module, bw_module = _extract_fwd_bwd_modules(joint_module, saved_values)
  File "/home/jansel/pytorch/functorch/functorch/_src/partitioners.py", line 116, in _extract_fwd_bwd_modules
    bwd_module = fx.GraphModule(joint_module, bwd_graph)
  File "/home/jansel/pytorch/torch/fx/graph_module.py", line 366, in __init__
    self.graph = graph
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1309, in __setattr__
    super().__setattr__(name, value)
  File "/home/jansel/pytorch/torch/fx/graph_module.py", line 404, in graph
    self.recompile()
  File "/home/jansel/pytorch/torch/fx/graph_module.py", line 641, in recompile
    cls.forward = _forward_from_src(self._code, python_code.globals)
  File "/home/jansel/pytorch/torch/fx/graph_module.py", line 77, in _forward_from_src
    _exec_with_source(src, globals_copy)
  File "/home/jansel/pytorch/torch/fx/graph_module.py", line 71, in _exec_with_source
    exec(compile(src, key, 'exec'), globals)
  File "<eval_with_key>.10", line 115
    return [Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, view_sym_int_3, permute_default_47, view_sym_int_1, permute_default_39, view_sym_int_2, permute_default_43, view_sym_int, permute_default_35, view_sym_int_4, permute_default_51, squeeze_dim_7, squeeze_dim_5, mm_default_18, squeeze_dim_4, Invalid Node, Invalid Node, None]
```

cc @Chillee

**Comment by jansel** [comment]
Look like this error is also happening for HF AllenaiLongformerBase: #796

**Comment by Chillee** [comment]
I don't see this error anymore when running. Closing.
