### ISSUE TITLE
[mobilenet_v3_large][prims+nvfuser] ValueError: Received type <class 'NoneType'> that is neither a tensor or a number!

### ISSUE THREAD

**Issue by xwang233** [pytorch/torchdynamo#759]
Reproduce:
```python
# python benchmarks/torchbench.py --training -d cuda --fast --prims-nvfuser --skip-accuracy-check --generate-aot-autograd-stats --isolate -k mobilenet_v3_large
cuda train mobilenet_v3_large                 ERROR:root:unhandled error
Traceback (most recent call last):
  File "/opt/pytorch/torchdynamo/benchmarks/common.py", line 879, in run_one_model
    new_result = model_iter_fn(model, example_inputs)
  File "benchmarks/torchbench.py", line 366, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "benchmarks/torchbench.py", line 366, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "benchmarks/torchbench.py", line 370, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/pytorch/vision/torchvision/models/mobilenetv3.py", line 235, in forward
    def forward(self, x: Tensor) -> Tensor:
  File "/opt/pytorch/torchdynamo/torchdynamo/eval_frame.py", line 94, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/functorch/functorch/_src/aot_autograd.py", line 696, in forward
    return compiled_f(
  File "/opt/pytorch/torchdynamo/torchdynamo/eval_frame.py", line 94, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/functorch/functorch/_src/aot_autograd.py", line 246, in forward
    fw_outs = normalize_as_list(compiled_fw(*flat_tensor_args))
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 655, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.40", line 63, in forward
    fused_28 = self.fused_28(to_dtype)
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 655, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/passes/backends/nvfuser.py", line 251, in lower_to_prims_and_execute
    DecompositionInterpreter(graph_module, prim_graph, decomposition_table=aten2prim_decomp).run(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 496, in run
    return super().run(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/interpreter.py", line 129, in run
    self.env[node] = self.run_node(node)
  File "/opt/pytorch/pytorch/torch/fx/interpreter.py", line 166, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/interpreter.py", line 238, in call_function
    return target(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 56, in __call__
    return self._op(*args, **kwargs or {})
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 307, in __torch_dispatch__
    return func_overload(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 56, in __call__
    return self._op(*args, **kwargs or {})
  File "/opt/pytorch/pytorch/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 404, in __torch_dispatch__
    return proxy_call(self, func_overload, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 147, in proxy_call
    return CURRENT_DECOMPOSITION_TABLE[func_overload](*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_prims_common/wrappers.py", line 206, in _fn
    result = fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_prims_common/wrappers.py", line 108, in _fn
    promoted_args = {
  File "/opt/pytorch/pytorch/torch/_prims_common/wrappers.py", line 109, in <dictcomp>
    x: _maybe_convert_to_dtype(bound.arguments[x], compute_dtype)
  File "/opt/pytorch/pytorch/torch/_prims_common/wrappers.py", line 35, in _maybe_convert_to_dtype
    raise ValueError(
ValueError: Received type <class 'NoneType'> that is neither a tensor or a number!
ERROR
ERROR
cuda               gmean=nanx mean=nanx
mobilenet_v3_large gmean=nanx mean=nanx
0                  gmean=nanx mean=nanx
0.0000             gmean=nanx mean=nanx
```

Env:

- V100, cuda 11.7
- torch_commit: https://github.com/pytorch/pytorch/commit/b4b60c2a2e423f49d81d7d634de6ead5c77d3640
- torchbench_commit: https://github.com/pytorch/benchmark/commit/97393f44bb8ddb9c52e86e982a99abf6d35047f7
- torchdynamo_commit: https://github.com/pytorch/torchdynamo/commit/7b039ccbfdef2f4a50b9155ed5e8e1fd4a882664
- torchvision_commit: https://github.com/pytorch/vision/commit/1d0786b0a35661408388ed4268e382f56bcde627

**Comment by anijain2305** [comment]
cc @SherlockNoMad

**Comment by rdspring1** [comment]
I printed out the graph_module in File `/opt/pytorch/pytorch/torch/fx/passes/backends/nvfuser.py` at `lower_to_prims_and_execute`.

Here is the failing module:
```
fused_28()
def forward(self, getitem):
    add_tensor = torch.ops.aten.add.Tensor(getitem, 3)
    clamp_default = torch.ops.aten.clamp.default(add_tensor, 0);  add_tensor = None
    clamp_default_1 = torch.ops.aten.clamp.default(clamp_default, None, 6);  clamp_default = None
    mul_tensor = torch.ops.aten.mul.Tensor(getitem, clamp_default_1);  getitem = clamp_default_1 = None
    div_tensor = torch.ops.aten.div.Tensor(mul_tensor, 6);  mul_tensor = None
    return div_tensor
```

 It is failing because `_maybe_convert_to_dtype` doesn't handle the `None` argument in the second `clamp` function.

**Comment by csarofeen** [comment]
@rdspring1 @IvanYashchuk would either of you be able to work on fixing this issue?

**Comment by IvanYashchuk** [comment]
I'll try to fix it today.

**Comment by IvanYashchuk** [comment]
Thanks, Ryan, for your analysis!
`clamp` function can accept None for its max or min arguments and this case wasn't tested in PyTorch.

I have verified that https://github.com/pytorch/pytorch/pull/83586 fixes the reported problem.
