### ISSUE TITLE
[BigBird][aot_nvfuser] Got RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by xwang233** [pytorch/torchdynamo#761]
Reproduce:

```python
# python benchmarks/huggingface.py --training -d cuda --fast --accuracy-aot-ts-mincut --nvfuser --skip-accuracy-check --generate-aot-autograd-stats --isolate --float16 -k BigBird
cuda train BigBird                            DEBUG torchdynamo.optimizations.training: Unable to use AOT Autograd because graph has mutation
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.49", line 85, in forward
    bmm_3 = torch.bmm(reshape_10, reshape_11);  reshape_10 = reshape_11 = None
RuntimeError: expected scalar type Half but found Float

Call using an FX-traced Module, line 85 of the traced Module's generated forward function:
    reshape_11 = cat_2.reshape((-1, 448, 64));  cat_2 = None
    bmm_3 = torch.bmm(reshape_10, reshape_11);  reshape_10 = reshape_11 = None

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    view_11 = bmm_3.view((1, 12, 64, 64));  bmm_3 = None

    unsqueeze_1 = view_11.unsqueeze(2);  view_11 = None

ERROR:root:unhandled error
Traceback (most recent call last):
  File "/opt/pytorch/torchdynamo/benchmarks/common.py", line 879, in run_one_model
    new_result = model_iter_fn(model, example_inputs)
  File "benchmarks/huggingface.py", line 424, in forward_and_backward_pass
    pred = mod(**cloned_inputs)
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 2394, in forward
    @add_start_docstrings_to_model_forward(BIG_BIRD_INPUTS_DOCSTRING.format("batch_size, sequence_length"))
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 1985, in forward
    @add_start_docstrings_to_model_forward(BIG_BIRD_INPUTS_DOCSTRING.format("batch_size, sequence_length"))
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 1641, in forward
    layer_outputs = layer_module(
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 1477, in forward
    def forward(
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 1406, in forward
    self_outputs = self.self(
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 449, in forward
    def forward(
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 519, in bigbird_block_sparse_attention
    def bigbird_block_sparse_attention(
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 519, in bigbird_block_sparse_attention
    def bigbird_block_sparse_attention(
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 519, in bigbird_block_sparse_attention
    def bigbird_block_sparse_attention(
  [Previous line repeated 2 more times]
  File "/opt/pytorch/torchdynamo/torchdynamo/eval_frame.py", line 94, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 655, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 275, in __call__
    raise e.with_traceback(None)
RuntimeError: expected scalar type Half but found Float
ERROR
ERROR
cuda    gmean=nanx mean=nanx
BigBird gmean=nanx mean=nanx
0       gmean=nanx mean=nanx
0.0000  gmean=nanx mean=nanx
```

Env:

- A100, cuda 11.7
- torch_commit: https://github.com/pytorch/pytorch/commit/b4b60c2a2e423f49d81d7d634de6ead5c77d3640
- torchbench_commit: https://github.com/pytorch/benchmark/commit/97393f44bb8ddb9c52e86e982a99abf6d35047f7
- torchdynamo_commit: https://github.com/pytorch/torchdynamo/commit/7b039ccbfdef2f4a50b9155ed5e8e1fd4a882664
- torchvision_commit: https://github.com/pytorch/vision/commit/1d0786b0a35661408388ed4268e382f56bcde627

**Comment by ezyang** [comment]
also reported at https://github.com/pytorch/torchdynamo/issues/80
