### ISSUE TITLE
Fix python key tracing errors with quantized models

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#79]
Repro
```
./torchbench.py --no-skip --python-key -n 1 -k mobilenet_v2_quantized
```
Partial output:
```
ERROR:torchdynamo.optimizations.python_key:exception running call_function torch.quantize_per_tensor (inputs_0_, mod_features_0_0_input_scale_0, mod_features_0_0_input_zero_point_0, torch.quint8) {}
Traceback (most recent call last):
  File "/home/jansel/torchdynamo/torchdynamo/optimizations/python_key.py", line 77, in run_node
    result = super().run_node(n)
  File "/home/jansel/pytorch/torch/fx/interpreter.py", line 147, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/jansel/pytorch/torch/fx/interpreter.py", line 219, in call_function
    return target(*args, **kwargs)
  File "/home/jansel/functorch/functorch/_src/python_key.py", line 112, in __torch_dispatch__
    return wrap_with_proxy(real_out, proxy_out)
  File "/home/jansel/functorch/functorch/_src/python_key.py", line 104, in wrap_with_proxy
    return PythonTensor(e, proxy)
  File "/home/jansel/functorch/functorch/_src/python_key.py", line 60, in __new__
    proxy.node.meta['tensor_meta'] = _extract_tensor_metadata(r)
  File "/home/jansel/pytorch/torch/fx/passes/shape_prop.py", line 48, in _extract_tensor_metadata
    qscheme = result.qscheme()
RuntimeError: toIValue() cannot handle converting to type: QScheme
```

This effects 2 quantized modules with the same error.

cc @Chillee @anijain2305

**Comment by bitfort** [comment]
1.13 P0 is to fall back quietly.  

Long term we want this to actually work / speed up.

**Comment by Chillee** [comment]
Root cause here is fairly bizarre. It appears that for some of the operators in the TorchDynamo resulting graph, `operator(PythonTensor)` is resulting in a regular tensor instead of a PythonTensor.

Ah, might have found it. 

https://github.com/pytorch/pytorch/pull/50859

This PR breaks(?) composite compliance, as it forces `aten::flatten` (a composite op) to call `native::reshape`, which prevents redispatching.

But... this seems to work fine with normal tensors, it's only when it's a quantized tensor that it fails. I'm guessing there's an operator somewhere that has some different implementation for QuantCPU? not sure.

Minimal repro
```
def f(x):
  out = torch.flatten(x)
  return out

val = torch.quantize_per_tensor(torch.randn(2,3,4,5), 0.1, 10, torch.quint8)
print(make_fx(f)(val))
```
results in
```
def forward(self, x_1):
    _reshape_alias = torch.ops.aten._reshape_alias(x_1, [120], [1]);  x_1 = None
    _tensor_constant0 = self._tensor_constant0
    return _tensor_constant0
```

**Comment by ciciewang** [comment]
on hold for now.

**Comment by Chillee** [comment]
Not sure why, but this seems to work for me now.
