### ISSUE TITLE
Missing aten::eq with model fastNLP_Bert in torchbenchmark

### ISSUE THREAD

**Issue by shingjan** [pytorch/torchdynamo#813]

**Comment by ezyang** [comment]
For ease of tracking, I'm moving this to the torchdynamo repo, but I recommend trying a non-TS backend (as we're working on getting rid of it).

**Comment by shingjan** [comment]
@ezyang Thanks for the note! What other non-TS backend would you recommend in this case? The reason I was using TS is bcoz TorchScript seems to be the de facto backend for torchdynamo if we want to utilize the model partitioning. I am assuming `eager mode` is not the answer.

**Comment by ezyang** [comment]
err, what exactly do you mean by "model partitioning?" Do you mean AOTAutograd's partitioner for saving memory across forward/backwards? AOT eager would actually be sufficient for that, though you'd lose the overhead reduction benefit of ts

**Comment by shingjan** [comment]
@ezyang Sorry for the late response. The following is the error if I change the backend to `eager`:
```
python benchmarks/torchbench.py --only fastNLP_Bert --backend eager -dcpu
cpu  eval  fastNLP_Bert                       ERROR FROM offset=360 filename /home/yj/anaconda3/envs/torchdynamo/lib/python3.8/site-packages/fastNLP/embeddings/bert_embedding.py 467 NotImplementedError
========== TorchDynamo Stack Trace ==========
Traceback (most recent call last):
  File "/home/yj/torchdynamo/torchdynamo/convert_frame.py", line 288, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/home/yj/torchdynamo/torchdynamo/bytecode_transformation.py", line 338, in transform_code_object
    transformations(instructions, code_options)
  File "/home/yj/torchdynamo/torchdynamo/convert_frame.py", line 264, in transform
    tracer.run()
  File "/home/yj/torchdynamo/torchdynamo/symbolic_convert.py", line 312, in run
    and self.step()
  File "/home/yj/torchdynamo/torchdynamo/symbolic_convert.py", line 290, in step
    getattr(self, inst.opname)(inst)
  File "/home/yj/torchdynamo/torchdynamo/symbolic_convert.py", line 151, in wrapper
    return inner_fn(self, inst)
  File "/home/yj/torchdynamo/torchdynamo/symbolic_convert.py", line 629, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/yj/torchdynamo/torchdynamo/symbolic_convert.py", line 226, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/yj/torchdynamo/torchdynamo/variables/torch.py", line 209, in call_function
    proxy=tx.output.create_proxy(
  File "/home/yj/torchdynamo/torchdynamo/output_graph.py", line 449, in create_proxy
    rv = super().create_proxy(
  File "/home/yj/anaconda3/envs/torchdynamo/lib/python3.8/site-packages/torch/fx/proxy.py", line 65, in create_proxy
    args_ = self.create_arg(args)
  File "/home/yj/anaconda3/envs/torchdynamo/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 342, in create_arg
    return super().create_arg(a)
  File "/home/yj/anaconda3/envs/torchdynamo/lib/python3.8/site-packages/torch/fx/proxy.py", line 127, in create_arg
    return type(a)(self.create_arg(elem) for elem in a)
  File "/home/yj/anaconda3/envs/torchdynamo/lib/python3.8/site-packages/torch/fx/proxy.py", line 127, in <genexpr>
    return type(a)(self.create_arg(elem) for elem in a)
  File "/home/yj/anaconda3/envs/torchdynamo/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 342, in create_arg
    return super().create_arg(a)
  File "/home/yj/anaconda3/envs/torchdynamo/lib/python3.8/site-packages/torch/fx/proxy.py", line 127, in create_arg
    return type(a)(self.create_arg(elem) for elem in a)
  File "/home/yj/anaconda3/envs/torchdynamo/lib/python3.8/site-packages/torch/fx/proxy.py", line 127, in <genexpr>
    return type(a)(self.create_arg(elem) for elem in a)
  File "/home/yj/anaconda3/envs/torchdynamo/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 342, in create_arg
    return super().create_arg(a)
  File "/home/yj/anaconda3/envs/torchdynamo/lib/python3.8/site-packages/torch/fx/proxy.py", line 153, in create_arg
    raise NotImplementedError(f"argument of type: {type(a)}")
NotImplementedError: argument of type: <class 'numpy.int64'>
```
It is the same error if I switch to `aot_autograd`. I am not quite sure what is aot eager so I tried both `eager` and `aot_autograd`. Also I wonder if you can provide more context on TorchScript being rid of. Is there a decision made to deprecate TorchScript in favor of some other alternative? Thanks!

**Comment by ezyang** [comment]
This would be the same bug as https://github.com/pytorch/torchdynamo/issues/837 then

**Comment by shingjan** [comment]
The error on aot_autograd and eager seems to be the same bug as #837 and I will follou-up with the result on torchscript once the fix is checked in. Circling back to TorchScript being deprecated, is there any more context about that? Thanks!

**Comment by ezyang** [comment]
So, I'm talking specifically about dynamo backends. The TS+nvFuser backend is historically the most stable backend but it has some hard to fix TS-related problems that we aren't planning to actually fix. Instead, for compiled mode, you should either use inductor, or the new Python+nvFuser backend.
