### ISSUE TITLE
index_put_ assertion in hf_GPT2ForSequenceClassification

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#818]
```
cuda train GPT2ForSequenceClassification      WARNING:root:using triton random, expect difference from eager
ERROR:root:unhandled error
Traceback (most recent call last):
  File "/scratch/jansel/wd20220811/torchdynamo/torchinductor/graph.py", line 221, in call_function
    return lowerings[target](*args, **kwargs)
  File "/scratch/jansel/wd20220811/torchdynamo/torchinductor/lowering.py", line 139, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/scratch/jansel/wd20220811/torchdynamo/torchinductor/lowering.py", line 1406, in index_put_
    iter_ranges.append(V.graph.sizevars.guard_equals(i_size, v_size))
  File "/scratch/jansel/wd20220811/torchdynamo/torchinductor/sizevars.py", line 127, in guard_equals
    assert self.size_hint(expr) == 0, (expr, self.size_hint(expr))
AssertionError: (2, 2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/jansel/wd20220811/torchdynamo/benchmarks/common.py", line 974, in run_one_model
    new_result = accuracy_model_iter_fn(model, example_inputs)
  File "/scratch/jansel/wd20220811/torchdynamo/torchdynamo/eval_frame.py", line 135, in _fn
    return fn(*args, **kwargs)
  File "./benchmarks/huggingface.py", line 417, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "./benchmarks/huggingface.py", line 417, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "./benchmarks/huggingface.py", line 421, in forward_and_backward_pass
    pred = mod(**cloned_inputs)
  File "/scratch/jansel/wd20220811/pytorch/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/jansel/wd20220811/env/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1346, in forward
    @add_start_docstrings_to_model_forward(GPT2_INPUTS_DOCSTRING)
  File "/scratch/jansel/wd20220811/torchdynamo/torchdynamo/eval_frame.py", line 135, in _fn
    return fn(*args, **kwargs)
  File "/scratch/jansel/wd20220811/pytorch/functorch/functorch/_src/aot_autograd.py", line 702, in forward
    return compiled_f(
  File "/scratch/jansel/wd20220811/torchdynamo/torchdynamo/eval_frame.py", line 135, in _fn
    return fn(*args, **kwargs)
  File "/scratch/jansel/wd20220811/pytorch/functorch/functorch/_src/aot_autograd.py", line 257, in forward
    compiled_bw = bw_compiler(bw_module, bw_args)
  File "/scratch/jansel/wd20220811/torchdynamo/torchdynamo/optimizations/backends.py", line 542, in _wrapped_bw_compiler
    return torchdynamo.disable(bw_compiler(*args, **kwargs))
  File "/scratch/jansel/wd20220811/torchdynamo/torchinductor/compile_fx.py", line 281, in bw_compiler
    return compile_fx_inner(
  File "/scratch/jansel/wd20220811/torchdynamo/torchinductor/compile_fx.py", line 155, in compile_fx_inner
    wrap(graph.run)(*example_inputs)
  File "/scratch/jansel/wd20220811/torchdynamo/torchinductor/graph.py", line 122, in run
    return super().run(*args)
  File "/scratch/jansel/wd20220811/pytorch/torch/fx/interpreter.py", line 129, in run
    self.env[node] = self.run_node(node)
  File "/scratch/jansel/wd20220811/torchdynamo/torchinductor/graph.py", line 271, in run_node
    result = super().run_node(n)
  File "/scratch/jansel/wd20220811/pytorch/torch/fx/interpreter.py", line 162, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/scratch/jansel/wd20220811/torchdynamo/torchinductor/graph.py", line 223, in call_function
    raise LoweringException(e, target, args, kwargs) from e
torchinductor.exc.LoweringException: AssertionError: (2, 2)
  target: aten.index_put_.default
  args[0]: TensorBox(StorageBox(
    ComputedBuffer(name='buf0', layout=FlexibleLayout('cuda', torch.float32, size=[4, 1024, 2], stride=[2048, 2, 1]), data=Pointwise(
      'cuda',
      torch.float32,
      constant(0, torch.float32),
      ranges=[4, 1024, 2],
      origins={clone_default_48}
    ))
  ))
  args[1]: [TensorBox(StorageBox(
    InputBuffer(name='arange_1', layout=FixedLayout('cuda', torch.float32, size=[4], stride=[1]))
  )), TensorBox(StorageBox(
    InputBuffer(name='sub_tensor_49', layout=FixedLayout('cuda', torch.bool, size=[4], stride=[1]))
  ))]
  args[2]: TensorBox(StorageBox(
    InputBuffer(name='tangents_26', layout=FixedLayout('cuda', torch.float32, size=[4, 2], stride=[2, 1]))
  ))
  args[3]: True
ERROR
```

**Comment by Chillee** [comment]
Perhaps a similar error as here? https://github.com/pytorch/torchdynamo/issues/623

**Comment by Chillee** [comment]
@jansel Can you put a repro command for this?

**Comment by jansel** [comment]
> @jansel Can you put a repro command for this?

Looks like @ngimel already fixed this.  I believe it was just:
```
./benchmarks/huggingface.py -dcuda --inductor --training -k GPT2ForSequenceClassification
```

**Comment by ngimel** [comment]
This one now (after I land #855) errors with IMA in autograd

**Comment by Chillee** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/83367 (although still accuracy errors, probably dropout).

```
cuda train GPT2ForSequenceClassification      WARNING:root:using triton random, expect difference from eager
Similarity score=0.4877658188343048
Accuracy failed for key name logits
INCORRECT
1.743x p=0.00
speedup    gmean=1.74x mean=1.74x
```
