### ISSUE TITLE
`pytorch-geometric` dynamo failure

### ISSUE THREAD

**Issue by msaroufim** [pytorch/torchdynamo#829]
`torch-geometric` is one of the most popular Graph Neural Network libraries in the pytorch ecosystem

## Setup

```
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.12.0+cu116.html
pip install torch-sparse -f https://data.pyg.org/whl/torch-1.12.0+cu116.html
pip install torch-geometric
```

## Repro
Adapted from their hello world example https://github.com/pyg-team/pytorch_geometric#train-your-own-gnn-model

```python
import torch
from torch import Tensor
from torch_geometric.nn import GCNConv
from torch_geometric.datasets import Planetoid
import torchdynamo

dataset = Planetoid(root='.', name='Cora')

class GCN(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super().__init__()
        self.conv1 = GCNConv(in_channels, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, out_channels)

    def forward(self, x: Tensor, edge_index: Tensor) -> Tensor:
        # x: Node feature matrix of shape [num_nodes, in_channels]
        # edge_index: Graph connectivity matrix of shape [2, num_edges]
        x = self.conv1(x, edge_index).relu()
        x = self.conv2(x, edge_index)
        return x

model = GCN(dataset.num_features, 16, dataset.num_classes)


import torch.nn.functional as F

data = dataset[0]
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

pred = model(data.x, data.edge_index)
loss = F.cross_entropy(pred[data.train_mask], data.y[data.train_mask])

with torchdynamo.optimize("eager"):
    # Backpropagation
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
```

## Logs

```
(pyg) ubuntu@ip-172-31-27-252:~$ python gnn.py 
ERROR FROM offset=72 filename /home/ubuntu/anaconda3/envs/pyg/lib/python3.8/site-packages/torch/optim/optimizer.py 238 TypeError
========== TorchDynamo Stack Trace ==========
Traceback (most recent call last):
  File "/home/ubuntu/torchdynamo/torchdynamo/convert_frame.py", line 288, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/home/ubuntu/torchdynamo/torchdynamo/bytecode_transformation.py", line 338, in transform_code_object
    transformations(instructions, code_options)
  File "/home/ubuntu/torchdynamo/torchdynamo/convert_frame.py", line 264, in transform
    tracer.run()
  File "/home/ubuntu/torchdynamo/torchdynamo/symbolic_convert.py", line 312, in run
    and self.step()
  File "/home/ubuntu/torchdynamo/torchdynamo/symbolic_convert.py", line 290, in step
    getattr(self, inst.opname)(inst)
  File "/home/ubuntu/torchdynamo/torchdynamo/symbolic_convert.py", line 538, in FOR_ITER
    self.replace_all(it, next_iter)
  File "/home/ubuntu/torchdynamo/torchdynamo/symbolic_convert.py", line 252, in replace_all
    self.update_locals_and_stack(oldvar, newvar)
  File "/home/ubuntu/torchdynamo/torchdynamo/symbolic_convert.py", line 236, in update_locals_and_stack
    self.stack = [VariableTracker.apply(repl, x, cache) for x in self.stack]
  File "/home/ubuntu/torchdynamo/torchdynamo/symbolic_convert.py", line 236, in <listcomp>
    self.stack = [VariableTracker.apply(repl, x, cache) for x in self.stack]
  File "/home/ubuntu/torchdynamo/torchdynamo/variables/base.py", line 99, in apply
    updated_dict[key] = cls.apply(fn, updated_dict[key], cache)
  File "/home/ubuntu/torchdynamo/torchdynamo/variables/base.py", line 100, in apply
    result = fn(value.clone(**updated_dict))
  File "/home/ubuntu/torchdynamo/torchdynamo/variables/base.py", line 73, in clone
    return self.__class__(**args)
  File "/home/ubuntu/torchdynamo/torchdynamo/variables/misc.py", line 298, in __init__
    super(ProfileRecordFunctionVariable, self).__init__(
  File "/home/ubuntu/torchdynamo/torchdynamo/variables/misc.py", line 118, in __init__
    super(ContextWrappingVariable, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'enter'
========== Exception (above) while processing ==========
  File "gnn.py", line 35, in <module>
    optimizer.zero_grad()
  File "/home/ubuntu/anaconda3/envs/pyg/lib/python3.8/site-packages/torch/optim/optimizer.py", line 216, in zero_grad
    def zero_grad(self, set_to_none: bool = False):
========== End debug info ==========
ERROR FROM offset=166 filename /home/ubuntu/anaconda3/envs/pyg/lib/python3.8/site-packages/torch/optim/adam.py 136 NotImplementedError
========== TorchDynamo Stack Trace ==========
Traceback (most recent call last):
  File "/home/ubuntu/torchdynamo/torchdynamo/convert_frame.py", line 288, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/home/ubuntu/torchdynamo/torchdynamo/bytecode_transformation.py", line 338, in transform_code_object
    transformations(instructions, code_options)
  File "/home/ubuntu/torchdynamo/torchdynamo/convert_frame.py", line 264, in transform
    tracer.run()
  File "/home/ubuntu/torchdynamo/torchdynamo/symbolic_convert.py", line 312, in run
    and self.step()
  File "/home/ubuntu/torchdynamo/torchdynamo/symbolic_convert.py", line 290, in step
    getattr(self, inst.opname)(inst)
  File "/home/ubuntu/torchdynamo/torchdynamo/symbolic_convert.py", line 151, in wrapper
    return inner_fn(self, inst)
  File "/home/ubuntu/torchdynamo/torchdynamo/symbolic_convert.py", line 105, in impl
    self.push(fn_var.call_function(self, self.popn(nargs), {}))
  File "/home/ubuntu/torchdynamo/torchdynamo/variables/builtin.py", line 335, in call_function
    result = handler(tx, *args, **kwargs)
  File "/home/ubuntu/torchdynamo/torchdynamo/variables/builtin.py", line 536, in call_getitem
    return args[0].call_method(tx, "__getitem__", args[1:], kwargs)
  File "/home/ubuntu/torchdynamo/torchdynamo/variables/user_defined.py", line 206, in call_method
    return self.odict_getitem(tx, args[0])
  File "/home/ubuntu/torchdynamo/torchdynamo/variables/user_defined.py", line 374, in odict_getitem
    ODictGetItemSource(self.source, key.as_python_constant()),
  File "/home/ubuntu/torchdynamo/torchdynamo/variables/base.py", line 144, in as_python_constant
    raise NotImplementedError(f"{self} is not a constant")
NotImplementedError: TensorVariable() is not a constant
========== Exception (above) while processing ==========
  File "gnn.py", line 37, in <module>
    optimizer.step()
  File "/home/ubuntu/anaconda3/envs/pyg/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pyg/lib/python3.8/site-packages/torch/optim/adam.py", line 105, in step
    @torch.no_grad()
  File "/home/ubuntu/anaconda3/envs/pyg/lib/python3.8/site-packages/torch/optim/adam.py", line 105, in step
    @torch.no_grad()
========== End debug info ==========
```

cc: @anijain2305

**Comment by yanboliang** [comment]
@msaroufim I had fix this by https://github.com/pytorch/torchdynamo/pull/867 and verified it works well. Let me know if it works on you end or any other questions.

**Comment by msaroufim** [comment]
That was fast, what was the problem at a high level? I can send you more examples asap if this was helpful

**Comment by yanboliang** [comment]
The problem is we don't handle ```autograd.profiler.*``` well, but they are used widely during model training iterations, e.g, ```optimizer.zero_grad()``` and ```optimizer.step()``` in your example. Sure, if you have other examples that's doesn't work well, send me the repros and I'm glad to help debug.
