### ISSUE TITLE
TorchBench Inference Accuracy Error: hf_Reformer

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#838]
Repro:
```
./benchmarks/torchbench.py -dcuda --inductor --float32 --no-skip  -k hf_Reformer
````
Error msg:
```
Similarity score=0.7499349117279053
Accuracy failed for key name logits
INCORRECT
ERROR
```

**Comment by Chillee** [comment]
I see that there's `randn` calls in the forwards pass - I'm suspicious the accuracy differences are coming from that.

However, when I enabled randn fallback, I ran into this error: https://github.com/pytorch/torchdynamo/issues/907

**Comment by jansel** [comment]
```
I am getting cuda eval  hf_Reformer                        ERROR:root:unhandled error
Traceback (most recent call last):
  File "/home/jansel/torchdynamo/benchmarks/common.py", line 1137, in run_one_model
    new_result = optimized_model_iter_fn(model, example_inputs)
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 153, in _fn
    return fn(*args, **kwargs)
  File "./benchmarks/torchbench.py", line 367, in forward_pass
    def forward_pass(self, mod, inputs, collect_outputs=True):
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/reformer/modeling_reformer.py", line 2336, in forward
    @add_start_docstrings_to_model_forward(REFORMER_INPUTS_DOCSTRING)
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/reformer/modeling_reformer.py", line 2010, in forward
    @add_start_docstrings_to_model_forward(REFORMER_INPUTS_DOCSTRING)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/reformer/modeling_reformer.py", line 2100, in forward
    embedding_output = self.embeddings(
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/reformer/modeling_reformer.py", line 239, in forward
    def forward(self, input_ids=None, position_ids=None, inputs_embeds=None, start_idx_pos_encodings=0):
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/reformer/modeling_reformer.py", line 146, in forward
    def forward(self, position_ids):
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/transformers/models/reformer/modeling_reformer.py", line 146, in forward
    def forward(self, position_ids):
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 153, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/pytorch/functorch/functorch/_src/aot_autograd.py", line 880, in forward
    return compiled_f(
  File "/home/jansel/pytorch/functorch/functorch/_src/aot_autograd.py", line 871, in new_func
    return compiled_fn(args)
  File "/home/jansel/pytorch/functorch/functorch/_src/aot_autograd.py", line 274, in new_fn
    fw_outs = call_func_with_args(compiled_fw, args)
  File "/home/jansel/pytorch/functorch/functorch/_src/aot_autograd.py", line 251, in call_func_with_args
    out = normalize_as_list(f(*args))
  File "/home/jansel/torchdynamo/torchinductor/compile_fx.py", line 127, in run
    dst.copy_(src)
RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.
ERROR
unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.
ERROR
```
(running in inference mode)

**Comment by eellison** [comment]
Should be fixed with https://github.com/pytorch/torchdynamo/pull/1208
