### ISSUE TITLE
PyTorch test suite regression test_module_backward_global_hook_writeable

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#847]
Bisected to https://github.com/pytorch/torchdynamo/pull/763

Repro command

```
PYTORCH_TEST_WITH_DYNAMO=1 python test/test_nn.py -k test_module_backward_global_hook_writeable
```

error

```
======================================================================                               
FAIL: test_module_backward_global_hook_writeable (__main__.TestModuleGlobalHooks)
----------------------------------------------------------------------                             
Traceback (most recent call last):                                                                   
  File "test/test_nn.py", line 21073, in test_module_backward_global_hook_writeable                  
    def test_module_backward_global_hook_writeable(self):                                            
  File "test/test_nn.py", line 21073, in test_module_backward_global_hook_writeable
    def test_module_backward_global_hook_writeable(self):                                          
  File "test/test_nn.py", line 21073, in test_module_backward_global_hook_writeable
    def test_module_backward_global_hook_writeable(self):             
  [Previous line repeated 1 more time]
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_utils.py", line 2382, in assert
Equal
    assert_equal(                                                                                    
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 25 / 25 (100.0%)
Greatest absolute difference: 0.24967582497447965 at index (4, 2) (up to 1e-07 allowed)
Greatest relative difference: 0.5 at index (0, 0) (up to 1e-07 allowed)

----------------------------------------------------------------------
```

**Comment by ezyang** [comment]
I plan to xfail this test for now

**Comment by anijain2305** [comment]
Thanks! Yes, let's skip this one. This is interesting

**Comment by ezyang** [comment]
Also regressions in test_jit.py test_desugar_module and test_binary_ufuncs.py test_cumulative_trapezoid_cpu

Logs https://github.com/pytorch/pytorch/runs/7867692993?check_suite_focus=true https://github.com/pytorch/pytorch/runs/7867693086?check_suite_focus=true

**Comment by ezyang** [comment]
There's some breakage with scipy import handling

**Comment by anijain2305** [comment]
We have fixed the scipy import handling.

For hooks, we can keep this as low priority. We don't have good way of handling hooks in TorchDynamo, and we have been skipping similar tests in PyTorch CI.
