### ISSUE TITLE
Inductor error: pyhpc_turbulent_kinetic_energy inference failed with LoweringException

### ISSUE THREAD

**Issue by pyjhzwh** [pytorch/torchdynamo#927]
On the lasted main branch (444e380e499edcfba70bd9ad2ad43b11f64ad842)
`python benchmarks/torchbench.py --inductor-settings -dcuda --float16 -n50 --inductor --filter pyhpc_turbulent_kinetic_energy` will fail
```
Traceback (most recent call last):                                                                                                                                                            
  File "/scratch/panyj/work/cpy/torchdynamo/torchinductor/graph.py", line 227, in call_function                                                                                               
    return lowerings[target](*args, **kwargs)                                                                                                                                                 
  File "/scratch/panyj/work/cpy/torchdynamo/torchinductor/lowering.py", line 172, in wrapped                                                                                                  
    return decomp_fn(*args, **kwargs)                                                                                                                                                         
  File "/scratch/panyj/work/cpy/torchdynamo/torchinductor/lowering.py", line 2636, in fill_                                                                                                   
    return mutate_to(x, full_like(x, fill_value))                                                                                                                                             
  File "/scratch/panyj/work/cpy/torchdynamo/torchinductor/lowering.py", line 172, in wrapped                                                                                                  
    return decomp_fn(*args, **kwargs)                                                                                                                                                         
  File "/scratch/panyj/work/cpy/torchdynamo/torchinductor/lowering.py", line 1194, in full_like                                                                                               
    return create_tensor_like(tensor_constructor(fill_value))(x, **kwargs)                                                                                                                    
  File "/scratch/panyj/work/cpy/torchdynamo/torchinductor/lowering.py", line 1237, in _constant_like                                                                                          
    return creation_fn(                                                                                                                                                                       
  File "/scratch/panyj/work/cpy/torchdynamo/torchinductor/lowering.py", line 1210, in inner                                                                                                   
    return _full(fill_value, device, dtype, size)                                                                                                                                             
  File "/scratch/panyj/work/cpy/torchdynamo/torchinductor/lowering.py", line 1183, in _full                                                                                                   
    assert isinstance(value, (int, float)), "Expected int or float"                                                                                                                           
AssertionError: Expected int or float                               
```

**Comment by Chillee** [comment]
What's the value there?

**Comment by pyjhzwh** [comment]
Oh, my bad. I was on 2-day-ago branch. Works on the latest one
