### ISSUE TITLE
Dynamo is still not producing accurate Python stack traces

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#941]
The frames don't have correct line numbers (if that's the problem? Hard to say.)

```
======================================================================                                 
FAIL: test_grid_sample_large_index_2d_cpu_float32 (__main__.TestNNDeviceTypeCPU)                       
----------------------------------------------------------------------                                 
Traceback (most recent call last):                                                                     
  File "/raid/ezyang/pytorch-scratch2/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test                                                                                          
    result = test(self, **param_kwargs)                                                                
  File "/raid/ezyang/pytorch-scratch2/torch/testing/_internal/common_device_type.py", line 935, in dep_fn                                                                                                     
    return fn(self, *args, **kwargs)                                                                   
  File "test/test_nn.py", line 17339, in test_grid_sample_large_index_2d                               
    @dtypes(torch.float, torch.double)                                                                 
  File "test/test_nn.py", line 17339, in test_grid_sample_large_index_2d                               
    @dtypes(torch.float, torch.double)                                                                 
  File "test/test_nn.py", line 17339, in test_grid_sample_large_index_2d                               
    @dtypes(torch.float, torch.double)                                                                 
AssertionError: False is not true : View must use 64-bit indexing                                      
                                                                                                       
---------------------------------------------------------------------- 
```

Steps to reproduce:

1. Build PyTorch with https://github.com/ezyang/pytorch/pull/new/stack-trace-insuff-repro
2. `PYTORCH_TEST_WITH_DYNAMO=1 python test/test_nn.py -k test_grid_sample_large_index_2d_cpu_float32`

cc @mlazos

**Comment by ezyang** [comment]
(dynamo shouldn't be failing this test either, but that's a separate matter...)

**Comment by mlazos** [comment]
So I took a look at this, basically what's happening is there is a graph break, so dynamo introduces another function call (the __resume_x_x functions to continue after the graph break), but the name of the code object is the same as the original. This will be a recurring issue any time dynamo introduces new functions which didn't exist in the original code. I don't think it will be possible to recover the original stack trace (without the extra frames that dynamo introduces) because this is the interpreter calling dynamo generated code, without dynamo involvement at all, but what is possible is to track the original linenumbers and filenames and end up with something like the following:

<filename> line 17339, in test_grid_sample_large_index_2d 
<filename> <line number of original instructions> in torchdynamo_compiled_fn_0
<filename> <line number of original instructions> in torchdynamo_compiled_fn_1

Do you think that's an acceptable UX?

**Comment by jansel** [comment]
The `__resume_x_x` functions mean graphs breaks. So the "correct" stack trace for the example above would only have `test_grid_sample_large_index_2d` once (not thrice), and include the actual line number the error happened on rather than the first line of the function.

IMO the easiest improvement would be to update the co_filename/co_firstlineno for the `__resume_x_x` function to be the first line after the graph break.  You could do this by adding:
```
code_options["co_firstlineno"] = ...
```
to this function:
https://github.com/pytorch/torchdynamo/blob/e4f79007f52299b8b677d42a32f71c8b2de88a29/torchdynamo/resume_execution.py#L140
based on the current line number stored by symbolic_convert.

----

TorchDynamo's Python bytecode codegen does support line numbers:
https://github.com/pytorch/torchdynamo/blob/e4f79007f52299b8b677d42a32f71c8b2de88a29/torchdynamo/bytecode_transformation.py#L22
But we aren't populating them for any instructions not directly copied from user code.

If you don't populate it, it ends up defaulting to `co_firstlineno`, which is what you see above.  It is not totally clear what to populate them with, as the instructions are usually "call the generated graph" rather than some line of user code.

The problem we will have is if the error happens in the generated graph, we will need the help of the backend to expose the linenumber of the error.

**Comment by jansel** [comment]
Another option would be to stash some extra debug info in `co_filename` to make the trace look like:
```
Traceback (most recent call last):                                                                     
  File "/raid/ezyang/pytorch-scratch2/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test                                                                                          
    result = test(self, **param_kwargs)                                                                
  File "/raid/ezyang/pytorch-scratch2/torch/testing/_internal/common_device_type.py", line 935, in dep_fn                                                                                                     
    return fn(self, *args, **kwargs)                                                                   
  File "test/test_nn.py", line 17339, in test_grid_sample_large_index_2d                               
    @dtypes(torch.float, torch.double)                                                                 
  File "<torchdynamo graph break of above>", line XXX                                                                                            
  File "<torchdynamo graph break of above>", line YYY                                         
```
which should be the result of setting:
```
code_options["co_filename"] = "<torchdynamo graph break of above>"
code_options["co_firstlineno"] = lineno_of_graph_break
```
