### ISSUE TITLE
optimizer.step() failed when using AOT autograd backend 

### ISSUE THREAD

**Issue by yanboliang** [pytorch/torchdynamo#953]
Minimal repro:
```
import torch
from torch import nn
import torch.optim as optim
import torchdynamo
import logging

torchdynamo.config.log_level = logging.DEBUG

a = 2.4785694
b = 7.3256989
error = 0.1
n = 100 

x = torch.randn(n, 1)
y = a * x + b + (torch.randn(n, 1) * error)

model = nn.Linear(1, 1)
optimizer = optim.SGD(model.parameters(), lr=5e-5)
loss_fn = nn.MSELoss()

niter = 1
for _ in range(0, niter):
    model.train()
    with torchdynamo.optimize("aot_nop"):
        optimizer.zero_grad()
        predictions = model(x)
        loss = loss_fn(predictions, y)
        loss.backward()
        optimizer.step()
    
    print("-" * 10)
    print("learned a = {}".format(list(model.parameters())[0].data[0, 0]))
    print("learned b = {}".format(list(model.parameters())[1].data[0]))
```

Error:
```
========== TorchDynamo Stack Trace ==========
Traceback (most recent call last):
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/output_graph.py", line 383, in call_user_compiler
    compiled_fn = self.compiler_fn(gm, self.example_inputs())
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/optimizations/training.py", line 33, in compile_fn
    return cls(gm, example_inputs).verified_candidate()
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/optimizations/training.py", line 76, in __init__
    mutated = has_mutation(self.gm, self.example_inputs)
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/optimizations/analysis.py", line 125, in has_mutation
    ShapeAliasingAndMutationProp(new_gm).run(*example_inputs)
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/optimizations/analysis.py", line 107, in run
    super().run(*args)
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/torch/fx/interpreter.py", line 129, in run
    self.env[node] = self.run_node(node)
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/optimizations/analysis.py", line 50, in run_node
    result = getattr(self, n.op)(n.target, args, kwargs)
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/torch/fx/interpreter.py", line 238, in call_function
    return target(*args, **kwargs)
TypeError: _operator.iadd() takes no keyword arguments

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/convert_frame.py", line 303, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/bytecode_transformation.py", line 338, in transform_code_object
    transformations(instructions, code_options)
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/convert_frame.py", line 287, in transform
    tracer.run()
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/symbolic_convert.py", line 334, in run
    and self.step()
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/symbolic_convert.py", line 307, in step
    getattr(self, inst.opname)(inst)
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/symbolic_convert.py", line 1353, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/output_graph.py", line 317, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/output_graph.py", line 359, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/output_graph.py", line 392, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torchdynamo.exc.BackendCompilerFailed: compile_fn raised TypeError: _operator.iadd() takes no keyword arguments

You can suppress this exception and fall back to eager by setting:
    torchdynamo.config.raise_on_backend_error = False
```

It works well if switch backend from ```aot_nop``` to ```eager```.

cc @Chillee

**Comment by ezyang** [comment]
ShapeAliasingAndMutationProp needs to die lol

**Comment by yanboliang** [comment]
Update Dynamo config fixed this issue:
```
import functorch.compile
functorch.compile.config.use_functionalize = True

# run FX normalization passes in optimizer
normalize_ir = False
```

**Comment by ezyang** [comment]
@bdhirsh this is a good reason to turn functionalization on by default, it saves people from debugging spurious problems.

**Comment by bdhirsh** [comment]
totally agreed. Progress: Animesh's latest run finished, and showed a bunch of inductor failures - probably enough that we should fix the majority of them before turning functionalization on (https://github.com/pytorch/torchdynamo/issues/970#issuecomment-1226027971).

From staring at the logs a bit, it seems like most of those failures will be fixed by the stack at  https://github.com/pytorch/pytorch/pull/83992. I applied those patches locally and kicked off another inductor on my AWS instance, so I'll report back with the results later.

**Comment by bdhirsh** [comment]
FWIW - now that functionalization is turned on I tried running the above repro again.

First I hit an issue with fake tensor - it looks like we trace the original user's code in dynamo with fake tensors, but "lose" the fake tensor mode later:
```
put_graph.py", line 368, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/scratch/hirsheybar/work/benchmark/pytorch/torchdynamo/torchdynamo/out
put_graph.py", line 401, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torchdynamo.exc.BackendCompilerFailed: compile_fn raised Exception: Invoking o
perators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. P
lease convert all Tensors to FakeTensors first. Found in aten.copy_.default(*(
tensor([[4.9326e-43]]), FakeTensor(<torch._subclasses.fake_tensor.FakeTensorMo
de object at 0x7f1753e5aa90>, FakeTensor(..., device='meta', size=(1, 1)), cpu
)), **{})

```

I skipped that error for now by setting `fake_tensors_available = False` in `torchdynamo/torchdynamo/utils.py`, and the example now passes.

**Comment by yanboliang** [comment]
@bdhirsh Yes, I verified with disabling fake tensor, it works well too.

**Comment by yanboliang** [comment]
I'll close this one and open another one to track the fake tensor bug. Thanks all!
