### ISSUE TITLE
vision_maskrcnn is incorrectly hitting cpp backend for inductor

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#974]
Repro:

```
$ ./benchmarks/torchbench.py --inductor --float16 -dcuda --no-skip -k vision_maskrcnn
```

stack:

```
  File "/raid/ezyang/pytorch-scratch2/functorch/functorch/_src/aot_autograd.py", line 855, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/raid/ezyang/pytorch-scratch2/functorch/functorch/_src/aot_autograd.py", line 435, in create_aot_dispatcher_function
    return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
  File "/raid/ezyang/pytorch-scratch2/functorch/functorch/_src/aot_autograd.py", line 276, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/raid/ezyang/torchdynamo/torchinductor/compile_fx.py", line 220, in fw_compiler
    return compile_fx_inner(
  File "/raid/ezyang/torchdynamo/torchdynamo/debug_utils.py", line 248, in debug_wrapper
    raise e
  File "/raid/ezyang/torchdynamo/torchdynamo/debug_utils.py", line 236, in debug_wrapper
    compiled_fn = compiler(gm, example_inputs, **kwargs)
  File "/raid/ezyang/torchdynamo/torchinductor/compile_fx.py", line 112, in compile_fx_inner
    compiled_fn = wrap(graph.compile_to_fn())
  File "/raid/ezyang/torchdynamo/torchinductor/graph.py", line 299, in compile_to_fn
    code = self.codegen()
  File "/raid/ezyang/torchdynamo/torchinductor/graph.py", line 293, in codegen
    self.scheduler.codegen()
  File "/raid/ezyang/torchdynamo/torchinductor/scheduler.py", line 1205, in codegen
    self.get_backend(device).codegen(*group)
  File "/raid/ezyang/torchdynamo/torchinductor/codegen/cpp.py", line 522, in codegen
    node.run(vars, reduction_vars)
  File "/raid/ezyang/torchdynamo/torchinductor/scheduler.py", line 347, in run
    self.codegen(index_vars)
  File "/raid/ezyang/torchdynamo/torchinductor/scheduler.py", line 367, in codegen
    self._body(*index_vars)
  File "/raid/ezyang/torchdynamo/torchinductor/ir.py", line 3133, in __call__
    result = self.root_block()
  File "/raid/ezyang/torchdynamo/torchinductor/ir.py", line 3228, in __call__
    return gm.forward(V.get_ops_handler())
  File "<eval_with_key>.734", line 7, in forward
    to_dtype = ops.to_dtype(load, torch.float16);  load = None
  File "/raid/ezyang/torchdynamo/torchinductor/codegen/common.py", line 583, in inner
    self.compute, getattr(parent_handler, name)(*args, **kwargs)
  File "/raid/ezyang/torchdynamo/torchinductor/codegen/cpp.py", line 165, in to_dtype
    assert dtype in DTYPE_TO_CPP, f"{dtype} missing from {__name__}.DTYPE_TO_CPP"
AssertionError: torch.float16 missing from torchinductor.codegen.cpp.DTYPE_TO_CPP
ERROR
torch.float16 missing from torchinductor.codegen.cpp.DTYPE_TO_CPP
```

@voznesenskym says he's already investigating a similar problem in internal models.

**Comment by ezyang** [comment]
we think https://github.com/pytorch/torchdynamo/issues/907 may be root cause

**Comment by voznesenskym** [comment]
@ezyang  I think this might be correct? I am seeing CPU devices explicitly created in the model, and in dynamo. I do not believe this is a bug, but we need much better tooling around detecting devices.

**Comment by ezyang** [comment]
In that case we need to add float16 support to the cpu backend (ugh)

**Comment by jansel** [comment]
The node being copied CPU=>CUDA is:
```
ComputedBuffer(name='buf30', layout=FixedLayout('cpu', torch.float16, size=[3, 4], stride=[4, 1]), data=Pointwise(
  'cpu',
  torch.float16,
  to_dtype(load(arg11_1, 4*i0 + i1, False), torch.float16),
  ranges=[3, 4],
  origins={_to_copy_default}
))
```
so the only CPU op involved is `.to(float16)` -- which we are actually generating ourselves.

This patch might help, by doing the conversion on GPU:
```patch
diff --git a/torchinductor/lowering.py b/torchinductor/lowering.py
index 2ac5906..e8cbf0d 100644
--- a/torchinductor/lowering.py
+++ b/torchinductor/lowering.py
@@ -308,10 +308,10 @@ def _to_copy(
     assert not layout or layout == torch.strided, "TODO"
     assert not pin_memory, "TODO"
     assert not memory_format, "TODO"
-    if dtype is not None:
-        x = to_dtype(x, decode_dtype(dtype))
     if device is not None and device != x.get_device():
         x = to_device(x, device)
+    if dtype is not None:
+        x = to_dtype(x, decode_dtype(dtype))
     return x
```

Though after applying it we get a new error:
```
Traceback (most recent call last):
  File "/home/jansel/torchdynamo/benchmarks/common.py", line 1074, in run_one_model
    new_result = optimized_model_iter_fn(model, example_inputs)
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 153, in _fn
    return fn(*args, **kwargs)
  File "./benchmarks/torchbench.py", line 349, in forward_pass
    def forward_pass(self, mod, inputs, collect_outputs=True):
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/torchvision/torchvision/models/detection/generalized_rcnn.py", line 46, in forward
    def forward(self, images, targets=None):
  File "/home/jansel/torchvision/torchvision/models/detection/generalized_rcnn.py", line 46, in forward
    def forward(self, images, targets=None):
  File "/home/jansel/torchvision/torchvision/models/detection/generalized_rcnn.py", line 46, in forward
    def forward(self, images, targets=None):
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/torchvision/torchvision/models/detection/rpn.py", line 335, in forward
    def forward(
  File "/home/jansel/torchvision/torchvision/models/detection/rpn.py", line 241, in filter_proposals
    def filter_proposals(
  File "/home/jansel/torchvision/torchvision/models/detection/rpn.py", line 241, in filter_proposals
    def filter_proposals(
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 153, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/pytorch/functorch/functorch/_src/aot_autograd.py", line 790, in forward
    return compiled_f(
  File "/home/jansel/pytorch/functorch/functorch/_src/aot_autograd.py", line 776, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/home/jansel/pytorch/functorch/functorch/_src/aot_autograd.py", line 358, in create_aot_dispatcher_function
    return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
  File "/home/jansel/pytorch/functorch/functorch/_src/aot_autograd.py", line 199, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/home/jansel/torchdynamo/torchinductor/compile_fx.py", line 222, in fw_compiler
    return compile_fx_inner(
  File "/home/jansel/torchdynamo/torchdynamo/debug_utils.py", line 248, in debug_wrapper
    raise e
  File "/home/jansel/torchdynamo/torchdynamo/debug_utils.py", line 236, in debug_wrapper
    compiled_fn = compiler(gm, example_inputs, **kwargs)
  File "/home/jansel/torchdynamo/torchinductor/compile_fx.py", line 122, in compile_fx_inner
    compiled_fn = cudagraphify(
  File "/home/jansel/torchdynamo/torchinductor/compile_fx.py", line 151, in cudagraphify
    model(*inputs)
  File "/tmp/torchinductor_jansel/iv/civi5wdgoc67k4zqm4fxzap3alhzovodpl4nvna4saetikshl56z.py", line 19, in call
    return (buf1, buf2, buf0, buf3, )
NameError: name 'buf1' is not defined
```

**Comment by jansel** [comment]
After applying some partial fixes in #974, I tried the minifier -- but it didn't seem to work.  cc @Chillee 

I was running
```
COMPILER_REPRO_LEVEL=3 ./benchmarks/torchbench.py --inductor-dynamic --float16 -dcuda --no-skip -k vision_maskrcnn
```

I get a lot of printouts of:
```
wrote out to minifier_launcher.py
wrote out to minifier_launcher.py
wrote out to minifier_launcher.py
wrote out to minifier_launcher.py
wrote out to minifier_launcher.py
wrote out to minifier_launcher.py
wrote out to minifier_launcher.py
```

But then it finishes I get:
```
$ python minifier_launcher.py
Traceback (most recent call last):
  File "minifier_launcher.py", line 49, in <module>
    minifier(
  File "/home/jansel/pytorch/functorch/functorch/_src/fx_minifier.py", line 90, in minifier
    raise RuntimeError("Input graph did not fail the tester")
RuntimeError: Input graph did not fail the tester
```

**Comment by voznesenskym** [comment]
> The node being copied CPU=>CUDA is:
> 
> ```
> 
> ComputedBuffer(name='buf30', layout=FixedLayout('cpu', torch.float16, size=[3, 4], stride=[4, 1]), data=Pointwise(
> 
>   'cpu',
> 
>   torch.float16,
> 
>   to_dtype(load(arg11_1, 4*i0 + i1, False), torch.float16),
> 
>   ranges=[3, 4],
> 
>   origins={_to_copy_default}
> 
> ))
> 
> ```
> 
> so the only CPU op involved is `.to(float16)` -- which we are actually generating ourselves.
> 
> 
> 
> This patch might help, by doing the conversion on GPU:
> 
> ```patch
> 
> diff --git a/torchinductor/lowering.py b/torchinductor/lowering.py
> 
> index 2ac5906..e8cbf0d 100644
> 
> --- a/torchinductor/lowering.py
> 
> +++ b/torchinductor/lowering.py
> 
> @@ -308,10 +308,10 @@ def _to_copy(
> 
>      assert not layout or layout == torch.strided, "TODO"
> 
>      assert not pin_memory, "TODO"
> 
>      assert not memory_format, "TODO"
> 
> -    if dtype is not None:
> 
> -        x = to_dtype(x, decode_dtype(dtype))
> 
>      if device is not None and device != x.get_device():
> 
>          x = to_device(x, device)
> 
> +    if dtype is not None:
> 
> +        x = to_dtype(x, decode_dtype(dtype))
> 
>      return x
> 
> ```
> 
> 
> 
> Though after applying it we get a new error:
> 
> ```
> 
> Traceback (most recent call last):
> 
>   File "/home/jansel/torchdynamo/benchmarks/common.py", line 1074, in run_one_model
> 
>     new_result = optimized_model_iter_fn(model, example_inputs)
> 
>   File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 153, in _fn
> 
>     return fn(*args, **kwargs)
> 
>   File "./benchmarks/torchbench.py", line 349, in forward_pass
> 
>     def forward_pass(self, mod, inputs, collect_outputs=True):
> 
>   File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1185, in _call_impl
> 
>     return forward_call(*input, **kwargs)
> 
>   File "/home/jansel/torchvision/torchvision/models/detection/generalized_rcnn.py", line 46, in forward
> 
>     def forward(self, images, targets=None):
> 
>   File "/home/jansel/torchvision/torchvision/models/detection/generalized_rcnn.py", line 46, in forward
> 
>     def forward(self, images, targets=None):
> 
>   File "/home/jansel/torchvision/torchvision/models/detection/generalized_rcnn.py", line 46, in forward
> 
>     def forward(self, images, targets=None):
> 
>   File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1185, in _call_impl
> 
>     return forward_call(*input, **kwargs)
> 
>   File "/home/jansel/torchvision/torchvision/models/detection/rpn.py", line 335, in forward
> 
>     def forward(
> 
>   File "/home/jansel/torchvision/torchvision/models/detection/rpn.py", line 241, in filter_proposals
> 
>     def filter_proposals(
> 
>   File "/home/jansel/torchvision/torchvision/models/detection/rpn.py", line 241, in filter_proposals
> 
>     def filter_proposals(
> 
>   File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 153, in _fn
> 
>     return fn(*args, **kwargs)
> 
>   File "/home/jansel/pytorch/functorch/functorch/_src/aot_autograd.py", line 790, in forward
> 
>     return compiled_f(
> 
>   File "/home/jansel/pytorch/functorch/functorch/_src/aot_autograd.py", line 776, in new_func
> 
>     compiled_fn = create_aot_dispatcher_function(
> 
>   File "/home/jansel/pytorch/functorch/functorch/_src/aot_autograd.py", line 358, in create_aot_dispatcher_function
> 
>     return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
> 
>   File "/home/jansel/pytorch/functorch/functorch/_src/aot_autograd.py", line 199, in aot_dispatch_base
> 
>     compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
> 
>   File "/home/jansel/torchdynamo/torchinductor/compile_fx.py", line 222, in fw_compiler
> 
>     return compile_fx_inner(
> 
>   File "/home/jansel/torchdynamo/torchdynamo/debug_utils.py", line 248, in debug_wrapper
> 
>     raise e
> 
>   File "/home/jansel/torchdynamo/torchdynamo/debug_utils.py", line 236, in debug_wrapper
> 
>     compiled_fn = compiler(gm, example_inputs, **kwargs)
> 
>   File "/home/jansel/torchdynamo/torchinductor/compile_fx.py", line 122, in compile_fx_inner
> 
>     compiled_fn = cudagraphify(
> 
>   File "/home/jansel/torchdynamo/torchinductor/compile_fx.py", line 151, in cudagraphify
> 
>     model(*inputs)
> 
>   File "/tmp/torchinductor_jansel/iv/civi5wdgoc67k4zqm4fxzap3alhzovodpl4nvna4saetikshl56z.py", line 19, in call
> 
>     return (buf1, buf2, buf0, buf3, )
> 
> NameError: name 'buf1' is not defined
> 
> ```
> 
> 
> 
> 
> 
> 

If I change where the cpu device is set to "cuda" in the model source - and remove an assert on our end, I can get the same exact error. That might make for an easier minification and repro story. Let me see if that minimizes on my end.

**Comment by desertfire** [comment]
> After applying some partial fixes in #974, I tried the minifier -- but it didn't seem to work. cc @Chillee
> 
> I was running
> 
> ```
> COMPILER_REPRO_LEVEL=3 ./benchmarks/torchbench.py --inductor-dynamic --float16 -dcuda --no-skip -k vision_maskrcnn
> ```
> 
> I get a lot of printouts of:
> 
> ```
> wrote out to minifier_launcher.py
> wrote out to minifier_launcher.py
> wrote out to minifier_launcher.py
> wrote out to minifier_launcher.py
> wrote out to minifier_launcher.py
> wrote out to minifier_launcher.py
> wrote out to minifier_launcher.py
> ```
> 
> But then it finishes I get:
> 
> ```
> $ python minifier_launcher.py
> Traceback (most recent call last):
>   File "minifier_launcher.py", line 49, in <module>
>     minifier(
>   File "/home/jansel/pytorch/functorch/functorch/_src/fx_minifier.py", line 90, in minifier
>     raise RuntimeError("Input graph did not fail the tester")
> RuntimeError: Input graph did not fail the tester
> ```

Please  rebase to this PR, https://github.com/pytorch/torchdynamo/pull/967

**Comment by voznesenskym** [comment]
> NameError: name 'buf1' is not defined

#993 gets the same error without needing to do dtype conversion, potentially easier for debugging?

**Comment by jansel** [comment]
Minified version:
```
import torch
from torch import tensor, device
import torch.fx as fx
from torchdynamo.testing import rand_strided
from math import inf
from torch.fx.experimental.proxy_tensor import make_fx

# torch version: 1.13.0a0+gite09821f
# torch cuda version: 11.6
# torch git version: e09821f784bc9e9f13d361e9d2eb3fa1d7d07263


# CUDA Info: 
# nvcc: NVIDIA (R) Cuda compiler driver 
# Copyright (c) 2005-2022 NVIDIA Corporation 
# Built on Tue_Mar__8_18:18:20_PST_2022 
# Cuda compilation tools, release 11.6, V11.6.124 
# Build cuda_11.6.r11.6/compiler.31057947_0 

# GPU Hardware Info: 
# NVIDIA GeForce RTX 3090 : 1 

class Repro(torch.nn.Module):



    def forward(self, arg0_1, arg1_1):
        index_tensor = torch.ops.aten.index.Tensor(arg1_1, [arg0_1]);  arg1_1 = arg0_1 = None
        return (index_tensor,)
    
args = [((0,), (1,), torch.int64, 'cuda'), ((5000, 4), (4, 1), torch.float16, 'cuda')]
args = [rand_strided(shape, stride, dtype, device) for shape, stride, dtype, device in args]
mod = make_fx(Repro())(*args)

from torchinductor.compile_fx import compile_fx_inner

compiled = compile_fx_inner(mod, args)
compiled(*args)

```

**Comment by voznesenskym** [comment]
ref #1029
